package
{
   import mx.resources.ResourceBundle;
   
   public class bg_BG$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function bg_BG$LocalizedStrings_properties()
      {
         super("bg_BG","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Заключване",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Въведете данните за достъп до Hörmann-портала",
            "ERROR_DELETE_ADMIN":"Не е възможно",
            "LOGIN_SHOULD_SAVE":"Запаметяване на данните",
            "LOAD_USERS_TITLE":"Моля, изчакайте",
            "CHANGE_GW_NAME_SETTING":"Възприемане",
            "CONFIRM_DELETE_GROUP":"Изтриване на устройство",
            "GENERAL_NO":"не",
            "DESC_GWSCREEN_ADD":"Добавяне на локални Gateways",
            "DRIVE_MESSAGE_NOT_RETRACTED":"неспуснат",
            "WIFI_PASSPHRASE":"Парола",
            "CHANNEL_ON":"Вкл.",
            "SCENARIOS":"Сценарии",
            "ERROR_SET_ADMIN_RIGHTS":"Не е възможно",
            "DESC_DEFAULT_GW_SAVE":"Изграждане на бърз достъп до актуален Gateway",
            "POPUP_INFO":"Указание",
            "DRIVE_MESSAGE_ERROR":"ВНИМАНИЕ: Грешка",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Име на мрежата",
            "EMAIL_BODY":"Можете да ни изпращате въпросите си по имейл. За тази цел на Ваше разположение е и нашата функция FAQ.\n\nВаш BiSecur-Home Support-Team",
            "CONFIRM_DELETE_USER":"Изтриване на потребител",
            "DESC_CHANNELS_BACK":"Назад към списъка с устройства",
            "CHANGE_PWD_FIRST_START":"От съображения за сигурност променете заводската настройка на Вашата парола след първата регистрация",
            "GENERAL_DEFAULT_GATEWAY":"Бърз достъп",
            "CHANGE_PWD_PASSWORD_INVALID":"Грешка",
            "ERROR_NO_GW_TITLE":"Няма Gateways",
            "POPUP_SETTING_STATE_CONTENT":"Командата се изпълнява",
            "WIFI_LOADING_DATA_CONTENT":"Зареждат се данните на WLAN",
            "OPTIONS_RESET_LOGIN_DATA":"Изтриване на запаметените данни за логване",
            "EDIT_USER_TITLE":"Редактиране на потребител",
            "DESC_HOME_PREFERENCES":"Промяна на настройките за Gateway и приложение",
            "WIFI_ACTIVE_STATE":"Статус на WLAN",
            "STATE_COLLECTING":"Зареждане",
            "ADD_SCENARIO":"Добавяне на сценарий",
            "STATE_COLLECTING_FAILED_CONTENT":"Статусът не е зареден",
            "GATE_SWING_GATE_SINGLE":"Крилна врата с 1 крило",
            "ACTORS":"Устройства",
            "POPUP_AGREEMENT":"Ползване / Защита на данните",
            "CHANNEL_OPEN_DOOR":"Oтваряне",
            "DESC_ACTORS_REFRESH":"Актуализиране на статуса",
            "GENERAL_OFF":"Изключено",
            "OPTIONS_HELP":"Онлайн помощ",
            "COPY_PORTS_CONTENT":"Приведете предавателя в режим за прехвърляне на радиокод, виж инструкцията. Изберете канала, който ще наследи кода.",
            "GENERAL_SELECT":"Моля, изберете...",
            "ERROR_ADAPTER_BUSY":"Грешка",
            "INFO_BOX_INFOS":"Общо",
            "GATE_LIGHT":"Осветление",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Отваряне на условията за ползване",
            "DESC_MANAGE_POPUPS_WARNINGS":"Скриване на предупредителни Popup съобщения",
            "MAX_USERSS_REACHED_CONTENT":"Достигнат е максималният брой потребители.",
            "GENERAL_REMOVE":"Отстраняване",
            "OPTIONS":"Настройки",
            "DESC_HOME_SCENARIOS":"Изготвяне и управление на сценарии",
            "CHANNEL_OFF":"Изкл.",
            "GENERAL_PORTAL_ID":"ID на устройството",
            "EDIT_GROUP":"Обработване на устройство",
            "ERROR_LERANIN_PORT_CONTENT":"Регистрирането на желания канал е неуспешно",
            "ERROR_CONNECTION_CLOSED":"Грешка",
            "CHANNEL_ON_OFF":"Вкл. / Изкл.",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Наименование",
            "OPTIONS_EDIT_USERS":"Управление на потребители",
            "LOADING_STATES_CONTENT":"Извиква се информация за актуалния статус.\nМоля, изчакайте...",
            "LERAN_PORTS_CONTENT":"Приведете устройството в режим за регистриране, виж инструкцията. Изберете канала, на който ще регистрирате код.",
            "REMOVE_PORTS_CONTENT":"Моля, изберете каналите, които желаете да изтриете.",
            "GATE_SWING_GATE_DOUBLE":"Крилна врата с 2 крила",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Проверете дали сте въвели данните си за портала или сте добавили локален Gateway.",
            "CHANNEL_SINK":"спускане",
            "OPTIONS_EDIT_USERS_TITLE":"Потребител",
            "MAX_PORTS_REACHED_CONTENT":"Заети са максималният брой канали",
            "MAX_PORTS_REACHED":"Не е възможно",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Няма връзка с търсеното устройство",
            "PORTAL_AUTHENTICATION_FAILED":"Неуспешно",
            "NOTIFICATION_CENTER":"Известия",
            "LEARNING_PROCESS":"Регистриране",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Потребителското име трябва да съдържа 2 - 20 знака",
            "WIFI_STATE_CONNECTED":"Свързване",
            "COPY_PORTS":"Наследяване от ръчен предавател",
            "POPUP_SEARCH_CONTENT":"Търсене на Gateways Hörmann \n\nТози процес може да отнеме няколко секунди!",
            "DESC_MANAGE_POPUPS_CANCEL":"Прекъсване на действието",
            "DESC_WIFI_PASSWORD":"Парола",
            "DESC_WIFI_SAVE":"Запаметяване",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Активен стоп",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Добавяне на устройство",
            "WIFI_STATE_BUSY":"Връзката се изгражда",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Въведената парола е грешна",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Промяна на името на този Gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Името се възприема",
            "DESC_ACTORS_EDIT":"Управление или изтриване на устройства",
            "DESC_WIFI_STATE":"Статус на връзката",
            "ERROR_REMOVE_USER":"Неуспешно",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Възприемане на настройката",
            "HOME_TITLE":"Главна страница",
            "GENERAL_USERNAME":"Потребителско име",
            "DRIVE_MESSAGE_OPENED":"Отворена",
            "CONFIRM_DELETE":"Сигурни ли сте, че желаете да изтриете този Gateway?",
            "DRIVE_MESSAGE_CLOSED":"Затворена",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Няма връзка с порталния сървър",
            "REMOVING_PROCESS_CONTENT":"Каналът се изтрива",
            "DESC_EDIT_USERS_BACK":"Назад към \"Настройки\"",
            "ERROR_NO_GROUP_FOUND":"Устройството не е намерено",
            "ERROR_INVALID_GATEWAY":"Не е намерен Gateway",
            "DESC_WIFI_BACK":"Назад към \"Настройки\"",
            "MAX_USERS_REACHED":"Не е възможно",
            "DESC_CHANGE_PASSWORD_USERNAME":"Потребителско име",
            "POPUP_AGREEMENT_ACCEPT_USE":"Приемам условията за ползване",
            "ERROR_LERNING_PORT":"Неуспешно",
            "POPUP_ADD_GATEWAY_CONTENT":"Въвеждане на IP адрес:",
            "ERROR_ADD_GROUP":"Грешка",
            "DRIVE_MESSAGE_NO_DATA":"Не са налични данни",
            "CHANGE_PWD_FAILED":"Неуспешно",
            "SAVING_USER_RIGHTS_CONTENT":"Потребителските права се запаметяват",
            "DRIVE_MESSAGE_UNLOCKED":"отключена",
            "GENERAL_SAVE":"Запаметяване",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Свързване",
            "GATE_SECTIONAL_DOOR":"Гаражна врата с вертикално отваряне",
            "OPTIONS_CHANGE_PASSWORD":"Промяна на парола",
            "CHANNEL":"Обслужване",
            "CHANGE_GW_NAME_CONTENT":"Име на Gateway",
            "DRIVE_MESSAGE_RETRACTED":"спуснат",
            "DESC_ADDGWSCREEN_BACK":"Назад към прегледа на Gateways",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Не е възможно",
            "OPTIONS_SET_USER_RIGHTS":"Потребителски права",
            "CHANGE_GW_NAME_ERROR":"Неуспешно",
            "CHANNEL_LIFT":"издигане",
            "LOGIN_FAILED_TITLE":"Неуспешно",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Ако потвърдите изтриването на данните за логване с OK, паролата трябва да се въведе отново при избора на Gateway",
            "CHANNEL_UNLOCK":"Отключване",
            "GENERAL_PORTAL_SERVER":"Портален сървър",
            "DESC_SCENARIOS_BACK":"Назад към главното меню",
            "CHANGE_PWD_USERNAME":"Потребител:",
            "POPUP_GATE_NOT_RESPONSABLE":"Приложението може да изпрати командата до устройството, но не разпознава неговото актуално състояние.",
            "DESC_GW_NAME":"Име на Gateway",
            "GATE_BARRIER":"бариера",
            "LEARN_PORTS":"Регистриране на радиокод",
            "GENERAL_BACK":"Назад",
            "DESC_GWSCREEN_EDIT":"Запаметени за изтриване Gateways",
            "OPTIONS_MANAGE_POPUPS":"Управление на Popup съобщения",
            "POPUP_LOGIN_PROCESS_CONTENT":"Моля, изчакайте...",
            "CONFIRM_DELETE_USER_CONTENT":"Сигурни ли сте, че желаете да изтриете потребителя?",
            "DESC_MENU":"Меню",
            "LOGIN_FAILED_WRONG_DATA":"Въведеното потребителско име или паролата са грешни",
            "GENERAL_CANCEL":"Отказване",
            "ADD_GROUP":"Добавяне на устройство",
            "WIFI_STATE_AP_NOT_FOUND":"Мрежата не е намерена",
            "WIFI_STATE_NOT_CONNECTED":"Няма свързване",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Обслужването през портала е активирано!",
            "POPUP_ADD_GATEWAY":"Добавяне на Gateway",
            "GENERAL_NEXT":"Напред",
            "POPUP_SUPPRESS":"Блокиране на Popup",
            "POPUP_SEARCH_TITLE":"Търсене...",
            "WIFI_SCANNING_CONTENT":"Търсене на видими WLAN мрежи",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Не е намерен Gateway",
            "DESC_ACTORS_ADD":"Създаване на устройство",
            "ERROR_ADD_GROUP_NO_TYPE":"Не е избран тип за новото устройство.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Проверете данните за логване",
            "GENERAL_REFESHED":"Актуализирано",
            "OPTIONS_SUPPRESS_WARNINGS":"Скриване на предупреждения",
            "LOGIN_FAILED_GATEWAY_BUSY":"Този Gateway се използва. Опитайте отново.",
            "DESC_EMAIL":"Изпратете имейл до Support",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Изключена функция \"Трайно отворена врата\"",
            "CLEANING_PORTS_CONTENT":"Подготвя се добавяне",
            "DESC_HOME_ACTORS":"Разпознаване и управление на устройства",
            "ERROR_TIMEOUT":"Грешка при свързване",
            "CREATE_USER_TITLE":"Добавяне на потребител",
            "ERROR_DELETE_ADMIN_CONTENT":"Администраторът не може да бъде изтрит",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Бърз достъп",
            "ADD_SCENARIO_NAME":"Фамилия",
            "HIST":"Архив",
            "DESC_RESET_LOGIN_SUBMIT":"Потвърждаване на изтриването",
            "POPUP_WARNING":"ВНИМАНИЕ",
            "REMOVE_GROUP_PROCESS":"Устройството се изтрива",
            "POPUP_LOGIN_PROCESS":"Регистриране",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Моля, изчакайте...",
            "DESC_DEFAULT_GW_SUBMIT":"Възприемане на настройката",
            "DESC_CHANGE_PASSWORD_RETYPE":"Повтаряне на въвеждането",
            "LOAD_USERS_CONTENT":"Зареждат се всички потребители на този Gateway.\nТози процес може да отнеме няколко секунди.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Ако за даден Gateway е активиран бърз достъп, приложението се логва автоматично при възможност",
            "GATE_OTHER":"Други устройства",
            "CHANGE_PWD_USER_INVALID":"Грешка",
            "CHANNEL_LIGHT":"Осветление",
            "LOGIN_TITLE":"Регистриране",
            "CHANNEL_HALF":"Частично отваряне",
            "GATEWAY_SCREEN_ADD_HELP":"За да добавите Gateways, изберете символа+.",
            "ERROR_TIMEOUT_CONTENT":"Надвишаване на определеното време при комуникация с Gateway",
            "ERROR_NO_PORTS_LEARNED":"Не е възможно добавяне",
            "OPTIONS_SUPPRESS_INFOS":"Скриване на указания",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Грешка",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Автоматичен режим",
            "GENERAL_DELETE":"Изтриване",
            "GENERAL_PASSWORD":"Парола",
            "STATE_COLLECTING_CONTENT":"Изпраща се запитване за статуса на устройствата",
            "ERROR_REMOVE_USER_CONTENT":"Потребителят не може да бъде изтрит",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Грешка",
            "ACTORS_ADD_HELP":"За да добавите устройство, изберете символа+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Сигурни ли сте, че желаете да изтриете устройството?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Моля, изчакайте...",
            "GENERAL_YES":"да",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Преди добавяне на устройство трябва да проведете процес по разпознаване за минимум един канал",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Името не може да бъде променено",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Приложението все още не е открило Gateways.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Неуспешна оторизация",
            "DESC_MANAGE_POPUPS_INFOS":"Скриване на информационни Popup съобщения",
            "GATE_PILOMAT_POLLER":"болард",
            "DESC_CHANNELS_STATE":"Статус на устройството, способно да изпраща обратна сигнализация",
            "DESC_GWSCREEN_REFRESH":"Актуализиране на списъка с Gateways",
            "POPUP_SCENARIO_DISPATCHING":"Сценарият се изпълнява",
            "ERROR_PORT_UNREACHABLE":"Неуспешно",
            "POPUP_GATEWAY_FOUND_CONTENT":"Добавени са следните Gateways:",
            "WIFI_STATE_SECURITY_MISMATCH":"Видът кодиране на WLAN не се поддържа",
            "LOGOUT_NAMED":"отписване",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Отваряне на условията за защита на данни",
            "ERROR_NO_GW_CONTENT":"В локалната мрежа не може да бъде намерен Gateway Hörmann.\nСъс знака +добавете други Gateways",
            "DESC_EDIT_USERS_ADD":"Добавяне на потребител",
            "ERROR_NO_PORT_FOUND":"Портът не е намерен",
            "GATE_SLIDING_GATE":"Плъзгаща се врата",
            "DESC_CHANNELS_BUTTONS":"Командни елементи на устройството",
            "DRIVE_MESSAGE_EXTENDED":"издигнат",
            "WIFI_SELECTED_NETWORK":"Фамилия",
            "ERROR_ADD_GROUP_NO_NAME":"Не е въведено име за новото устройство.",
            "DESC_HELP":"Функция \"Помощ\"",
            "CHANGE_PWD_NEW_PASSWORD":"Нова парола",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Възприемане на нова парола",
            "DESC_CHANGE_PASSWORD_PWD":"Въвеждане на нова парола",
            "ERROR_EDIT_ADMIN_CONTENT":"Администраторът не може да се редактира",
            "CHANGE_GW_NAME_NAME_INVALID":"Неуспешно",
            "STATE_COLLECTING_FAILED":"Грешка",
            "GENERAL_ADD":"Добавяне",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Парола\" и \"Повторете паролата\" трябва да са идентични",
            "WIFI_SETTINGS":"Настройки на WLAN",
            "LEARN_PORTS_TITLE":"Добавяне на устройство",
            "ERROR_CHANGE_USERNAME":"Неуспешно",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"роуд блокер",
            "ERROR_INVALID_GATEWAY_CONTENT":"Няма връзка с Gateway. Проверете името на хоста.",
            "DESC_EDIT_USERS_EDIT":"Изтриване на потребител",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Името на устройството трябва да съдържа 2 - 20 знака",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Не е възможен бърз достъп",
            "CHANNEL_UP":"Отваряне",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Включена функция \"Трайно отворена врата\"",
            "PORTAL_VALIDATION_FAILED":"Неуспешно",
            "DESC_RESET_LOGIN_CANCEL":"Прекъсване на действието",
            "CHANGE_PWD_SETTING_PASSWORD":"Възприемане",
            "LOADING_GROUPS_TITLE":"Зареждане",
            "DESC_DEFAULT_GW_CANCEL":"Прекъсване на действието",
            "DESC_SET_RIGHTS_SAVE":"Възприемане на промените",
            "REMOVING_PROCESS":"Изтриване",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Този Gateway не може да бъде достигнат",
            "CONFIRM_DELETE_TITLE":"Изтриване на Gateway",
            "SCENARIOS_ADD_HELP":"За да добавите сценарий, изберете символа+.",
            "LOGOUT":"Отписване",
            "DESC_ACTORS_BACK":"Назад към главното меню",
            "ERROR_ADAPTER_BUSY_CONTENT":"Командата не може да бъде изпълнена.\n Gateway се използва.",
            "DESC_WIFI_NETWORK_SCAN":"Търсене по мрежи",
            "DRIVE_MESSAGE_HALF":"Частично отворена",
            "DESC_SCENARIOS_ADD":"Съставяне на сценарий",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Комуникацията с Gateway е неуспешна",
            "SAVING_USER_RIGHTS":"Запаметяване",
            "DESC_GWSCREEN_PORTAL":"Въвеждане на данните за портала",
            "GATE_JACK":"Радиоуправляем контакт",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"В същата мрежа ли се намирата като Вашия Gateway?",
            "GATE_DOOR":"Врата",
            "POPUP_PORTAL_UNAVAILABLE":"Няма връзка с порталния сървър",
            "DESC_SET_RIGHTS_BACK":"Назад към \"Потребители\"",
            "GATE_SMARTKEY":"Задвижване за брава",
            "POPUP_GATEWAY_FOUND_TITILE":"Търсенето приключи",
            "WIFI_LOADING_DATA_TITLE":"Зареждане",
            "GENERAL_PORTS":"Канали",
            "DESC_SCENARIOS_EDIT":"Управление или изтриване на сценарии",
            "OPTIONS_LEARNED_PORTS":"Разпознати канали:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Приемам условията за защита на данни",
            "DESC_EDIT_USERS_SET_RIGHTS":"Избор на потребител с цел промяна на правата му за достъп",
            "DRIVE_MESSAGE_HALF_MOVING":"Частично отворена / В движение",
            "PORTAL_SET_ID_DIALOG":"Настройки на портала",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Няма референтна точка",
            "POPUP_SETTING_STATE":"Моля, изчакайте...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Потребителското име не може да бъде променено",
            "GROUP_REQUESTABLE":"Устройството може да изпраща обратна сигнализация",
            "LOADING_STATES_TITLE":"Зареждане",
            "DESC_HOME_USERS":"Управление на потребители",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Паролата трябва да съдържа 4 - 20 знака",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Паролата се възприема",
            "POPUP_GATE_OUT_OF_VIEW":"Управляването на автоматично задвижвана врата без визуален контакт с нея е позволено, само ако в допълнение към стандартно наличното ограничение на силите сте инсталирали фотоклетка към вратата.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Изберете дали Popup съобщенията да бъдат показвани или скривани",
            "CHANNEL_IMPULS":"Импулс",
            "PORTAL_VALIDATION_SUCCEEDED":"Оторизиран",
            "DRIVE_MESSAGE_LOCKED":"Заключена",
            "CHANNEL_DOWN":"Затваряне",
            "POPUP_INET_SPEED_LOW":"Вашият канал за предаване на информация не е достатъчен за това приложение",
            "CHANGE_PWD_FAILED_CONTENT":"Паролата не може да бъде променена",
            "GENERAL_GROUP_TYPE":"Тип устройство",
            "CHANNEL_WALK":"Подвижно крило",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Гаражна врата с хоризонтално отваряне",
            "POPUP_AGREEMENT_CONTENT":"Преди ползването на приложението трябва да приемете условията за защита на данни / ползване",
            "INFO":"Информация",
            "LOADING_GROUPS_CONTENT":"Зареждане на устройства",
            "GATE_PILOMAT_REIFENKILLER":"преграда с шипове",
            "GATE_PILOMAT_HUBBALKEN":"бариера с повдигащо се рамо",
            "GENERAL_RETYPE":"Повторете паролата",
            "DESC_OTIONS_BACK":"Назад към главното меню",
            "DESC_SET_RIGHTS":"Избор на устройство с цел предоставяне на права за достъп на потребителя",
            "WIFI_SCANNING_TITLE":"Търсене",
            "WIFI_STATE_CONNECTION_FAILURE":"Неуспешно изграждане на връзката",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Потребителското име трябва да съдържа 2 - 20 знака",
            "REMOVE_PORTS":"Изтриване",
            "GENERAL_ON":"Включено",
            "DESC_CHANGE_PASSWORD_CANCEL":"Прекъсване на действието",
            "LEARNING_PROCESS_CONTENT":"Моля, изчакайте...",
            "LOGIN_FAILED_UNKNOWN":"Възникна неочаквана грешка",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Потребителските права на администратора не могат да бъдат променяни"
         };
         return _loc1_;
      }
   }
}
