package
{
   import mx.resources.ResourceBundle;
   
   public class cs_CS$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function cs_CS$LocalizedStrings_properties()
      {
         super("cs_CS","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Zamknout",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Vložte přístupová data pro portál Hörmann",
            "ERROR_DELETE_ADMIN":"Není možné",
            "LOGIN_SHOULD_SAVE":"Uložit data",
            "LOAD_USERS_TITLE":"Čekejte prosím",
            "CHANGE_GW_NAME_SETTING":"Převzít",
            "CONFIRM_DELETE_GROUP":"Smazat zařízení",
            "GENERAL_NO":"Ne",
            "DESC_GWSCREEN_ADD":"Přidat lokální brány",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nezasunuté",
            "WIFI_PASSPHRASE":"Heslo",
            "CHANNEL_ON":"Zapnuto",
            "SCENARIOS":"Scénáře",
            "ERROR_SET_ADMIN_RIGHTS":"Není možné",
            "DESC_DEFAULT_GW_SAVE":"Zřídit rychlý přístup pro aktuální bránu",
            "POPUP_INFO":"Upozornění",
            "DRIVE_MESSAGE_ERROR":"POZOR: Chyba",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/cs/ochrana-dat",
            "DESC_WIFI_NETWORK_NAME":"Jméno sítě",
            "EMAIL_BODY":"Své dotazy nám můžete zaslat e-mailem. K tomu máte k dispozici naši funkci FAQ.\n\nVáš tým BiSecur-Home Support",
            "CONFIRM_DELETE_USER":"Smazat uživatele",
            "DESC_CHANNELS_BACK":"Zpět na seznam zařízení",
            "CHANGE_PWD_FIRST_START":"Po prvním přihlášení změňte z bezpečnostních důvodů tovární nastavení svého hesla",
            "GENERAL_DEFAULT_GATEWAY":"Rychlý přístup",
            "CHANGE_PWD_PASSWORD_INVALID":"Chyba",
            "ERROR_NO_GW_TITLE":"Žádné brány",
            "POPUP_SETTING_STATE_CONTENT":"Povel se provádí",
            "WIFI_LOADING_DATA_CONTENT":"Data WLAN se zavádějí",
            "OPTIONS_RESET_LOGIN_DATA":"Smazat uložená přihlašovací data",
            "EDIT_USER_TITLE":"Zpracovat uživatele",
            "DESC_HOME_PREFERENCES":"Změnit nastavení brány a aplikace",
            "WIFI_ACTIVE_STATE":"Stav WLAN",
            "STATE_COLLECTING":"Zavádí se",
            "ADD_SCENARIO":"Přidat scénář",
            "STATE_COLLECTING_FAILED_CONTENT":"Stav nebyl zaveden",
            "GATE_SWING_GATE_SINGLE":"1křídlá otočná brána",
            "ACTORS":"Přístroje",
            "POPUP_AGREEMENT":"Užívání / ochrana dat",
            "CHANNEL_OPEN_DOOR":"Otevřít",
            "DESC_ACTORS_REFRESH":"Aktualizovat stav",
            "GENERAL_OFF":"Vypnuto",
            "OPTIONS_HELP":"Online nápověda",
            "COPY_PORTS_CONTENT":"Nastavte vysílač do režimu převzetí, viz návod. Zvolte přebíraný kanál.",
            "GENERAL_SELECT":"Zvolte prosím...",
            "ERROR_ADAPTER_BUSY":"Chyba",
            "INFO_BOX_INFOS":"Všeobecně",
            "GATE_LIGHT":"Světlo",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Otevřít podmínky užívání",
            "DESC_MANAGE_POPUPS_WARNINGS":"Potlačit výstražná místní hlášení",
            "MAX_USERSS_REACHED_CONTENT":"Bylo dosaženo maximálního počtu uživatelů.",
            "GENERAL_REMOVE":"Odstranit",
            "OPTIONS":"Nastavení",
            "DESC_HOME_SCENARIOS":"Vytvářet a spravovat scénáře",
            "CHANNEL_OFF":"Vypnuto",
            "GENERAL_PORTAL_ID":"ID přístrojů",
            "EDIT_GROUP":"Zpracovat přístroj",
            "ERROR_LERANIN_PORT_CONTENT":"Programování požadovaného kanálu se nezdařilo.",
            "ERROR_CONNECTION_CLOSED":"Chyba",
            "CHANNEL_ON_OFF":"Zapnout / vypnout",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Označení",
            "OPTIONS_EDIT_USERS":"Spravovat uživatele",
            "LOADING_STATES_CONTENT":"Je vyžadován aktuální stav.\nČekejte prosím...",
            "LERAN_PORTS_CONTENT":"Nastavte zařízení do režimu programování, viz návod. Zvolte kanál k programování.",
            "REMOVE_PORTS_CONTENT":"Vyberte kanály, které chcete smazat.",
            "GATE_SWING_GATE_DOUBLE":"2křídlá otočná brána",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Zkontrolujte, zda jste zapsali svoje portálová data nebo přidali lokální bránu.",
            "CHANNEL_SINK":"Spouštění",
            "OPTIONS_EDIT_USERS_TITLE":"Uživatel",
            "MAX_PORTS_REACHED_CONTENT":"Maximální počet kanálů obsazen",
            "MAX_PORTS_REACHED":"Není možné",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Dotazované zařízení nebylo dostupné",
            "PORTAL_AUTHENTICATION_FAILED":"Nezdařilo se",
            "NOTIFICATION_CENTER":"Zprávy",
            "LEARNING_PROCESS":"Programovat",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Jméno uživatele musí mít 2 - 20 znaků",
            "WIFI_STATE_CONNECTED":"Spojeno",
            "COPY_PORTS":"Převzít z dálkového ovladače",
            "POPUP_SEARCH_CONTENT":"Vyhledávání bran Hörmann \n\nTento proces může trvat několik sekund.",
            "DESC_MANAGE_POPUPS_CANCEL":"Přerušit akci",
            "DESC_WIFI_PASSWORD":"Heslo",
            "DESC_WIFI_SAVE":"Uložit",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop aktivní",
            "SELECT_GATEWAY":"Brány",
            "CLEANING_PORTS":"Přidat zařízení",
            "WIFI_STATE_BUSY":"Spojení se vytváří",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Zadané heslo je nesprávné",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Změnit jméno brány",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Jméno se přebírá",
            "DESC_ACTORS_EDIT":"Spravovat nebo smazat zařízení",
            "DESC_WIFI_STATE":"Stav spojení",
            "ERROR_REMOVE_USER":"Nezdařilo se",
            "LANG_TAG":"CZ",
            "DESC_MANAGE_POPUPS_SUBMIT":"Převzít nastavení",
            "HOME_TITLE":"Hlavní stránka",
            "GENERAL_USERNAME":"Jméno uživatele",
            "DRIVE_MESSAGE_OPENED":"Otevřeno",
            "CONFIRM_DELETE":"Opravdu chcete bránu smazat?",
            "DRIVE_MESSAGE_CLOSED":"Zavřeno",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portálový server nebyl dostupný",
            "REMOVING_PROCESS_CONTENT":"Kanál se maže",
            "DESC_EDIT_USERS_BACK":"Zpět na nastavení",
            "ERROR_NO_GROUP_FOUND":"Zařízení nenalezeno",
            "ERROR_INVALID_GATEWAY":"Žádná brána nebyla nalezena",
            "DESC_WIFI_BACK":"Zpět na nastavení",
            "MAX_USERS_REACHED":"Není možné",
            "DESC_CHANGE_PASSWORD_USERNAME":"Jméno uživatele",
            "POPUP_AGREEMENT_ACCEPT_USE":"Akceptuji podmínky užívání",
            "ERROR_LERNING_PORT":"Nezdařilo se",
            "POPUP_ADD_GATEWAY_CONTENT":"Zadat adresu IP:",
            "ERROR_ADD_GROUP":"Chyba",
            "DRIVE_MESSAGE_NO_DATA":"Žádná data nejsou k dispozici",
            "CHANGE_PWD_FAILED":"Nezdařilo se",
            "SAVING_USER_RIGHTS_CONTENT":"Uživatelská práva se ukládají",
            "DRIVE_MESSAGE_UNLOCKED":"nezamknuto",
            "GENERAL_SAVE":"Uložit",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Spojit",
            "GATE_SECTIONAL_DOOR":"Svisle pohyblivá garážová vrata",
            "OPTIONS_CHANGE_PASSWORD":"Změnit heslo",
            "CHANNEL":"Obsluha",
            "CHANGE_GW_NAME_CONTENT":"Jméno brány",
            "DRIVE_MESSAGE_RETRACTED":"zasunuté",
            "DESC_ADDGWSCREEN_BACK":"Zpět k přehledu bran",
            "EMAIL_SUBJECT":"Podpora",
            "ERROR_EDIT_ADMIN":"Není možné",
            "OPTIONS_SET_USER_RIGHTS":"Uživatelská práva",
            "CHANGE_GW_NAME_ERROR":"Nezdařilo se",
            "CHANNEL_LIFT":"Zvedání",
            "LOGIN_FAILED_TITLE":"Nezdařilo se",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Jestliže smazání přihlašovacích dat potvrdíte stisknutím OK, musí se heslo při výběru brány znovu zadat.",
            "CHANNEL_UNLOCK":"Odemknout",
            "GENERAL_PORTAL_SERVER":"Portálový server",
            "DESC_SCENARIOS_BACK":"Zpět na hlavní nabídku",
            "CHANGE_PWD_USERNAME":"Uživatel:",
            "POPUP_GATE_NOT_RESPONSABLE":"Aplikace může tento povel vyslat na zařízení, nerozpozná však aktuální stav zařízení.",
            "DESC_GW_NAME":"Jméno brány",
            "GATE_BARRIER":"závora",
            "LEARN_PORTS":"Naprogramovat kód dálkového ovládání",
            "GENERAL_BACK":"Zpět",
            "DESC_GWSCREEN_EDIT":"K mazání uložených bran",
            "OPTIONS_MANAGE_POPUPS":"Spravovat místní hlášení",
            "POPUP_LOGIN_PROCESS_CONTENT":"Čekejte prosím...",
            "CONFIRM_DELETE_USER_CONTENT":"Opravdu chcete uživatele smazat?",
            "DESC_MENU":"Nabídka",
            "LOGIN_FAILED_WRONG_DATA":"Zadané jméno uživatele nebo heslo je nesprávné.",
            "GENERAL_CANCEL":"Storno",
            "ADD_GROUP":"Přidat zařízení",
            "WIFI_STATE_AP_NOT_FOUND":"Síť nenalezena",
            "WIFI_STATE_NOT_CONNECTED":"Nespojeno",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Vaše obsluha přes portál je aktivována!",
            "POPUP_ADD_GATEWAY":"Přidat bránu",
            "GENERAL_NEXT":"Další",
            "POPUP_SUPPRESS":"Místní nabídku již neotvírat",
            "POPUP_SEARCH_TITLE":"Vyhledávání...",
            "WIFI_SCANNING_CONTENT":"Vyhledej viditelné sítě WLAN",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Žádná brána nebyla nalezena",
            "DESC_ACTORS_ADD":"Vytvořit zařízení",
            "ERROR_ADD_GROUP_NO_TYPE":"Pro nové zařízení nebyl vybrán žádný typ.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Zkontrolujte přihlašovací údaje",
            "GENERAL_REFESHED":"Aktualizováno",
            "OPTIONS_SUPPRESS_WARNINGS":"Potlačit výstrahy",
            "LOGIN_FAILED_GATEWAY_BUSY":"Brána je vytížena. Zkuste to znovu.",
            "DESC_EMAIL":"Poslat e-mail na technickou podporu.",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Trvalé odemknutí vypnuto",
            "CLEANING_PORTS_CONTENT":"Připravuje se přidání",
            "DESC_HOME_ACTORS":"Naprogramovat a spravovat zařízení",
            "ERROR_TIMEOUT":"Chyba spojení",
            "CREATE_USER_TITLE":"Přidat uživatele",
            "ERROR_DELETE_ADMIN_CONTENT":"Správce nemůže být vymazán",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Rychlý přístup",
            "ADD_SCENARIO_NAME":"Jméno",
            "HIST":"Historie",
            "DESC_RESET_LOGIN_SUBMIT":"Potvrdit mazání",
            "POPUP_WARNING":"POZOR",
            "REMOVE_GROUP_PROCESS":"Zařízení se maže",
            "POPUP_LOGIN_PROCESS":"Přihlásit",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Čekejte prosím...",
            "DESC_DEFAULT_GW_SUBMIT":"Převzít nastavení",
            "DESC_CHANGE_PASSWORD_RETYPE":"Opakovat zadání",
            "LOAD_USERS_CONTENT":"Zavádějí se všichni uživatelé brány.\nTento proces může trvat několik sekund.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Je-li pro bránu aktivován rychlý přístup, aplikace se podle možností automaticky přihlásí.",
            "GATE_OTHER":"Ostatní zařízení",
            "CHANGE_PWD_USER_INVALID":"Chyba",
            "CHANNEL_LIGHT":"Světlo",
            "LOGIN_TITLE":"Přihlásit",
            "CHANNEL_HALF":"Částečné otevření",
            "GATEWAY_SCREEN_ADD_HELP":"K přidání brány zvolte symbol+.",
            "ERROR_TIMEOUT_CONTENT":"Překročení času při komunikaci s bránou",
            "ERROR_NO_PORTS_LEARNED":"Přidání není možné",
            "OPTIONS_SUPPRESS_INFOS":"Potlačit upozornění",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Chyba",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatický provoz",
            "GENERAL_DELETE":"Smazat",
            "GENERAL_PASSWORD":"Heslo",
            "STATE_COLLECTING_CONTENT":"Probíhá dotaz na stav zařízení",
            "ERROR_REMOVE_USER_CONTENT":"Uživatele se nepodařilo smazat",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Chyba",
            "ACTORS_ADD_HELP":"K přidání přístroje zvolte symbol+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Opravdu chcete zařízení smazat?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Čekejte prosím...",
            "GENERAL_YES":"Ano",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Před přidáním zařízení naprogramujte alespoň jeden kanál",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Jméno nebylo možné změnit.",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Aplikace ještě nenašla žádné brány.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Kontrola oprávnění se nezdařila",
            "DESC_MANAGE_POPUPS_INFOS":"Potlačit informační místní hlášení",
            "GATE_PILOMAT_POLLER":"Sloupek",
            "DESC_CHANNELS_STATE":"Stav zařízení schopného zpětného hlášení",
            "DESC_GWSCREEN_REFRESH":"Aktualizace seznamu bran",
            "POPUP_SCENARIO_DISPATCHING":"Scénář se provádí",
            "ERROR_PORT_UNREACHABLE":"Nezdařilo se",
            "POPUP_GATEWAY_FOUND_CONTENT":"Byly přidány tyto brány:",
            "WIFI_STATE_SECURITY_MISMATCH":"Druh šifrování WLAN není podporován",
            "LOGOUT_NAMED":"odhlásit",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Otevřít podmínky ochrany dat",
            "ERROR_NO_GW_CONTENT":"V místní síti nebyla nalezena žádná brána Hörmann.\nDalší brány přidejte pomocí znaku+",
            "DESC_EDIT_USERS_ADD":"Přidat uživatele",
            "ERROR_NO_PORT_FOUND":"Port nenalezen",
            "GATE_SLIDING_GATE":"Posuvná brána",
            "DESC_CHANNELS_BUTTONS":"Ovládací prvky zařízení",
            "DRIVE_MESSAGE_EXTENDED":"vysunuté",
            "WIFI_SELECTED_NETWORK":"Jméno",
            "ERROR_ADD_GROUP_NO_NAME":"Pro nové zařízení nebylo zadáno žádné jméno.",
            "DESC_HELP":"Funkce nápovědy",
            "CHANGE_PWD_NEW_PASSWORD":"Nové heslo",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Převzít nové heslo",
            "DESC_CHANGE_PASSWORD_PWD":"Zadání nového hesla",
            "ERROR_EDIT_ADMIN_CONTENT":"Administrátora nelze zpracovat",
            "CHANGE_GW_NAME_NAME_INVALID":"Nezdařilo se",
            "STATE_COLLECTING_FAILED":"Chyba",
            "GENERAL_ADD":"Přidat",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Heslo\" a \"Opakované zadání hesla\" musí být identické",
            "WIFI_SETTINGS":"Nastavení WLAN",
            "LEARN_PORTS_TITLE":"Přidat zařízení",
            "ERROR_CHANGE_USERNAME":"Nezdařilo se",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Road blok ",
            "ERROR_INVALID_GATEWAY_CONTENT":"Spojení s bránou nemohlo být vytvořeno. Ověřte jméno hosta.",
            "DESC_EDIT_USERS_EDIT":"Vymazat uživatele",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Jméno zařízení musí mít 2 - 20 znaků",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Rychlý přístup není možný",
            "CHANNEL_UP":"Otevřít",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Trvalé odemknutí zapnuto",
            "PORTAL_VALIDATION_FAILED":"Nezdařilo se",
            "DESC_RESET_LOGIN_CANCEL":"Přerušit akci",
            "CHANGE_PWD_SETTING_PASSWORD":"Převzít",
            "LOADING_GROUPS_TITLE":"Zavádí se",
            "DESC_DEFAULT_GW_CANCEL":"Přerušit akci",
            "DESC_SET_RIGHTS_SAVE":"Převzít změny",
            "REMOVING_PROCESS":"Smazat",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Brána není dostupná",
            "CONFIRM_DELETE_TITLE":"Smazat bránu",
            "SCENARIOS_ADD_HELP":"K přidání scénáře zvolte symbol+.",
            "LOGOUT":"Odhlášení",
            "DESC_ACTORS_BACK":"Zpět na hlavní nabídku",
            "ERROR_ADAPTER_BUSY_CONTENT":"Povel nemohl být proveden.\n Brána je vytížena.",
            "DESC_WIFI_NETWORK_SCAN":"Vyhledávat sítě",
            "DRIVE_MESSAGE_HALF":"Částečně otevřeno",
            "DESC_SCENARIOS_ADD":"Vytvořit scénář",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Komunikace s bránou selhala",
            "SAVING_USER_RIGHTS":"Ulož",
            "DESC_GWSCREEN_PORTAL":"Zadání dat portálu",
            "GATE_JACK":"Dálkově ovládaná zásuvka",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Jste na stejné síti jako vaše brána?",
            "GATE_DOOR":"Dveře",
            "POPUP_PORTAL_UNAVAILABLE":"Portálový server nebyl dostupný",
            "DESC_SET_RIGHTS_BACK":"Zpět na uživatele",
            "GATE_SMARTKEY":"Pohon zamykání dveří",
            "POPUP_GATEWAY_FOUND_TITILE":"Hledání ukončeno",
            "WIFI_LOADING_DATA_TITLE":"Zavádí se",
            "GENERAL_PORTS":"Kanály",
            "DESC_SCENARIOS_EDIT":"Spravovat nebo mazat scénáře",
            "OPTIONS_LEARNED_PORTS":"Naprogramované kanály:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Akceptuji podmínky ochrany dat",
            "DESC_EDIT_USERS_SET_RIGHTS":"Vybrat uživatele za účelem změny přístupových práv",
            "DRIVE_MESSAGE_HALF_MOVING":"Částečně otevřeno / pohybující se",
            "PORTAL_SET_ID_DIALOG":"Nastavení portálu",
            "DRIVE_MESSAGE_NOT_REFERENCED":"žádný referenční bod",
            "POPUP_SETTING_STATE":"Čekejte prosím...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/cs/podminky-pouzivani",
            "ERROR_CHANGE_USERNAME_CONTENT":"Uživatelské jméno se nepodařilo změnit",
            "GROUP_REQUESTABLE":"Zařízení je schopno zpětného hlášení",
            "LOADING_STATES_TITLE":"Zavádí se",
            "DESC_HOME_USERS":"Spravovat uživatele",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Heslo musí mít 4 - 20 znaků",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Heslo se přebírá",
            "POPUP_GATE_OUT_OF_VIEW":"Řídicí jednotka vratového zařízení na pohon bez dohledu na vrata je dovolena jen tehdy, jestliže navíc k standardně dodávané funkci mezní síly na vrata nainstalujete i světelnou závoru.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Zvolte, zda mají být místní hlášení zobrazena nebo potlačena",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorizováno",
            "DRIVE_MESSAGE_LOCKED":"zamknuto",
            "CHANNEL_DOWN":"Zavřít",
            "POPUP_INET_SPEED_LOW":"Vaše datové připojení pro tuto aplikaci nestačí",
            "CHANGE_PWD_FAILED_CONTENT":"Heslo se nepodařilo změnit",
            "GENERAL_GROUP_TYPE":"Typ přístroje",
            "CHANNEL_WALK":"Pohyblivé křídlo",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Vodorovně pohyblivá garážová vrata",
            "POPUP_AGREEMENT_CONTENT":"Před užíváním aplikace akceptujte podmínky ochrany dat / podmínky užívání",
            "INFO":"Informace",
            "LOADING_GROUPS_CONTENT":"Zavádí se zařízení",
            "GATE_PILOMAT_REIFENKILLER":"Hrotové bariéry",
            "GATE_PILOMAT_HUBBALKEN":"Dopravní závora",
            "GENERAL_RETYPE":"Opakované zadání hesla",
            "DESC_OTIONS_BACK":"Zpět na hlavní nabídku",
            "DESC_SET_RIGHTS":"Vybrat zařízení za účelem přidělení přístupových práv uživateli",
            "WIFI_SCANNING_TITLE":"Vyhledej",
            "WIFI_STATE_CONNECTION_FAILURE":"Navázání spojení se nezdařilo",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Jméno uživatele musí mít 2 - 20 znaků",
            "REMOVE_PORTS":"Smazat",
            "GENERAL_ON":"Zapnuto",
            "DESC_CHANGE_PASSWORD_CANCEL":"Přerušit akci",
            "LEARNING_PROCESS_CONTENT":"Čekejte prosím...",
            "LOGIN_FAILED_UNKNOWN":"Došlo k neočekávané chybě.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Uživatelská práva správce nelze měnit"
         };
         return _loc1_;
      }
   }
}
