package
{
   import mx.resources.ResourceBundle;
   
   public class da_DK$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function da_DK$LocalizedStrings_properties()
      {
         super("da_DK","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Låse",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Indtast adgangsdataene for Hörmann-portalen",
            "ERROR_DELETE_ADMIN":"Ikke mulig",
            "LOGIN_SHOULD_SAVE":"Gem data",
            "LOAD_USERS_TITLE":"Vent venligst",
            "CHANGE_GW_NAME_SETTING":"Overtag",
            "CONFIRM_DELETE_GROUP":"Slet apparat",
            "GENERAL_NO":"Nej",
            "DESC_GWSCREEN_ADD":"Tilføj lokale gateways",
            "DRIVE_MESSAGE_NOT_RETRACTED":"Ikke tilbagetrukket",
            "WIFI_PASSPHRASE":"Password",
            "CHANNEL_ON":"TIL",
            "SCENARIOS":"Scenarier",
            "ERROR_SET_ADMIN_RIGHTS":"Ikke mulig",
            "DESC_DEFAULT_GW_SAVE":"Indstil hurtig adgang for den aktuelle gateway",
            "POPUP_INFO":"OBS:",
            "DRIVE_MESSAGE_ERROR":"BEMÆRK!: Fejl",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/da/databeskyttelse",
            "DESC_WIFI_NETWORK_NAME":"Netværksnavn",
            "EMAIL_BODY":"Du kan sende dine spørgsmål til os pr. e-mail. Til dette formål står vores FAQ-funktion også til din rådighed.\n\nIhr BiSecur-Home Support-Team",
            "CONFIRM_DELETE_USER":"Slet bruger",
            "DESC_CHANNELS_BACK":"Tilbage til apparatlisten",
            "CHANGE_PWD_FIRST_START":"Af sikkerhedsårsager skal du ændre dit fabriksindstillede password efter den første ibrugtagning",
            "GENERAL_DEFAULT_GATEWAY":"Hurtig adgang",
            "CHANGE_PWD_PASSWORD_INVALID":"Fejl",
            "ERROR_NO_GW_TITLE":"Ingen gateways",
            "POPUP_SETTING_STATE_CONTENT":"Kommandoen udføres",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-data indlæses",
            "OPTIONS_RESET_LOGIN_DATA":"De gemte login-data slettes",
            "EDIT_USER_TITLE":"Redigér bruger",
            "DESC_HOME_PREFERENCES":"Ændr indstillingerne for gateway\'en og app\'en",
            "WIFI_ACTIVE_STATE":"WLAN-status",
            "STATE_COLLECTING":"Loader",
            "ADD_SCENARIO":"Tilføj scenarie",
            "STATE_COLLECTING_FAILED_CONTENT":"Statussen blev ikke indlæst",
            "GATE_SWING_GATE_SINGLE":"1-fløjet sidehængt låge",
            "ACTORS":"Apparater",
            "POPUP_AGREEMENT":"Brug / databeskyttelse",
            "CHANNEL_OPEN_DOOR":"Åbn",
            "DESC_ACTORS_REFRESH":"Aktualiser status",
            "GENERAL_OFF":"Frakoblet",
            "OPTIONS_HELP":"Online hjælp",
            "COPY_PORTS_CONTENT":"Stil senderen i overførselsmodus, se vejledningen. Vælg kanalen, der skal overføres.",
            "GENERAL_SELECT":"Vælg venligst ...",
            "ERROR_ADAPTER_BUSY":"Fejl",
            "INFO_BOX_INFOS":"Generelt",
            "GATE_LIGHT":"Lys",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Åbn vilkår for brugen",
            "DESC_MANAGE_POPUPS_WARNINGS":"Ignorer advarsels-pop-up-vinduer",
            "MAX_USERSS_REACHED_CONTENT":"Det maks. antal brugere er nået.",
            "GENERAL_REMOVE":"Fjern",
            "OPTIONS":"Indstillinger",
            "DESC_HOME_SCENARIOS":"Opret og administrer scenarier",
            "CHANNEL_OFF":"FRA",
            "GENERAL_PORTAL_ID":"Apparat-ID",
            "EDIT_GROUP":"Bearbejd apparat",
            "ERROR_LERANIN_PORT_CONTENT":"Indlæringen af den ønskede kanal mislykkedes",
            "ERROR_CONNECTION_CLOSED":"Fejl",
            "CHANNEL_ON_OFF":"TIL / FRA",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Betegnelse",
            "OPTIONS_EDIT_USERS":"Administrér brugere",
            "LOADING_STATES_CONTENT":"Den aktuelle status hentes.\nVent venligst ...",
            "LERAN_PORTS_CONTENT":"Stil apparatet i indlæringsmodus, se vejledningen. Vælg kanalen, der skal indlæres.",
            "REMOVE_PORTS_CONTENT":"Vælg kanalerne, som du ønsker at slette.",
            "GATE_SWING_GATE_DOUBLE":"2-fløjet sidehængt låge",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Kontrollér, om du har indtastet dine portaldata eller tilføjet en lokal gateway.",
            "CHANNEL_SINK":"Sænke",
            "OPTIONS_EDIT_USERS_TITLE":"Bruger",
            "MAX_PORTS_REACHED_CONTENT":"Maks. antal kanaler optaget",
            "MAX_PORTS_REACHED":"Ikke mulig",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Det pågældende apparat står ikke til rådighed",
            "PORTAL_AUTHENTICATION_FAILED":"Mislykkedes",
            "NOTIFICATION_CENTER":"Beskeder",
            "LEARNING_PROCESS":"Indlæring",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Brugernavnet skal bestå af 2 - 20 tegn",
            "WIFI_STATE_CONNECTED":"Forbundet",
            "COPY_PORTS":"Overfør fra håndsender",
            "POPUP_SEARCH_CONTENT":"Søger efter Hörmann-gateways \n\nDenne procedure kan vare nogle sekunder.",
            "DESC_MANAGE_POPUPS_CANCEL":"Afbryd handling",
            "DESC_WIFI_PASSWORD":"Password",
            "DESC_WIFI_SAVE":"Gem",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop aktivt",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Tilføj apparat",
            "WIFI_STATE_BUSY":"Forbindelsen oprettes",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Det indtastede password er forkert",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Ændr gateway-navn",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Navnet overtages",
            "DESC_ACTORS_EDIT":"Administrer eller slet apparater",
            "DESC_WIFI_STATE":"Forbindelsesstatus",
            "ERROR_REMOVE_USER":"Mislykkedes",
            "LANG_TAG":"DA",
            "DESC_MANAGE_POPUPS_SUBMIT":"Overtag indstilling",
            "HOME_TITLE":"Startside",
            "GENERAL_USERNAME":"Brugernavn",
            "DRIVE_MESSAGE_OPENED":"Åben",
            "CONFIRM_DELETE":"Er du sikker på, at du vil slette gateway\'en?",
            "DRIVE_MESSAGE_CLOSED":"Lukket",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portal serveren står ikke til rådighed",
            "REMOVING_PROCESS_CONTENT":"Kanalen slettes",
            "DESC_EDIT_USERS_BACK":"Tilbage til indstillinger",
            "ERROR_NO_GROUP_FOUND":"Apparat kunne ikke findes",
            "ERROR_INVALID_GATEWAY":"Gateway kunne ikke findes",
            "DESC_WIFI_BACK":"Tilbage til indstillingerne",
            "MAX_USERS_REACHED":"Ikke mulig",
            "DESC_CHANGE_PASSWORD_USERNAME":"Brugernavn",
            "POPUP_AGREEMENT_ACCEPT_USE":"Jeg accepterer vilkårene for brugen",
            "ERROR_LERNING_PORT":"Mislykkedes",
            "POPUP_ADD_GATEWAY_CONTENT":"Indtast IP-adresse:",
            "ERROR_ADD_GROUP":"Fejl",
            "DRIVE_MESSAGE_NO_DATA":"Der foreligger ingen data",
            "CHANGE_PWD_FAILED":"Mislykkedes",
            "SAVING_USER_RIGHTS_CONTENT":"Brugerrettighederne gemmes",
            "DRIVE_MESSAGE_UNLOCKED":"Ikke låst",
            "GENERAL_SAVE":"Gem",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Forbind",
            "GATE_SECTIONAL_DOOR":"Garageport med vertikal åbning",
            "OPTIONS_CHANGE_PASSWORD":"Ændr password",
            "CHANNEL":"Betjening",
            "CHANGE_GW_NAME_CONTENT":"Gateway-navn",
            "DRIVE_MESSAGE_RETRACTED":"Tilbagetrukket",
            "DESC_ADDGWSCREEN_BACK":"Tilbage til gateway-oversigt",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Ikke mulig",
            "OPTIONS_SET_USER_RIGHTS":"Brugerrettigheder",
            "CHANGE_GW_NAME_ERROR":"Mislykkedes",
            "CHANNEL_LIFT":"Hæve",
            "LOGIN_FAILED_TITLE":"Mislykkedes",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Hvis du bekræfter sletningen af login-dataene med OK, skal dit password indtastes igen, når du vælger gateway\'en",
            "CHANNEL_UNLOCK":"Oplås",
            "GENERAL_PORTAL_SERVER":"Portal server",
            "DESC_SCENARIOS_BACK":"Tilbage til hovedmenuen",
            "CHANGE_PWD_USERNAME":"Bruger:",
            "POPUP_GATE_NOT_RESPONSABLE":"App\'en kan sende kommandoen til apparatet, men registrerer ikke apparatets aktuelle tilstand.",
            "DESC_GW_NAME":"Gateway-navn",
            "GATE_BARRIER":"bom",
            "LEARN_PORTS":"Indlær trådløs kode",
            "GENERAL_BACK":"Tilbage",
            "DESC_GWSCREEN_EDIT":"Til sletning af gemte gateways",
            "OPTIONS_MANAGE_POPUPS":"Administrér pop-up-beskeder",
            "POPUP_LOGIN_PROCESS_CONTENT":"Vent venligst ...",
            "CONFIRM_DELETE_USER_CONTENT":"Er du sikker på, at du vil slette brugeren?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"Det indtastede brugernavn eller password er forkert",
            "GENERAL_CANCEL":"Afbryd",
            "ADD_GROUP":"Tilføj apparat",
            "WIFI_STATE_AP_NOT_FOUND":"Netværk kunne ikke findes",
            "WIFI_STATE_NOT_CONNECTED":"Ikke forbundet",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Din betjening via portalen er aktiveret!",
            "POPUP_ADD_GATEWAY":"Tilføj gateway",
            "GENERAL_NEXT":"Næste",
            "POPUP_SUPPRESS":"Åbn ikke pop-up igen",
            "POPUP_SEARCH_TITLE":"Søgning ...",
            "WIFI_SCANNING_CONTENT":"Søgning efter synlige WLAN-netværk",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Gateway kunne ikke findes",
            "DESC_ACTORS_ADD":"Opret apparat",
            "ERROR_ADD_GROUP_NO_TYPE":"Der blev ikke valgt nogen type for det nye apparat.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Kontrollér dine login-data",
            "GENERAL_REFESHED":"Aktualiseret",
            "OPTIONS_SUPPRESS_WARNINGS":"Ignorer advarsler",
            "LOGIN_FAILED_GATEWAY_BUSY":"Gateway\'en er optaget. Forsøg igen.",
            "DESC_EMAIL":"Send e-mail til support\'en",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Konstant åben FRA",
            "CLEANING_PORTS_CONTENT":"Tilføjelse forberedes",
            "DESC_HOME_ACTORS":"Indlær og administrer apparater",
            "ERROR_TIMEOUT":"Forbindelsesfejl",
            "CREATE_USER_TITLE":"Tilføj bruger",
            "ERROR_DELETE_ADMIN_CONTENT":"Administratoren kan ikke slettes",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Hurtig adgang",
            "ADD_SCENARIO_NAME":"Navn",
            "HIST":"Historik",
            "DESC_RESET_LOGIN_SUBMIT":"Bekræft sletning",
            "POPUP_WARNING":"BEMÆRK!",
            "REMOVE_GROUP_PROCESS":"Apparatet slettes",
            "POPUP_LOGIN_PROCESS":"Tilmeld",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Vent venligst ...",
            "DESC_DEFAULT_GW_SUBMIT":"Overtag indstilling",
            "DESC_CHANGE_PASSWORD_RETYPE":"Gentag indtastning",
            "LOAD_USERS_CONTENT":"Alle gateway-brugerne indlæses.\nDenne procedure kan vare nogle sekunder.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Hvis hurtig adgang er aktiveret for en gateway, logger app\'en sig så vidt muligt automatisk på",
            "GATE_OTHER":"Andre apparater",
            "CHANGE_PWD_USER_INVALID":"Fejl",
            "CHANNEL_LIGHT":"Lys",
            "LOGIN_TITLE":"Tilmeld",
            "CHANNEL_HALF":"Delåbning",
            "GATEWAY_SCREEN_ADD_HELP":"Vælg +symbolet for at tilføje en gateway.",
            "ERROR_TIMEOUT_CONTENT":"Tidsoverskridelse ved kommunikation med gateway\'en",
            "ERROR_NO_PORTS_LEARNED":"Kan ikke tilføjes",
            "OPTIONS_SUPPRESS_INFOS":"Ignorer anvisninger",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Fejl",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatisk drift",
            "GENERAL_DELETE":"Slet",
            "GENERAL_PASSWORD":"Password",
            "STATE_COLLECTING_CONTENT":"Der forespørges om apparaternes status",
            "ERROR_REMOVE_USER_CONTENT":"Brugeren blev ikke slettet",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Fejl",
            "ACTORS_ADD_HELP":"Vælg +symbolet for at tilføje et apparat.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Er du sikker på, at du vil slette apparatet?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Vent venligst ...",
            "GENERAL_YES":"Ja",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Der skal indlæres mindst en kanal, inden der tilføjes et apparat",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Navnet kunne ikke ændres",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"App\'en har ikke fundet nogen gateways endnu.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentificering mislykkedes",
            "DESC_MANAGE_POPUPS_INFOS":"Ignorer informations-pop-up-vinduer",
            "GATE_PILOMAT_POLLER":"Pullert",
            "DESC_CHANNELS_STATE":"Status for apparatet, der egner sig til tilbagemelding",
            "DESC_GWSCREEN_REFRESH":"Aktualisering af gateway-listen",
            "POPUP_SCENARIO_DISPATCHING":"Scenarie udføres",
            "ERROR_PORT_UNREACHABLE":"Mislykkedes",
            "POPUP_GATEWAY_FOUND_CONTENT":"Der blev tilføjet følgende gateways:",
            "WIFI_STATE_SECURITY_MISMATCH":"WLAN-netværkets kryptering understøttes ikke",
            "LOGOUT_NAMED":"log af",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Åbn vilkår for databeskyttelsen",
            "ERROR_NO_GW_CONTENT":"Der kunne ikke findes nogen Hörmann-gateway i det lokale netværk.\nTilføj yderligere gateways med tegnet+",
            "DESC_EDIT_USERS_ADD":"Tilføj bruger",
            "ERROR_NO_PORT_FOUND":"Port kunne ikke findes",
            "GATE_SLIDING_GATE":"Skydelåge",
            "DESC_CHANNELS_BUTTONS":"Apparatets betjeningselementer",
            "DRIVE_MESSAGE_EXTENDED":"Forlænget",
            "WIFI_SELECTED_NETWORK":"Navn",
            "ERROR_ADD_GROUP_NO_NAME":"Der blev ikke indtastet et navn for det nye apparat.",
            "DESC_HELP":"Hjælpefunktion",
            "CHANGE_PWD_NEW_PASSWORD":"Nyt password",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Overtag nyt password",
            "DESC_CHANGE_PASSWORD_PWD":"Indtastning af nyt password",
            "ERROR_EDIT_ADMIN_CONTENT":"Administratoren kan ikke bearbejdes",
            "CHANGE_GW_NAME_NAME_INVALID":"Mislykkedes",
            "STATE_COLLECTING_FAILED":"Fejl",
            "GENERAL_ADD":"Tilføj",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Password\" og \"Gentag password\" skal være identiske",
            "WIFI_SETTINGS":"WLAN-indstillinger",
            "LEARN_PORTS_TITLE":"Tilføj apparat",
            "ERROR_CHANGE_USERNAME":"Mislykkedes",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Spærret for gennemkørsel",
            "ERROR_INVALID_GATEWAY_CONTENT":"Der kunne ikke oprettes forbindelse til gateway\'en. Kontrollér host-navnet.",
            "DESC_EDIT_USERS_EDIT":"Slet bruger",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Apparatnavnet skal bestå af 2 - 20 tegn",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Hurtig adgang ikke mulig",
            "CHANNEL_UP":"Åben",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Konstant åben TIL",
            "PORTAL_VALIDATION_FAILED":"Mislykkedes",
            "DESC_RESET_LOGIN_CANCEL":"Afbryd handling",
            "CHANGE_PWD_SETTING_PASSWORD":"Overtag",
            "LOADING_GROUPS_TITLE":"Loader",
            "DESC_DEFAULT_GW_CANCEL":"Afbryd handling",
            "DESC_SET_RIGHTS_SAVE":"Overtag ændringer",
            "REMOVING_PROCESS":"Slet",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Gateway\'en står ikke til rådighed",
            "CONFIRM_DELETE_TITLE":"Slet gateway",
            "SCENARIOS_ADD_HELP":"Vælg +symbolet for at tilføje et scenarie.",
            "LOGOUT":"Log af",
            "DESC_ACTORS_BACK":"Tilbage til hovedmenuen",
            "ERROR_ADAPTER_BUSY_CONTENT":"Kommandoen kunne ikke udføres.\n Gateway\'en er optaget.",
            "DESC_WIFI_NETWORK_SCAN":"Søg efter netværk",
            "DRIVE_MESSAGE_HALF":"Delvist åben",
            "DESC_SCENARIOS_ADD":"Opret scenarie",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Kommunikationen med gateway\'en mislykkedes",
            "SAVING_USER_RIGHTS":"Gemmer",
            "DESC_GWSCREEN_PORTAL":"Indtastning af portaldata",
            "GATE_JACK":"Trådløs stikdåse",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Er du i det samme netværk som din gateway?",
            "GATE_DOOR":"Dør",
            "POPUP_PORTAL_UNAVAILABLE":"Portal serveren står ikke til rådighed",
            "DESC_SET_RIGHTS_BACK":"Tilbage til brugere",
            "GATE_SMARTKEY":"Dørlåsdrev",
            "POPUP_GATEWAY_FOUND_TITILE":"Søgning afsluttet",
            "WIFI_LOADING_DATA_TITLE":"Loader",
            "GENERAL_PORTS":"Kanaler",
            "DESC_SCENARIOS_EDIT":"Administrer eller slet scenarier",
            "OPTIONS_LEARNED_PORTS":"Indlærte kanaler:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Jeg accepterer vilkårene for databeskyttelsen",
            "DESC_EDIT_USERS_SET_RIGHTS":"Vælg bruger for at ændre brugerens adgangsrettigheder",
            "DRIVE_MESSAGE_HALF_MOVING":"Delvist åben / kører",
            "PORTAL_SET_ID_DIALOG":"Portalindstillinger",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Intet referencepunkt",
            "POPUP_SETTING_STATE":"Vent venligst ...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/da/vilkar-for-brug",
            "ERROR_CHANGE_USERNAME_CONTENT":"Brugernavnet blev ikke ændret",
            "GROUP_REQUESTABLE":"Apparatet egner sig til at sende tilbagemelding",
            "LOADING_STATES_TITLE":"Loader",
            "DESC_HOME_USERS":"Administrér brugere",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Dit password skal bestå af 4 - 20 tegn",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Password overtages",
            "POPUP_GATE_OUT_OF_VIEW":"Styringen af et automatisk portanlæg uden udsyn til porten er kun tilladt, hvis der i tillæg til den standardmæssige kraftbegrænsning er installeret en fotocelle på porten.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Vælg, om pop-up-beskeder skal vises eller ignoreres",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Autoriseret",
            "DRIVE_MESSAGE_LOCKED":"Låst",
            "CHANNEL_DOWN":"Lukket",
            "POPUP_INET_SPEED_LOW":"Din dataforbindelse er ikke tilstrækkelig til denne anvendelse",
            "CHANGE_PWD_FAILED_CONTENT":"Adgangskoden blev ikke ændret",
            "GENERAL_GROUP_TYPE":"Apparattype",
            "CHANNEL_WALK":"Gangfløj",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Garageport med horisontal åbning",
            "POPUP_AGREEMENT_CONTENT":"Du skal acceptere vilkårene for databeskyttelse / brug, inden du tager app\'en i brug",
            "INFO":"Informationer",
            "LOADING_GROUPS_CONTENT":"Indlæser apparater",
            "GATE_PILOMAT_REIFENKILLER":"Sømmåtter",
            "GATE_PILOMAT_HUBBALKEN":"Løftebomme",
            "GENERAL_RETYPE":"Gentag password",
            "DESC_OTIONS_BACK":"Tilbage til hovedmenuen",
            "DESC_SET_RIGHTS":"Vælg apparat for at tildele brugeren adgangsrettigheder",
            "WIFI_SCANNING_TITLE":"Søgning",
            "WIFI_STATE_CONNECTION_FAILURE":"Opbygning af forbindelse mislykkedes",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Brugernavnet skal bestå af 2 - 20 tegn",
            "REMOVE_PORTS":"Slet",
            "GENERAL_ON":"Tilkoblet",
            "DESC_CHANGE_PASSWORD_CANCEL":"Afbryd handling",
            "LEARNING_PROCESS_CONTENT":"Vent venligst ...",
            "LOGIN_FAILED_UNKNOWN":"Der er opstået en uventet fejl",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Administratorens brugerrettigheder kunne ikke ændres"
         };
         return _loc1_;
      }
   }
}
