package
{
   import mx.resources.ResourceBundle;
   
   public class de_DE$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function de_DE$LocalizedStrings_properties()
      {
         super("de_DE","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "PORTAL_SET_ID_DIALOG_CONTENT":"Tragen Sie die Hörmann-Portal Zugangsdaten ein",
            "ERROR_DELETE_ADMIN":"Nicht möglich",
            "CHANNEL_LOCK":"Verriegeln",
            "LOGIN_SHOULD_SAVE":"Daten speichern",
            "LOAD_USERS_TITLE":"Bitte warten",
            "CHANGE_GW_NAME_SETTING":"Übernehmen",
            "CONFIRM_DELETE_GROUP":"Gerät löschen",
            "GENERAL_NO":"Nein",
            "DESC_GWSCREEN_ADD":"Lokale Gateways hinzufügen",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nicht eingefahren",
            "WIFI_PASSPHRASE":"Passwort",
            "CHANNEL_ON":"Ein",
            "SCENARIOS":"Szenarien",
            "ERROR_SET_ADMIN_RIGHTS":"Nicht möglich",
            "DESC_DEFAULT_GW_SAVE":"Schnellzugriff für aktuelles Gateway einrichten",
            "POPUP_INFO":"Hinweis",
            "DRIVE_MESSAGE_ERROR":"ACHTUNG: Fehler",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/datenschutz",
            "DESC_WIFI_NETWORK_NAME":"Netzwerkname",
            "EMAIL_BODY":"Ihre Fragen können Sie uns per E-Mail zusenden. Hierfür steht Ihnen auch unsere FAQ-Funktion zur Verfügung.\n\nIhr BiSecur-Home Support-Team",
            "CONFIRM_DELETE_USER":"Benutzer löschen",
            "DESC_CHANNELS_BACK":"Zurück zur Geräteliste",
            "CHANGE_PWD_FIRST_START":"Ändern Sie aus Sicherheitsgründen die Werkseinstellung ihres Passwortes nach Erstanmeldung",
            "GENERAL_DEFAULT_GATEWAY":"Schnellzugriff",
            "CHANGE_PWD_PASSWORD_INVALID":"Fehler",
            "ERROR_NO_GW_TITLE":"Keine Gateways",
            "POPUP_SETTING_STATE_CONTENT":"Der Befehl wird durchgeführt",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-Daten werden geladen",
            "OPTIONS_RESET_LOGIN_DATA":"Gespeicherte Logindaten löschen",
            "EDIT_USER_TITLE":"Benutzer bearbeiten",
            "DESC_HOME_PREFERENCES":"Einstellungen zu Gateway und App ändern",
            "WIFI_ACTIVE_STATE":"WLAN Status",
            "STATE_COLLECTING":"Lade",
            "ADD_SCENARIO":"Szenario hinzufügen",
            "STATE_COLLECTING_FAILED_CONTENT":"Status wurde nicht geladen",
            "GATE_SWING_GATE_SINGLE":"1-flg. Drehtor",
            "ACTORS":"Geräte",
            "POPUP_AGREEMENT":"Nutzung / Datenschutz",
            "CHANNEL_OPEN_DOOR":"Öffnen",
            "DESC_ACTORS_REFRESH":"Status aktualisieren",
            "GENERAL_OFF":"Ausgeschaltet",
            "OPTIONS_HELP":"Online-Hilfe",
            "COPY_PORTS_CONTENT":"Versetzen Sie den Sender in den Vererbungsmodus, siehe Anleitung. Wählen Sie den erbenden Kanal.",
            "GENERAL_SELECT":"Bitte wählen...",
            "ERROR_ADAPTER_BUSY":"Fehler",
            "INFO_BOX_INFOS":"Allgemein",
            "GATE_LIGHT":"Licht",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Nutzungsbedingungen öffnen",
            "DESC_MANAGE_POPUPS_WARNINGS":"Warnungs-Popups unterdrücken",
            "MAX_USERSS_REACHED_CONTENT":"Die maximale Anzahl der Benutzer wurde erreicht.",
            "GENERAL_REMOVE":"Entfernen",
            "OPTIONS":"Einstellungen",
            "DESC_HOME_SCENARIOS":"Szenarien erstellen und verwalten",
            "CHANNEL_OFF":"Aus",
            "GENERAL_PORTAL_ID":"Geräte ID",
            "EDIT_GROUP":"Gerät bearbeiten",
            "ERROR_LERANIN_PORT_CONTENT":"Das Einlernen des gewünschten Kanals ist fehlgeschlagen",
            "ERROR_CONNECTION_CLOSED":"Fehler",
            "CHANNEL_ON_OFF":"Ein / Aus",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Bezeichnung",
            "OPTIONS_EDIT_USERS":"Benutzer verwalten",
            "LOADING_STATES_CONTENT":"Der aktuelle Status wird abgerufen.\nBitte warten...",
            "LERAN_PORTS_CONTENT":"Versetzen Sie das Gerät in den Einlernmodus, siehe Anleitung. Wählen Sie den einzulernenden Kanal.",
            "REMOVE_PORTS_CONTENT":"Wählen Sie die Kanäle aus, die Sie löschen möchten.",
            "GATE_SWING_GATE_DOUBLE":"2-flg. Drehtor",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Prüfen Sie, ob Sie Ihre Portaldaten eingetragen oder ein lokales Gateway hinzugefügt haben.",
            "CHANNEL_SINK":"Senken",
            "OPTIONS_EDIT_USERS_TITLE":"Benutzer",
            "MAX_PORTS_REACHED_CONTENT":"Maximale Anzahl der Kanäle belegt",
            "MAX_PORTS_REACHED":"Nicht möglich",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Das angefragte Gerät konnte nicht erreicht werden",
            "PORTAL_AUTHENTICATION_FAILED":"Fehlgeschlagen",
            "NOTIFICATION_CENTER":"Benachrichtigungen",
            "LEARNING_PROCESS":"Einlernen",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Der Benutzname muss aus 2 - 20 Zeichen bestehen",
            "WIFI_STATE_CONNECTED":"Verbunden",
            "COPY_PORTS":"Von Handsender vererben",
            "POPUP_SEARCH_CONTENT":"Suche nach Hörmann-Gateways \n\nDieser Vorgang kann einige Sekunden in Anspruch nehmen.",
            "DESC_MANAGE_POPUPS_CANCEL":"Aktion abbrechen",
            "DESC_WIFI_PASSWORD":"Passwort",
            "DESC_WIFI_SAVE":"Speichern",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stopp aktiv",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Gerät hinzufügen",
            "WIFI_STATE_BUSY":"Verbindung wird hergestellt",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Das eingegebene Passwort ist falsch",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Name des Gateways ändern",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Der Name wird übernommen",
            "DESC_WIFI_STATE":"Verbindungsstatus",
            "DESC_ACTORS_EDIT":"Geräte verwalten oder löschen",
            "LANG_TAG":"DE",
            "ERROR_REMOVE_USER":"Fehlgeschlagen",
            "DESC_MANAGE_POPUPS_SUBMIT":"Einstellung übernehmen",
            "HOME_TITLE":"Hauptseite",
            "GENERAL_USERNAME":"Benutzername",
            "DRIVE_MESSAGE_OPENED":"Geöffnet",
            "CONFIRM_DELETE":"Sind Sie sicher, dass Sie das Gateway löschen möchten?",
            "DRIVE_MESSAGE_CLOSED":"Geschlossen",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Der Portalserver konnte nicht erreicht werden",
            "REMOVING_PROCESS_CONTENT":"Der Kanal wird gelöscht",
            "DESC_EDIT_USERS_BACK":"Zurück zu Einstellungen",
            "ERROR_NO_GROUP_FOUND":"Gerät nicht gefunden",
            "ERROR_INVALID_GATEWAY":"Kein Gateway gefunden",
            "DESC_WIFI_BACK":"Zurück zu den Einstellungen",
            "MAX_USERS_REACHED":"Nicht möglich",
            "DESC_CHANGE_PASSWORD_USERNAME":"Benutzername",
            "POPUP_AGREEMENT_ACCEPT_USE":"Ich akzeptiere die Nutzungsbedingungen",
            "ERROR_LERNING_PORT":"Fehlgeschlagen",
            "POPUP_ADD_GATEWAY_CONTENT":"IP Adresse eintragen:",
            "ERROR_ADD_GROUP":"Fehler",
            "DRIVE_MESSAGE_NO_DATA":"Keine Daten verfügbar",
            "CHANGE_PWD_FAILED":"Fehlgeschlagen",
            "SAVING_USER_RIGHTS_CONTENT":"Benutzerrechte werden gespeichert",
            "DRIVE_MESSAGE_UNLOCKED":"nicht verriegelt",
            "GENERAL_SAVE":"Speichern",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Verbinden",
            "GATE_SECTIONAL_DOOR":"Vertikal laufendes Garagentor",
            "OPTIONS_CHANGE_PASSWORD":"Passwort ändern",
            "CHANNEL":"Bedienung",
            "CHANGE_GW_NAME_CONTENT":"Name des Gateways",
            "DRIVE_MESSAGE_RETRACTED":"eingefahren",
            "DESC_ADDGWSCREEN_BACK":"Zurück zur Gateway-Übersicht",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Nicht möglich",
            "OPTIONS_SET_USER_RIGHTS":"Benutzerrechte",
            "CHANGE_GW_NAME_ERROR":"Fehlgeschlagen",
            "CHANNEL_LIFT":"Heben",
            "LOGIN_FAILED_TITLE":"Fehlgeschlagen",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Wenn Sie das Löschen der Logindaten mit OK bestätigen, muss das Passwort beim Auswählen des Gateways erneut eingegeben werden",
            "CHANNEL_UNLOCK":"Entriegeln",
            "GENERAL_PORTAL_SERVER":"Portal Server",
            "DESC_SCENARIOS_BACK":"Zurück zum Hauptmenü",
            "CHANGE_PWD_USERNAME":"Benutzer:",
            "DESC_GW_NAME":"Name des Gateways",
            "POPUP_GATE_NOT_RESPONSABLE":"Die App kann diesen Befehl an das Gerät senden, erkennt aber nicht den aktuellen Zustand des Gerätes.",
            "GATE_BARRIER":"Schranke",
            "LEARN_PORTS":"Funkcode einlernen",
            "GENERAL_BACK":"Zurück",
            "DESC_GWSCREEN_EDIT":"Zum Löschen gespeicherter Gateways",
            "OPTIONS_MANAGE_POPUPS":"Popup-Meldungen verwalten",
            "POPUP_LOGIN_PROCESS_CONTENT":"Bitte warten...",
            "CONFIRM_DELETE_USER_CONTENT":"Sind Sie sicher, dass Sie den Benutzer löschen möchten?",
            "DESC_MENU":"Menü",
            "LOGIN_FAILED_WRONG_DATA":"Der eingegebene Benutzername oder das Passwort ist falsch",
            "GENERAL_CANCEL":"Abbrechen",
            "ADD_GROUP":"Gerät hinzufügen",
            "WIFI_STATE_AP_NOT_FOUND":"Netzwerk nicht gefunden",
            "WIFI_STATE_NOT_CONNECTED":"Nicht verbunden",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Ihre Bedienung über das Portal ist aktiviert!",
            "POPUP_ADD_GATEWAY":"Gateway hinzufügen",
            "GENERAL_NEXT":"Weiter",
            "POPUP_SUPPRESS":"Popup nicht mehr öffnen",
            "POPUP_SEARCH_TITLE":"Suche...",
            "WIFI_SCANNING_CONTENT":"Suche nach sichtbaren WLAN Netzwerken",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Kein Gateway gefunden",
            "DESC_ACTORS_ADD":"Gerät erstellen",
            "ERROR_ADD_GROUP_NO_TYPE":"Es wurde kein Typ für das neue Gerät gewählt.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Überprüfen Sie die Logindaten",
            "GENERAL_REFESHED":"Aktualisiert",
            "OPTIONS_SUPPRESS_WARNINGS":"Warnungen unterdrücken",
            "LOGIN_FAILED_GATEWAY_BUSY":"Das Gateway ist ausgelastet. Versuchen Sie es erneut.",
            "DESC_EMAIL":"E-Mail an den Support senden",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Dauer-Auf Aus",
            "CLEANING_PORTS_CONTENT":"Hinzufügen wird vorbereitet",
            "DESC_HOME_ACTORS":"Geräte einlernen und verwalten",
            "ERROR_TIMEOUT":"Verbindungsfehler",
            "CREATE_USER_TITLE":"Benutzer hinzufügen",
            "ERROR_DELETE_ADMIN_CONTENT":"Der Administrator kann nicht gelöscht werden",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Schnellzugriff",
            "ADD_SCENARIO_NAME":"Name",
            "HIST":"Historie",
            "DESC_RESET_LOGIN_SUBMIT":"Löschen bestätigen",
            "POPUP_WARNING":"ACHTUNG",
            "REMOVE_GROUP_PROCESS":"Das Gerät wird gelöscht",
            "POPUP_LOGIN_PROCESS":"Anmelden",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Bitte warten...",
            "DESC_DEFAULT_GW_SUBMIT":"Einstellung übernehmen",
            "DESC_CHANGE_PASSWORD_RETYPE":"Eingabe wiederholen",
            "LOAD_USERS_CONTENT":"Es werden alle Benutzer vom Gateway geladen.\nDieser Vorgang kann einige Sekunden in Anspruch nehmen.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Ist für ein Gateway der Schnellzugriff aktiviert, loggt sich die App nach Möglichkeit automatisch ein",
            "GATE_OTHER":"Sonstige Geräte",
            "CHANGE_PWD_USER_INVALID":"Fehler",
            "CHANNEL_LIGHT":"Licht",
            "LOGIN_TITLE":"Anmelden",
            "CHANNEL_HALF":"Teilöffnung",
            "GATEWAY_SCREEN_ADD_HELP":"Zum Hinzufügen eines Gateways wählen Sie das +Symbol.",
            "ERROR_TIMEOUT_CONTENT":"Zeitüberschreitung bei der Kommunikation mit dem Gateway",
            "ERROR_NO_PORTS_LEARNED":"Hinzufügen nicht möglich",
            "OPTIONS_SUPPRESS_INFOS":"Hinweise unterdrücken",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Fehler",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatikbetrieb",
            "GENERAL_DELETE":"Löschen",
            "GENERAL_PASSWORD":"Passwort",
            "STATE_COLLECTING_CONTENT":"Status der Geräte wird angefragt",
            "ERROR_REMOVE_USER_CONTENT":"Der Benutzer konnte nicht gelöscht werden",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Fehler",
            "ACTORS_ADD_HELP":"Zum Hinzufügen eines Geräts wählen Sie das +Symbol.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Sind Sie sicher, dass Sie das Gerät löschen möchten?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Bitte warten...",
            "GENERAL_YES":"Ja",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Vor Hinzufügen eines Gerätes mindestens einen Kanal einlernen",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Der Name konnte nicht geändert werden",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Die App hat noch keine Gateways gefunden.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Authentifizierung fehlgeschlagen",
            "DESC_MANAGE_POPUPS_INFOS":"Informations-Popups unterdrücken",
            "GATE_PILOMAT_POLLER":"Poller",
            "DESC_CHANNELS_STATE":"Status des rückmeldefähigen Gerätes",
            "DESC_GWSCREEN_REFRESH":"Aktualisieren der Gatewayliste",
            "POPUP_SCENARIO_DISPATCHING":"Szenario wird ausgeführt",
            "ERROR_PORT_UNREACHABLE":"Fehlgeschlagen",
            "POPUP_GATEWAY_FOUND_CONTENT":"Folgende Gateways wurden hinzugefügt:",
            "WIFI_STATE_SECURITY_MISMATCH":"Die Verschlüsselungsart des WLANs wird nicht untersützt",
            "LOGOUT_NAMED":"abmelden",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Datenschutzbedingungen öffnen",
            "DESC_EDIT_USERS_ADD":"Benutzer hinzufügen",
            "ERROR_NO_GW_CONTENT":"Es konnte kein Hörmann-Gateway im lokalen Netzwerk gefunden werden.\nWeitere Gateways über das + Zeichen hinzufügen",
            "ERROR_NO_PORT_FOUND":"Port nicht gefunden",
            "GENERAL_PRESENTER_ACTIVE":"Im Demomodus nicht möglich...",
            "GATE_SLIDING_GATE":"Schiebetor",
            "DESC_CHANNELS_BUTTONS":"Bedienelemente des Gerätes",
            "DRIVE_MESSAGE_EXTENDED":"ausgefahren",
            "WIFI_SELECTED_NETWORK":"Name",
            "ERROR_ADD_GROUP_NO_NAME":"Es wurde kein Name für das neue Gerät eingegeben.",
            "DESC_HELP":"Hilfefunktion",
            "CHANGE_PWD_NEW_PASSWORD":"Neues Passwort",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Neues Passwort übernehmen",
            "DESC_CHANGE_PASSWORD_PWD":"Eingabe neues Passwort",
            "CHANGE_GW_NAME_NAME_INVALID":"Fehlgeschlagen",
            "ERROR_EDIT_ADMIN_CONTENT":"Der Administrator kann nicht bearbeitet werden",
            "STATE_COLLECTING_FAILED":"Fehler",
            "GENERAL_ADD":"Hinzufügen",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Passwort\" und \"Passwort wiederholen\" müssen identisch sein",
            "WIFI_SETTINGS":"WLAN Einstellungen",
            "LEARN_PORTS_TITLE":"Gerät hinzufügen",
            "ERROR_CHANGE_USERNAME":"Fehlgeschlagen",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Durchfahrtssperre",
            "ERROR_INVALID_GATEWAY_CONTENT":"Es konnte keine Verbindung mit dem Gateway hergestellt werden. Überprüfen Sie den Host-Namen.",
            "DESC_EDIT_USERS_EDIT":"Benutzer löschen",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Der Gerätename muss aus 4 - 20 Zeichen bestehen",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Schnellzugriff nicht möglich",
            "CHANNEL_UP":"Auf",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Dauer-Auf Ein",
            "PORTAL_VALIDATION_FAILED":"Fehlgeschlagen",
            "DESC_RESET_LOGIN_CANCEL":"Aktion abbrechen",
            "CHANGE_PWD_SETTING_PASSWORD":"Übernehmen",
            "LOADING_GROUPS_TITLE":"Lade",
            "DESC_SET_RIGHTS_SAVE":"Änderungen übernehmen",
            "DESC_DEFAULT_GW_CANCEL":"Aktion abbrechen",
            "REMOVING_PROCESS":"Löschen",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Das Gateway ist nicht erreichbar",
            "CONFIRM_DELETE_TITLE":"Gateway löschen",
            "SCENARIOS_ADD_HELP":"Zum Hinzufügen eines Szenarios wählen Sie das +Symbol.",
            "LOGOUT":"Abmelden",
            "DESC_ACTORS_BACK":"Zurück zum Hauptmenü",
            "ERROR_ADAPTER_BUSY_CONTENT":"Der Befehl konnte nicht durchgeführt werden.\n Das Gateway ist ausgelastet.",
            "DESC_WIFI_NETWORK_SCAN":"Nach Netzwerken suchen",
            "DRIVE_MESSAGE_HALF":"Teilgeöffnet",
            "DESC_SCENARIOS_ADD":"Szenario erstellen",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Kommunikation mit dem Gateway ist fehlgeschlagen",
            "SAVING_USER_RIGHTS":"Speichere",
            "DESC_GWSCREEN_PORTAL":"Eingabe der Portaldaten",
            "GATE_JACK":"Funk-Steckdose",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Sind Sie in demselben Netzwerk wie Ihr Gateway?",
            "GATE_DOOR":"Tür",
            "POPUP_PORTAL_UNAVAILABLE":"Der Portalserver konnte nicht erreicht werden",
            "DESC_SET_RIGHTS_BACK":"Zurück zu Benutzern",
            "GATE_SMARTKEY":"Türschloss-Antrieb",
            "POPUP_GATEWAY_FOUND_TITILE":"Suchvorgang beendet",
            "WIFI_LOADING_DATA_TITLE":"Lade",
            "GENERAL_PORTS":"Kanäle",
            "DESC_SCENARIOS_EDIT":"Szenarien verwalten oder löschen",
            "OPTIONS_LEARNED_PORTS":"Eingelernte Kanäle:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Ich akzeptiere die Datenschutzbedingungen",
            "DESC_EDIT_USERS_SET_RIGHTS":"Benutzer auswählen um dessen Zugriffsrechte zu ändern",
            "DRIVE_MESSAGE_HALF_MOVING":"Teilgeöffnet / Fahrend",
            "PORTAL_SET_ID_DIALOG":"Portaleinstellungen",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Kein Referenzpunkt",
            "POPUP_SETTING_STATE":"Bitte warten...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/nutzungsbedingungen",
            "ERROR_CHANGE_USERNAME_CONTENT":"Der Benutzername konnte nicht geändert werden",
            "GROUP_REQUESTABLE":"Das Gerät ist rückmeldefähig",
            "LOADING_STATES_TITLE":"Lade",
            "DESC_HOME_USERS":"Benutzer verwalten",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Das Passwort muss aus 4 - 20 Zeichen bestehen",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Das Passwort wird übernommen",
            "POPUP_GATE_OUT_OF_VIEW":"Die Steuerung einer automatischen Toranlage ohne Sicht zum Tor, ist nur dann erlaubt, wenn Sie zusätzlich zur serienmäßig vorhandenen Kraftbegrenzung eine Lichtschranke am Tor installiert haben.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Wählen Sie, ob Popup-Meldungen angezeigt oder unterdrückt werden",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorisiert",
            "DRIVE_MESSAGE_LOCKED":"verriegelt",
            "CHANNEL_DOWN":"Zu",
            "POPUP_INET_SPEED_LOW":"Ihre Datenverbindung reicht für diese Anwendung nicht aus",
            "CHANGE_PWD_FAILED_CONTENT":"Das Passwort konnte nicht geändert werden",
            "GENERAL_GROUP_TYPE":"Geräte-Typ",
            "CHANNEL_WALK":"Gehflügel",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horizontal laufendes Garagentor",
            "POPUP_AGREEMENT_CONTENT":"Akzeptieren Sie vor Nutzung der App die Datenschutz- / Nutzungsbedingungen",
            "INFO":"Informationen",
            "LOADING_GROUPS_CONTENT":"Lade Geräte",
            "GATE_PILOMAT_REIFENKILLER":"Reifenkiller",
            "GATE_PILOMAT_HUBBALKEN":"Hubbalken",
            "GENERAL_RETYPE":"Passwort wiederholen",
            "DESC_OTIONS_BACK":"Zurück zum Hauptmenü",
            "DESC_SET_RIGHTS":"Gerät auswählen um dem Benutzer Zugriffsrechte zu gewähren",
            "WIFI_SCANNING_TITLE":"Suche",
            "WIFI_STATE_CONNECTION_FAILURE":"Verbindungsaufbau fehlgeschlagen",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Der Benutzername muss aus 2 - 20 Zeichen bestehen",
            "REMOVE_PORTS":"Löschen",
            "GENERAL_ON":"Eingeschaltet",
            "DESC_CHANGE_PASSWORD_CANCEL":"Aktion abbrechen",
            "LEARNING_PROCESS_CONTENT":"Bitte warten…",
            "LOGIN_FAILED_UNKNOWN":"Es ist ein unerwarteter Fehler aufgetreten",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Die Benutzerrechte des Administrators können nicht geändert werden"
         };
         return _loc1_;
      }
   }
}
