package
{
   import mx.resources.ResourceBundle;
   
   public class el_GR$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function el_GR$LocalizedStrings_properties()
      {
         super("el_GR","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"κλείδωμα",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Καταχωρήστε τα στοιχεία πρόσβασης της πύλης Hörmann",
            "ERROR_DELETE_ADMIN":"Δεν είναι δυνατό",
            "LOGIN_SHOULD_SAVE":"Αποθήκευση δεδομένων",
            "LOAD_USERS_TITLE":"Περιμένετε",
            "CHANGE_GW_NAME_SETTING":"Αποδοχή",
            "CONFIRM_DELETE_GROUP":"Διαγραφή συσκευής",
            "GENERAL_NO":"Όχι",
            "DESC_GWSCREEN_ADD":"Προσθήκη τοπικών πυλών",
            "DRIVE_MESSAGE_NOT_RETRACTED":"μη βυθισμένο",
            "WIFI_PASSPHRASE":"Κωδικός πρόσβασης",
            "CHANNEL_ON":"Ενεργοποίηση",
            "SCENARIOS":"Σενάρια",
            "ERROR_SET_ADMIN_RIGHTS":"Δεν είναι δυνατό",
            "DESC_DEFAULT_GW_SAVE":"Δημιουργία γρήγορης πρόσβασης για την τρέχουσα πύλη",
            "POPUP_INFO":"Υπόδειξη:",
            "DRIVE_MESSAGE_ERROR":"ΠΡΟΣΟΧΗ: σφάλμα",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Όνομα δικτύου",
            "EMAIL_BODY":"Μπορείτε να μας στείλετε τις ερωτήσεις σας μέσω email. Μπορείτε, επίσης, να ανατρέξετε στις Συχνές ερωτήσεις.\n\nΗ ομάδα εξυπηρέτησης BiSecur-Home",
            "CONFIRM_DELETE_USER":"Διαγραφή χρήστη",
            "DESC_CHANNELS_BACK":"Πίσω στη λίστα συσκευών",
            "CHANGE_PWD_FIRST_START":"Για λόγους ασφαλείας αλλάξτε την εργοστασιακή ρύθμιση του κωδικού πρόσβασης μετά την πρώτη σύνδεση",
            "GENERAL_DEFAULT_GATEWAY":"Γρήγορη πρόσβαση",
            "CHANGE_PWD_PASSWORD_INVALID":"Σφάλμα",
            "ERROR_NO_GW_TITLE":"Δεν υπάρχουν πύλες",
            "POPUP_SETTING_STATE_CONTENT":"Η εντολή εκτελείται",
            "WIFI_LOADING_DATA_CONTENT":"Γίνεται φόρτωση των στοιχείων WLAN",
            "OPTIONS_RESET_LOGIN_DATA":"Διαγραφή αποθηκευμένων στοιχείων πρόσβασης",
            "EDIT_USER_TITLE":"Επεξεργασία χρήστη",
            "DESC_HOME_PREFERENCES":"Αλλαγή ρυθμίσεων για την πύλη και την εφαρμογή",
            "WIFI_ACTIVE_STATE":"Κατάσταση WLAN",
            "STATE_COLLECTING":"Φόρτωση",
            "ADD_SCENARIO":"Προσθήκη σεναρίου",
            "STATE_COLLECTING_FAILED_CONTENT":"Η κατάσταση δεν φορτώθηκε",
            "GATE_SWING_GATE_SINGLE":"Ανοιγόμενη πόρτα 1 φύλλου",
            "ACTORS":"Συσκευή",
            "POPUP_AGREEMENT":"Χρήση / Πολιτική απορρήτου",
            "CHANNEL_OPEN_DOOR":"Άνοιγμα",
            "DESC_ACTORS_REFRESH":"Ενημέρωση κατάστασης",
            "GENERAL_OFF":"Απενεργοποιήθηκε",
            "OPTIONS_HELP":"Online βοήθεια",
            "COPY_PORTS_CONTENT":"Ρυθμίστε τον πομπό στη λειτουργία μετάδοσης, βλ. οδηγίες. Επιλέξτε το κανάλι μετάδοσης",
            "GENERAL_SELECT":"Επιλέξτε...",
            "ERROR_ADAPTER_BUSY":"Σφάλμα",
            "INFO_BOX_INFOS":"Γενικά",
            "GATE_LIGHT":"Φως",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Άνοιγμα όρων χρήσης",
            "DESC_MANAGE_POPUPS_WARNINGS":"Απόκρυψη αναδυόμενων προειδοποιήσεων",
            "MAX_USERSS_REACHED_CONTENT":"Επιτεύχθηκε ο μέγιστος αριθμός χρηστών.",
            "GENERAL_REMOVE":"Απεγκατάσταση",
            "OPTIONS":"Ρυθμίσεις",
            "DESC_HOME_SCENARIOS":"Δημιουργία και διαχείριση σεναρίων",
            "CHANNEL_OFF":"Απενεργοποίηση",
            "GENERAL_PORTAL_ID":"Ταυτότητα συσκευής",
            "EDIT_GROUP":"Επεξεργασία συσκευής",
            "ERROR_LERANIN_PORT_CONTENT":"Η ρύθμιση του επιθυμητού καναλιού απέτυχε",
            "ERROR_CONNECTION_CLOSED":"Σφάλμα",
            "CHANNEL_ON_OFF":"On / Off",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Ονομασία",
            "OPTIONS_EDIT_USERS":"Διαχείριση χρηστών",
            "LOADING_STATES_CONTENT":"Εμφανίζεται η τρέχουσα κατάσταση.\nΠεριμένετε...",
            "LERAN_PORTS_CONTENT":"Ρυθμίστε τη συσκευή στη λειτουργία ρύθμισης, βλ. οδηγίες. Επιλέξτε το κανάλι προς ρύθμιση.",
            "REMOVE_PORTS_CONTENT":"Επιλέξτε τα κανάλια που θέλετε να διαγράψετε.",
            "GATE_SWING_GATE_DOUBLE":"Ανοιγόμενη πόρτα 2 φύλλων",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Ελέγξτε αν έχουν καταχωρηθεί τα δεδομένα πύλης σας ή αν προστέθηκε τοπική πύλη.",
            "CHANNEL_SINK":"Χαμήλωμα",
            "OPTIONS_EDIT_USERS_TITLE":"Χρήστης",
            "MAX_PORTS_REACHED_CONTENT":"Μέγιστος αριθμός καναλιών κατειλημμένος",
            "MAX_PORTS_REACHED":"Δεν είναι δυνατό",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Δεν ήταν δυνατή η πρόσβαση στη συσκευή που ζητήσατε",
            "PORTAL_AUTHENTICATION_FAILED":"Αποτυχία",
            "NOTIFICATION_CENTER":"Ειδοποιήσεις",
            "LEARNING_PROCESS":"Ρύθμιση",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Το όνομα χρήστη πρέπει να αποτελείται από 2 - 20 χαρακτήρες",
            "WIFI_STATE_CONNECTED":"Συνδέθηκε",
            "COPY_PORTS":"Μεταβίβαση από το τηλεχειριστήριο",
            "POPUP_SEARCH_CONTENT":"Αναζήτηση πυλών Hörmann \n\nΓια τη διαδικασία αυτή μπορεί να απαιτηθούν μερικά δευτερόλεπτα.",
            "DESC_MANAGE_POPUPS_CANCEL":"Ακύρωση ενέργειας",
            "DESC_WIFI_PASSWORD":"Κωδικός πρόσβασης",
            "DESC_WIFI_SAVE":"Αποθήκευση",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Ενεργοποίηση ακινητοποίησης",
            "SELECT_GATEWAY":"Πύλες",
            "CLEANING_PORTS":"Προσθήκη συσκευής",
            "WIFI_STATE_BUSY":"Γίνεται σύνδεση",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Ο κωδικός πρόσβασης που πληκτρολογήσατε είναι λάθος",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Αλλαγή ονόματος πύλης",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Γίνεται αποδοχή του ονόματος",
            "DESC_ACTORS_EDIT":"Διαχείριση ή διαγραφή συσκευών",
            "DESC_WIFI_STATE":"Κατάσταση σύνδεσης",
            "ERROR_REMOVE_USER":"Αποτυχία",
            "LANG_TAG":"EL",
            "DESC_MANAGE_POPUPS_SUBMIT":"Αποδοχή ρύθμισης",
            "HOME_TITLE":"Κύρια σελίδα",
            "GENERAL_USERNAME":"Όνομα χρήστη",
            "DRIVE_MESSAGE_OPENED":"Ανοιχτή",
            "CONFIRM_DELETE":"Είστε βέβαιοι ότι θέλετε να διαγράψετε την πύλη;",
            "DRIVE_MESSAGE_CLOSED":"Κλειστή",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Δεν ήταν δυνατή η πρόσβαση στο διακομιστή πύλης",
            "REMOVING_PROCESS_CONTENT":"Το κανάλι διαγράφεται",
            "DESC_EDIT_USERS_BACK":"Πίσω στις ρυθμίσεις",
            "ERROR_NO_GROUP_FOUND":"Η συσκευή δεν βρέθηκε",
            "ERROR_INVALID_GATEWAY":"Δεν βρέθηκε πύλη",
            "DESC_WIFI_BACK":"Πίσω στις ρυθμίσεις",
            "MAX_USERS_REACHED":"Δεν είναι δυνατό",
            "DESC_CHANGE_PASSWORD_USERNAME":"Όνομα χρήστη",
            "POPUP_AGREEMENT_ACCEPT_USE":"Αποδέχομαι τους όρους χρήσης",
            "ERROR_LERNING_PORT":"Αποτυχία",
            "POPUP_ADD_GATEWAY_CONTENT":"Καταχώρηση διεύθυνσης IP:",
            "ERROR_ADD_GROUP":"Σφάλμα",
            "DRIVE_MESSAGE_NO_DATA":"Δεν υπάρχουν διαθέσιμα στοιχεία",
            "CHANGE_PWD_FAILED":"Αποτυχία",
            "SAVING_USER_RIGHTS_CONTENT":"Τα δικαιώματα χρήστη αποθηκεύονται",
            "DRIVE_MESSAGE_UNLOCKED":"Δεν έχει κλειδωθεί",
            "GENERAL_SAVE":"Αποθήκευση",
            "INFO_BOX_FAQ":"Συχνές ερωτήσεις",
            "GENERAL_CONNNECT":"Σύνδεση",
            "GATE_SECTIONAL_DOOR":"Κάθετα κινούμενη γκαραζόπορτα",
            "OPTIONS_CHANGE_PASSWORD":"Αλλαγή κωδικού πρόσβασης",
            "CHANNEL":"Χειρισμός",
            "CHANGE_GW_NAME_CONTENT":"Όνομα πύλης",
            "DRIVE_MESSAGE_RETRACTED":"βυθισμένο",
            "DESC_ADDGWSCREEN_BACK":"Επιστροφή στην επισκόπηση πυλών",
            "EMAIL_SUBJECT":"Εξυπηρέτηση",
            "ERROR_EDIT_ADMIN":"Δεν είναι δυνατό",
            "OPTIONS_SET_USER_RIGHTS":"Δικαιώματα χρήστη",
            "CHANGE_GW_NAME_ERROR":"Αποτυχία",
            "CHANNEL_LIFT":"Ανύψωση",
            "LOGIN_FAILED_TITLE":"Αποτυχία",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Όταν επιβεβαιώνετε τη διαγραφή των στοιχείων πρόσβασης με OK, πρέπει να πληκτρολογηθεί ξανά ο κωδικός πρόσβασης κατά την επιλογή της πύλης",
            "CHANNEL_UNLOCK":"ξεκλείδωμα",
            "GENERAL_PORTAL_SERVER":"Διακομιστής πύλης",
            "DESC_SCENARIOS_BACK":"Πίσω στο κύριο μενού",
            "CHANGE_PWD_USERNAME":"Χρήστης:",
            "POPUP_GATE_NOT_RESPONSABLE":"Η εφαρμογή μπορεί να στείλει την εντολή αυτή στη συσκευή, ωστόσο δεν αναγνωρίζει την τρέχουσα κατάσταση της συσκευής.",
            "DESC_GW_NAME":"Όνομα πύλης",
            "GATE_BARRIER":"Μπάρα",
            "LEARN_PORTS":"Ρύθμιση κωδικού τηλεχειρισμού",
            "GENERAL_BACK":"Πίσω",
            "DESC_GWSCREEN_EDIT":"Για τη διαγραφή αποθηκευμένων πυλών",
            "OPTIONS_MANAGE_POPUPS":"Διαχείριση αναδυόμενων μηνυμάτων",
            "POPUP_LOGIN_PROCESS_CONTENT":"Περιμένετε...",
            "CONFIRM_DELETE_USER_CONTENT":"Είστε βέβαιοι ότι θέλετε να διαγράψετε το χρήστη;",
            "DESC_MENU":"Μενού",
            "LOGIN_FAILED_WRONG_DATA":"Το όνομα χρήστη ή ο κωδικός πρόσβασης που πληκτρολογήσατε είναι λάθος",
            "GENERAL_CANCEL":"Άκυρο",
            "ADD_GROUP":"Προσθήκη συσκευής",
            "WIFI_STATE_AP_NOT_FOUND":"Δεν βρέθηκε δίκτυο",
            "WIFI_STATE_NOT_CONNECTED":"Δεν συνδέθηκε",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Ο χειρισμός σας μέσω της πύλης είναι ενεργοποιημένος!",
            "POPUP_ADD_GATEWAY":"Προσθήκη πύλης",
            "GENERAL_NEXT":"Συνέχεια",
            "POPUP_SUPPRESS":"Μην ανοίγετε πλέον το αναδυόμενο παράθυρο",
            "POPUP_SEARCH_TITLE":"Αναζήτηση...",
            "WIFI_SCANNING_CONTENT":"Αναζήτηση για ορατά δίκτυα WLAN",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Δεν βρέθηκε πύλη",
            "DESC_ACTORS_ADD":"Δημιουργία συσκευής",
            "ERROR_ADD_GROUP_NO_TYPE":"Δεν επιλέχθηκε τύπος για τη νέα συσκευή.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Ελέγξτε τα στοιχεία πρόσβασης",
            "GENERAL_REFESHED":"Ενημερώθηκε",
            "OPTIONS_SUPPRESS_WARNINGS":"Απόκρυψη προειδοποιήσεων",
            "LOGIN_FAILED_GATEWAY_BUSY":"Η πύλη είναι υπερφορτωμένη. Δοκιμάστε ξανά.",
            "DESC_EMAIL":"Αποστολή email στο τμήμα εξυπηρέτησης",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Συνεχώς ανοιχτή - απενεργοποιήθηκε",
            "CLEANING_PORTS_CONTENT":"Γίνεται προετοιμασία για την προσθήκη",
            "DESC_HOME_ACTORS":"Ρύθμιση και διαχείριση συσκευών",
            "ERROR_TIMEOUT":"Σφάλμα σύνδεσης",
            "CREATE_USER_TITLE":"Προσθήκη χρήστη",
            "ERROR_DELETE_ADMIN_CONTENT":"Ο διαχειριστής δεν μπορεί να διαγραφεί",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Γρήγορη πρόσβαση",
            "ADD_SCENARIO_NAME":"Επώνυμο",
            "HIST":"Ιστορικό",
            "DESC_RESET_LOGIN_SUBMIT":"Επιβεβαίωση διαγραφής",
            "POPUP_WARNING":"ΠΡΟΣΟΧΗ",
            "REMOVE_GROUP_PROCESS":"Η συσκευή διαγράφεται",
            "POPUP_LOGIN_PROCESS":"Σύνδεση",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Περιμένετε...",
            "DESC_DEFAULT_GW_SUBMIT":"Αποδοχή ρύθμισης",
            "DESC_CHANGE_PASSWORD_RETYPE":"Επανάληψη εισαγωγής",
            "LOAD_USERS_CONTENT":"Φορτώνονται όλοι οι χρήστες της πύλης.\nΓια τη διαδικασία αυτή μπορεί να απαιτηθούν μερικά δευτερόλεπτα.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Όταν σε μια πύλη είναι ενεργοποιημένη η γρήγορη πρόσβαση, τότε η εφαρμογή συνδέεται αυτόματα όταν αυτό είναι εφικτό",
            "GATE_OTHER":"Λοιπές συσκευές",
            "CHANGE_PWD_USER_INVALID":"Σφάλμα",
            "CHANNEL_LIGHT":"Φως",
            "LOGIN_TITLE":"Σύνδεση",
            "CHANNEL_HALF":"Μερικό άνοιγμα",
            "GATEWAY_SCREEN_ADD_HELP":"Για την προσθήκη μιας πύλης πατήστε το σύμβολο+.",
            "ERROR_TIMEOUT_CONTENT":"Υπέρβαση χρόνου κατά την επικοινωνία με την πύλη",
            "ERROR_NO_PORTS_LEARNED":"Δεν είναι δυνατή η προσθήκη",
            "OPTIONS_SUPPRESS_INFOS":"Απόκρυψη υποδείξεων",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Σφάλμα",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Αυτόματη λειτουργία",
            "GENERAL_DELETE":"Διαγραφή",
            "GENERAL_PASSWORD":"Κωδικός πρόσβασης",
            "STATE_COLLECTING_CONTENT":"Ζητήθηκε η κατάσταση της συσκευής",
            "ERROR_REMOVE_USER_CONTENT":"Δεν ήταν δυνατή η διαγραφή του χρήστη",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Σφάλμα",
            "ACTORS_ADD_HELP":"Για την προσθήκη μιας συσκευής πατήστε το σύμβολο+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Είστε βέβαιοι ότι θέλετε να διαγράψετε τη συσκευή;",
            "REMOVE_GROUP_PROCESS_CONTENT":"Περιμένετε...",
            "GENERAL_YES":"Ναι",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Πριν από την προσθήκη μιας συσκευής ρυθμίστε τουλάχιστον ένα κανάλι",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Δεν ήταν δυνατή η αλλαγή του ονόματος",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Η εφαρμογή δεν εντόπισε πύλες.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Η επαλήθευση απέτυχε",
            "DESC_MANAGE_POPUPS_INFOS":"Απόκρυψη αναδυόμενων πληροφοριών",
            "GATE_PILOMAT_POLLER":"Κολωνάκια",
            "DESC_CHANNELS_STATE":"Κατάσταση της συσκευής με δυνατότητα απόκρισης",
            "DESC_GWSCREEN_REFRESH":"Ενημέρωση της λίστας πυλών",
            "POPUP_SCENARIO_DISPATCHING":"Το σενάριο εκτελείται",
            "ERROR_PORT_UNREACHABLE":"Αποτυχία",
            "POPUP_GATEWAY_FOUND_CONTENT":"Προστέθηκαν οι ακόλουθες πύλες:",
            "WIFI_STATE_SECURITY_MISMATCH":"Ο τύπος κρυπτογράφησης του WLAN δεν υποστηρίζεται",
            "LOGOUT_NAMED":"αποσύνδεση",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Άνοιγμα όρων προστασίας δεδομένων",
            "ERROR_NO_GW_CONTENT":"Δεν ήταν δυνατή η εύρεση καμίας πύλης Hörmann-στο τοπικό δίκτυο.\nΠροσθέστε περισσότερες πύλες με το σύμβολο+",
            "DESC_EDIT_USERS_ADD":"Προσθήκη χρήστη",
            "ERROR_NO_PORT_FOUND":"Η πύλη δεν βρέθηκε",
            "GATE_SLIDING_GATE":"συρόμενη πόρτα",
            "DESC_CHANNELS_BUTTONS":"Στοιχεία χειρισμού της συσκευής",
            "DRIVE_MESSAGE_EXTENDED":"ανυψωμένο",
            "WIFI_SELECTED_NETWORK":"Επώνυμο",
            "ERROR_ADD_GROUP_NO_NAME":"Δεν πληκτρολογήθηκε όνομα για τη νέα συσκευή.",
            "DESC_HELP":"Βοηθητική λειτουργία",
            "CHANGE_PWD_NEW_PASSWORD":"Νέος κωδικός πρόσβασης",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Αποδοχή νέου κωδικού πρόσβασης",
            "DESC_CHANGE_PASSWORD_PWD":"Εισαγωγή νέου κωδικούς πρόσβασης",
            "ERROR_EDIT_ADMIN_CONTENT":"Δεν είναι δυνατή η επεξεργασία του διαχειριστή",
            "CHANGE_GW_NAME_NAME_INVALID":"Αποτυχία",
            "STATE_COLLECTING_FAILED":"Σφάλμα",
            "GENERAL_ADD":"Επικόλληση",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"Τα πεδία \"Κωδικός πρόσβασης\" και \"Επαναλάβετε τον κωδικό πρόσβασης\" πρέπει να είναι ίδια",
            "WIFI_SETTINGS":"Ρυθμίσεις WLAN",
            "LEARN_PORTS_TITLE":"Προσθήκη συσκευής",
            "ERROR_CHANGE_USERNAME":"Αποτυχία",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Οδοφράγματα",
            "ERROR_INVALID_GATEWAY_CONTENT":"Δεν ήταν δυνατή η σύνδεση με την πύλη. Ελέγξτε το όνομα κεντρικού υπολογιστή.",
            "DESC_EDIT_USERS_EDIT":"Διαγραφή χρήστη",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Το όνομα συσκευής πρέπει να αποτελείται από 2 - 20 χαρακτήρες",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Δεν είναι δυνατή η γρήγορη πρόσβαση",
            "CHANNEL_UP":"Άνοιγμα",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Συνεχώς ανοιχτή - ενεργοποιήθηκε",
            "PORTAL_VALIDATION_FAILED":"Αποτυχία",
            "DESC_RESET_LOGIN_CANCEL":"Ακύρωση ενέργειας",
            "CHANGE_PWD_SETTING_PASSWORD":"Αποδοχή",
            "LOADING_GROUPS_TITLE":"Φόρτωση",
            "DESC_DEFAULT_GW_CANCEL":"Ακύρωση ενέργειας",
            "DESC_SET_RIGHTS_SAVE":"Αποδοχή αλλαγών",
            "REMOVING_PROCESS":"Διαγραφή",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Δεν είναι δυνατή η πρόσβαση στην πύλη",
            "CONFIRM_DELETE_TITLE":"Διαγραφή πύλης",
            "SCENARIOS_ADD_HELP":"Για την προσθήκη ενός σεναρίου πατήστε το σύμβολο+.",
            "LOGOUT":"Αποσύνδεση",
            "DESC_ACTORS_BACK":"Πίσω στο κύριο μενού",
            "ERROR_ADAPTER_BUSY_CONTENT":"Η εντολή δεν ήταν δυνατόν να εκτελεστεί.\n Η πύλη είναι υπερφορτωμένη.",
            "DESC_WIFI_NETWORK_SCAN":"Αναζήτηση δικτύων",
            "DRIVE_MESSAGE_HALF":"Μερικώς ανοιχτή",
            "DESC_SCENARIOS_ADD":"Δημιουργία σεναρίου",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Η επικοινωνία με την πύλη απέτυχε.",
            "SAVING_USER_RIGHTS":"Αποθήκευση",
            "DESC_GWSCREEN_PORTAL":"Εισαγωγή των στοιχείων πύλης",
            "GATE_JACK":"Ασύρματη πρίζα",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Βρίσκεστε στο ίδιο δίκτυο με την πύλη σας;",
            "GATE_DOOR":"Πόρτα εισόδου",
            "POPUP_PORTAL_UNAVAILABLE":"Δεν ήταν δυνατή η πρόσβαση στο διακομιστή πύλης",
            "DESC_SET_RIGHTS_BACK":"Πίσω στους χρήστες",
            "GATE_SMARTKEY":"Μηχανισμός κλειδαριάς πόρτας",
            "POPUP_GATEWAY_FOUND_TITILE":"Η αναζήτηση ολοκληρώθηκε",
            "WIFI_LOADING_DATA_TITLE":"Φόρτωση",
            "GENERAL_PORTS":"Κανάλια",
            "DESC_SCENARIOS_EDIT":"Διαχείριση ή διαγραφή σεναρίων",
            "OPTIONS_LEARNED_PORTS":"Ρυθμισμένα κανάλια:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Αποδέχομαι τους όρους προστασίας δεδομένων",
            "DESC_EDIT_USERS_SET_RIGHTS":"Επιλογή χρήση για αλλαγή των δικαιωμάτων πρόσβασης",
            "DRIVE_MESSAGE_HALF_MOVING":"Μερικώς ανοιχτή / Κινείται",
            "PORTAL_SET_ID_DIALOG":"Ρυθμίσεις πύλης",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Χωρίς σημείο αναφοράς",
            "POPUP_SETTING_STATE":"Περιμένετε...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Δεν ήταν δυνατή η αλλαγή του ονόματος χρήστη",
            "GROUP_REQUESTABLE":"Η συσκευή έχει τη δυνατότητα απόκρισης",
            "LOADING_STATES_TITLE":"Φόρτωση",
            "DESC_HOME_USERS":"Διαχείριση χρηστών",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Ο κωδικός πρόσβασης πρέπει να αποτελείται από 4 - 20 χαρακτήρες",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Γίνεται αποδοχή του κωδικού πρόσβασης",
            "POPUP_GATE_OUT_OF_VIEW":"Το σύστημα ελέγχου ενός αυτόματου συστήματος πόρτας χωρίς ορατότητα στην πόρτα επιτρέπεται μόνο όταν εκτός από τον περιορισμό ισχύος που περιλαμβάνεται στο βασικό εξοπλισμό έχετε επιπλέον εγκαταστήσει ένα φωτοκύτταρο στην πόρτα.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Επιλέξτε αν θέλετε να εμφανίζονται αναδυόμενα μηνύματα",
            "CHANNEL_IMPULS":"Παλμός",
            "PORTAL_VALIDATION_SUCCEEDED":"Με εξουσιοδότηση",
            "DRIVE_MESSAGE_LOCKED":"Κλειδωμένο",
            "CHANNEL_DOWN":"Κλείσιμο",
            "POPUP_INET_SPEED_LOW":"Η σύνδεση δεδομένων σας δεν επαρκεί για αυτήν τη χρήση",
            "CHANGE_PWD_FAILED_CONTENT":"Δεν ήταν δυνατή η αλλαγή του κωδικού χρήστη",
            "GENERAL_GROUP_TYPE":"Τύπος συσκευής",
            "CHANNEL_WALK":"Κινητό φύλλο",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Οριζόντια κινούμενη γκαραζόπορτα",
            "POPUP_AGREEMENT_CONTENT":"Πριν από τη χρήση της εφαρμογής αποδεχτείτε τους όρους προστασίας δεδομένων / χρήσης",
            "INFO":"Πληροφορίες",
            "LOADING_GROUPS_CONTENT":"Φόρτωση συσκευής",
            "GATE_PILOMAT_REIFENKILLER":"Βυθιζόμενα καρφιά",
            "GATE_PILOMAT_HUBBALKEN":"Μπάρες διέλευσης οχημάτων",
            "GENERAL_RETYPE":"Επαναλάβετε τον κωδικό πρόσβασης",
            "DESC_OTIONS_BACK":"Πίσω στο κύριο μενού",
            "DESC_SET_RIGHTS":"Επιλογή συσκευής για απόδοση δικαιωμάτων πρόσβασης στο χρήστη",
            "WIFI_SCANNING_TITLE":"Αναζήτηση",
            "WIFI_STATE_CONNECTION_FAILURE":"Η δημιουργία σύνδεσης απέτυχε",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Το όνομα χρήστη πρέπει να αποτελείται από 2 - 20 χαρακτήρες",
            "REMOVE_PORTS":"Διαγραφή",
            "GENERAL_ON":"Ενεργοποιήθηκε",
            "DESC_CHANGE_PASSWORD_CANCEL":"Ακύρωση ενέργειας",
            "LEARNING_PROCESS_CONTENT":"Περιμένετε...",
            "LOGIN_FAILED_UNKNOWN":"Προέκυψε μη αναμενόμενο σφάλμα",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Δεν είναι δυνατή η αλλαγή των δικαιωμάτων χρήστη του διαχειριστή"
         };
         return _loc1_;
      }
   }
}
