package
{
   import mx.resources.ResourceBundle;
   
   public class es_ES$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function es_ES$LocalizedStrings_properties()
      {
         super("es_ES","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Bloquear",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Introduzca lo datos de acceso del portal de Hörmann.",
            "ERROR_DELETE_ADMIN":"No posible",
            "LOGIN_SHOULD_SAVE":"Guardar datos",
            "LOAD_USERS_TITLE":"Espere...",
            "CHANGE_GW_NAME_SETTING":"Adoptar",
            "CONFIRM_DELETE_GROUP":"Borrar dispositivo",
            "GENERAL_NO":"No",
            "DESC_GWSCREEN_ADD":"Añadir gateways locales",
            "DRIVE_MESSAGE_NOT_RETRACTED":"no retraído",
            "WIFI_PASSPHRASE":"Contraseña",
            "CHANNEL_ON":"Conectado",
            "SCENARIOS":"Escenarios",
            "ERROR_SET_ADMIN_RIGHTS":"No posible",
            "DESC_DEFAULT_GW_SAVE":"Crear acceso rápido para gateway actual",
            "POPUP_INFO":"Indicación",
            "DRIVE_MESSAGE_ERROR":"ATENCIÓN: Error",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/es/proteccion-de-datos",
            "DESC_WIFI_NETWORK_NAME":"Nombre de red",
            "EMAIL_BODY":"Puede enviarnos sus consultas por correo electrónico. Para ello dispone también de nuestra función de FAQ.\n\nSu equipo de asistencia técnica de BiSecur-Home",
            "CONFIRM_DELETE_USER":"Borrar usuario",
            "DESC_CHANNELS_BACK":"Volver a la lista de dispositivos",
            "CHANGE_PWD_FIRST_START":"Por motivos de seguridad, después del primer registro, modifique los ajustes de fábrica de su contraseña.",
            "GENERAL_DEFAULT_GATEWAY":"Acceso rápido",
            "CHANGE_PWD_PASSWORD_INVALID":"Error",
            "ERROR_NO_GW_TITLE":"No hay ningún gateway",
            "POPUP_SETTING_STATE_CONTENT":"Se realiza la orden",
            "WIFI_LOADING_DATA_CONTENT":"Los datos WLAN se están cargando.",
            "OPTIONS_RESET_LOGIN_DATA":"Borrar los datos de acceso guardados",
            "EDIT_USER_TITLE":"Editar usuario",
            "DESC_HOME_PREFERENCES":"Cambiar los ajustes para el gateway y la App",
            "WIFI_ACTIVE_STATE":"Estado del WLAN",
            "STATE_COLLECTING":"Cargando...",
            "ADD_SCENARIO":"Añadir ambiente",
            "STATE_COLLECTING_FAILED_CONTENT":"No se ha cargado el estado.",
            "GATE_SWING_GATE_SINGLE":"Puerta batiente de 1 hoja",
            "ACTORS":"Dispositivos",
            "POPUP_AGREEMENT":"Uso / Protección de los datos",
            "CHANNEL_OPEN_DOOR":"Abrir",
            "DESC_ACTORS_REFRESH":"Actualizar estado",
            "GENERAL_OFF":"Desconectado",
            "OPTIONS_HELP":"Ayuda online",
            "COPY_PORTS_CONTENT":"Coloque el emisor en modo de transferencia (ver instrucciones). Seleccione el canal para transferir.",
            "GENERAL_SELECT":"Seleccione...",
            "ERROR_ADAPTER_BUSY":"Error",
            "INFO_BOX_INFOS":"Generalidades",
            "GATE_LIGHT":"Luz",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Abrir las condiciones de uso",
            "DESC_MANAGE_POPUPS_WARNINGS":"Suprimir los popup de advertencia",
            "MAX_USERSS_REACHED_CONTENT":"Se ha alcanzado el número máximo de usuarios.",
            "GENERAL_REMOVE":"Eliminar",
            "OPTIONS":"Ajustes",
            "DESC_HOME_SCENARIOS":"Crear y administrar ambientes",
            "CHANNEL_OFF":"Desconectado",
            "GENERAL_PORTAL_ID":"ID del dispositivo",
            "EDIT_GROUP":"Editar dispositivo",
            "ERROR_LERANIN_PORT_CONTENT":"Memorización del canal deseado fallida",
            "ERROR_CONNECTION_CLOSED":"Error",
            "CHANNEL_ON_OFF":"ON / OFF",
            "GENERAL_SUBMIT":"Aceptar",
            "GENERAL_GROUP_NAME":"Denominación",
            "OPTIONS_EDIT_USERS":"Gestión de usuarios",
            "LOADING_STATES_CONTENT":"Se consulta el estado actual.\nEspere...",
            "LERAN_PORTS_CONTENT":"Coloque el dispositivo en modo de aprendizaje (ver instrucciones). Seleccione el canal para programar.",
            "REMOVE_PORTS_CONTENT":"Seleccione los canales que desea borrar.",
            "GATE_SWING_GATE_DOUBLE":"Puerta batiente de 2 hojas",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Compruebe que ha introducido sus datos del portal o añadido un gateway local.",
            "CHANNEL_SINK":"Descender",
            "OPTIONS_EDIT_USERS_TITLE":"Usuario",
            "MAX_PORTS_REACHED_CONTENT":"Cantidad máx. de canales ocupada",
            "MAX_PORTS_REACHED":"No posible",
            "ERROR_PORT_UNREACHABLE_CONTENT":"No ha sido posible conectarse con el dispositivo consultado.",
            "PORTAL_AUTHENTICATION_FAILED":"Fallido",
            "NOTIFICATION_CENTER":"Notificaciones",
            "LEARNING_PROCESS":"Memorizar",
            "CHANGE_PWD_USER_INVALID_CONTENT":"El nombre de usuario debe estar compuesto de 2 a 20 caracteres.",
            "WIFI_STATE_CONNECTED":"Conectado",
            "COPY_PORTS":"Transferir del emisor manual",
            "POPUP_SEARCH_CONTENT":"Búsqueda de gateways de Hörmann \n\nEste proceso puede durar varios segundos.",
            "DESC_MANAGE_POPUPS_CANCEL":"Interrumpir la acción",
            "DESC_WIFI_PASSWORD":"Contraseña",
            "DESC_WIFI_SAVE":"Guardar",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Parada activa",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Añadir dispositivo",
            "WIFI_STATE_BUSY":"Se está creando conexión",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"La contraseña introducida es incorrecta.",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Modificar el nombre del gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Se ha adoptado el nombre.",
            "DESC_ACTORS_EDIT":"Administrar o borrar los dispositivos",
            "DESC_WIFI_STATE":"Estado de conexión",
            "ERROR_REMOVE_USER":"Fallido",
            "LANG_TAG":"ES",
            "DESC_MANAGE_POPUPS_SUBMIT":"Adoptar ajustes",
            "HOME_TITLE":"Página principal",
            "GENERAL_USERNAME":"Nombre de usuario",
            "DRIVE_MESSAGE_OPENED":"Abierta",
            "CONFIRM_DELETE":"¿Realmente desea borrar el gateway?",
            "DRIVE_MESSAGE_CLOSED":"Cerrada",
            "PORTAL_VALIDATION_FAILED_CONTENT":"No se ha podido conectar con el servidor del portal.",
            "REMOVING_PROCESS_CONTENT":"El canal se borra.",
            "DESC_EDIT_USERS_BACK":"Volver a los ajustes",
            "ERROR_NO_GROUP_FOUND":"No se ha encontrado el dispositivo.",
            "ERROR_INVALID_GATEWAY":"No se ha encontrado ningún gateway",
            "DESC_WIFI_BACK":"Volver a los ajustes",
            "MAX_USERS_REACHED":"No posible",
            "DESC_CHANGE_PASSWORD_USERNAME":"Nombre de usuario",
            "POPUP_AGREEMENT_ACCEPT_USE":"Acepto las condiciones de uso.",
            "ERROR_LERNING_PORT":"Fallido",
            "POPUP_ADD_GATEWAY_CONTENT":"Introducir la dirección IP:",
            "ERROR_ADD_GROUP":"Error",
            "DRIVE_MESSAGE_NO_DATA":"Ningún dato disponible",
            "CHANGE_PWD_FAILED":"Fallido",
            "SAVING_USER_RIGHTS_CONTENT":"Se guardan los derechos de usuario.",
            "DRIVE_MESSAGE_UNLOCKED":"Sin bloquear",
            "GENERAL_SAVE":"Guardar",
            "INFO_BOX_FAQ":"FAQ (preguntas más frecuentes)",
            "GENERAL_CONNNECT":"Conectar",
            "GATE_SECTIONAL_DOOR":"Puerta de garaje de desplazamiento vertical",
            "OPTIONS_CHANGE_PASSWORD":"Cambiar contraseña",
            "CHANNEL":"Funcionamiento",
            "CHANGE_GW_NAME_CONTENT":"Nombre del gateway",
            "DRIVE_MESSAGE_RETRACTED":"retraído",
            "DESC_ADDGWSCREEN_BACK":"Volver a la lista de gateways",
            "EMAIL_SUBJECT":"Asistencia técnica",
            "ERROR_EDIT_ADMIN":"No posible",
            "OPTIONS_SET_USER_RIGHTS":"Derechos de usuario",
            "CHANGE_GW_NAME_ERROR":"Fallido",
            "CHANNEL_LIFT":"Elevar",
            "LOGIN_FAILED_TITLE":"Fallido",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Si borra los datos de acceso confirmándolo con OK, debe introducirse nuevamente la contraseña al seleccionar el gateway.",
            "CHANNEL_UNLOCK":"Desbloquear",
            "GENERAL_PORTAL_SERVER":"Servidor del portal",
            "DESC_SCENARIOS_BACK":"Volver al menú principal",
            "CHANGE_PWD_USERNAME":"Usuario:",
            "POPUP_GATE_NOT_RESPONSABLE":"La App puede enviar esta orden al dispositivo, pero no reconoce su estado actual.",
            "DESC_GW_NAME":"Nombre del gateway",
            "GATE_BARRIER":"barrera",
            "LEARN_PORTS":"Programar código de radiofrecuencia",
            "GENERAL_BACK":"Volver",
            "DESC_GWSCREEN_EDIT":"Para borrar los gateways guardados",
            "OPTIONS_MANAGE_POPUPS":"Administrar los avisos popup",
            "POPUP_LOGIN_PROCESS_CONTENT":"Espere...",
            "CONFIRM_DELETE_USER_CONTENT":"¿Realmente desea borrar el usuario?",
            "DESC_MENU":"Menú",
            "LOGIN_FAILED_WRONG_DATA":"El nombre de usuario o la contraseña son incorrectos.",
            "GENERAL_CANCEL":"Cancelar",
            "ADD_GROUP":"Añadir dispositivo",
            "WIFI_STATE_AP_NOT_FOUND":"Red no encontrada",
            "WIFI_STATE_NOT_CONNECTED":"No conectado",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Su manejo está activado a través del portal.",
            "POPUP_ADD_GATEWAY":"Añadir gateway",
            "GENERAL_NEXT":"continuar",
            "POPUP_SUPPRESS":"No volver a abrir el popup",
            "POPUP_SEARCH_TITLE":"Búsqueda...",
            "WIFI_SCANNING_CONTENT":"Búsqueda de redes WLAN visibles",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"No se ha encontrado ningún gateway",
            "DESC_ACTORS_ADD":"Crear dispositivos",
            "ERROR_ADD_GROUP_NO_TYPE":"No se ha seleccionado ningún tipo para el dispositivo nuevo.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Compruebe los datos de login.",
            "GENERAL_REFESHED":"Actualizada",
            "OPTIONS_SUPPRESS_WARNINGS":"Suprimir las advertencias",
            "LOGIN_FAILED_GATEWAY_BUSY":"El gateway está completamente ocupado. Vuelva a intentarlo.",
            "DESC_EMAIL":"Enviar un correo a la asistencia técnica",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Apertura permanente desconectada",
            "CLEANING_PORTS_CONTENT":"Preparando la función “Añadir”",
            "DESC_HOME_ACTORS":"Memorizar y administrar dispositivos",
            "ERROR_TIMEOUT":"Error de conexión",
            "CREATE_USER_TITLE":"Añadir usuario",
            "ERROR_DELETE_ADMIN_CONTENT":"No puede borrarse el administrador.",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Acceso rápido",
            "ADD_SCENARIO_NAME":"Nombre",
            "HIST":"Historia",
            "DESC_RESET_LOGIN_SUBMIT":"Confirmar “Borrar”",
            "POPUP_WARNING":"Atención",
            "REMOVE_GROUP_PROCESS":"El dispositivo se borra.",
            "POPUP_LOGIN_PROCESS":"Login",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Espere...",
            "DESC_DEFAULT_GW_SUBMIT":"Adoptar ajustes",
            "DESC_CHANGE_PASSWORD_RETYPE":"Repetir la entrada",
            "LOAD_USERS_CONTENT":"Se están cargando todos los usuarios del gateway.\nEste proceso puede durar varios segundos.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Si está activado el acceso rápido para un gateway, la App inicia sesión automáticamente cuando sea posible.",
            "GATE_OTHER":"Otros dispositivos",
            "CHANGE_PWD_USER_INVALID":"Error",
            "CHANNEL_LIGHT":"Luz",
            "LOGIN_TITLE":"Login",
            "CHANNEL_HALF":"Apertura parcial",
            "GATEWAY_SCREEN_ADD_HELP":"Para añadir un gateway, seleccione el signo+.",
            "ERROR_TIMEOUT_CONTENT":"Se ha excedido el tiempo de comunicación con el gateway.",
            "ERROR_NO_PORTS_LEARNED":"No es posible la función “Añadir”.",
            "OPTIONS_SUPPRESS_INFOS":"Suprimir las indicaciones",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Error",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Modo automático",
            "GENERAL_DELETE":"Borrar",
            "GENERAL_PASSWORD":"Contraseña",
            "STATE_COLLECTING_CONTENT":"Se consulta el estado de los dispositivos.",
            "ERROR_REMOVE_USER_CONTENT":"No se ha podido borrar el usuario",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Error",
            "ACTORS_ADD_HELP":"Para añadir un dispositivo, seleccione el signo+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"¿Realmente desea borrar el dispositivo?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Espere...",
            "GENERAL_YES":"Sí",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Antes de añadir un dispositivo memorizar como mínimo un canal.",
            "CHANGE_GW_NAME_ERROR_CONTENT":"No se ha podido cambiar el nombre.",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"La App no ha encontrado aún ningún gateway.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentificación fallida",
            "DESC_MANAGE_POPUPS_INFOS":"Suprimir los popup de información",
            "GATE_PILOMAT_POLLER":"Bolardo",
            "DESC_CHANNELS_STATE":"Estado del dispositivo con función de respuesta",
            "DESC_GWSCREEN_REFRESH":"Actualización de la lista de gateway",
            "POPUP_SCENARIO_DISPATCHING":"Se ejecuta el ambiente",
            "ERROR_PORT_UNREACHABLE":"Fallido",
            "POPUP_GATEWAY_FOUND_CONTENT":"Se han añadido los gateways siguientes:",
            "WIFI_STATE_SECURITY_MISMATCH":"No se soporta el tipo de encriptación del WLAN.",
            "LOGOUT_NAMED":"salir",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Abrir las condiciones de privacidad",
            "ERROR_NO_GW_CONTENT":"No se ha encontrado ningún gateway Hörmann en la red local.\nAñadir otros gateways con la tecla+.",
            "DESC_EDIT_USERS_ADD":"Añadir usuario",
            "ERROR_NO_PORT_FOUND":"No se ha encontrado el puerto",
            "GATE_SLIDING_GATE":"Cancela corredera",
            "DESC_CHANNELS_BUTTONS":"Elementos de mando del dispositivo",
            "DRIVE_MESSAGE_EXTENDED":"elevado",
            "WIFI_SELECTED_NETWORK":"Nombre",
            "ERROR_ADD_GROUP_NO_NAME":"No se ha introducido ningún nombre para el dispositivo nuevo.",
            "DESC_HELP":"Función de ayuda",
            "CHANGE_PWD_NEW_PASSWORD":"Nueva contraseña",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Adoptar la nueva contraseña",
            "DESC_CHANGE_PASSWORD_PWD":"Introducción de la nueva contraseña",
            "ERROR_EDIT_ADMIN_CONTENT":"No se puede editar el administrador",
            "CHANGE_GW_NAME_NAME_INVALID":"Fallido",
            "STATE_COLLECTING_FAILED":"Error",
            "GENERAL_ADD":"Añadir",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Contraseña\" y \"Repetir contraseña\" deben ser idénticos",
            "WIFI_SETTINGS":"Ajustes de WLAN",
            "LEARN_PORTS_TITLE":"Añadir dispositivo",
            "ERROR_CHANGE_USERNAME":"Fallido",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Bloqueo de paso",
            "ERROR_INVALID_GATEWAY_CONTENT":"No se ha podido establecer una conexión con el gateway. Compruebe el nombre del host.",
            "DESC_EDIT_USERS_EDIT":"Borrar usuario",
            "ERROR_ADD_GROUP_NAME_LENGTH":"El nombre del dispositivo debe estar compuesto de 2 a 20 caracteres",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"No es posible el acceso rápido.",
            "CHANNEL_UP":"Abrir",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Apertura permanente conectada",
            "PORTAL_VALIDATION_FAILED":"Fallido",
            "DESC_RESET_LOGIN_CANCEL":"Interrumpir la acción",
            "CHANGE_PWD_SETTING_PASSWORD":"Adoptar",
            "LOADING_GROUPS_TITLE":"Cargando...",
            "DESC_DEFAULT_GW_CANCEL":"Interrumpir la acción",
            "DESC_SET_RIGHTS_SAVE":"Adoptar modificaciones",
            "REMOVING_PROCESS":"Borrar",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"No es posible conectarse con el gateway.",
            "CONFIRM_DELETE_TITLE":"Borrar gateway",
            "SCENARIOS_ADD_HELP":"Para añadir un escenario, seleccione el signo+.",
            "LOGOUT":"Salir",
            "DESC_ACTORS_BACK":"Volver al menú principal",
            "ERROR_ADAPTER_BUSY_CONTENT":"La orden no ha podido realizarse.\n El gateway está completamente ocupado.",
            "DESC_WIFI_NETWORK_SCAN":"Buscar redes",
            "DRIVE_MESSAGE_HALF":"Abierto parcialmente",
            "DESC_SCENARIOS_ADD":"Crear ambiente",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Comunicación con el gateway fallida",
            "SAVING_USER_RIGHTS":"Guardando",
            "DESC_GWSCREEN_PORTAL":"Introducción de los datos del portal",
            "GATE_JACK":"Caja de enchufe vía radiofrecuencia",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"¿Se encuentra en la misma red que su gateway?",
            "GATE_DOOR":"Puerta",
            "POPUP_PORTAL_UNAVAILABLE":"No se ha podido conectar con el servidor del portal.",
            "DESC_SET_RIGHTS_BACK":"Volver a “Usuarios”",
            "GATE_SMARTKEY":"Automatismo de cerradura de puerta",
            "POPUP_GATEWAY_FOUND_TITILE":"Búsqueda concluida",
            "WIFI_LOADING_DATA_TITLE":"Cargando...",
            "GENERAL_PORTS":"Canales",
            "DESC_SCENARIOS_EDIT":"Administrar o borrar el ambiente",
            "OPTIONS_LEARNED_PORTS":"Canales memorizados:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Acepto las condiciones de privacidad.",
            "DESC_EDIT_USERS_SET_RIGHTS":"Seleccionar usuario para cambiar sus derechos de acceso",
            "DRIVE_MESSAGE_HALF_MOVING":"Abierta parcialmente / En movimiento",
            "PORTAL_SET_ID_DIALOG":"Ajustes del portal",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Sin punto de referencia",
            "POPUP_SETTING_STATE":"Espere...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/es/condiciones-de-uso",
            "ERROR_CHANGE_USERNAME_CONTENT":"No se ha podido cambiar el nombre de usuario",
            "GROUP_REQUESTABLE":"El dispositivo cuenta con la función de respuesta.",
            "LOADING_STATES_TITLE":"Cargando...",
            "DESC_HOME_USERS":"Gestión de usuarios",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"La contraseña debe estar compuesta de 4 a 20 caracteres.",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Se ha adoptado la contraseña.",
            "POPUP_GATE_OUT_OF_VIEW":"Solo está permitido manejar una instalación de puerta automática sin visión sobre la puerta si adicionalmente a la limitación de fuerza existente de serie ha montado también una célula fotoeléctrica en la puerta.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Seleccione si los avisos popup deben mostrarse o suprimirse.",
            "CHANNEL_IMPULS":"Impulso",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorizado",
            "DRIVE_MESSAGE_LOCKED":"Bloqueada",
            "CHANNEL_DOWN":"Cerrar",
            "POPUP_INET_SPEED_LOW":"Su conexión de datos no es suficiente para esta aplicación.",
            "CHANGE_PWD_FAILED_CONTENT":"No se ha podido cambiar la contraseña",
            "GENERAL_GROUP_TYPE":"Tipo de dispositivo",
            "CHANNEL_WALK":"Hoja principal",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Puerta de garaje de desplazamiento horizontal",
            "POPUP_AGREEMENT_CONTENT":"Antes de usar la App acepte las condiciones de privacidad / condiciones de uso.",
            "INFO":"Información",
            "LOADING_GROUPS_CONTENT":"Cargando dispositivos",
            "GATE_PILOMAT_REIFENKILLER":"Pinchaneumáticos",
            "GATE_PILOMAT_HUBBALKEN":"Barrera de elevación",
            "GENERAL_RETYPE":"Repetir contraseña",
            "DESC_OTIONS_BACK":"Volver al menú principal",
            "DESC_SET_RIGHTS":"Seleccionar el dispositivo para otorgar derechos de acceso al usuario",
            "WIFI_SCANNING_TITLE":"Búsqueda",
            "WIFI_STATE_CONNECTION_FAILURE":"Creación de conexión fallida",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"El nombre de usuario debe estar compuesto de 2 a 20 caracteres.",
            "REMOVE_PORTS":"Borrar",
            "GENERAL_ON":"Conectado",
            "DESC_CHANGE_PASSWORD_CANCEL":"Interrumpir la acción",
            "LEARNING_PROCESS_CONTENT":"Espere...",
            "LOGIN_FAILED_UNKNOWN":"Se ha producido un error inesperado.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"No pueden modificarse los derechos de usuario del administrador."
         };
         return _loc1_;
      }
   }
}
