package
{
   import mx.resources.ResourceBundle;
   
   public class et_ET$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function et_ET$LocalizedStrings_properties()
      {
         super("et_ET","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Lukusta",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Sisestage Hörmanni portaali ligipääsuandmed",
            "ERROR_DELETE_ADMIN":"Ei ole võimalik",
            "LOGIN_SHOULD_SAVE":"Andmete salvestamine",
            "LOAD_USERS_TITLE":"Palun oodake",
            "CHANGE_GW_NAME_SETTING":"Ülevõtmine",
            "CONFIRM_DELETE_GROUP":"Kustuta seade",
            "GENERAL_NO":"Ei",
            "DESC_GWSCREEN_ADD":"Lokaalse Gateway lisamine",
            "DRIVE_MESSAGE_NOT_RETRACTED":"ei ole sees",
            "WIFI_PASSPHRASE":"parool",
            "CHANNEL_ON":"sees",
            "SCENARIOS":"Stsenaariumid",
            "ERROR_SET_ADMIN_RIGHTS":"Ei ole võimalik",
            "DESC_DEFAULT_GW_SAVE":"Kiirligipääsu seadistamine aktiveeritud Gateway\'le",
            "POPUP_INFO":"Märkus",
            "DRIVE_MESSAGE_ERROR":"TÄHELEPANU: Viga",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Võrgu nimi",
            "EMAIL_BODY":"Te võite oma küsimused saata meile e-maili teel. Selle jaoks saate kasutada ka meie KKK funktsiooni.\n\nBiSecur-Home teenuse klienditugi",
            "CONFIRM_DELETE_USER":"Kustuta kasutaja",
            "DESC_CHANNELS_BACK":"Tagasi seadmete nimekirja",
            "CHANGE_PWD_FIRST_START":"Muutke salasõna tehaseseadistus turvalisuse huvides peale esmakordsest sisse logimist ära",
            "GENERAL_DEFAULT_GATEWAY":"Kiirligipääs",
            "CHANGE_PWD_PASSWORD_INVALID":"Viga",
            "ERROR_NO_GW_TITLE":"Gateway\'d puuduvad",
            "POPUP_SETTING_STATE_CONTENT":"Käsku teostatakse",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-i andmeid laetakse",
            "OPTIONS_RESET_LOGIN_DATA":"Salvestatud sisselogimisandmete kustutamine",
            "EDIT_USER_TITLE":"Kasutajate andmete muutmine",
            "DESC_HOME_PREFERENCES":"Gateway ja rakenduse seadete muutmine",
            "WIFI_ACTIVE_STATE":"WLAN olek",
            "STATE_COLLECTING":"Laen",
            "ADD_SCENARIO":"Stsenaariumi lisamine",
            "STATE_COLLECTING_FAILED_CONTENT":"Olekut ei laetud",
            "GATE_SWING_GATE_SINGLE":"1 tiivaga tiibvärav",
            "ACTORS":"seadmed",
            "POPUP_AGREEMENT":"Kasutamine / Andmekaitse",
            "CHANNEL_OPEN_DOOR":"Ava",
            "DESC_ACTORS_REFRESH":"Oleku värskendamine",
            "GENERAL_OFF":"Välja lülitatud",
            "OPTIONS_HELP":"Online abi",
            "COPY_PORTS_CONTENT":"Seadke kaugjuhtimispult õpetamisrežiimi, vaata juhend. Valige õpetatav kanal.",
            "GENERAL_SELECT":"Palun valige...",
            "ERROR_ADAPTER_BUSY":"Viga",
            "INFO_BOX_INFOS":"Üldine",
            "GATE_LIGHT":"Valgus",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Ava kasutustingimused",
            "DESC_MANAGE_POPUPS_WARNINGS":"Blokeeri hoiatuste hüpikaknad",
            "MAX_USERSS_REACHED_CONTENT":"Lubatud maksimaalne kasutajate arv on täis.",
            "GENERAL_REMOVE":"Eemalda",
            "OPTIONS":"Seaded",
            "DESC_HOME_SCENARIOS":"Stsenaariumide koostamine ja haldamine",
            "CHANNEL_OFF":"väljas",
            "GENERAL_PORTAL_ID":"Seadme ID",
            "EDIT_GROUP":"Muuda seadet",
            "ERROR_LERANIN_PORT_CONTENT":"Soovitud kanali õpetamine ebaõnnestus.",
            "ERROR_CONNECTION_CLOSED":"Viga",
            "CHANNEL_ON_OFF":"Sees / väljas",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Nimetus",
            "OPTIONS_EDIT_USERS":"Kasutajate haldus",
            "LOADING_STATES_CONTENT":"Küsitakse hetke olekut.\nPalun oodake...",
            "LERAN_PORTS_CONTENT":"Aktiveerige seadme õppimisrežiim, vaata juhend. Valige õpetatav kanal.",
            "REMOVE_PORTS_CONTENT":"Valige välja need kanalid, mida soovite kustutada.",
            "GATE_SWING_GATE_DOUBLE":"2 tiivaga tiibvärav",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Kontrollige, kas Te olete oma portaaliandmed sisestanud või lisanud lokaalse Gateway.",
            "CHANNEL_SINK":"langeta",
            "OPTIONS_EDIT_USERS_TITLE":"Kasutaja",
            "MAX_PORTS_REACHED_CONTENT":"Maksimaalne arv kanaleid hõivatud",
            "MAX_PORTS_REACHED":"Ei ole võimalik",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Soovitud seadmega ei olnud võimalik ühendust saada",
            "PORTAL_AUTHENTICATION_FAILED":"Ebaõnnestus",
            "NOTIFICATION_CENTER":"Teated",
            "LEARNING_PROCESS":"Õpetamine",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Kasutajanimi peab olema 2 - 20 märgi pikkune",
            "WIFI_STATE_CONNECTED":"Ühendatud",
            "COPY_PORTS":"Õpi kaugjuhtimispuldilt",
            "POPUP_SEARCH_CONTENT":"Hörmanni Gateway otsimine \n\nSee protsess võib võtta aega mõned sekundid.",
            "DESC_MANAGE_POPUPS_CANCEL":"Katkesta tegevus",
            "DESC_WIFI_PASSWORD":"parool",
            "DESC_WIFI_SAVE":"Salvesta",
            "DRIVE_MESSAGE_STOP_ACTIVE":"stopp aktiveeritud",
            "SELECT_GATEWAY":"Gateway\'d",
            "CLEANING_PORTS":"Lisa seade",
            "WIFI_STATE_BUSY":"Ühendust luuakse",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Sisestatud salasõna on vale",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Gateway nime muutmine",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Nimi kinnitatakse",
            "DESC_ACTORS_EDIT":"Seadmete haldamine või kustutamine",
            "DESC_WIFI_STATE":"Ühenduse olek",
            "ERROR_REMOVE_USER":"Ebaõnnestus",
            "LANG_TAG":"ET",
            "DESC_MANAGE_POPUPS_SUBMIT":"Kinnita seadistus",
            "HOME_TITLE":"Pealeht",
            "GENERAL_USERNAME":"Kasutajanimi",
            "DRIVE_MESSAGE_OPENED":"avatud",
            "CONFIRM_DELETE":"Kas olete kindel, et soovite Gateway kustutada?",
            "DRIVE_MESSAGE_CLOSED":"suletud",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portaali server ei ole kätte saadav",
            "REMOVING_PROCESS_CONTENT":"Kanal kustutatakse",
            "DESC_EDIT_USERS_BACK":"Tagasi seadetesse",
            "ERROR_NO_GROUP_FOUND":"Seadet ei leitud",
            "ERROR_INVALID_GATEWAY":"Gateway\'d ei leitud",
            "DESC_WIFI_BACK":"Tagasi seadetesse",
            "MAX_USERS_REACHED":"Ei ole võimalik",
            "DESC_CHANGE_PASSWORD_USERNAME":"Kasutajanimi",
            "POPUP_AGREEMENT_ACCEPT_USE":"Ma nõustun kasutustingimustega",
            "ERROR_LERNING_PORT":"Ebaõnnestus",
            "POPUP_ADD_GATEWAY_CONTENT":"Sisestage IP aadress:",
            "ERROR_ADD_GROUP":"Viga",
            "DRIVE_MESSAGE_NO_DATA":"Andmed puuduvad",
            "CHANGE_PWD_FAILED":"Ebaõnnestus",
            "SAVING_USER_RIGHTS_CONTENT":"Kasutajaõigused salvestatakse",
            "DRIVE_MESSAGE_UNLOCKED":"ei ole lukustatud",
            "GENERAL_SAVE":"Salvesta",
            "INFO_BOX_FAQ":"KKK",
            "GENERAL_CONNNECT":"Ühenda",
            "GATE_SECTIONAL_DOOR":"Vertikaalselt liikuv garaažiuks",
            "OPTIONS_CHANGE_PASSWORD":"Parooli muutmine",
            "CHANNEL":"Kasutamine",
            "CHANGE_GW_NAME_CONTENT":"Gateway nimi",
            "DRIVE_MESSAGE_RETRACTED":"sees",
            "DESC_ADDGWSCREEN_BACK":"Tagasi Gateway\'de ülevaate juurde",
            "EMAIL_SUBJECT":"Klienditugi",
            "ERROR_EDIT_ADMIN":"Ei ole võimalik",
            "OPTIONS_SET_USER_RIGHTS":"Kasutajaõigused",
            "CHANGE_GW_NAME_ERROR":"Ebaõnnestus",
            "CHANNEL_LIFT":"tõsta",
            "LOGIN_FAILED_TITLE":"Ebaõnnestus",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Kui Te kinnitate sisselogimisandmete kustutamise nupule OK vajutamisega, siis peate vastava Gateway valimisel salasõna uuesti sisestama",
            "CHANNEL_UNLOCK":"Lukust lahti",
            "GENERAL_PORTAL_SERVER":"Portaali server",
            "DESC_SCENARIOS_BACK":"Tagasi peamenüüsse",
            "CHANGE_PWD_USERNAME":"Kasutaja:",
            "POPUP_GATE_NOT_RESPONSABLE":"Rakendus saab selle käsu seadmele saata, ei tunne aga ära seadme hetke olekut.",
            "DESC_GW_NAME":"Gateway nimi",
            "GATE_BARRIER":"tõkkepuu",
            "LEARN_PORTS":"Raadiokoodi õpetamine",
            "GENERAL_BACK":"Tagasi",
            "DESC_GWSCREEN_EDIT":"Salvestatud Gateway\'de kustutamiseks",
            "OPTIONS_MANAGE_POPUPS":"Hüpikakende teade haldamine",
            "POPUP_LOGIN_PROCESS_CONTENT":"Palun oodake...",
            "CONFIRM_DELETE_USER_CONTENT":"Kas olete kindel, et soovite kasutajat kustutada?",
            "DESC_MENU":"Menüü",
            "LOGIN_FAILED_WRONG_DATA":"Sisestatud kasutajanimi või salasõna on vale.",
            "GENERAL_CANCEL":"Katkesta",
            "ADD_GROUP":"Lisa seade",
            "WIFI_STATE_AP_NOT_FOUND":"Võrku ei leitud",
            "WIFI_STATE_NOT_CONNECTED":"Ei ole ühendatud",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Kasutamine portaali kaudu on Teie jaoks aktiveeritud!",
            "POPUP_ADD_GATEWAY":"Gateway lisamine",
            "GENERAL_NEXT":"Edasi",
            "POPUP_SUPPRESS":"Hüpikakent enam ei avata",
            "POPUP_SEARCH_TITLE":"Otsimine...",
            "WIFI_SCANNING_CONTENT":"Otsi nähtavaid WLAN võrke",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Gateway\'d ei leitud",
            "DESC_ACTORS_ADD":"Seadme loomine",
            "ERROR_ADD_GROUP_NO_TYPE":"Uue seadme jaoks ei valitud tüüpi.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Kontrollige sisselogimise andmeid",
            "GENERAL_REFESHED":"uuendatud",
            "OPTIONS_SUPPRESS_WARNINGS":"Hoiatuste blokeerimine",
            "LOGIN_FAILED_GATEWAY_BUSY":"Gateway on hetkel koormatud. Proovige hiljem uuesti.",
            "DESC_EMAIL":"E-maili saatmine klienditoele",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"pidevalt avatud väljas",
            "CLEANING_PORTS_CONTENT":"Lisamist valmistatakse ette",
            "DESC_HOME_ACTORS":"Seadmete õppimine ja haldamine",
            "ERROR_TIMEOUT":"Ühenduse viga",
            "CREATE_USER_TITLE":"Kasutaja lisamine",
            "ERROR_DELETE_ADMIN_CONTENT":"Administraatorit ei saa kustutada",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Kiirligipääs",
            "ADD_SCENARIO_NAME":"Nimi",
            "HIST":"Ajalugu",
            "DESC_RESET_LOGIN_SUBMIT":"Kinnita kustutamine",
            "POPUP_WARNING":"TÄHELEPANU",
            "REMOVE_GROUP_PROCESS":"Seade kustutatakse",
            "POPUP_LOGIN_PROCESS":"Sisselogimine",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Palun oodake...",
            "DESC_DEFAULT_GW_SUBMIT":"Kinnita seadistus",
            "DESC_CHANGE_PASSWORD_RETYPE":"Sisesta uuesti",
            "LOAD_USERS_CONTENT":"Gateway\'lt laetakse kõik kasutajad.\nSee protsess võib võtta aega mõningad sekundid.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Kui Gateway kiirligipääs on aktiveeritud, siis logib rakendus võimalusel ise automaatselt sisse",
            "GATE_OTHER":"Muud seadmed",
            "CHANGE_PWD_USER_INVALID":"Viga",
            "CHANNEL_LIGHT":"Valgus",
            "LOGIN_TITLE":"Sisselogimine",
            "CHANNEL_HALF":"Osaline avamine",
            "GATEWAY_SCREEN_ADD_HELP":"Gateway lisamiseks valige +sümbol.",
            "ERROR_TIMEOUT_CONTENT":"Ajapiirangu ületamine kommunikatsioonil Gateway\'ga",
            "ERROR_NO_PORTS_LEARNED":"Lisamine ei ole võimalik",
            "OPTIONS_SUPPRESS_INFOS":"Märkuste blokeerimine",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Viga",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automaatrežiim",
            "GENERAL_DELETE":"Kustutamine",
            "GENERAL_PASSWORD":"parool",
            "STATE_COLLECTING_CONTENT":"Küsitakse seadmete olekut",
            "ERROR_REMOVE_USER_CONTENT":"Kasutajat ei õnnestunud kustutada",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Viga",
            "ACTORS_ADD_HELP":"Seadme lisamiseks valige +sümbol.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Kas olete kindel, et soovite seadet kustutada?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Palun oodake...",
            "GENERAL_YES":"Jah",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Enne seadme lisamist tuleb vähemalt üks kanal õpetada",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Nime ei õnnestunud muuta",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Rakendus ei ole veel ühtegi Gateway\'d leidnud",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentimine ebaõnnestus",
            "DESC_MANAGE_POPUPS_INFOS":"Blokeeri info hüpikaknad",
            "GATE_PILOMAT_POLLER":"pollar",
            "DESC_CHANNELS_STATE":"Tagasisidevõimelise seadme olek",
            "DESC_GWSCREEN_REFRESH":"Gateway\'de nimekirja värskendamine",
            "POPUP_SCENARIO_DISPATCHING":"Stsenaarium teostatakse",
            "ERROR_PORT_UNREACHABLE":"Ebaõnnestus",
            "POPUP_GATEWAY_FOUND_CONTENT":"Lisati järgmised Gateway\'d:",
            "WIFI_STATE_SECURITY_MISMATCH":"Seda WLAN-i krüpteeringu liiki ei toetata",
            "LOGOUT_NAMED":"väljalogimine",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Ava andmekaitsetingimused",
            "ERROR_NO_GW_CONTENT":"Kohalikus võrgus ei õnnestunud Hörmanni Gateway\'d tuvastada.\nLisage täiendavaid Gateway seadmeid +märgi kaudu",
            "DESC_EDIT_USERS_ADD":"Kasutaja lisamine",
            "ERROR_NO_PORT_FOUND":"Porti ei leitud",
            "GATE_SLIDING_GATE":"Liugvärav",
            "DESC_CHANNELS_BUTTONS":"Seadme käituselemendid",
            "DRIVE_MESSAGE_EXTENDED":"väljas",
            "WIFI_SELECTED_NETWORK":"Nimi",
            "ERROR_ADD_GROUP_NO_NAME":"Uue seadme jaoks ei sisestatud nime.",
            "DESC_HELP":"Abifunktsioon",
            "CHANGE_PWD_NEW_PASSWORD":"Uus parool",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Kinnita uus salasõna",
            "DESC_CHANGE_PASSWORD_PWD":"Sisesta uus salasõna",
            "ERROR_EDIT_ADMIN_CONTENT":"Administraatori seadeid ei saa muuta",
            "CHANGE_GW_NAME_NAME_INVALID":"Ebaõnnestus",
            "STATE_COLLECTING_FAILED":"Viga",
            "GENERAL_ADD":"Lisa",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Parool\" ja \"Korda parooli\" peavad olema identsed",
            "WIFI_SETTINGS":"WLAN seaded",
            "LEARN_PORTS_TITLE":"Lisa seade",
            "ERROR_CHANGE_USERNAME":"Ebaõnnestus",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"läbisõidutõkis",
            "ERROR_INVALID_GATEWAY_CONTENT":"Gateway\'ga ei õnnestunud ühendust luua. Palun kontrollige hostinime.",
            "DESC_EDIT_USERS_EDIT":"Kustuta kasutaja",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Seadme nimi peab olema 2 - 20 märki pikk",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Kiirligipääs ei ole võimalik",
            "CHANNEL_UP":"Lahti",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"pidevalt avatud sees",
            "PORTAL_VALIDATION_FAILED":"Ebaõnnestus",
            "DESC_RESET_LOGIN_CANCEL":"Katkesta tegevus",
            "CHANGE_PWD_SETTING_PASSWORD":"Ülevõtmine",
            "LOADING_GROUPS_TITLE":"Laen",
            "DESC_DEFAULT_GW_CANCEL":"Katkesta tegevus",
            "DESC_SET_RIGHTS_SAVE":"Kinnita muudatus",
            "REMOVING_PROCESS":"Kustutamine",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Gateway\'ga ei ole võimalik ühendust saada",
            "CONFIRM_DELETE_TITLE":"Gateway kustutamine",
            "SCENARIOS_ADD_HELP":"Stsenaariumi lisamiseks valige +sümbol.",
            "LOGOUT":"Väljalogimine",
            "DESC_ACTORS_BACK":"Tagasi peamenüüsse",
            "ERROR_ADAPTER_BUSY_CONTENT":"Käsku ei olnud võimalik teostada.\n Gateway on hetkel koormatud.",
            "DESC_WIFI_NETWORK_SCAN":"Otsi võrkude järgi",
            "DRIVE_MESSAGE_HALF":"osaliselt avatud",
            "DESC_SCENARIOS_ADD":"Stsenaariumi koostamine",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Kommunikatsioon Gateway\'ga ebaõnnestus.",
            "SAVING_USER_RIGHTS":"Salvesta",
            "DESC_GWSCREEN_PORTAL":"Portaali andmete sisestamine",
            "GATE_JACK":"Raadio-pistikupesa",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Kas olete samas võrgus kui Teie Gateway?",
            "GATE_DOOR":"Uks",
            "POPUP_PORTAL_UNAVAILABLE":"Portaali server ei ole kätte saadav",
            "DESC_SET_RIGHTS_BACK":"Tagasi kasutajate nimekirja",
            "GATE_SMARTKEY":"Ukselukuajam",
            "POPUP_GATEWAY_FOUND_TITILE":"Otsing lõpetatud",
            "WIFI_LOADING_DATA_TITLE":"Laen",
            "GENERAL_PORTS":"Kanalid",
            "DESC_SCENARIOS_EDIT":"Stsenaariumide haldamine ja kustutamine",
            "OPTIONS_LEARNED_PORTS":"Õpitud kanalid:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Ma nõustun andmekaitsetingimustega",
            "DESC_EDIT_USERS_SET_RIGHTS":"Kasutaja valimine ligipääsuõiguste muutmiseks",
            "DRIVE_MESSAGE_HALF_MOVING":"osaliselt avatud / liikumises",
            "PORTAL_SET_ID_DIALOG":"Portaali seadistused",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Referentspunkt puudub",
            "POPUP_SETTING_STATE":"Palun oodake...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Kasutajanime ei õnnestunud muuta",
            "GROUP_REQUESTABLE":"Seade on tagasisidevõimeline",
            "LOADING_STATES_TITLE":"Laen",
            "DESC_HOME_USERS":"Kasutajate haldus",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Salasõna peab olema 4 - 20 märgi pikkune",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Salasõna kinnitatakse",
            "POPUP_GATE_OUT_OF_VIEW":"Ajamiga ukse- või väravasüsteemi käitamine ilma, et see oleks nägemisväljas, on lubatud ainult siis, kui uksele või väravale on paigaldatud lisaks standardvarustuses olemasolevale jõupiirangule veel ka fotosilm.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Valige kas hüpikakendega teateid kuvatakse või mitte",
            "CHANNEL_IMPULS":"Impulss",
            "PORTAL_VALIDATION_SUCCEEDED":"autoriseeritud",
            "DRIVE_MESSAGE_LOCKED":"lukustatud",
            "CHANNEL_DOWN":"Kinni",
            "POPUP_INET_SPEED_LOW":"Teie andmesideühendus ei ole selle rakenduse jaoks piisav",
            "CHANGE_PWD_FAILED_CONTENT":"Parooli ei õnnestunud muuta",
            "GENERAL_GROUP_TYPE":"Seadme tüüp",
            "CHANNEL_WALK":"Käigutiib",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horisontaalselt liikuv garaažiuks",
            "POPUP_AGREEMENT_CONTENT":"Enne rakenduse kasutamist tuleb nõustuda andmekaitse- / kasutustingimustega",
            "INFO":"Informatsioonid",
            "LOADING_GROUPS_CONTENT":"Laen seadmeid",
            "GATE_PILOMAT_REIFENKILLER":"rehvipurustaja",
            "GATE_PILOMAT_HUBBALKEN":"tõkkepuu",
            "GENERAL_RETYPE":"Korda parooli",
            "DESC_OTIONS_BACK":"Tagasi peamenüüsse",
            "DESC_SET_RIGHTS":"Seadme valimine kasutajale ligipääsuõiguste andmiseks",
            "WIFI_SCANNING_TITLE":"Otsi",
            "WIFI_STATE_CONNECTION_FAILURE":"Ühenduse loomine ebaõnnestus",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Kasutajanimi peab olema 2 - 20 märgi pikkune",
            "REMOVE_PORTS":"Kustutamine",
            "GENERAL_ON":"Sisse lülitatud",
            "DESC_CHANGE_PASSWORD_CANCEL":"Katkesta tegevus",
            "LEARNING_PROCESS_CONTENT":"Palun oodake...",
            "LOGIN_FAILED_UNKNOWN":"Esines ootamatu viga.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Administraatori kasutajaõigusi ei saa muuta!"
         };
         return _loc1_;
      }
   }
}
