package
{
   import mx.resources.ResourceBundle;
   
   public class fi_FI$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function fi_FI$LocalizedStrings_properties()
      {
         super("fi_FI","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Lukitse",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Syötä Hörmann-portaalin pääsytiedot",
            "ERROR_DELETE_ADMIN":"Ei mahdollinen",
            "LOGIN_SHOULD_SAVE":"Tietojen tallentaminen",
            "LOAD_USERS_TITLE":"Odota",
            "CHANGE_GW_NAME_SETTING":"Tallenna",
            "CONFIRM_DELETE_GROUP":"Laitteen poistaminen",
            "GENERAL_NO":"Ei",
            "DESC_GWSCREEN_ADD":"Paikallisten yhdyskäytävien lisääminen",
            "DRIVE_MESSAGE_NOT_RETRACTED":"Ei sisäänajettu",
            "WIFI_PASSPHRASE":"Salasana",
            "CHANNEL_ON":"Päällä",
            "SCENARIOS":"Tapahtumasarjat",
            "ERROR_SET_ADMIN_RIGHTS":"Ei mahdollinen",
            "DESC_DEFAULT_GW_SAVE":"Pikapääsyn luominen sen hetkiseen yhdyskäytävään",
            "POPUP_INFO":"Ohje",
            "DRIVE_MESSAGE_ERROR":"HUOMIO: virhe",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Verkon nimi",
            "EMAIL_BODY":"Voit lähettää kysymyksesi meille sähköpostilla. Voit käyttää myös sivullamme olevaa FAQ-toimintoa.\n\nTerveisin BiSecur-Home Support-tiimi",
            "CONFIRM_DELETE_USER":"Käyttäjän poistaminen",
            "DESC_CHANNELS_BACK":"Takaisin laitelistaan",
            "CHANGE_PWD_FIRST_START":"Vaihda turvallisuussyistä salasanasi tehdasasetus ensimmäisen sisäänkirjautumisen jälkeen",
            "GENERAL_DEFAULT_GATEWAY":"Pikapääsy",
            "CHANGE_PWD_PASSWORD_INVALID":"Virhe",
            "ERROR_NO_GW_TITLE":"Ei yhdyskäytäviä",
            "POPUP_SETTING_STATE_CONTENT":"Komento suoritetaan",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-tiedot ladataan",
            "OPTIONS_RESET_LOGIN_DATA":"Poista tallennetut sisäänkirjautumistiedot",
            "EDIT_USER_TITLE":"Käyttäjien muokkaaminen",
            "DESC_HOME_PREFERENCES":"Yhdyskäytävän ja sovelluksen asetusten muuttaminen",
            "WIFI_ACTIVE_STATE":"WLAN-tila",
            "STATE_COLLECTING":"Lataa",
            "ADD_SCENARIO":"Lisää tapahtumasarja",
            "STATE_COLLECTING_FAILED_CONTENT":"Tilaa ei ole ladattu",
            "GATE_SWING_GATE_SINGLE":"1-lehtinen saranoitu ovi",
            "ACTORS":"Laitteet ",
            "POPUP_AGREEMENT":"Käyttö / tietosuoja",
            "CHANNEL_OPEN_DOOR":"Avaa",
            "DESC_ACTORS_REFRESH":"Tilan päivittäminen",
            "GENERAL_OFF":"Kytketty pois",
            "OPTIONS_HELP":"Online-apu",
            "COPY_PORTS_CONTENT":"Aseta kanava opettamistilaan, ks. ohje. Valitse opetettava kanava.",
            "GENERAL_SELECT":"Valitse...",
            "ERROR_ADAPTER_BUSY":"Virhe",
            "INFO_BOX_INFOS":"Yleistä",
            "GATE_LIGHT":"Valo",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Käyttöehtojen avaaminen",
            "DESC_MANAGE_POPUPS_WARNINGS":"Popup-varoitusilmoitusten piilottaminen",
            "MAX_USERSS_REACHED_CONTENT":"Käyttäjien suurin lukumäärä on saavutettu.",
            "GENERAL_REMOVE":"Poistaminen",
            "OPTIONS":"Asetukset",
            "DESC_HOME_SCENARIOS":"Tapahtumaketjujen luominen ja hallitseminen",
            "CHANNEL_OFF":"Pois päältä",
            "GENERAL_PORTAL_ID":"Laite-ID",
            "EDIT_GROUP":"Laitteen muokkaaminen",
            "ERROR_LERANIN_PORT_CONTENT":"Halutun kanavan opettaminen epäonnistui",
            "ERROR_CONNECTION_CLOSED":"Virhe",
            "CHANNEL_ON_OFF":"Päällä/pois",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Nimitys",
            "OPTIONS_EDIT_USERS":"Käyttäjien hallinta",
            "LOADING_STATES_CONTENT":"Sen hetkinen tila avataan.\nOdota...",
            "LERAN_PORTS_CONTENT":"Aseta laite oppimistilaan, ks. ohje. Valitse opetettava kanava.",
            "REMOVE_PORTS_CONTENT":"Valitse kanavat, jotka haluat poistaa.",
            "GATE_SWING_GATE_DOUBLE":"2-lehtinen saranoitu ovi",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Tarkista, oletko syöttänyt portaalitiedot vai lisännyt paikallisen yhdyskäytävän.",
            "CHANNEL_SINK":"Lasku",
            "OPTIONS_EDIT_USERS_TITLE":"Käyttäjä",
            "MAX_PORTS_REACHED_CONTENT":"Kanavien maksimilukumäärä varattu",
            "MAX_PORTS_REACHED":"Ei mahdollinen",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Pyydettyä laitetta ei saavutettu",
            "PORTAL_AUTHENTICATION_FAILED":"Epäonnistui",
            "NOTIFICATION_CENTER":"Viestit",
            "LEARNING_PROCESS":"Opettaminen",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Käyttäjänimessä on oltava 2 - 20 merkkiä",
            "WIFI_STATE_CONNECTED":"Yhteys luotu",
            "COPY_PORTS":"Käsilähettimestä opettaminen",
            "POPUP_SEARCH_CONTENT":"Hakee Hörmann-yhdyskäytäviä \n\nToimenpide voi kestää useita sekunteja.",
            "DESC_MANAGE_POPUPS_CANCEL":"Toimenpiteen keskeyttäminen",
            "DESC_WIFI_PASSWORD":"Salasana",
            "DESC_WIFI_SAVE":"Tallentaminen",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Pysäytys aktiivinen",
            "SELECT_GATEWAY":"Yhdyskäytävät",
            "CLEANING_PORTS":"Lisää laite",
            "WIFI_STATE_BUSY":"Yhteys luodaan",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Syötetty salasana on virheellinen",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Vaihda yhdyskäytävän nimi",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Nimi tallennetaan",
            "DESC_ACTORS_EDIT":"Laitteiden hallitseminen ja poistaminen",
            "DESC_WIFI_STATE":"Yhteyden tila",
            "ERROR_REMOVE_USER":"Epäonnistui",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Asetuksen tallentaminen",
            "HOME_TITLE":"Aloitussivu",
            "GENERAL_USERNAME":"Käyttäjänimi",
            "DRIVE_MESSAGE_OPENED":"auki",
            "CONFIRM_DELETE":"Oletko varma, että haluat poistaa yhdyskäytävän?",
            "DRIVE_MESSAGE_CLOSED":"Suljettu",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portaalipalvelinta ei saavutettu",
            "REMOVING_PROCESS_CONTENT":"Kanava poistetaan",
            "DESC_EDIT_USERS_BACK":"Takaisin asetuksiin",
            "ERROR_NO_GROUP_FOUND":"Laitetta ei löytynyt",
            "ERROR_INVALID_GATEWAY":"Yhdyskäytävää ei löytynyt",
            "DESC_WIFI_BACK":"Takaisin asetuksiin",
            "MAX_USERS_REACHED":"Ei mahdollinen",
            "DESC_CHANGE_PASSWORD_USERNAME":"Käyttäjänimi",
            "POPUP_AGREEMENT_ACCEPT_USE":"Hyväksyn käyttöehdot",
            "ERROR_LERNING_PORT":"Epäonnistui",
            "POPUP_ADD_GATEWAY_CONTENT":"Syötä IP-osoite:",
            "ERROR_ADD_GROUP":"Virhe",
            "DRIVE_MESSAGE_NO_DATA":"Tietoja ei saatavilla",
            "CHANGE_PWD_FAILED":"Epäonnistui",
            "SAVING_USER_RIGHTS_CONTENT":"Käyttäjäoikeudet tallennetaan",
            "DRIVE_MESSAGE_UNLOCKED":"Ei lukittu",
            "GENERAL_SAVE":"Tallentaminen",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Yhdistäminen",
            "GATE_SECTIONAL_DOOR":"Vertikaalisesti liikkuva autotallin ovi",
            "OPTIONS_CHANGE_PASSWORD":"Vaihda salasana",
            "CHANNEL":"Käyttö",
            "CHANGE_GW_NAME_CONTENT":"Yhdyskäytävän nimi",
            "DRIVE_MESSAGE_RETRACTED":"Sisäänajettu",
            "DESC_ADDGWSCREEN_BACK":"Palaa takaisin yhdyskäytävien yleisnäkymään",
            "EMAIL_SUBJECT":"Tuki",
            "ERROR_EDIT_ADMIN":"Ei mahdollinen",
            "OPTIONS_SET_USER_RIGHTS":"Käyttäjäoikeudet",
            "CHANGE_GW_NAME_ERROR":"Epäonnistui",
            "CHANNEL_LIFT":"Nosto",
            "LOGIN_FAILED_TITLE":"Epäonnistui",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Mikäli vahvistat sisäänkirjautumistietojen poistamisen valitsemalla OK, salasana on syötettävä uudelleen yhdyskäytävän valinnan yhteydessä",
            "CHANNEL_UNLOCK":"Avaa lukitus",
            "GENERAL_PORTAL_SERVER":"Portaalipalvelin",
            "DESC_SCENARIOS_BACK":"Palaa päävalikkoon",
            "CHANGE_PWD_USERNAME":"Käyttäjä:",
            "POPUP_GATE_NOT_RESPONSABLE":"Sovellus voi lähettää kyseisen komennon laitteelle muttei tunnista laitteen sen hetkistä tilaa.",
            "DESC_GW_NAME":"Yhdyskäytävän nimi",
            "GATE_BARRIER":"puomi",
            "LEARN_PORTS":"Radiokoodin opettaminen",
            "GENERAL_BACK":"takaisin",
            "DESC_GWSCREEN_EDIT":"Tallennettujen yhdyskäytävien poistaminen",
            "OPTIONS_MANAGE_POPUPS":"Popup-ilmoitusten hallinta",
            "POPUP_LOGIN_PROCESS_CONTENT":"Odota...",
            "CONFIRM_DELETE_USER_CONTENT":"Oletko varma, että haluat poistaa käyttäjän?",
            "DESC_MENU":"Valikko",
            "LOGIN_FAILED_WRONG_DATA":"Syötetty käyttäjänimi tai salasana on virheellinen",
            "GENERAL_CANCEL":"Keskeytä",
            "ADD_GROUP":"Lisää laite",
            "WIFI_STATE_AP_NOT_FOUND":"Verkkoa ei löytynyt",
            "WIFI_STATE_NOT_CONNECTED":"Yhteyttä ei luotu",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Portaalin kautta tapahtuva käyttösi on aktivoitu!",
            "POPUP_ADD_GATEWAY":"Lisää yhdyskäytävä",
            "GENERAL_NEXT":"Jatka",
            "POPUP_SUPPRESS":"Älä enää avaa popup-ilmoitusta",
            "POPUP_SEARCH_TITLE":"Haetaan...",
            "WIFI_SCANNING_CONTENT":"Hae näkyviä WLAN-verkkoja",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Yhdyskäytävää ei löytynyt",
            "DESC_ACTORS_ADD":"Laitteen luominen",
            "ERROR_ADD_GROUP_NO_TYPE":"Uudelle laitteelle ei ole valittu tyyppiä.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Tarkista sisäänkirjautumistiedot",
            "GENERAL_REFESHED":"Päivitetty",
            "OPTIONS_SUPPRESS_WARNINGS":"Varoitusten piilottaminen",
            "LOGIN_FAILED_GATEWAY_BUSY":"Yhdyskäytävä on kuormitettuna. Yritä uudelleen.",
            "DESC_EMAIL":"Lähetä sähköpostia tukitiimille",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Kesto auki pois päältä",
            "CLEANING_PORTS_CONTENT":"Lisäämistä valmistellaan",
            "DESC_HOME_ACTORS":"Laitteiden opettaminen ja hallitseminen",
            "ERROR_TIMEOUT":"Yhteysvirhe",
            "CREATE_USER_TITLE":"Lisää käyttäjä",
            "ERROR_DELETE_ADMIN_CONTENT":"Administraattoria ei voi poistaa",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Pikapääsy",
            "ADD_SCENARIO_NAME":"Nimi",
            "HIST":"Historia",
            "DESC_RESET_LOGIN_SUBMIT":"Poistamisen vahvistaminen",
            "POPUP_WARNING":"VAROITUS",
            "REMOVE_GROUP_PROCESS":"Laite poistetaan",
            "POPUP_LOGIN_PROCESS":"Kirjaudu sisään",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Odota...",
            "DESC_DEFAULT_GW_SUBMIT":"Asetuksen tallentaminen",
            "DESC_CHANGE_PASSWORD_RETYPE":"Syötön toistaminen",
            "LOAD_USERS_CONTENT":"Kaikki yhdyskäytävän laitteet ladataan.\nKyseinen toimenpide voi kestää useita sekunteja.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Mikäli yhdyskäytävälle on aktivoitu pikapääsy, sovellus kirjautuu mahdollisuuksien mukaan automaattisesti sisään",
            "GATE_OTHER":"Muut laitteet",
            "CHANGE_PWD_USER_INVALID":"Virhe",
            "CHANNEL_LIGHT":"Valo",
            "LOGIN_TITLE":"Kirjaudu sisään",
            "CHANNEL_HALF":"Osittainen aukaisu",
            "GATEWAY_SCREEN_ADD_HELP":"Valitse symboli+ yhdyskäytävän lisäämiseksi.",
            "ERROR_TIMEOUT_CONTENT":"Aika ylitetty yhdyskäytävän kanssa tapahtuvassa tiedonsiirrossa",
            "ERROR_NO_PORTS_LEARNED":"Lisääminen ei ole mahdollista",
            "OPTIONS_SUPPRESS_INFOS":"Ohjeiden piilottaminen",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Virhe",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automaattikäyttö",
            "GENERAL_DELETE":"Poistaminen",
            "GENERAL_PASSWORD":"Salasana",
            "STATE_COLLECTING_CONTENT":"Laitteiden tilaa kysellään",
            "ERROR_REMOVE_USER_CONTENT":"Käyttäjää ei voitu poistaa",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Virhe",
            "ACTORS_ADD_HELP":"Valitse symboli+ laitteen lisäämiseksi.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Oletko varma, että haluat poistaa laitteen?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Odota...",
            "GENERAL_YES":"Kyllä",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Opeta vähintään yksi kanava ennen laitteen lisäämistä",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Nimeä ei voitu muuttaa",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Sovellus ei ole vielä löytänyt yhdyskäytäviä.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Tunnistautuminen epäonnistui",
            "DESC_MANAGE_POPUPS_INFOS":"Popup-tietoilmoitusten piilottaminen",
            "GATE_PILOMAT_POLLER":"Pollari",
            "DESC_CHANNELS_STATE":"Paluuilmoituskykyisen laitteen tila",
            "DESC_GWSCREEN_REFRESH":"Yhdyskäytävälistan päivittäminen",
            "POPUP_SCENARIO_DISPATCHING":"Tapahtumasarja suoritetaan",
            "ERROR_PORT_UNREACHABLE":"Epäonnistui",
            "POPUP_GATEWAY_FOUND_CONTENT":"Seuraavat yhdyskäytävät on lisätty:",
            "WIFI_STATE_SECURITY_MISMATCH":"WLANin salaustyyppiä ei tueta",
            "LOGOUT_NAMED":"Kirjaudu ulos",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Tietosuojaehtojen avaaminen",
            "ERROR_NO_GW_CONTENT":"Hörmann-yhdyskäytävää ei löytynyt paikallisesta verkosta.\nLisää muita yhdyskäytäviä +merkillä",
            "DESC_EDIT_USERS_ADD":"Lisää käyttäjä",
            "ERROR_NO_PORT_FOUND":"Porttia ei löytynyt",
            "GATE_SLIDING_GATE":"Liukuovi",
            "DESC_CHANNELS_BUTTONS":"Laitteen ohjauselementit",
            "DRIVE_MESSAGE_EXTENDED":"Ulosajettu",
            "WIFI_SELECTED_NETWORK":"Nimi",
            "ERROR_ADD_GROUP_NO_NAME":"Uudelle laitteelle ei ole annettu nimeä.",
            "DESC_HELP":"Aputoiminto",
            "CHANGE_PWD_NEW_PASSWORD":"Uusi salasana",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Uuden salasanan tallentaminen",
            "DESC_CHANGE_PASSWORD_PWD":"Uuden salasanan syöttäminen",
            "ERROR_EDIT_ADMIN_CONTENT":"Ylläpitäjää ei voi muokata",
            "CHANGE_GW_NAME_NAME_INVALID":"Epäonnistui",
            "STATE_COLLECTING_FAILED":"Virhe",
            "GENERAL_ADD":"Lisää",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"Kohtien ”Salasana” ja ”Toista salasana” on oltava identtisiä",
            "WIFI_SETTINGS":"WLAN-asetukset",
            "LEARN_PORTS_TITLE":"Lisää laite",
            "ERROR_CHANGE_USERNAME":"Epäonnistui",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Läpiajon esto",
            "ERROR_INVALID_GATEWAY_CONTENT":"Yhteyden luonti yhdyskäytävään epäonnistui. Tarkista Host-nimi.",
            "DESC_EDIT_USERS_EDIT":"Käyttäjän poistaminen",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Laitteen nimessä on oltava 2 - 20 merkkiä",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Pikapääsy ei mahdollinen",
            "CHANNEL_UP":"Auki",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Kesto auki päällä",
            "PORTAL_VALIDATION_FAILED":"Epäonnistui",
            "DESC_RESET_LOGIN_CANCEL":"Toimenpiteen keskeyttäminen",
            "CHANGE_PWD_SETTING_PASSWORD":"Tallenna",
            "LOADING_GROUPS_TITLE":"Lataa",
            "DESC_DEFAULT_GW_CANCEL":"Toimenpiteen keskeyttäminen",
            "DESC_SET_RIGHTS_SAVE":"Muutosten tallentaminen",
            "REMOVING_PROCESS":"Poistaminen",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Yhdyskäytävä ei ole saavutettavissa",
            "CONFIRM_DELETE_TITLE":"Poista yhdyskäytävä",
            "SCENARIOS_ADD_HELP":"Valitse symboli+ tilanteen lisäämiseksi.",
            "LOGOUT":"Kirjaudu ulos",
            "DESC_ACTORS_BACK":"Palaa päävalikkoon",
            "ERROR_ADAPTER_BUSY_CONTENT":"Komentoa ei voitu suorittaa.\n Yhdyskäytävä on kuormitettuna.",
            "DESC_WIFI_NETWORK_SCAN":"Hae verkkoja",
            "DRIVE_MESSAGE_HALF":"Osittain avattu",
            "DESC_SCENARIOS_ADD":"Tapahtumaketjun luominen",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Tiedonsiirto yhdyskäytävän kanssa epäonnistui",
            "SAVING_USER_RIGHTS":"Tallenna",
            "DESC_GWSCREEN_PORTAL":"Portaalitietojen syöttäminen",
            "GATE_JACK":"Radio-ohjattu pistorasia",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Oletko samassa verkossa kuin yhdyskäytävä?",
            "GATE_DOOR":"Ovi",
            "POPUP_PORTAL_UNAVAILABLE":"Portaalipalvelinta ei saavutettu",
            "DESC_SET_RIGHTS_BACK":"Takaisin käyttäjiin",
            "GATE_SMARTKEY":"Ovilukon käyttölaite",
            "POPUP_GATEWAY_FOUND_TITILE":"Haku lopetettu",
            "WIFI_LOADING_DATA_TITLE":"Lataa",
            "GENERAL_PORTS":"Kanavat",
            "DESC_SCENARIOS_EDIT":"Tapahtumaketjujen hallitseminen ja poistaminen",
            "OPTIONS_LEARNED_PORTS":"Opetetut kanavat:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Hyväksyn tietosuojaehdot",
            "DESC_EDIT_USERS_SET_RIGHTS":"Käyttäjän valitseminen pääsyoikeuksien rajoittamiseksi",
            "DRIVE_MESSAGE_HALF_MOVING":"Osittain avattu / liikkuva",
            "PORTAL_SET_ID_DIALOG":"Portaaliasetukset",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Ei referenssikohtaa",
            "POPUP_SETTING_STATE":"Odota...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Käyttäjänimeä ei voitu muuttaa",
            "GROUP_REQUESTABLE":"Laite on paluuilmoituskykyinen",
            "LOADING_STATES_TITLE":"Lataa",
            "DESC_HOME_USERS":"Käyttäjien hallinta",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Salasanassa on oltava 4 - 20 merkkiä",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Salasana tallennetaan",
            "POPUP_GATE_OUT_OF_VIEW":"Automaattisen ovilaitteiston ohjaaminen ilman suoraa näkyvyyttä oveen on sallittua vain, mikäli oveen on asennettu vakiovarusteisena voimanrajoituksena valopuomi.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Valitse, näytetäänkö popup-ilmoitukset vai piilotetaanko ne",
            "CHANNEL_IMPULS":"Impulssi",
            "PORTAL_VALIDATION_SUCCEEDED":"Valtuutettu",
            "DRIVE_MESSAGE_LOCKED":"Lukittu",
            "CHANNEL_DOWN":"Kiinni",
            "POPUP_INET_SPEED_LOW":"Tietoyhteys ei riitä tälle sovellukselle",
            "CHANGE_PWD_FAILED_CONTENT":"Salasanaa ei voitu muuttaa",
            "GENERAL_GROUP_TYPE":"Laitetyyppi",
            "CHANNEL_WALK":"Käyntiovi",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horisontaalisesti liikkuva autotallin ovi",
            "POPUP_AGREEMENT_CONTENT":"Hyväksy ennen sovelluksen käyttöä tietosuoja- / käyttöehdot",
            "INFO":"Tietoja",
            "LOADING_GROUPS_CONTENT":"Lataa laitteet",
            "GATE_PILOMAT_REIFENKILLER":"Lävistävä ajoeste",
            "GATE_PILOMAT_HUBBALKEN":"Nostopalkki",
            "GENERAL_RETYPE":"Syötä salasana uudelleen",
            "DESC_OTIONS_BACK":"Palaa päävalikkoon",
            "DESC_SET_RIGHTS":"Laitteen valitseminen käyttäjän pääsyoikeuksien antamiseksi",
            "WIFI_SCANNING_TITLE":"Haku",
            "WIFI_STATE_CONNECTION_FAILURE":"Yhteyden luonti epäonnistui",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Käyttäjänimessä on oltava 2 - 20 merkkiä",
            "REMOVE_PORTS":"Poistaminen",
            "GENERAL_ON":"Kytketty päälle",
            "DESC_CHANGE_PASSWORD_CANCEL":"Toimenpiteen keskeyttäminen",
            "LEARNING_PROCESS_CONTENT":"Odota...",
            "LOGIN_FAILED_UNKNOWN":"Odottamaton virhe on ilmennyt",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Administraattorin käyttäjäoikeuksia ei voi muuttaa"
         };
         return _loc1_;
      }
   }
}
