package
{
   import mx.resources.ResourceBundle;
   
   public class fr_FR$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function fr_FR$LocalizedStrings_properties()
      {
         super("fr_FR","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Verrouiller",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Saisissez les données d’accès au portail Hörmann",
            "ERROR_DELETE_ADMIN":"Impossible",
            "LOGIN_SHOULD_SAVE":"Enregistrer les données",
            "LOAD_USERS_TITLE":"Veuillez patienter",
            "CHANGE_GW_NAME_SETTING":"Appliquer",
            "CONFIRM_DELETE_GROUP":"Supprimer l’appareil",
            "GENERAL_NO":"Non",
            "DESC_GWSCREEN_ADD":"Ajouter des passerelles locales",
            "DRIVE_MESSAGE_NOT_RETRACTED":"non rentrée",
            "WIFI_PASSPHRASE":"Mot de passe",
            "CHANNEL_ON":"Marche",
            "SCENARIOS":"Scénarios",
            "ERROR_SET_ADMIN_RIGHTS":"Impossible",
            "DESC_DEFAULT_GW_SAVE":"Installer un accès rapide pour la passerelle actuelle",
            "POPUP_INFO":"Remarque",
            "DRIVE_MESSAGE_ERROR":"ATTENTION : erreur",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/fr/protection-des-donnees",
            "DESC_WIFI_NETWORK_NAME":"Nom du réseau",
            "EMAIL_BODY":"Vous pouvez nous envoyer vos questions par e-mail. Vous pouvez également utiliser pour cela la fonction de la FAQ.\n\nVotre équipe d’assistance technique BiSecur Home",
            "CONFIRM_DELETE_USER":"Supprimer l’utilisateur",
            "DESC_CHANNELS_BACK":"Revenir à la liste d’appareils",
            "CHANGE_PWD_FIRST_START":"Pour des raisons de sécurité, veuillez modifier les paramètres par défaut de votre mot de passe après la première connexion",
            "GENERAL_DEFAULT_GATEWAY":"Accès rapide",
            "CHANGE_PWD_PASSWORD_INVALID":"Erreur",
            "ERROR_NO_GW_TITLE":"Aucune passerelle",
            "POPUP_SETTING_STATE_CONTENT":"Ordre en cours d’exécution",
            "WIFI_LOADING_DATA_CONTENT":"Données WiFi en cours de chargement",
            "OPTIONS_RESET_LOGIN_DATA":"Supprimer les données de connexion enregistrées",
            "EDIT_USER_TITLE":"Modifier les droits d’utilisateurs",
            "DESC_HOME_PREFERENCES":"Modifier les réglages de la passerelle et de l’appli",
            "WIFI_ACTIVE_STATE":"Statut WiFi",
            "STATE_COLLECTING":"Chargement",
            "ADD_SCENARIO":"Ajouter un scénario",
            "STATE_COLLECTING_FAILED_CONTENT":"Le statut n’a pas été chargé",
            "GATE_SWING_GATE_SINGLE":"Portail à 1 battant",
            "ACTORS":"Appareils",
            "POPUP_AGREEMENT":"Utilisation / Protection des données",
            "CHANNEL_OPEN_DOOR":"Ouvrir",
            "DESC_ACTORS_REFRESH":"Actualiser le statut",
            "GENERAL_OFF":"Arrêt",
            "OPTIONS_HELP":"Aide en ligne",
            "COPY_PORTS_CONTENT":"Mettez l’émetteur en mode de transmission, voir instructions. Sélectionnez le canal auquel doit être transmis le code.",
            "GENERAL_SELECT":"Sélectionner...",
            "ERROR_ADAPTER_BUSY":"Erreur",
            "INFO_BOX_INFOS":"Généralités",
            "GATE_LIGHT":"Eclairage",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Consulter les conditions d’utilisation",
            "DESC_MANAGE_POPUPS_WARNINGS":"Bloquer les pop-up d’avertissement",
            "MAX_USERSS_REACHED_CONTENT":"Nombre maximal d’utilisateurs atteint.",
            "GENERAL_REMOVE":"Supprimer",
            "OPTIONS":"Paramètres",
            "DESC_HOME_SCENARIOS":"Créer et gérer les scénarios",
            "CHANNEL_OFF":"Arrêt",
            "GENERAL_PORTAL_ID":"ID appareils",
            "EDIT_GROUP":"Modifier l’appareil",
            "ERROR_LERANIN_PORT_CONTENT":"L’apprentissage du canal souhaité a échoué",
            "ERROR_CONNECTION_CLOSED":"Erreur",
            "CHANNEL_ON_OFF":"Marche / Arrêt",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Désignation",
            "OPTIONS_EDIT_USERS":"Gérer les utilisateurs",
            "LOADING_STATES_CONTENT":"Interrogation du statut actuel en cours.\nVeuillez patienter...",
            "LERAN_PORTS_CONTENT":"Mettez l’appareil en mode d’apprentissage, voir instructions. Sélectionnez le canal devant être appris.",
            "REMOVE_PORTS_CONTENT":"Sélectionnez les canaux que vous souhaitez supprimer.",
            "GATE_SWING_GATE_DOUBLE":"Portail à 2 battants",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Contrôlez si les informations du portail ont été saisies ou si une passerelle locale a été ajoutée.",
            "CHANNEL_SINK":"Abaissement",
            "OPTIONS_EDIT_USERS_TITLE":"Utilisateurs",
            "MAX_PORTS_REACHED_CONTENT":"Nombre max. de canaux occupé",
            "MAX_PORTS_REACHED":"Impossible",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Impossible d’atteindre l’appareil demandé",
            "PORTAL_AUTHENTICATION_FAILED":"Echec",
            "NOTIFICATION_CENTER":"Alertes",
            "LEARNING_PROCESS":"Apprentissage",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Le nom d’utilisateur doit se composer de 2 à 20 caractères",
            "WIFI_STATE_CONNECTED":"Connecté",
            "COPY_PORTS":"Transmettre depuis l’émetteur",
            "POPUP_SEARCH_CONTENT":"Recherche de passerelles Hörmann \n\nCette procédure peut prendre quelques secondes.",
            "DESC_MANAGE_POPUPS_CANCEL":"Annuler l’action",
            "DESC_WIFI_PASSWORD":"Mot de passe",
            "DESC_WIFI_SAVE":"Enregistrer",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Arrêt actif",
            "SELECT_GATEWAY":"Passerelles",
            "CLEANING_PORTS":"Ajouter un appareil",
            "WIFI_STATE_BUSY":"Connexion en cours",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Le mot de passe saisi est incorrect",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Modifier le nom de la passerelle",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Application du nom",
            "DESC_ACTORS_EDIT":"Gérer ou supprimer les appareils",
            "DESC_WIFI_STATE":"Statut de connexion",
            "ERROR_REMOVE_USER":"Echec –",
            "LANG_TAG":"FR",
            "DESC_MANAGE_POPUPS_SUBMIT":"Appliquer le réglage",
            "HOME_TITLE":"Page principale",
            "GENERAL_USERNAME":"Nom d’utilisateur",
            "DRIVE_MESSAGE_OPENED":"Ouvert",
            "CONFIRM_DELETE":"Voulez-vous vraiment supprimer la passerelle ?",
            "DRIVE_MESSAGE_CLOSED":"Fermé",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Impossible d’atteindre le serveur portail",
            "REMOVING_PROCESS_CONTENT":"Canal en cours de suppression",
            "DESC_EDIT_USERS_BACK":"Revenir aux paramètres",
            "ERROR_NO_GROUP_FOUND":"Appareil introuvable",
            "ERROR_INVALID_GATEWAY":"Passerelle introuvable",
            "DESC_WIFI_BACK":"Revenir aux paramètres",
            "MAX_USERS_REACHED":"Impossible",
            "DESC_CHANGE_PASSWORD_USERNAME":"Nom d’utilisateur",
            "POPUP_AGREEMENT_ACCEPT_USE":"J’accepte les conditions d’utilisation",
            "ERROR_LERNING_PORT":"Echec",
            "POPUP_ADD_GATEWAY_CONTENT":"Saisissez l’adresse IP :",
            "ERROR_ADD_GROUP":"Erreur",
            "DRIVE_MESSAGE_NO_DATA":"Aucune donnée disponible",
            "CHANGE_PWD_FAILED":"Echec –",
            "SAVING_USER_RIGHTS_CONTENT":"Enregistrement des droits d’utilisateur",
            "DRIVE_MESSAGE_UNLOCKED":"Non verrouillé",
            "GENERAL_SAVE":"Enregistrer",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Connexion",
            "GATE_SECTIONAL_DOOR":"Porte de garage à déplacement vertical",
            "OPTIONS_CHANGE_PASSWORD":"Modifier le mot de passe",
            "CHANNEL":"Commande",
            "CHANGE_GW_NAME_CONTENT":"Nom de la passerelle",
            "DRIVE_MESSAGE_RETRACTED":"rentrée",
            "DESC_ADDGWSCREEN_BACK":"Revenir à la vue d’ensemble des passerelles",
            "EMAIL_SUBJECT":"Assistance",
            "ERROR_EDIT_ADMIN":"Impossible",
            "OPTIONS_SET_USER_RIGHTS":"Droits d’utilisateurs",
            "CHANGE_GW_NAME_ERROR":"Echec",
            "CHANNEL_LIFT":"Soulèvement",
            "LOGIN_FAILED_TITLE":"Echec",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Si vous confirmez la suppression des données de connexion avec OK, le mot de passe doit être à nouveau saisi lors de la sélection de la passerelle",
            "CHANNEL_UNLOCK":"Déverrouiller",
            "GENERAL_PORTAL_SERVER":"Serveur portail",
            "DESC_SCENARIOS_BACK":"Revenir au menu principal",
            "CHANGE_PWD_USERNAME":"Utilisateur :",
            "POPUP_GATE_NOT_RESPONSABLE":"L’appli peut envoyer cet ordre à l’appareil, sans toutefois pouvoir reconnaître l’état de ce dernier.",
            "DESC_GW_NAME":"Nom de la passerelle",
            "GATE_BARRIER":"barrière",
            "LEARN_PORTS":"Apprendre un code radio",
            "GENERAL_BACK":"Précédent",
            "DESC_GWSCREEN_EDIT":"Suppression des passerelles enregistrées",
            "OPTIONS_MANAGE_POPUPS":"Gérer les messages pop-up",
            "POPUP_LOGIN_PROCESS_CONTENT":"Veuillez patienter...",
            "CONFIRM_DELETE_USER_CONTENT":"Voulez-vous vraiment supprimer l’utilisateur ?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"Le nom d’utilisateur ou le mot de passe indiqué est incorrect",
            "GENERAL_CANCEL":"Annuler",
            "ADD_GROUP":"Ajouter un appareil",
            "WIFI_STATE_AP_NOT_FOUND":"Réseau introuvable",
            "WIFI_STATE_NOT_CONNECTED":"Non connecté",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Commande via le portail activée.",
            "POPUP_ADD_GATEWAY":"Ajouter une passerelle",
            "GENERAL_NEXT":"Suivant",
            "POPUP_SUPPRESS":"Ne plus ouvrir la fenêtre pop-up",
            "POPUP_SEARCH_TITLE":"Recherche...",
            "WIFI_SCANNING_CONTENT":"Recherche de réseaux WiFi visibles",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Passerelle introuvable",
            "DESC_ACTORS_ADD":"Créer un appareil",
            "ERROR_ADD_GROUP_NO_TYPE":"Aucun type n’a été sélectionné pour le nouvel appareil.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Vérifiez les données de connexion",
            "GENERAL_REFESHED":"Liste actualisée",
            "OPTIONS_SUPPRESS_WARNINGS":"Bloquer les avertissements",
            "LOGIN_FAILED_GATEWAY_BUSY":"La passerelle est saturée. Veuillez réessayer ultérieurement.",
            "DESC_EMAIL":"Envoyer un e-mail à l’assistance technique",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Ouverture permanente inactive",
            "CLEANING_PORTS_CONTENT":"Ajout en cours",
            "DESC_HOME_ACTORS":"Apprentissage et gestion des appareils",
            "ERROR_TIMEOUT":"Erreur de connexion",
            "CREATE_USER_TITLE":"Ajouter un utilisateur",
            "ERROR_DELETE_ADMIN_CONTENT":"L’administrateur ne peut être supprimé",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Accès rapide",
            "ADD_SCENARIO_NAME":"Nom",
            "HIST":"Historique",
            "DESC_RESET_LOGIN_SUBMIT":"Confirmer la suppression",
            "POPUP_WARNING":"ATTENTION",
            "REMOVE_GROUP_PROCESS":"Appareil en cours de suppression",
            "POPUP_LOGIN_PROCESS":"Se connecter",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Veuillez patienter...",
            "DESC_DEFAULT_GW_SUBMIT":"Appliquer le réglage",
            "DESC_CHANGE_PASSWORD_RETYPE":"Confirmer la saisie",
            "LOAD_USERS_CONTENT":"Chargement de tous les utilisateurs de la passerelle.\nCette procédure peut prendre quelques secondes.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Si l’accès rapide est activé pour une passerelle, l’appli se connecte, dans la mesure du possible, automatiquement",
            "GATE_OTHER":"Autres appareils",
            "CHANGE_PWD_USER_INVALID":"Erreur",
            "CHANNEL_LIGHT":"Eclairage",
            "LOGIN_TITLE":"Se connecter",
            "CHANNEL_HALF":"Ouverture partielle",
            "GATEWAY_SCREEN_ADD_HELP":"Pour ajouter une passerelle, appuyez sur le symbole+.",
            "ERROR_TIMEOUT_CONTENT":"Dépassement du temps lors de la communication avec la passerelle",
            "ERROR_NO_PORTS_LEARNED":"Ajout impossible",
            "OPTIONS_SUPPRESS_INFOS":"Bloquer les conseils",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Erreur",
            "OPTIONS_WIFI_SETTINGS":"WiFi",
            "CHANNEL_AUTO_CLOSE":"Mode automatique",
            "GENERAL_DELETE":"Supprimer",
            "GENERAL_PASSWORD":"Mot de passe",
            "STATE_COLLECTING_CONTENT":"Interrogation du statut des appareils en cours",
            "ERROR_REMOVE_USER_CONTENT":"L’utilisateur n’a pas pu être supprimé",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Erreur",
            "ACTORS_ADD_HELP":"Pour ajouter un appareil, appuyez sur le symbole+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Voulez-vous vraiment supprimer l’appareil ?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Veuillez patienter...",
            "GENERAL_YES":"Oui",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Avant d’ajouter un appareil, procédez à l’apprentissage d’au moins un canal",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Le nom n’a pu être modifié",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"L’appli n’a encore trouvé aucune passerelle.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Echec de l’authentification",
            "DESC_MANAGE_POPUPS_INFOS":"Bloquer les pop-up d’information",
            "GATE_PILOMAT_POLLER":"Bornes",
            "DESC_CHANNELS_STATE":"Statut de l’appareil avec capacité de rétrosignal",
            "DESC_GWSCREEN_REFRESH":"Actualisation de la liste de passerelles",
            "POPUP_SCENARIO_DISPATCHING":"Scénario en cours",
            "ERROR_PORT_UNREACHABLE":"Echec",
            "POPUP_GATEWAY_FOUND_CONTENT":"Les passerelles suivantes ont été ajoutées :",
            "WIFI_STATE_SECURITY_MISMATCH":"Le type de cryptage du WiFi n’est pas soutenu",
            "LOGOUT_NAMED":"Se déconnecter",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Consulter les conditions de protection des données",
            "ERROR_NO_GW_CONTENT":"Aucune passerelle Hörmann n’a pu être trouvée sur le réseau local.\nAjouter d’autres passerelles via le signe+",
            "DESC_EDIT_USERS_ADD":"Ajouter un utilisateur",
            "ERROR_NO_PORT_FOUND":"Port introuvable",
            "GATE_SLIDING_GATE":"Portail coulissant",
            "DESC_CHANNELS_BUTTONS":"Eléments de commande de l’appareil",
            "DRIVE_MESSAGE_EXTENDED":"sortie",
            "WIFI_SELECTED_NETWORK":"Nom",
            "ERROR_ADD_GROUP_NO_NAME":"Aucun nom n’a été saisi pour le nouvel appareil.",
            "DESC_HELP":"Fonction d’aide",
            "CHANGE_PWD_NEW_PASSWORD":"Nouveau mot de passe",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Appliquer le nouveau mot de passe",
            "DESC_CHANGE_PASSWORD_PWD":"Saisie du nouveau mot de passe",
            "ERROR_EDIT_ADMIN_CONTENT":"L’administrateur ne peut pas être modifié",
            "CHANGE_GW_NAME_NAME_INVALID":"Echec",
            "STATE_COLLECTING_FAILED":"Erreur",
            "GENERAL_ADD":"Ajouter",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Mot de passe\" et \"Confirmer le mot de passe\" doivent être identiques",
            "WIFI_SETTINGS":"Paramètres WiFi",
            "LEARN_PORTS_TITLE":"Ajouter un appareil",
            "ERROR_CHANGE_USERNAME":"Echec –",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Blocage du passage",
            "ERROR_INVALID_GATEWAY_CONTENT":"Aucune connexion à la passerelle n’a pu être établie. Vérifiez le nom d’hôte.",
            "DESC_EDIT_USERS_EDIT":"Supprimer l’utilisateur",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Le nom de l’appareil doit se composer de 2 à 20 caractères",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Accès rapide impossible",
            "CHANNEL_UP":"Ouverture",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Ouverture permanente active",
            "PORTAL_VALIDATION_FAILED":"Echec",
            "DESC_RESET_LOGIN_CANCEL":"Annuler l’action",
            "CHANGE_PWD_SETTING_PASSWORD":"Appliquer",
            "LOADING_GROUPS_TITLE":"Chargement",
            "DESC_DEFAULT_GW_CANCEL":"Annuler l’action",
            "DESC_SET_RIGHTS_SAVE":"Appliquer les modifications",
            "REMOVING_PROCESS":"Supprimer",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Impossible d’atteindre la passerelle",
            "CONFIRM_DELETE_TITLE":"Supprimer la passerelle",
            "SCENARIOS_ADD_HELP":"Pour ajouter un scénario, appuyez sur le symbole+.",
            "LOGOUT":"Se déconnecter",
            "DESC_ACTORS_BACK":"Revenir au menu principal",
            "ERROR_ADAPTER_BUSY_CONTENT":"L’ordre n’a pu être exécuté.\n La passerelle est saturée.",
            "DESC_WIFI_NETWORK_SCAN":"Recherche de réseaux",
            "DRIVE_MESSAGE_HALF":"Partiellement ouvert",
            "DESC_SCENARIOS_ADD":"Créer un scénario",
            "ERROR_CONNECTION_CLOSED_CONTENT":"La communication avec la passerelle a été interrompue",
            "SAVING_USER_RIGHTS":"Enregistrement",
            "DESC_GWSCREEN_PORTAL":"Saisie des données du portail",
            "GATE_JACK":"Prise sans fil",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Etes-vous connecté au même réseau que votre passerelle ?",
            "GATE_DOOR":"Porte",
            "POPUP_PORTAL_UNAVAILABLE":"Impossible d’atteindre le serveur portail",
            "DESC_SET_RIGHTS_BACK":"Revenir aux utilisateurs",
            "GATE_SMARTKEY":"Motorisation de serrure de porte",
            "POPUP_GATEWAY_FOUND_TITILE":"Recherche terminée",
            "WIFI_LOADING_DATA_TITLE":"Chargement",
            "GENERAL_PORTS":"Canaux",
            "DESC_SCENARIOS_EDIT":"Gérer ou supprimer les scénarios",
            "OPTIONS_LEARNED_PORTS":"Canaux appris :",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"J’accepte les conditions de protection des données",
            "DESC_EDIT_USERS_SET_RIGHTS":"Pour modifier les droits d’accès d’un utilisateur, sélectionner ce dernier",
            "DRIVE_MESSAGE_HALF_MOVING":"Partiellement ouvert / En mouvement",
            "PORTAL_SET_ID_DIALOG":"Paramètres du portail",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Aucun point de référence",
            "POPUP_SETTING_STATE":"Veuillez patienter...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/fr/conditions-utilisation",
            "ERROR_CHANGE_USERNAME_CONTENT":"Le nom d’utilisateur n’a pas pu être modifié",
            "GROUP_REQUESTABLE":"Appareil avec capacité de rétrosignal",
            "LOADING_STATES_TITLE":"Chargement",
            "DESC_HOME_USERS":"Gérer les utilisateurs",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Le mot de passe doit se composer de 4 à 20 caractères",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Application du mot de passe",
            "POPUP_GATE_OUT_OF_VIEW":"Sans contact visuel avec la porte, la commande d’une installation de porte motorisée est exclusivement autorisée si une cellule photoélectrique est installée sur la porte en plus du limiteur d’effort présent de série.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Choisissez si les messages pop-up doivent être affichés ou bloqués",
            "CHANNEL_IMPULS":"Impulsion",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorisé",
            "DRIVE_MESSAGE_LOCKED":"Verrouillé",
            "CHANNEL_DOWN":"Fermé",
            "POPUP_INET_SPEED_LOW":"Connexion de données insuffisante pour l’application",
            "CHANGE_PWD_FAILED_CONTENT":"Le mot de passe n’a pas pu être modifié",
            "GENERAL_GROUP_TYPE":"Type d’appareil",
            "CHANNEL_WALK":"Vantail d’entrée",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Porte de garage à déplacement horizontal",
            "POPUP_AGREEMENT_CONTENT":"Pour pouvoir utiliser l’appli, acceptez les conditions de protection des données et d’utilisation",
            "INFO":"Informations",
            "LOADING_GROUPS_CONTENT":"Chargement des appareils",
            "GATE_PILOMAT_REIFENKILLER":"Herses",
            "GATE_PILOMAT_HUBBALKEN":"Barrières levantes",
            "GENERAL_RETYPE":"Confirmer le mot de passe",
            "DESC_OTIONS_BACK":"Revenir au menu principal",
            "DESC_SET_RIGHTS":"Pour attribuer des droits d’accès à un utilisateur, sélectionner l’appareil concerné",
            "WIFI_SCANNING_TITLE":"Recherche",
            "WIFI_STATE_CONNECTION_FAILURE":"Echec de l’établissement de la connexion",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Le nom d’utilisateur doit se composer de 2 à 20 caractères",
            "REMOVE_PORTS":"Supprimer",
            "GENERAL_ON":"Marche",
            "DESC_CHANGE_PASSWORD_CANCEL":"Annuler l’action",
            "LEARNING_PROCESS_CONTENT":"Veuillez patienter...",
            "LOGIN_FAILED_UNKNOWN":"Une erreur inattendue est survenue",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Les droits d’utilisateur de l’administrateur ne peuvent être modifiés"
         };
         return _loc1_;
      }
   }
}
