package
{
   import mx.resources.ResourceBundle;
   
   public class hr_HR$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function hr_HR$LocalizedStrings_properties()
      {
         super("hr_HR","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Zaključavanje",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Unesite pristupne podatke na Hörmann-Portalu",
            "ERROR_DELETE_ADMIN":"Nije moguće",
            "LOGIN_SHOULD_SAVE":"Pohraniti podatke",
            "LOAD_USERS_TITLE":"Molimo pričekajte",
            "CHANGE_GW_NAME_SETTING":"Preuzimanje",
            "CONFIRM_DELETE_GROUP":"Obrisati uređaj",
            "GENERAL_NO":"Ne",
            "DESC_GWSCREEN_ADD":"Dodavanje lokalnog gatewaya",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nisu spušteni",
            "WIFI_PASSPHRASE":"Zaporka",
            "CHANNEL_ON":"Uključivanje",
            "SCENARIOS":"Scenarij",
            "ERROR_SET_ADMIN_RIGHTS":"Nije moguće",
            "DESC_DEFAULT_GW_SAVE":"Podesiti brzi pristup aktualnom Gateway",
            "POPUP_INFO":"Napomena",
            "DRIVE_MESSAGE_ERROR":"PAŽNJA: greška",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Ime mreže",
            "EMAIL_BODY":"Pitanja nam možete poslati e-mailom. Na raspolaganju Vam stoji i naša funkcija FAQ za često postavljena pitanja.\nIhr BiSecur-Home Support-Team",
            "CONFIRM_DELETE_USER":"Brisanje korisnika",
            "DESC_CHANNELS_BACK":"Povratak na listu uređaja",
            "CHANGE_PWD_FIRST_START":"Iz sigurnosnih razloga promijenite tvornički postavljenu lozinku nakon prve prijave",
            "GENERAL_DEFAULT_GATEWAY":"Brzi dohvat",
            "CHANGE_PWD_PASSWORD_INVALID":"Greška",
            "ERROR_NO_GW_TITLE":"Gateway ne postoji",
            "POPUP_SETTING_STATE_CONTENT":"Provođenje naredbe",
            "WIFI_LOADING_DATA_CONTENT":"Učitavanje WLAN-podataka",
            "OPTIONS_RESET_LOGIN_DATA":"Obrisati pohranjene pristupne podatke",
            "EDIT_USER_TITLE":"Obrada korisnika",
            "DESC_HOME_PREFERENCES":"Promijeniti postavke Gatewaya i aplikacije",
            "WIFI_ACTIVE_STATE":"WLAN Status",
            "STATE_COLLECTING":"Unos",
            "ADD_SCENARIO":"Dodati scenarij",
            "STATE_COLLECTING_FAILED_CONTENT":"Status nije očitan",
            "GATE_SWING_GATE_SINGLE":"1-krilna vrata",
            "ACTORS":"uređaji",
            "POPUP_AGREEMENT":"Korištenje / Zaštita podataka",
            "CHANNEL_OPEN_DOOR":"Otvaranje",
            "DESC_ACTORS_REFRESH":"Aktualizacija statusa",
            "GENERAL_OFF":"Isključeno",
            "OPTIONS_HELP":"Online-pomoć",
            "COPY_PORTS_CONTENT":"Odašiljač stavite u modus za odašiljanje. Odaberite kanal koji preuzima kôd.",
            "GENERAL_SELECT":"Molimo odaberite...",
            "ERROR_ADAPTER_BUSY":"Greška",
            "INFO_BOX_INFOS":"Općenito",
            "GATE_LIGHT":"Svjetlo",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Otvoriti uvjete za korištenje",
            "DESC_MANAGE_POPUPS_WARNINGS":"Sakriti upozoravajuće popup poruke",
            "MAX_USERSS_REACHED_CONTENT":"Dosegnut je maksimalni broj korisnika.",
            "GENERAL_REMOVE":"Uklanjanje",
            "OPTIONS":"Podešenja",
            "DESC_HOME_SCENARIOS":"Pohranjivanje i uređivanje sa scenarijima",
            "CHANNEL_OFF":"Isključivanje",
            "GENERAL_PORTAL_ID":"ID uređaja",
            "EDIT_GROUP":"Obrada uređaja",
            "ERROR_LERANIN_PORT_CONTENT":"Učitavanje željenog kanala na žalost nije uspjelo.",
            "ERROR_CONNECTION_CLOSED":"Greška",
            "CHANNEL_ON_OFF":"uključeno / isključeno",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Oznaka",
            "OPTIONS_EDIT_USERS":"Ažuriranje korisnika",
            "LOADING_STATES_CONTENT":"Dohvaćanje aktualnog statusa.Molimo pričekajte...",
            "LERAN_PORTS_CONTENT":"Stavite uređaj u modus priučavanja, pogledajte uputu. Izaberite kanal koji se priučava.",
            "REMOVE_PORTS_CONTENT":"Odaberite kanale koje želite obrisati.",
            "GATE_SWING_GATE_DOUBLE":"2-krilna vrata",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Provjerite jeste li unijeli podatke o portalu ili jeste li unijeli lokalni gateway.",
            "CHANNEL_SINK":"spuštanje",
            "OPTIONS_EDIT_USERS_TITLE":"Korisnik",
            "MAX_PORTS_REACHED_CONTENT":"Dosegnut je maksimalni broj pohranjenih kanala",
            "MAX_PORTS_REACHED":"Nije moguće",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Traženi uređaj nije pronađen",
            "PORTAL_AUTHENTICATION_FAILED":"Neuspjelo",
            "NOTIFICATION_CENTER":"Obavijesti",
            "LEARNING_PROCESS":"Učitavanje",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Korisničko ime mora sadržavati između 2 - 20 znakova",
            "WIFI_STATE_CONNECTED":"Spojeno",
            "COPY_PORTS":"Upravljanje daljinskim upravljačima",
            "POPUP_SEARCH_CONTENT":"Traženje Hörmann-Gateway-a. Postupak može trajati nekoliko sekundi!",
            "DESC_MANAGE_POPUPS_CANCEL":"Prekinuti akciju",
            "DESC_WIFI_PASSWORD":"Zaporka",
            "DESC_WIFI_SAVE":"Pohranjivanje",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Aktivna je funkcija stop",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Dodati uređaj",
            "WIFI_STATE_BUSY":"Uspostavljanje veze",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Unesena lozinka je pogrešna",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Promjena Gateway imena",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Ime se preuzima",
            "DESC_ACTORS_EDIT":"Uređivanje ili brisanje uređaja",
            "DESC_WIFI_STATE":"Status povezivanja",
            "ERROR_REMOVE_USER":"Neuspjelo",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Preuzeti postavke",
            "HOME_TITLE":"Glavna stranica",
            "GENERAL_USERNAME":"Ime korisnika",
            "DRIVE_MESSAGE_OPENED":"Otvoreno",
            "CONFIRM_DELETE":"Želite li sigurno obrisati Getaway?",
            "DRIVE_MESSAGE_CLOSED":"Zatvoreno",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Nije uspostavljena veza s portalnim serverom",
            "REMOVING_PROCESS_CONTENT":"Brisanje kanala",
            "DESC_EDIT_USERS_BACK":"Povratak na postavke",
            "ERROR_NO_GROUP_FOUND":"Uređaj nije pronađen",
            "ERROR_INVALID_GATEWAY":"Nije pronađen Gateway",
            "DESC_WIFI_BACK":"Povratak na postavke",
            "MAX_USERS_REACHED":"Nije moguće",
            "DESC_CHANGE_PASSWORD_USERNAME":"Ime korisnika",
            "POPUP_AGREEMENT_ACCEPT_USE":"Prihvaćam uvjete za korištenje",
            "ERROR_LERNING_PORT":"Neuspjelo",
            "POPUP_ADD_GATEWAY_CONTENT":"Unijeti IP adresu:",
            "ERROR_ADD_GROUP":"Greška",
            "DRIVE_MESSAGE_NO_DATA":"Nema dostupnih podataka",
            "CHANGE_PWD_FAILED":"Neuspjelo",
            "SAVING_USER_RIGHTS_CONTENT":"Pohranjuju se korisnička prava",
            "DRIVE_MESSAGE_UNLOCKED":"nije zaključano",
            "GENERAL_SAVE":"Pohranjivanje",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Spajati",
            "GATE_SECTIONAL_DOOR":"Garažna vrata koja se kreću vertikalno",
            "OPTIONS_CHANGE_PASSWORD":"Promjena zaporke",
            "CHANNEL":"Rukovanje",
            "CHANGE_GW_NAME_CONTENT":"Gateway ime",
            "DRIVE_MESSAGE_RETRACTED":"spušteni",
            "DESC_ADDGWSCREEN_BACK":"Povratak na pregled gatewaya",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Nije moguće",
            "OPTIONS_SET_USER_RIGHTS":"Prava korisnika",
            "CHANGE_GW_NAME_ERROR":"Neuspjelo",
            "CHANNEL_LIFT":"podizanje",
            "LOGIN_FAILED_TITLE":"Neuspjelo",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Ukoliko se slažete s odabirom brisanja korisničkih podataka, pritisnite OK, kod novog Gatewaya potrebno je pohraniti novu lozinku",
            "CHANNEL_UNLOCK":"Otključavanje",
            "GENERAL_PORTAL_SERVER":"Portal server",
            "DESC_SCENARIOS_BACK":"Povratak na glavni izbornik",
            "CHANGE_PWD_USERNAME":"Korisnik:",
            "POPUP_GATE_NOT_RESPONSABLE":"Aplikacija može ovu naredbu poslati na uređaj, ali ne prepoznaje aktualni status uređaja.",
            "DESC_GW_NAME":"Gateway ime",
            "GATE_BARRIER":"rampa",
            "LEARN_PORTS":"Priučavanje bežičnog kôda",
            "GENERAL_BACK":"Natrag",
            "DESC_GWSCREEN_EDIT":"Brisanje pohranjenih Gatewaya",
            "OPTIONS_MANAGE_POPUPS":"Urediti popup-poruke",
            "POPUP_LOGIN_PROCESS_CONTENT":"Molimo pričekajte...",
            "CONFIRM_DELETE_USER_CONTENT":"Jeste sigurni da želite obrisati postojećeg korisnika?",
            "DESC_MENU":"Izbornik",
            "LOGIN_FAILED_WRONG_DATA":"Uneseno je pogrešno ime korisnika ili zaporka.",
            "GENERAL_CANCEL":"Prekinuti",
            "ADD_GROUP":"Dodati uređaj",
            "WIFI_STATE_AP_NOT_FOUND":"Mreža nije pronađena",
            "WIFI_STATE_NOT_CONNECTED":"Nije spojeno",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Aktivirano je Vaše upravljanje putem portala!",
            "POPUP_ADD_GATEWAY":"Dodati Gateway",
            "GENERAL_NEXT":"Dalje",
            "POPUP_SUPPRESS":"Ne otvarati više popup",
            "POPUP_SEARCH_TITLE":"Traži...",
            "WIFI_SCANNING_CONTENT":"Traženje vidljivih WLAN mreža",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Gateway nije pronađen.",
            "DESC_ACTORS_ADD":"Unos uređaja",
            "ERROR_ADD_GROUP_NO_TYPE":"Nije odabran tip za novi uređaj.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Provjerite podatke prijave",
            "GENERAL_REFESHED":"Aktualizirano",
            "OPTIONS_SUPPRESS_WARNINGS":"Sakriti upozorenja",
            "LOGIN_FAILED_GATEWAY_BUSY":"Gateway je trenutno opterećen. Pokušajte ponovno.",
            "DESC_EMAIL":"Poslati e-mail podršci",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Isključena funkcija \"trajno otvoreno\"",
            "CLEANING_PORTS_CONTENT":"Priprema za dodavanje uređaja je u tijeku",
            "DESC_HOME_ACTORS":"Učenje i uređivanje s uređajima",
            "ERROR_TIMEOUT":"Greška u spajanju",
            "CREATE_USER_TITLE":"Dodati korisnika",
            "ERROR_DELETE_ADMIN_CONTENT":"Administrator se ne može obrisati kao korisnik.",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Brzi dohvat",
            "ADD_SCENARIO_NAME":"Ime",
            "HIST":"Povijest",
            "DESC_RESET_LOGIN_SUBMIT":"Potvrditi brisanje",
            "POPUP_WARNING":"PAŽNJA",
            "REMOVE_GROUP_PROCESS":"Brisanje uređaja",
            "POPUP_LOGIN_PROCESS":"Prijaviti",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Molimo pričekajte...",
            "DESC_DEFAULT_GW_SUBMIT":"Preuzeti postavke",
            "DESC_CHANGE_PASSWORD_RETYPE":"Ponoviti unos",
            "LOAD_USERS_CONTENT":"Pozvani su svi korisnici Gateway-a.Ovaj postupak može potrajati nekoliko sekundi.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Ukoliko je u gatewayu aktiviran brzi pristup, aplikacija ima mogućnost samostalnog priključivanja",
            "GATE_OTHER":"Ostali uređaji",
            "CHANGE_PWD_USER_INVALID":"Greška",
            "CHANNEL_LIGHT":"Svjetlo",
            "LOGIN_TITLE":"Prijaviti",
            "CHANNEL_HALF":"Djelomično otvaranje",
            "GATEWAY_SCREEN_ADD_HELP":"Za dodavanje gatewaya odaberite simbol+.",
            "ERROR_TIMEOUT_CONTENT":"Isteklo vrijeme pri komunikaciji s Gateway",
            "ERROR_NO_PORTS_LEARNED":"Nije moguće dodavanje",
            "OPTIONS_SUPPRESS_INFOS":"Sakriti upute",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Greška",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatski pogon",
            "GENERAL_DELETE":"Brisanje",
            "GENERAL_PASSWORD":"Zaporka",
            "STATE_COLLECTING_CONTENT":"Ispituje se status uređaja",
            "ERROR_REMOVE_USER_CONTENT":"Korisnik se nije mogao izbrisati",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Greška",
            "ACTORS_ADD_HELP":"Za dodavanje uređaja odaberite simbol+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Jeste sigurni da želite obrisati naznačeni uređaj?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Molimo pričekajte...",
            "GENERAL_YES":"Da",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Pri dodavanju uređaja potrebno je pohraniti barem jedan kanal",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Ime se ne može promijeniti",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"App još nije pronašla gateway.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentifikacija nije uspjela",
            "DESC_MANAGE_POPUPS_INFOS":"Sakriti informacijske popup prozore",
            "GATE_PILOMAT_POLLER":"Stupići",
            "DESC_CHANNELS_STATE":"Status povratne informacije uređaja",
            "DESC_GWSCREEN_REFRESH":"Aktualizacija Gateway popisa",
            "POPUP_SCENARIO_DISPATCHING":"Izvođenje scenarija",
            "ERROR_PORT_UNREACHABLE":"Neuspjelo",
            "POPUP_GATEWAY_FOUND_CONTENT":"Dodatni su sljedeći gateways:",
            "WIFI_STATE_SECURITY_MISMATCH":"WLAN ne podržava način spajanja",
            "LOGOUT_NAMED":"odjaviti",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Otvoriti uvjete o zaštiti podataka",
            "ERROR_NO_GW_CONTENT":"U lokalnoj mreži nije pronađen Hörmann-Gateway. Dodajte ostale Gatewaye s+.",
            "DESC_EDIT_USERS_ADD":"Dodati korisnika",
            "ERROR_NO_PORT_FOUND":"Port nije pronađen",
            "GATE_SLIDING_GATE":"Klizna vrata",
            "DESC_CHANNELS_BUTTONS":"Upravljački elementi uređaja",
            "DRIVE_MESSAGE_EXTENDED":"podignuti",
            "WIFI_SELECTED_NETWORK":"Ime",
            "ERROR_ADD_GROUP_NO_NAME":"Za novi uređaj nije pohranjeno ime.",
            "DESC_HELP":"Pomoćne funkcije",
            "CHANGE_PWD_NEW_PASSWORD":"Nova zaporka",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Preuzeti novu lozinku",
            "DESC_CHANGE_PASSWORD_PWD":"Unos nove lozinke",
            "ERROR_EDIT_ADMIN_CONTENT":"Administrator se ne može obraditi",
            "CHANGE_GW_NAME_NAME_INVALID":"Neuspjelo",
            "STATE_COLLECTING_FAILED":"Greška",
            "GENERAL_ADD":"Dodati",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Zaporka\" i \"Ponovite zaporku\" moraju biti jednake",
            "WIFI_SETTINGS":"WLAN Postavke",
            "LEARN_PORTS_TITLE":"Dodati uređaj",
            "ERROR_CHANGE_USERNAME":"Neuspjelo",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Blokada prolaza",
            "ERROR_INVALID_GATEWAY_CONTENT":"Ne može se uspostaviti veza s Gateway. Provjerite Vaše korisničko ime.",
            "DESC_EDIT_USERS_EDIT":"Brisanje korisnika",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Ime uređaja mora imati između 2 - 20 znakova.",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Nije mogući brzi pristup.",
            "CHANNEL_UP":"otvoreno",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Uključena funkcija \"trajno otvoreno\"",
            "PORTAL_VALIDATION_FAILED":"Neuspjelo",
            "DESC_RESET_LOGIN_CANCEL":"Prekinuti akciju",
            "CHANGE_PWD_SETTING_PASSWORD":"Preuzimanje",
            "LOADING_GROUPS_TITLE":"Unos",
            "DESC_DEFAULT_GW_CANCEL":"Prekinuti akciju",
            "DESC_SET_RIGHTS_SAVE":"Preuzeti promjene",
            "REMOVING_PROCESS":"Brisanje",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Nije moguće povezivanje na Gateway",
            "CONFIRM_DELETE_TITLE":"Brisati Gateway",
            "SCENARIOS_ADD_HELP":"Za dodavanje scenarija odaberite simbol+.",
            "LOGOUT":"Odjaviti",
            "DESC_ACTORS_BACK":"Povratak na glavni izbornik",
            "ERROR_ADAPTER_BUSY_CONTENT":"Naredba nije provedena. Gateway je trenutno opterećen.",
            "DESC_WIFI_NETWORK_SCAN":"Traženje mreža",
            "DRIVE_MESSAGE_HALF":"Djelomično otvoreno",
            "DESC_SCENARIOS_ADD":"Pohranjivanje scenarija",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Komunikacija s Gateway nije uspjela.",
            "SAVING_USER_RIGHTS":"Pohraniti",
            "DESC_GWSCREEN_PORTAL":"Unos podataka portala",
            "GATE_JACK":"Bežična utičnica",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Jeste li na istoj mreži kao i Vaš gateway?",
            "GATE_DOOR":"Vrata",
            "POPUP_PORTAL_UNAVAILABLE":"Nije uspostavljena veza s portalnim serverom",
            "DESC_SET_RIGHTS_BACK":"Povratak na korisnike",
            "GATE_SMARTKEY":"Pogon brave za vrata",
            "POPUP_GATEWAY_FOUND_TITILE":"Postupak traženja je završen",
            "WIFI_LOADING_DATA_TITLE":"Unos",
            "GENERAL_PORTS":"Kanali",
            "DESC_SCENARIOS_EDIT":"Uređivanje ili brisanje scenarija",
            "OPTIONS_LEARNED_PORTS":"Pohranjeni kanali:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Prihvaćam uvjete o zaštiti podataka",
            "DESC_EDIT_USERS_SET_RIGHTS":"Odabir korisnika i promjena pristupnih prava",
            "DRIVE_MESSAGE_HALF_MOVING":"Djelomično otvoreno / U pokretu",
            "PORTAL_SET_ID_DIALOG":"Postavke portala",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Nema referentne točke",
            "POPUP_SETTING_STATE":"Molimo pričekajte...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Korisničko ime se nije moglo promijeniti",
            "GROUP_REQUESTABLE":"Uređaj može odaslati povratnu informaciju",
            "LOADING_STATES_TITLE":"Unos",
            "DESC_HOME_USERS":"Ažuriranje korisnika",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Lozinka mora sadržavati između 4 - 20 znakova",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Lozinka se preuzima",
            "POPUP_GATE_OUT_OF_VIEW":"Kada vrata nisu u vidnom polju, njima se može automatski upravljati samo ako su dodatno serijski opremljeni s ograničenjem snage i foto ćelijom.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Odaberite želite li da Vam popup-poruke budu prikazane ili skrivene",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorizirano",
            "DRIVE_MESSAGE_LOCKED":"Zaključano",
            "CHANNEL_DOWN":"zatvoreno",
            "POPUP_INET_SPEED_LOW":"Vaša podatkovna veza nije dostatna za ovu primjenu",
            "CHANGE_PWD_FAILED_CONTENT":"Lozinka se nije mogla promijeniti",
            "GENERAL_GROUP_TYPE":"Tip uređaja",
            "CHANNEL_WALK":"Prohodno krilo",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horizontalno otvaranje garažnih vrata",
            "POPUP_AGREEMENT_CONTENT":"Prije korištenja aplikacije prihvatite uvjete korištenja i uvjete o zaštiti podataka",
            "INFO":"Informacije",
            "LOADING_GROUPS_CONTENT":"Učitavanje uređaja",
            "GATE_PILOMAT_REIFENKILLER":"Naprave za uništavanje guma",
            "GATE_PILOMAT_HUBBALKEN":"Brklja",
            "GENERAL_RETYPE":"Ponoviti zaporku",
            "DESC_OTIONS_BACK":"Povratak na glavni izbornik",
            "DESC_SET_RIGHTS":"Odabir uređaja za promjenu pristupnih prava",
            "WIFI_SCANNING_TITLE":"Traženje",
            "WIFI_STATE_CONNECTION_FAILURE":"Uspostavljanje veze nije uspjelo",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Korisničko ime mora imati između 2 - 20 znakova",
            "REMOVE_PORTS":"Brisanje",
            "GENERAL_ON":"Uključeno",
            "DESC_CHANGE_PASSWORD_CANCEL":"Prekinuti akciju",
            "LEARNING_PROCESS_CONTENT":"Molim pričekajte...",
            "LOGIN_FAILED_UNKNOWN":"Dogodila se neočekivana greška.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Korisnička prava administratora ne mogu se mijenjati!"
         };
         return _loc1_;
      }
   }
}
