package
{
   import mx.resources.ResourceBundle;
   
   public class hu_HU$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function hu_HU$LocalizedStrings_properties()
      {
         super("hu_HU","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Reteszelés",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Adja meg a Hörmann portál hozzáférési adatait",
            "ERROR_DELETE_ADMIN":"nem lehetséges",
            "LOGIN_SHOULD_SAVE":"Adatok mentése",
            "LOAD_USERS_TITLE":"Kérem, várjon",
            "CHANGE_GW_NAME_SETTING":"Átvétel",
            "CONFIRM_DELETE_GROUP":"Eszköz törlése",
            "GENERAL_NO":"Nem",
            "DESC_GWSCREEN_ADD":"Helyi Gateway hozzáadása",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nem behúzva",
            "WIFI_PASSPHRASE":"Jelszó",
            "CHANNEL_ON":"BE",
            "SCENARIOS":"Kombinációk",
            "ERROR_SET_ADMIN_RIGHTS":"nem lehetséges",
            "DESC_DEFAULT_GW_SAVE":"Gyors hozzáférés beállítása az aktuális Gateway-hez",
            "POPUP_INFO":"Alapelv",
            "DRIVE_MESSAGE_ERROR":"FIGYELEM: hiba",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/hu/adatvedelem",
            "DESC_WIFI_NETWORK_NAME":"Hálózat neve",
            "EMAIL_BODY":"Kérdéseit elküldheti nekünk e-mailben. Ehhez rendelkezésre a GYIK funkció.\n\nIhr BiSecur-Home Support-Team",
            "CONFIRM_DELETE_USER":"Felhasználó törlése",
            "DESC_CHANNELS_BACK":"Vissza az eszközlistához",
            "CHANGE_PWD_FIRST_START":"Biztonsági okokból az első bejelentkezést követően változtassa meg az Ön gyárilag beállított jelszavát",
            "GENERAL_DEFAULT_GATEWAY":"Gyors hozzáférés",
            "CHANGE_PWD_PASSWORD_INVALID":"Hiba",
            "ERROR_NO_GW_TITLE":"Nincsenek Gateway-ek",
            "POPUP_SETTING_STATE_CONTENT":"Parancs végrehajtása",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-adatok betöltése",
            "OPTIONS_RESET_LOGIN_DATA":"Mentett bejelentkezési adatok törlése",
            "EDIT_USER_TITLE":"Felhasználó szerkesztése",
            "DESC_HOME_PREFERENCES":"Gateway és App beállításainak módosítása",
            "WIFI_ACTIVE_STATE":"WLAN állapot",
            "STATE_COLLECTING":"Töltés",
            "ADD_SCENARIO":"Kombináció beillesztése",
            "STATE_COLLECTING_FAILED_CONTENT":"A státusz nem lett letöltve",
            "GATE_SWING_GATE_SINGLE":"1-szárnyú szárnyaskapu",
            "ACTORS":"Eszközök:",
            "POPUP_AGREEMENT":"Használat / adatvédelem",
            "CHANNEL_OPEN_DOOR":"Nyitás",
            "DESC_ACTORS_REFRESH":"Státusz aktualizálása",
            "GENERAL_OFF":"Kikapcsolva",
            "OPTIONS_HELP":"Online segítség",
            "COPY_PORTS_CONTENT":"Állítsa az adót örökítő üzemmódba, lásd az utasítást. Válassza ki az örökítendő csatornát.",
            "GENERAL_SELECT":"Kérem válasszon...",
            "ERROR_ADAPTER_BUSY":"Hiba",
            "INFO_BOX_INFOS":"Általános",
            "GATE_LIGHT":"Lámpa",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Használati feltételek megnyitása",
            "DESC_MANAGE_POPUPS_WARNINGS":"Popup figyelmeztetések elrejtése",
            "MAX_USERSS_REACHED_CONTENT":"A maximális felhasználószám elérésre került.",
            "GENERAL_REMOVE":"Eltávolítás",
            "OPTIONS":"Beállítások",
            "DESC_HOME_SCENARIOS":"Kombinációk létrehozása és kezelése",
            "CHANNEL_OFF":"KI",
            "GENERAL_PORTAL_ID":"Eszköz ID",
            "EDIT_GROUP":"Eszköz szerkesztése",
            "ERROR_LERANIN_PORT_CONTENT":"Az adott csatorna betanítása hibára futott.",
            "ERROR_CONNECTION_CLOSED":"Hiba",
            "CHANNEL_ON_OFF":"BE / KI",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Megnevezés",
            "OPTIONS_EDIT_USERS":"Felhasználó-kezelés",
            "LOADING_STATES_CONTENT":"Az aktuális státusz lekérdezése.\nKérem, várjon ...",
            "LERAN_PORTS_CONTENT":"Állítsa az eszközt betanítási üzemmódba, lásd az utasítást. Válassza ki a betanítandó csatornát.",
            "REMOVE_PORTS_CONTENT":"Kérem válassza ki azokat a csatornákat, amelyeket törölni szeretné.",
            "GATE_SWING_GATE_DOUBLE":"2-szárnyú szárnyaskapu",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Vizsgálja meg, hogy megadta-e a portáladatokat vagy a helyi Gateway hozzáadása megtörtént-e.",
            "CHANNEL_SINK":"Süllyesztés",
            "OPTIONS_EDIT_USERS_TITLE":"Felhasználó",
            "MAX_PORTS_REACHED_CONTENT":"Foglalt a csatornák maximális száma",
            "MAX_PORTS_REACHED":"nem lehetséges",
            "ERROR_PORT_UNREACHABLE_CONTENT":"A kért eszköz nem elérhető",
            "PORTAL_AUTHENTICATION_FAILED":"Hiba",
            "NOTIFICATION_CENTER":"Emlékeztetők",
            "LEARNING_PROCESS":"Betanítás",
            "CHANGE_PWD_USER_INVALID_CONTENT":"A felhasználónévnek 2 - 20 karakterből kell állnia",
            "WIFI_STATE_CONNECTED":"Kapcsolódás",
            "COPY_PORTS":"Örökítés kéziadóról",
            "POPUP_SEARCH_CONTENT":"Hörmann Gateway kereséses \n\nEz a folyamat eltarthat néhány másodpercig.",
            "DESC_MANAGE_POPUPS_CANCEL":"Folyamat megszakítása",
            "DESC_WIFI_PASSWORD":"Jelszó",
            "DESC_WIFI_SAVE":"Mentés",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop aktív",
            "SELECT_GATEWAY":"Gateway-ek",
            "CLEANING_PORTS":"Eszköz hozzáadása",
            "WIFI_STATE_BUSY":"Kapcsolat felépítése",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"A megadott jelszó hibás",
            "OPTIONS_CHANGE_GATEWAY_NAME":"A Gateway átnevezése",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Név elfogadása",
            "DESC_ACTORS_EDIT":"Eszközök kezelése vagy törlése",
            "DESC_WIFI_STATE":"Kapcsolat állapota",
            "ERROR_REMOVE_USER":"Hiba",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Beállítás elfogadása",
            "HOME_TITLE":"Főoldal",
            "GENERAL_USERNAME":"Felhasználónév",
            "DRIVE_MESSAGE_OPENED":"Nyitva",
            "CONFIRM_DELETE":"Biztos benne, hogy törölni akarja a Gateway?",
            "DRIVE_MESSAGE_CLOSED":"Zárva",
            "PORTAL_VALIDATION_FAILED_CONTENT":"A portál kiszolgáló nem elérhető",
            "REMOVING_PROCESS_CONTENT":"A csatorna törlésre kerül",
            "DESC_EDIT_USERS_BACK":"Vissza a beállításokhoz",
            "ERROR_NO_GROUP_FOUND":"Eszköz nem található",
            "ERROR_INVALID_GATEWAY":"Nem található Gateway",
            "DESC_WIFI_BACK":"Vissza a beállításokhoz",
            "MAX_USERS_REACHED":"nem lehetséges",
            "DESC_CHANGE_PASSWORD_USERNAME":"Felhasználónév",
            "POPUP_AGREEMENT_ACCEPT_USE":"Elfogadom a használati feltételeket",
            "ERROR_LERNING_PORT":"Hiba",
            "POPUP_ADD_GATEWAY_CONTENT":"IP cím megadása:",
            "ERROR_ADD_GROUP":"Hiba",
            "DRIVE_MESSAGE_NO_DATA":"Nincsenek elérhető adatok",
            "CHANGE_PWD_FAILED":"Hiba",
            "SAVING_USER_RIGHTS_CONTENT":"Felhasználói jogok mentése",
            "DRIVE_MESSAGE_UNLOCKED":"nincs reteszelve",
            "GENERAL_SAVE":"Mentés",
            "INFO_BOX_FAQ":"GYIK",
            "GENERAL_CONNNECT":"Egyesítés",
            "GATE_SECTIONAL_DOOR":"Függőleges működésű garázskapu",
            "OPTIONS_CHANGE_PASSWORD":"Jelszó megváltoztatása",
            "CHANNEL":"Működtetés",
            "CHANGE_GW_NAME_CONTENT":"A Gateway neve:",
            "DRIVE_MESSAGE_RETRACTED":"behúzva",
            "DESC_ADDGWSCREEN_BACK":"Vissza a Gateway-áttekintőhöz",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Nem lehetséges",
            "OPTIONS_SET_USER_RIGHTS":"Felhasználói jogok",
            "CHANGE_GW_NAME_ERROR":"Hiba",
            "CHANNEL_LIFT":"Emelés",
            "LOGIN_FAILED_TITLE":"Hiba",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Ha az OK-val megerősíti a bejelentkezési adatok törlését, akkor a Gateway kiválasztásakor a jelszót újból meg kell adni.",
            "CHANNEL_UNLOCK":"Kireteszelés",
            "GENERAL_PORTAL_SERVER":"Portal szerver",
            "DESC_SCENARIOS_BACK":"Vissza a főmenübe",
            "CHANGE_PWD_USERNAME":"Felhasználó:",
            "POPUP_GATE_NOT_RESPONSABLE":"Az App el tudja küldeni ezt a parancsot az eszközre, de nem ismeri fel az eszköz aktuális állapotát.",
            "DESC_GW_NAME":"A Gateway neve:",
            "GATE_BARRIER":"sorompó",
            "LEARN_PORTS":"Rádiós kód betanítása",
            "GENERAL_BACK":"Vissza",
            "DESC_GWSCREEN_EDIT":"Mentett Gateway-ek törlése",
            "OPTIONS_MANAGE_POPUPS":"Popup üzenetek kezelése",
            "POPUP_LOGIN_PROCESS_CONTENT":"Kérem, várjon ...",
            "CONFIRM_DELETE_USER_CONTENT":"Biztos benne, hogy a felhasználót törölni akarja?",
            "DESC_MENU":"Menü",
            "LOGIN_FAILED_WRONG_DATA":"Hibás felhasználónév vagy jelszó",
            "GENERAL_CANCEL":"Megszakít",
            "ADD_GROUP":"Eszköz hozzáadása",
            "WIFI_STATE_AP_NOT_FOUND":"Hálózat nem található",
            "WIFI_STATE_NOT_CONNECTED":"Nincs kapcsolódás",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"A portálon keresztüli működtetés aktiválva.",
            "POPUP_ADD_GATEWAY":"Gateway hozzáadása",
            "GENERAL_NEXT":"Tovább",
            "POPUP_SUPPRESS":"Popup már nem nyitható",
            "POPUP_SEARCH_TITLE":"Keresés...",
            "WIFI_SCANNING_CONTENT":"Látható WLAN hálózatok keresése",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Nem található Gateway",
            "DESC_ACTORS_ADD":"Eszköz létrehozása",
            "ERROR_ADD_GROUP_NO_TYPE":"Az új eszközhöz nem lett típus kiválasztva.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Ellenőrizze a bejelentkezési adatokat",
            "GENERAL_REFESHED":"Aktualizálva",
            "OPTIONS_SUPPRESS_WARNINGS":"Figyelmeztetések elrejtése",
            "LOGIN_FAILED_GATEWAY_BUSY":"A Gateway jelenleg foglalt. Kérem, próbálkozzon később újra.",
            "DESC_EMAIL":"E-mail küldése a support számára",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Tartós nyitva KI",
            "CLEANING_PORTS_CONTENT":"Hozzáadás előkészítése",
            "DESC_HOME_ACTORS":"Eszközök betanítása és kezelése",
            "ERROR_TIMEOUT":"Csatlakozási hiba",
            "CREATE_USER_TITLE":"Felhasználó beillesztése",
            "ERROR_DELETE_ADMIN_CONTENT":"A rendszergazda nem törölhető",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Gyors hozzáférés",
            "ADD_SCENARIO_NAME":"Név",
            "HIST":"Előzmények",
            "DESC_RESET_LOGIN_SUBMIT":"Törlés megerősítése",
            "POPUP_WARNING":"FIGYELEM",
            "REMOVE_GROUP_PROCESS":"Az eszköz törlésre kerül",
            "POPUP_LOGIN_PROCESS":"Bejelentkezés",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Kérem, várjon ...",
            "DESC_DEFAULT_GW_SUBMIT":"Beállítás elfogadása",
            "DESC_CHANGE_PASSWORD_RETYPE":"Újra megadás",
            "LOAD_USERS_CONTENT":"A Gateway összes felhasználójának betöltése.\nEz a folyamat több időt vehet igénybe!",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Ha egy Gateway-hez aktív a gyors hozzáférés, akkor az App lehetőség szerint automatikusan bejelentkezik",
            "GATE_OTHER":"Egyéb eszközök",
            "CHANGE_PWD_USER_INVALID":"Hiba",
            "CHANNEL_LIGHT":"Lámpa",
            "LOGIN_TITLE":"Bejelentkezés",
            "CHANNEL_HALF":"Részleges nyitás",
            "GATEWAY_SCREEN_ADD_HELP":"Egy Gateway hozzáadásához válassza a +szimbólumot.",
            "ERROR_TIMEOUT_CONTENT":"Időtúllépés a Gateway-jel való kommunikáció közben.",
            "ERROR_NO_PORTS_LEARNED":"Hozzáadás nem lehetséges",
            "OPTIONS_SUPPRESS_INFOS":"Megjegyzések elrejtése",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Hiba",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automata üzemmód",
            "GENERAL_DELETE":"Törlés",
            "GENERAL_PASSWORD":"Jelszó",
            "STATE_COLLECTING_CONTENT":"Az eszközök státuszának lekérdezése",
            "ERROR_REMOVE_USER_CONTENT":"A felhasználót nem lehetett törölni",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Hiba",
            "ACTORS_ADD_HELP":"Egy eszköz hozzáadásához válassza a +szimbólumot.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Biztos benne, hogy az eszközt törölni akarja?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Kérem, várjon ...",
            "GENERAL_YES":"Igen",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Egy eszköz hozzáadása előtt legalább egy csatornát be kell tanítani",
            "CHANGE_GW_NAME_ERROR_CONTENT":"A nevet nem lehetett megváltoztatni",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Az App még nem talált Gateway-eket.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Az azonosítás hibára futott",
            "DESC_MANAGE_POPUPS_INFOS":"Popup információk elrejtése",
            "GATE_PILOMAT_POLLER":"Ütközésvédő oszlop",
            "DESC_CHANNELS_STATE":"Visszajelzésre képes eszköz állapota",
            "DESC_GWSCREEN_REFRESH":"Gateway-lista aktualizálása",
            "POPUP_SCENARIO_DISPATCHING":"Kombináció végrehajtása",
            "ERROR_PORT_UNREACHABLE":"Hiba",
            "POPUP_GATEWAY_FOUND_CONTENT":"A következő Gateway-ek lettek hozzáadva:",
            "WIFI_STATE_SECURITY_MISMATCH":"A WLAN titkosítási módja nem támogatott",
            "LOGOUT_NAMED":"Kijelentkezés",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Adatvédelmi feltételek megnyitása",
            "ERROR_NO_GW_CONTENT":"A helyi hálózaton nem található Hörmann Gateway.\nTovábbi Gateway egységeket a +jellel tud hozzáadni",
            "DESC_EDIT_USERS_ADD":"Felhasználó beillesztése",
            "ERROR_NO_PORT_FOUND":"Port nem található",
            "GATE_SLIDING_GATE":"Tolókapu",
            "DESC_CHANNELS_BUTTONS":"Az eszköz kezelőelemei",
            "DRIVE_MESSAGE_EXTENDED":"kitolva",
            "WIFI_SELECTED_NETWORK":"Név",
            "ERROR_ADD_GROUP_NO_NAME":"Az új eszközhöz nem lett név megadva.",
            "DESC_HELP":"Segítség funkció",
            "CHANGE_PWD_NEW_PASSWORD":"Új jelszó:",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Új jelszó elfogadása",
            "DESC_CHANGE_PASSWORD_PWD":"Új jelszó megadása",
            "ERROR_EDIT_ADMIN_CONTENT":"A rendszergazda nem szerkeszthető",
            "CHANGE_GW_NAME_NAME_INVALID":"Hiba",
            "STATE_COLLECTING_FAILED":"Hiba",
            "GENERAL_ADD":"Hozzáad",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"A \"Jelszó\" és a \"Jelszó ismétlése\" mezőben megadottaknak azonosnak kell lenniük",
            "WIFI_SETTINGS":"WLAN beállítások",
            "LEARN_PORTS_TITLE":"Eszköz hozzáadása",
            "ERROR_CHANGE_USERNAME":"Hiba",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Útakadály",
            "ERROR_INVALID_GATEWAY_CONTENT":"A kapcsolatot nem sikerült a Gateway-jel létrehozni. Kérem, ellenőrizze a megadott host-nevet.",
            "DESC_EDIT_USERS_EDIT":"Felhasználó törlése",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Az eszköz nevének 2 - 20 karakterből kell állnia",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Gyors hozzáférés nem lehetséges",
            "CHANNEL_UP":"NYITÁS",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Tartós nyitva BE",
            "PORTAL_VALIDATION_FAILED":"Hiba",
            "DESC_RESET_LOGIN_CANCEL":"Folyamat megszakítása",
            "CHANGE_PWD_SETTING_PASSWORD":"Átvétel",
            "LOADING_GROUPS_TITLE":"Töltés",
            "DESC_DEFAULT_GW_CANCEL":"Folyamat megszakítása",
            "DESC_SET_RIGHTS_SAVE":"Változások elfogadása",
            "REMOVING_PROCESS":"Törlés",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"A Gateway nem elérhető",
            "CONFIRM_DELETE_TITLE":"Gateway törlése",
            "SCENARIOS_ADD_HELP":"Kombináció hozzáadásához válassza a +szimbólumot.",
            "LOGOUT":"Kijelentkezés",
            "DESC_ACTORS_BACK":"Vissza a főmenübe",
            "ERROR_ADAPTER_BUSY_CONTENT":"A parancsot nem lehetett elvégezni.\n A Gateway jelenleg foglalt.",
            "DESC_WIFI_NETWORK_SCAN":"Hálózatok keresése",
            "DRIVE_MESSAGE_HALF":"Részben nyitva",
            "DESC_SCENARIOS_ADD":"Kombináció létrehozása",
            "ERROR_CONNECTION_CLOSED_CONTENT":"A kommunikáció a Gateway-jel hibára futott.",
            "SAVING_USER_RIGHTS":"Tárolók",
            "DESC_GWSCREEN_PORTAL":"Portáladatok megadása",
            "GATE_JACK":"Rádiós aljzat",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Ön ugyanazon a hálózaton van, mint a Gateway?",
            "GATE_DOOR":"Ajtó",
            "POPUP_PORTAL_UNAVAILABLE":"A portál kiszolgáló nem elérhető",
            "DESC_SET_RIGHTS_BACK":"Vissza a felhasználókhoz",
            "GATE_SMARTKEY":"Ajtózár-meghajtás",
            "POPUP_GATEWAY_FOUND_TITILE":"Keresési folyamat vége",
            "WIFI_LOADING_DATA_TITLE":"Töltés",
            "GENERAL_PORTS":"Csatornák",
            "DESC_SCENARIOS_EDIT":"Kombinációk kezelése vagy törlése",
            "OPTIONS_LEARNED_PORTS":"Betanított csatornák:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Elfogadom az adatvédelmi feltételeket",
            "DESC_EDIT_USERS_SET_RIGHTS":"Felhasználó kiválasztása, a hozzáférési jogok változtatásához",
            "DRIVE_MESSAGE_HALF_MOVING":"Részleges nyitás / Futásban",
            "PORTAL_SET_ID_DIALOG":"Portál-beállítások",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Nincs referenciapont",
            "POPUP_SETTING_STATE":"Kérem, várjon ...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/hu/felhasznalasi-feltetelek",
            "ERROR_CHANGE_USERNAME_CONTENT":"A felhasználónevet nem lehetett megváltoztatni",
            "GROUP_REQUESTABLE":"Az eszköz visszajelzésre képes",
            "LOADING_STATES_TITLE":"Töltés",
            "DESC_HOME_USERS":"Felhasználó-kezelés",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"A jelszónak 4 - 20 karakterből kell állnia",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"A jelszó elfogadása",
            "POPUP_GATE_OUT_OF_VIEW":"Egy automata kapuszerkezet vezérlését a kapura való rálátás nélkül csak akkor szabad működtetni, ha a szériában létező erőhatárolás mellett kiegészítésként egy fénysorompó is telepítve van a kapura.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Válassza ki, hogy a Popup üzenetek megjelenjenek vagy elrejtésre kerüljenek",
            "CHANNEL_IMPULS":"Impulzusos",
            "PORTAL_VALIDATION_SUCCEEDED":"Azonosítva",
            "DRIVE_MESSAGE_LOCKED":"reteszelve",
            "CHANNEL_DOWN":"ZÁRÁS",
            "POPUP_INET_SPEED_LOW":"Az Ön adatátviteli kapcsolata nem elegendő ehhez az alkalmazáshoz",
            "CHANGE_PWD_FAILED_CONTENT":"A jelszót nem lehetett megváltoztatni",
            "GENERAL_GROUP_TYPE":"Eszköztípus",
            "CHANNEL_WALK":"Nyílószárny",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Vízszintes működésű garázskapu",
            "POPUP_AGREEMENT_CONTENT":"Fogadja el az App használata előtt az adatvédelmi- / használati feltételeket",
            "INFO":"Információ",
            "LOADING_GROUPS_CONTENT":"Eszközök betöltése",
            "GATE_PILOMAT_REIFENKILLER":"Tüskés útakadályok",
            "GATE_PILOMAT_HUBBALKEN":"Emelőgerendák",
            "GENERAL_RETYPE":"Jelszó ismétlése",
            "DESC_OTIONS_BACK":"Vissza a főmenübe",
            "DESC_SET_RIGHTS":"Eszköz kiválasztása, a felhasználó hozzáférési jogainak biztosításához",
            "WIFI_SCANNING_TITLE":"Keresés",
            "WIFI_STATE_CONNECTION_FAILURE":"A kapcsolat felépítése hibára futott",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"A felhasználónévnek 2 - 20 karakterből kell állnia",
            "REMOVE_PORTS":"Törlés",
            "GENERAL_ON":"Bekapcsolva",
            "DESC_CHANGE_PASSWORD_CANCEL":"Folyamat megszakítása",
            "LEARNING_PROCESS_CONTENT":"Kérem, várjon",
            "LOGIN_FAILED_UNKNOWN":"Váratlan hiba lépett fel",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"A rendszergazda felhasználói jogai nem változtathatók meg!"
         };
         return _loc1_;
      }
   }
}
