package
{
   import mx.resources.ResourceBundle;
   
   public class it_IT$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function it_IT$LocalizedStrings_properties()
      {
         super("it_IT","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Bloccare",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Immettere i dati di accesso al portale Hörmann",
            "ERROR_DELETE_ADMIN":"Non possibile",
            "LOGIN_SHOULD_SAVE":"Salva dati",
            "LOAD_USERS_TITLE":"Attendere...",
            "CHANGE_GW_NAME_SETTING":"Applica",
            "CONFIRM_DELETE_GROUP":"Cancella apparecchio",
            "GENERAL_NO":"No",
            "DESC_GWSCREEN_ADD":"Aggiungi gateway locali",
            "DRIVE_MESSAGE_NOT_RETRACTED":"non abbassato",
            "WIFI_PASSPHRASE":"Password",
            "CHANNEL_ON":"Accensione",
            "SCENARIOS":"Scenari",
            "ERROR_SET_ADMIN_RIGHTS":"Non possibile",
            "DESC_DEFAULT_GW_SAVE":"Impostazione accesso rapido per gateway attuale",
            "POPUP_INFO":"Nota",
            "DRIVE_MESSAGE_ERROR":"ATTENZIONE: errore",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/it/protezione-dati",
            "DESC_WIFI_NETWORK_NAME":"Nome rete",
            "EMAIL_BODY":"Le domande possono essere inviate per e-mail. Inoltre è disponibile la nostra funzione FAQ.\n\nIhr BiSecur-Home Support-Team",
            "CONFIRM_DELETE_USER":"Cancella utente",
            "DESC_CHANNELS_BACK":"Torna all\'elenco apparecchi",
            "CHANGE_PWD_FIRST_START":"Per motivi di sicurezza modificare l\'impostazione di fabbrica della password dopo il primo accesso:",
            "GENERAL_DEFAULT_GATEWAY":"Accesso rapido",
            "CHANGE_PWD_PASSWORD_INVALID":"Errore",
            "ERROR_NO_GW_TITLE":"Nessun gateway",
            "POPUP_SETTING_STATE_CONTENT":"Esecuzione del comando in corso",
            "WIFI_LOADING_DATA_CONTENT":"Caricamento dati WLAN in corso",
            "OPTIONS_RESET_LOGIN_DATA":"Cancella dati login salvati",
            "EDIT_USER_TITLE":"Modifica utente",
            "DESC_HOME_PREFERENCES":"Modifica impostazioni gateway e app",
            "WIFI_ACTIVE_STATE":"Stato WLAN",
            "STATE_COLLECTING":"Carica",
            "ADD_SCENARIO":"Aggiungi scenario",
            "STATE_COLLECTING_FAILED_CONTENT":"Impossibile caricare lo stato",
            "GATE_SWING_GATE_SINGLE":"Cancello ad 1 battente",
            "ACTORS":"Apparecchi",
            "POPUP_AGREEMENT":"Utilizzo / Protezione dei dati",
            "CHANNEL_OPEN_DOOR":"Apri",
            "DESC_ACTORS_REFRESH":"Aggiorna stato",
            "GENERAL_OFF":"Spento",
            "OPTIONS_HELP":"Guida online",
            "COPY_PORTS_CONTENT":"Portare il trasmettitore in modalità di trasmissione, vedi istruzioni. Selezionare il canale da acquisire.",
            "GENERAL_SELECT":"Selezionare...",
            "ERROR_ADAPTER_BUSY":"Errore",
            "INFO_BOX_INFOS":"Generalità",
            "GATE_LIGHT":"Luce",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Apri condizioni di utilizzo",
            "DESC_MANAGE_POPUPS_WARNINGS":"Tralascia popup di avviso",
            "MAX_USERSS_REACHED_CONTENT":"È stato aggiunto il numero massimo di utenti.",
            "GENERAL_REMOVE":"Rimuovi",
            "OPTIONS":"Impostazioni",
            "DESC_HOME_SCENARIOS":"Creazione e gestione scenari",
            "CHANNEL_OFF":"Spegnimento",
            "GENERAL_PORTAL_ID":"ID apparecchi",
            "EDIT_GROUP":"Modifica dispositivo",
            "ERROR_LERANIN_PORT_CONTENT":"Apprendimento del canale desiderato fallito",
            "ERROR_CONNECTION_CLOSED":"Errore",
            "CHANNEL_ON_OFF":"On / Off",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Denominazione",
            "OPTIONS_EDIT_USERS":"Gestione utenti",
            "LOADING_STATES_CONTENT":"Richiesta stato attuale in corso.\nAttendere ...",
            "LERAN_PORTS_CONTENT":"Portare l\'apparecchio in modalità di apprendimento, vedi istruzioni. Selezionare il canale da apprendere.",
            "REMOVE_PORTS_CONTENT":"Selezionare i canali da cancellare.",
            "GATE_SWING_GATE_DOUBLE":"Cancello a 2 battenti",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Controllare se sono stati registrati i dati del portale o se è stato aggiunto un gateway locale.",
            "CHANNEL_SINK":"Abbassamento",
            "OPTIONS_EDIT_USERS_TITLE":"Utente",
            "MAX_PORTS_REACHED_CONTENT":"Numero massimo di canali occupato",
            "MAX_PORTS_REACHED":"Non possibile",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Impossibile raggiungere l\'apparecchio richiesto",
            "PORTAL_AUTHENTICATION_FAILED":"Operazione non riuscita",
            "NOTIFICATION_CENTER":"Avvisi",
            "LEARNING_PROCESS":"Apprendi",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Il nome utente deve essere formato da 2 - 20 caratteri",
            "WIFI_STATE_CONNECTED":"Connesso",
            "COPY_PORTS":"Trasmetti dal telecomando",
            "POPUP_SEARCH_CONTENT":"Ricerca gateway Hörmann \n\nL\'operazione potrebbe richiedere alcuni secondi.",
            "DESC_MANAGE_POPUPS_CANCEL":"Annulla azione",
            "DESC_WIFI_PASSWORD":"Password",
            "DESC_WIFI_SAVE":"Salva",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop attivo",
            "SELECT_GATEWAY":"Gateway",
            "CLEANING_PORTS":"Aggiungi apparecchio",
            "WIFI_STATE_BUSY":"Connessione in corso",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"La password inserita è errata",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Modifica nome gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Applicazione del nome in corso",
            "DESC_ACTORS_EDIT":"Gestisci o cancella apparecchi",
            "DESC_WIFI_STATE":"Stato connessione",
            "ERROR_REMOVE_USER":"Operazione non riuscita",
            "LANG_TAG":"IT",
            "DESC_MANAGE_POPUPS_SUBMIT":"Applica impostazione",
            "HOME_TITLE":"Pagina principale",
            "GENERAL_USERNAME":"Nome utente",
            "DRIVE_MESSAGE_OPENED":"Aperto",
            "CONFIRM_DELETE":"Cancellare veramente il gateway?",
            "DRIVE_MESSAGE_CLOSED":"Chiuso",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Impossibile raggiungere il server del portale",
            "REMOVING_PROCESS_CONTENT":"Il canale viene cancellato",
            "DESC_EDIT_USERS_BACK":"Ritorna alle impostazioni",
            "ERROR_NO_GROUP_FOUND":"Apparecchio non trovato",
            "ERROR_INVALID_GATEWAY":"Gateway non trovato",
            "DESC_WIFI_BACK":"Ritorna alle impostazioni",
            "MAX_USERS_REACHED":"Non possibile",
            "DESC_CHANGE_PASSWORD_USERNAME":"Nome utente",
            "POPUP_AGREEMENT_ACCEPT_USE":"Accetto le condizioni di utilizzo",
            "ERROR_LERNING_PORT":"Operazione non riuscita",
            "POPUP_ADD_GATEWAY_CONTENT":"Inserire l\'indirizzo IP:",
            "ERROR_ADD_GROUP":"Errore",
            "DRIVE_MESSAGE_NO_DATA":"Nessun dato disponibile",
            "CHANGE_PWD_FAILED":"Operazione non riuscita",
            "SAVING_USER_RIGHTS_CONTENT":"Salvataggio dati utente in corso",
            "DRIVE_MESSAGE_UNLOCKED":"Non bloccato",
            "GENERAL_SAVE":"Salva",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Collega",
            "GATE_SECTIONAL_DOOR":"Portone da garage a scorrimento verticale",
            "OPTIONS_CHANGE_PASSWORD":"Modifica password",
            "CHANNEL":"Comando",
            "CHANGE_GW_NAME_CONTENT":"Nome del gateway",
            "DRIVE_MESSAGE_RETRACTED":"in posizione abbassata",
            "DESC_ADDGWSCREEN_BACK":"Torna alla panoramica dei gateway",
            "EMAIL_SUBJECT":"Supporto",
            "ERROR_EDIT_ADMIN":"Non possibile",
            "OPTIONS_SET_USER_RIGHTS":"Diritti utente",
            "CHANGE_GW_NAME_ERROR":"Operazione non riuscita",
            "CHANNEL_LIFT":"Sollevamento",
            "LOGIN_FAILED_TITLE":"Operazione non riuscita",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Se confermi la cancellazione dei dati di login con OK devi immettere di nuovo la password alla selezione del gateway",
            "CHANNEL_UNLOCK":"Sbloccare",
            "GENERAL_PORTAL_SERVER":"Server portale",
            "DESC_SCENARIOS_BACK":"Torna al menu principale",
            "CHANGE_PWD_USERNAME":"Utente:",
            "POPUP_GATE_NOT_RESPONSABLE":"L\'app può inviare questo comando all\'apparecchio, ma non ne riconosce lo stato attuale.",
            "DESC_GW_NAME":"Nome del gateway",
            "GATE_BARRIER":"sbarra",
            "LEARN_PORTS":"Apprendi codice radio",
            "GENERAL_BACK":"Indietro",
            "DESC_GWSCREEN_EDIT":"Gateway salvati da cancellare",
            "OPTIONS_MANAGE_POPUPS":"Gestisci messaggi popup",
            "POPUP_LOGIN_PROCESS_CONTENT":"Attendere ...",
            "CONFIRM_DELETE_USER_CONTENT":"Procedere alla cancellazione dell\'utente?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"Nome utente o password errati.",
            "GENERAL_CANCEL":"Annulla",
            "ADD_GROUP":"Aggiungi apparecchio",
            "WIFI_STATE_AP_NOT_FOUND":"Rete non trovata",
            "WIFI_STATE_NOT_CONNECTED":"Non connesso",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Il comando tramite portale è stato attivato!",
            "POPUP_ADD_GATEWAY":"Aggiungi gateway",
            "GENERAL_NEXT":"Avanti",
            "POPUP_SUPPRESS":"Non aprire più popup",
            "POPUP_SEARCH_TITLE":"Cerca...",
            "WIFI_SCANNING_CONTENT":"Cerca reti WLAN visibili",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Gateway non trovato",
            "DESC_ACTORS_ADD":"Crea apparecchi",
            "ERROR_ADD_GROUP_NO_TYPE":"Non è stato selezionato un tipo per il nuovo apparecchio.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Controllare i dati di login",
            "GENERAL_REFESHED":"Aggiornato",
            "OPTIONS_SUPPRESS_WARNINGS":"Tralascia avvisi",
            "LOGIN_FAILED_GATEWAY_BUSY":"Il gateway è sovraccarico. Riprova.",
            "DESC_EMAIL":"Invia e-mail al Supporto",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Apertura permanente OFF",
            "CLEANING_PORTS_CONTENT":"Preparazione dell\'aggiunta in corso",
            "DESC_HOME_ACTORS":"Apprendimento e gestione apparecchi",
            "ERROR_TIMEOUT":"Errore di connessione",
            "CREATE_USER_TITLE":"Aggiungi utente",
            "ERROR_DELETE_ADMIN_CONTENT":"Impossibile cancellare l\'amministratore",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Accesso rapido",
            "ADD_SCENARIO_NAME":"Cognome",
            "HIST":"Cronologia",
            "DESC_RESET_LOGIN_SUBMIT":"Conferma cancellazione",
            "POPUP_WARNING":"ATTENZIONE",
            "REMOVE_GROUP_PROCESS":"L\'apparecchio viene cancellato",
            "POPUP_LOGIN_PROCESS":"Accedi",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Attendere ...",
            "DESC_DEFAULT_GW_SUBMIT":"Applica impostazione",
            "DESC_CHANGE_PASSWORD_RETYPE":"Ripeti inserimento",
            "LOAD_USERS_CONTENT":"È in corso il caricamento di tutti gli utenti dal gateway.\nL\'operazione potrebbe richiedere alcuni secondi.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Se per un gateway è attivato l\'accesso rapido, è possibile che l\'app si registri automaticamente",
            "GATE_OTHER":"Altri apparecchi",
            "CHANGE_PWD_USER_INVALID":"Errore",
            "CHANNEL_LIGHT":"Luce",
            "LOGIN_TITLE":"Accedi",
            "CHANNEL_HALF":"Apertura parziale",
            "GATEWAY_SCREEN_ADD_HELP":"Per aggiungere un gateway selezionare il simbolo+.",
            "ERROR_TIMEOUT_CONTENT":"Timeout nella comunicazione con il gateway",
            "ERROR_NO_PORTS_LEARNED":"Impossibile aggiungere",
            "OPTIONS_SUPPRESS_INFOS":"Tralascia note",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Errore",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Funzionamento automatico",
            "GENERAL_DELETE":"Cancellazione",
            "GENERAL_PASSWORD":"Password",
            "STATE_COLLECTING_CONTENT":"Richiesta stato apparecchio in corso",
            "ERROR_REMOVE_USER_CONTENT":"Impossibile cancellare l\'utente",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Errore",
            "ACTORS_ADD_HELP":"Per aggiungere un dispositivo selezionare il simbolo+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Procedere alla cancellazione dell\'apparecchio?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Attendere ...",
            "GENERAL_YES":"Sì",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Prima di aggiungere un apparecchio apprendere almeno un canale",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Non è stato possibile modificare il nome",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"L\'app non ha trovato il gateway.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autenticazione non riuscita",
            "DESC_MANAGE_POPUPS_INFOS":"Tralascia popup di informazione",
            "GATE_PILOMAT_POLLER":"Dissuasore",
            "DESC_CHANNELS_STATE":"Stato degli apparecchi con funzione di feedback",
            "DESC_GWSCREEN_REFRESH":"Aggiornamento dell\'elenco gateway",
            "POPUP_SCENARIO_DISPATCHING":"Scenario in esecuzione",
            "ERROR_PORT_UNREACHABLE":"Operazione non riuscita",
            "POPUP_GATEWAY_FOUND_CONTENT":"Sono stati aggiunti i seguenti gateway:",
            "WIFI_STATE_SECURITY_MISMATCH":"Il tipo di crittografia del WLAN non viene supportato",
            "LOGOUT_NAMED":"Logout",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Apri condizioni per la protezione dei dati",
            "ERROR_NO_GW_CONTENT":"Non è stato possibile trovare un gateway Hörmann nella rete locale.\nAggiungere ulteriori gateway con il segno+",
            "DESC_EDIT_USERS_ADD":"Aggiungi utente",
            "ERROR_NO_PORT_FOUND":"Porta non trovata",
            "GATE_SLIDING_GATE":"Cancello scorrevole",
            "DESC_CHANNELS_BUTTONS":"Strumenti di comando dell\'apparecchio",
            "DRIVE_MESSAGE_EXTENDED":"in posizione sollevata",
            "WIFI_SELECTED_NETWORK":"Cognome",
            "ERROR_ADD_GROUP_NO_NAME":"Non è stato indicato un nome per il nuovo apparecchio.",
            "DESC_HELP":"Guida",
            "CHANGE_PWD_NEW_PASSWORD":"Nuova password",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Applica nuova password",
            "DESC_CHANGE_PASSWORD_PWD":"Inserimento nuova password",
            "ERROR_EDIT_ADMIN_CONTENT":"Impossibile modificare l\'amministratore",
            "CHANGE_GW_NAME_NAME_INVALID":"Operazione non riuscita",
            "STATE_COLLECTING_FAILED":"Errore",
            "GENERAL_ADD":"Aggiungi",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Password\" e \"Ripeti password\" devono essere identiche",
            "WIFI_SETTINGS":"Impostazioni WLAN",
            "LEARN_PORTS_TITLE":"Aggiungi apparecchio",
            "ERROR_CHANGE_USERNAME":"Operazione non riuscita",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Road blocker",
            "ERROR_INVALID_GATEWAY_CONTENT":"Non è stato possibile creare il collegamento con il gateway. Verificare il nome host.",
            "DESC_EDIT_USERS_EDIT":"Cancella utente",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Il nome dell\'apparecchio deve essere formato da 2 - 20 caratteri",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Accesso rapido impossibile",
            "CHANNEL_UP":"Apertura",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Apertura permanente ON",
            "PORTAL_VALIDATION_FAILED":"Operazione non riuscita",
            "DESC_RESET_LOGIN_CANCEL":"Annulla azione",
            "CHANGE_PWD_SETTING_PASSWORD":"Applica",
            "LOADING_GROUPS_TITLE":"Carica",
            "DESC_DEFAULT_GW_CANCEL":"Annulla azione",
            "DESC_SET_RIGHTS_SAVE":"Applica modifiche",
            "REMOVING_PROCESS":"Cancellazione",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Il gateway non è raggiungibile",
            "CONFIRM_DELETE_TITLE":"Cancella gateway",
            "SCENARIOS_ADD_HELP":"Per aggiungere uno scenario selezionare il simbolo+.",
            "LOGOUT":"Logout",
            "DESC_ACTORS_BACK":"Torna al menu principale",
            "ERROR_ADAPTER_BUSY_CONTENT":"Impossibile eseguire il comando.\n Il gateway è sovraccarico.",
            "DESC_WIFI_NETWORK_SCAN":"Ricerca reti",
            "DRIVE_MESSAGE_HALF":"Parzialmente aperto",
            "DESC_SCENARIOS_ADD":"Crea scenario",
            "ERROR_CONNECTION_CLOSED_CONTENT":"La comunicazione col gateway è fallita.",
            "SAVING_USER_RIGHTS":"Salvataggio in corso",
            "DESC_GWSCREEN_PORTAL":"Inserimento dati portale",
            "GATE_JACK":"Presa radiocomandata",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Si trova nella stessa rete del gateway?",
            "GATE_DOOR":"Porta",
            "POPUP_PORTAL_UNAVAILABLE":"Impossibile raggiungere il server del portale",
            "DESC_SET_RIGHTS_BACK":"Torna agli utenti",
            "GATE_SMARTKEY":"Motorizzazione serratura",
            "POPUP_GATEWAY_FOUND_TITILE":"Ricerca conclusa",
            "WIFI_LOADING_DATA_TITLE":"Carica",
            "GENERAL_PORTS":"Canali",
            "DESC_SCENARIOS_EDIT":"Gestisci o cancella scenari",
            "OPTIONS_LEARNED_PORTS":"Canali appresi:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Accetto le condizioni per la protezione dei dati",
            "DESC_EDIT_USERS_SET_RIGHTS":"Selezionare utente per modificare i diritti di accesso",
            "DRIVE_MESSAGE_HALF_MOVING":"Parzialmente aperto / In manovra",
            "PORTAL_SET_ID_DIALOG":"Impostazioni portale",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Nessun punto di riferimento",
            "POPUP_SETTING_STATE":"Attendere ...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/it/condizioni-di-utilizzo",
            "ERROR_CHANGE_USERNAME_CONTENT":"Impossibile modificare il nome utente",
            "GROUP_REQUESTABLE":"L\'apparecchio ha la funzione di feedback",
            "LOADING_STATES_TITLE":"Carica",
            "DESC_HOME_USERS":"Gestione utenti",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"La password deve essere formata da 4 - 20 caratteri",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Applicazione password in corso",
            "POPUP_GATE_OUT_OF_VIEW":"Attenzione: la centralina di comando di un sistema di chiusura automatico può essere posizionata in un punto che non consente la vista del portone soltanto se, oltre al limitatore di sforzo di serie, sul portone viene installata una fotocellula.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Scegliere se i messaggi popup devono essere visualizzati o tralasciati",
            "CHANNEL_IMPULS":"Impulso",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorizzato",
            "DRIVE_MESSAGE_LOCKED":"Bloccata",
            "CHANNEL_DOWN":"Chiusura",
            "POPUP_INET_SPEED_LOW":"La connessione dati non è sufficiente per questa applicazione",
            "CHANGE_PWD_FAILED_CONTENT":"Impossibile modificare la password",
            "GENERAL_GROUP_TYPE":"Tipo di dispositivo",
            "CHANNEL_WALK":"Battente pedonale",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Portone da garage a scorrimento orizzontale",
            "POPUP_AGREEMENT_CONTENT":"Prima dell\'utilizzo dell\'app accettare le condizioni per la protezione dei dati e di utilizzo",
            "INFO":"Informazioni",
            "LOADING_GROUPS_CONTENT":"Carica apparecchi",
            "GATE_PILOMAT_REIFENKILLER":"Tyre killer",
            "GATE_PILOMAT_HUBBALKEN":"Barriere a movimento verticale",
            "GENERAL_RETYPE":"Ripeti password",
            "DESC_OTIONS_BACK":"Torna al menu principale",
            "DESC_SET_RIGHTS":"Selezionare apparecchio per modificare i diritti di accesso utente",
            "WIFI_SCANNING_TITLE":"Cerca",
            "WIFI_STATE_CONNECTION_FAILURE":"Connessione non riuscita",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Il nome utente deve essere formato da 2 - 20 caratteri",
            "REMOVE_PORTS":"Cancellazione",
            "GENERAL_ON":"Acceso",
            "DESC_CHANGE_PASSWORD_CANCEL":"Annulla azione",
            "LEARNING_PROCESS_CONTENT":"Attendere...",
            "LOGIN_FAILED_UNKNOWN":"Si è verificato un errore inatteso.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Impossibile modificare i diritti utente dell\'amministratore"
         };
         return _loc1_;
      }
   }
}
