package
{
   import mx.resources.ResourceBundle;
   
   public class lt_LT$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function lt_LT$LocalizedStrings_properties()
      {
         super("lt_LT","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Užrakinti",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Įveskite Hörmann portalo prieigos duomenis",
            "ERROR_DELETE_ADMIN":"Negalima",
            "LOGIN_SHOULD_SAVE":"Išsaugoti duomenis",
            "LOAD_USERS_TITLE":"Laukite",
            "CHANGE_GW_NAME_SETTING":"Perimti",
            "CONFIRM_DELETE_GROUP":"Ištrinti prietaisą",
            "GENERAL_NO":"ne",
            "DESC_GWSCREEN_ADD":"Pridėti vietines tinklų sąsajas",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nesustumta",
            "WIFI_PASSPHRASE":"Slaptažodis",
            "CHANNEL_ON":"Įj.",
            "SCENARIOS":"Scenarijai",
            "ERROR_SET_ADMIN_RIGHTS":"Negalima",
            "DESC_DEFAULT_GW_SAVE":"Įrengti esamos tinklų sąsajos sparčiąją prieigą",
            "POPUP_INFO":"Nurodymas",
            "DRIVE_MESSAGE_ERROR":"DĖMESIO: klaida",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Tinklo pavadinimas",
            "EMAIL_BODY":"Savo klausimus mums galite atsiųsti el. paštu. Tam taip pat galite naudoti mūsų DUK funkcija.\n\nJūsų „BiSecur-Home“ pagalbos centro kolektyvas",
            "CONFIRM_DELETE_USER":"Ištrinti naudotoją",
            "DESC_CHANNELS_BACK":"Atgal į prietaisų sąrašą",
            "CHANGE_PWD_FIRST_START":"Pirmą kartą prisiregistravę, saugumo sumetimais pakeiskite savo slaptažodžio gamyklinius nustatymus",
            "GENERAL_DEFAULT_GATEWAY":"Sparčioji prieiga",
            "CHANGE_PWD_PASSWORD_INVALID":"Klaida",
            "ERROR_NO_GW_TITLE":"Nėra tinklų sąsajų",
            "POPUP_SETTING_STATE_CONTENT":"Komanda vykdoma",
            "WIFI_LOADING_DATA_CONTENT":"WLAN duomenys įkeliami",
            "OPTIONS_RESET_LOGIN_DATA":"Ištrinti išsaugotus prisijungimo duomenis",
            "EDIT_USER_TITLE":"Apdoroti naudotojus",
            "DESC_HOME_PREFERENCES":"Pakeisti tinklų sąsajos ir taikomosios programos nustatymus",
            "WIFI_ACTIVE_STATE":"WLAN būsena",
            "STATE_COLLECTING":"Įkeliu",
            "ADD_SCENARIO":"Pridėti scenarijų",
            "STATE_COLLECTING_FAILED_CONTENT":"Būsena nebuvo įkelta",
            "GATE_SWING_GATE_SINGLE":"1 sąvaros sukamieji vartai",
            "ACTORS":"Prietaisai",
            "POPUP_AGREEMENT":"Naudojimas / duomenų apsauga",
            "CHANNEL_OPEN_DOOR":"Atidaryti",
            "DESC_ACTORS_REFRESH":"Atnaujinti būseną",
            "GENERAL_OFF":"Išjungta",
            "OPTIONS_HELP":"Internetinis žinynas",
            "COPY_PORTS_CONTENT":"Nustatykite siųstuvą į perėmimo režimą, žr. instrukciją. Pasirinkite kanalą, kurį reikia perimti.",
            "GENERAL_SELECT":"Pasirinkite...",
            "ERROR_ADAPTER_BUSY":"Klaida",
            "INFO_BOX_INFOS":"Bendroji informacija",
            "GATE_LIGHT":"Apšvietimas",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Atidaryti naudojimosi sąlygas",
            "DESC_MANAGE_POPUPS_WARNINGS":"Slopinti iššokančius įspėjimus",
            "MAX_USERSS_REACHED_CONTENT":"Pasiektas maksimalus naudotojų skaičius.",
            "GENERAL_REMOVE":"Pašalinti",
            "OPTIONS":"Nuostatos",
            "DESC_HOME_SCENARIOS":"Sukurti ir administruoti scenarijus",
            "CHANNEL_OFF":"Išj.",
            "GENERAL_PORTAL_ID":"Prietaiso ID",
            "EDIT_GROUP":"Apdoroti prietaisą",
            "ERROR_LERANIN_PORT_CONTENT":"Pageidaujamo kanalo suprogramuoti nepavyko",
            "ERROR_CONNECTION_CLOSED":"Klaida",
            "CHANNEL_ON_OFF":"Įj./išj.",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Pavadinimas",
            "OPTIONS_EDIT_USERS":"Administruoti vartotojus",
            "LOADING_STATES_CONTENT":"Esama būsena iškviečiama.\nLaukite...",
            "LERAN_PORTS_CONTENT":"Perkelkite prietaisą į programavimo režimą, žr. instrukciją. Pasirinkite kanalą, kurį reikia suprogramuoti.",
            "REMOVE_PORTS_CONTENT":"Pasirinkite kanalus, kuriuos norite ištrinti.",
            "GATE_SWING_GATE_DOUBLE":"2 sąvarų sukamieji vartai",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Patikrinkite, ar įrašėte savo portalo duomenis arba pridėjote vietinę tinklų sąsają.",
            "CHANNEL_SINK":"Nuleisti",
            "OPTIONS_EDIT_USERS_TITLE":"Naudotojas",
            "MAX_PORTS_REACHED_CONTENT":"Priskirtas maksimalus kanalų skaičius",
            "MAX_PORTS_REACHED":"Negalima",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Užklausto prietaiso nebuvo galima pasiekti",
            "PORTAL_AUTHENTICATION_FAILED":"Nesėkmingai",
            "NOTIFICATION_CENTER":"Pranešimai",
            "LEARNING_PROCESS":"Suprogramuoti",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Naudotojo vardas turi būti iš 2–20 simbolių",
            "WIFI_STATE_CONNECTED":"Sujungta",
            "COPY_PORTS":"Perimti iš rankinio siųstuvo",
            "POPUP_SEARCH_CONTENT":"Hörmann tinklų sąsajų paieška \n\nŠis procesas gali užtrukti kelias sekundes.",
            "DESC_MANAGE_POPUPS_CANCEL":"Nutraukti veiksmą",
            "DESC_WIFI_PASSWORD":"Slaptažodis",
            "DESC_WIFI_SAVE":"Išsaugoti",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Sustabdymas aktyvus",
            "SELECT_GATEWAY":"Tinklų sąsajos",
            "CLEANING_PORTS":"Pridėti prietaisą",
            "WIFI_STATE_BUSY":"Ryšys užmezgamas",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Įvestas slaptažodis yra neteisingas",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Pakeisti tinklų sąsajos vardą",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Vardas perimamas",
            "DESC_ACTORS_EDIT":"Administruoti arba ištrinti prietaisus",
            "DESC_WIFI_STATE":"Sujungimo būsena",
            "ERROR_REMOVE_USER":"Nesėkmingai",
            "LANG_TAG":"LT",
            "DESC_MANAGE_POPUPS_SUBMIT":"Perimti nustatymą",
            "HOME_TITLE":"Pagrindinis puslapis",
            "GENERAL_USERNAME":"Vartotojo vardas",
            "DRIVE_MESSAGE_OPENED":"Atidaryti",
            "CONFIRM_DELETE":"Esate įsitikinę, kad norite ištrinti tinklų sąsają?",
            "DRIVE_MESSAGE_CLOSED":"Uždaryti",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portalo serverio nebuvo galima pasiekti",
            "REMOVING_PROCESS_CONTENT":"Kanalas ištrinamas",
            "DESC_EDIT_USERS_BACK":"Atgal į nustatymus",
            "ERROR_NO_GROUP_FOUND":"Prietaisas nerastas",
            "ERROR_INVALID_GATEWAY":"Tinklų sąsaja nerasta",
            "DESC_WIFI_BACK":"Atgal prie nustatymų",
            "MAX_USERS_REACHED":"Negalima",
            "DESC_CHANGE_PASSWORD_USERNAME":"Vartotojo vardas",
            "POPUP_AGREEMENT_ACCEPT_USE":"Aš sutinku su naudojimosi sąlygomis.",
            "ERROR_LERNING_PORT":"Nesėkmingai",
            "POPUP_ADD_GATEWAY_CONTENT":"Įveskite IP adresą:",
            "ERROR_ADD_GROUP":"Klaida",
            "DRIVE_MESSAGE_NO_DATA":"Nėra duomenų",
            "CHANGE_PWD_FAILED":"Nesėkmingai",
            "SAVING_USER_RIGHTS_CONTENT":"Naudotojo teisės išsaugomos",
            "DRIVE_MESSAGE_UNLOCKED":"neužrakintos",
            "GENERAL_SAVE":"Išsaugoti",
            "INFO_BOX_FAQ":"DUK",
            "GENERAL_CONNNECT":"Sujungti",
            "GATE_SECTIONAL_DOOR":"Vertikaliai judantys garažo vartai",
            "OPTIONS_CHANGE_PASSWORD":"Pakeisti slaptažodį",
            "CHANNEL":"Valdymas",
            "CHANGE_GW_NAME_CONTENT":"Tinklų sąsajos vardas",
            "DRIVE_MESSAGE_RETRACTED":"sustumta",
            "DESC_ADDGWSCREEN_BACK":"Atgal į tinklų sąsajų apžvalgą",
            "EMAIL_SUBJECT":"Pagalbos centras",
            "ERROR_EDIT_ADMIN":"Negalima",
            "OPTIONS_SET_USER_RIGHTS":"Naudotojo teisės",
            "CHANGE_GW_NAME_ERROR":"Nesėkmingai",
            "CHANNEL_LIFT":"Pakelti",
            "LOGIN_FAILED_TITLE":"Nesėkmingai",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Kai prisijungimo duomenų ištrynimą patvirtinsite su OK, renkantis tinklų sąsają, slaptažodį reiks įvesti iš naujo",
            "CHANNEL_UNLOCK":"Atrakinti",
            "GENERAL_PORTAL_SERVER":"Portalo serveris",
            "DESC_SCENARIOS_BACK":"Atgal į pagrindinį meniu",
            "CHANGE_PWD_USERNAME":"Vartotojas:",
            "POPUP_GATE_NOT_RESPONSABLE":"Taikomoji programa šią programą gali nusiųsti prietaisui, tačiau neatpažįsta esamos prietaiso būsenos.",
            "DESC_GW_NAME":"Tinklų sąsajos vardas",
            "GATE_BARRIER":"Užtvaras",
            "LEARN_PORTS":"Suprogramuoti radijo ryšio kodą",
            "GENERAL_BACK":"Atgal",
            "DESC_GWSCREEN_EDIT":"Skirtas išsaugotoms tinklų sąsajoms ištrinti",
            "OPTIONS_MANAGE_POPUPS":"Administruoti iššokančius pranešimus",
            "POPUP_LOGIN_PROCESS_CONTENT":"Laukite...",
            "CONFIRM_DELETE_USER_CONTENT":"Esate įsitikinę, kad norite ištrinti naudotoją?",
            "DESC_MENU":"Meniu",
            "LOGIN_FAILED_WRONG_DATA":"Neteisingas įvestas vartotojo vardas arba slaptažodis",
            "GENERAL_CANCEL":"Nutraukti",
            "ADD_GROUP":"Pridėti prietaisą",
            "WIFI_STATE_AP_NOT_FOUND":"Tinklas nerastas",
            "WIFI_STATE_NOT_CONNECTED":"Nesujungta",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Valdymas per portalą aktyvintas!",
            "POPUP_ADD_GATEWAY":"Pridėti tinklų sąsają",
            "GENERAL_NEXT":"Toliau",
            "POPUP_SUPPRESS":"Iššokančio lango nebeatidaryti",
            "POPUP_SEARCH_TITLE":"Paieška...",
            "WIFI_SCANNING_CONTENT":"Matomų WLAN tinklų paieška",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Tinklų sąsaja nerasta",
            "DESC_ACTORS_ADD":"Sukurti prietaisą",
            "ERROR_ADD_GROUP_NO_TYPE":"Naujam tipui nebuvo parinktas tipas.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Patikrinkite prisijungimo duomenis",
            "GENERAL_REFESHED":"Atnaujintas",
            "OPTIONS_SUPPRESS_WARNINGS":"Slopinti įspėjimus",
            "LOGIN_FAILED_GATEWAY_BUSY":"Tinklų sąsaja apkrauta. Pamėginkite iš naujo.",
            "DESC_EMAIL":"Siųsti el. laišką pagalbos centrui",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"„Visada atidaryta“ išjungta",
            "CLEANING_PORTS_CONTENT":"Ruošiamasi pridėti",
            "DESC_HOME_ACTORS":"Suprogramuoti ir administruoti prietaisus",
            "ERROR_TIMEOUT":"Sujungimo klaida",
            "CREATE_USER_TITLE":"Pridėti vartotoją",
            "ERROR_DELETE_ADMIN_CONTENT":"Administratoriaus negalima ištrinti",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Sparčioji prieiga",
            "ADD_SCENARIO_NAME":"Vardas",
            "HIST":"Istorija",
            "DESC_RESET_LOGIN_SUBMIT":"Patvirtinti ištrynimą",
            "POPUP_WARNING":"DĖMESIO",
            "REMOVE_GROUP_PROCESS":"Prietaisas ištrinamas",
            "POPUP_LOGIN_PROCESS":"Prisiregistruoti",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Laukite...",
            "DESC_DEFAULT_GW_SUBMIT":"Perimti nustatymą",
            "DESC_CHANGE_PASSWORD_RETYPE":"Pakartoti įvestį",
            "LOAD_USERS_CONTENT":"Iš tinklų sąsajos įkeliami visi vartotojai.\nŠis procesas gali užtrukti kelias sekundes.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Jei tinklų sąsajai aktyvinta sparčioji prieiga, priklausomai nuo galimybių, taikomoji programa prisijungia automatiškai",
            "GATE_OTHER":"Kiti prietaisai",
            "CHANGE_PWD_USER_INVALID":"Klaida",
            "CHANNEL_LIGHT":"Apšvietimas",
            "LOGIN_TITLE":"Prisiregistruoti",
            "CHANNEL_HALF":"Dalinis atidarymas",
            "GATEWAY_SCREEN_ADD_HELP":"Norėdami pridėti tinklų sąsają, pasirinkite +simbolį.",
            "ERROR_TIMEOUT_CONTENT":"Laiko perviršis ryšio su tinklų sąsaja metu",
            "ERROR_NO_PORTS_LEARNED":"Pridėti negalima",
            "OPTIONS_SUPPRESS_INFOS":"Slopinti nurodymus",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Klaida",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatinis režimas",
            "GENERAL_DELETE":"Ištrinti",
            "GENERAL_PASSWORD":"Slaptažodis",
            "STATE_COLLECTING_CONTENT":"Užklausiama prietaisų būsenos",
            "ERROR_REMOVE_USER_CONTENT":"Nepavyko ištrinti naudotojo",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Klaida",
            "ACTORS_ADD_HELP":"Norėdami pridėti prietaisą, pasirinkite +simbolį.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Esate įsitikinę, kad norite ištrinti prietaisą?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Laukite...",
            "GENERAL_YES":"taip",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Prieš pridėdami prietaisą, suprogramuokite bent vieną kanalą",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Vardo nebuvo galima pakeisti",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Taikomoji programa dar nerado tinklų sąsajos.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentifikuoti nepavyko",
            "DESC_MANAGE_POPUPS_INFOS":"Slopinti iššokančią informaciją",
            "GATE_PILOMAT_POLLER":"Stulpelis",
            "DESC_CHANNELS_STATE":"Galinčių duoti atsaką prietaisų būsena",
            "DESC_GWSCREEN_REFRESH":"Tinklų sąsajų sąrašo atnaujinimas",
            "POPUP_SCENARIO_DISPATCHING":"Scenarijus vykdomas",
            "ERROR_PORT_UNREACHABLE":"Nesėkmingai",
            "POPUP_GATEWAY_FOUND_CONTENT":"Buvo pridėtos šios tinklų sąsajos:",
            "WIFI_STATE_SECURITY_MISMATCH":"WLAN kodavimo būdas nepalaikomas",
            "LOGOUT_NAMED":"Išsiregistruoti",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Atidaryti duomenų apsaugos sąlygas",
            "ERROR_NO_GW_CONTENT":"Vietiniame tinkle nebuvo galima rasti Hörmann tinklų sąsajos.\nKitas tinklų sąsajas pridėkite per +ženklą",
            "DESC_EDIT_USERS_ADD":"Pridėti vartotoją",
            "ERROR_NO_PORT_FOUND":"Prievadas nerastas",
            "GATE_SLIDING_GATE":"Stumdomieji vartai",
            "DESC_CHANNELS_BUTTONS":"Prietaiso valdymo elementai",
            "DRIVE_MESSAGE_EXTENDED":"išstumta",
            "WIFI_SELECTED_NETWORK":"Vardas",
            "ERROR_ADD_GROUP_NO_NAME":"Nebuvo įvestas naujo prietaiso pavadinimas.",
            "DESC_HELP":"Pagalbinė funkcija",
            "CHANGE_PWD_NEW_PASSWORD":"Naujas slaptažodis",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Perimti naują slaptažodį",
            "DESC_CHANGE_PASSWORD_PWD":"Naujo slaptažodžio įvedimas",
            "ERROR_EDIT_ADMIN_CONTENT":"Negalima redaguoti administratoriaus",
            "CHANGE_GW_NAME_NAME_INVALID":"Nesėkmingai",
            "STATE_COLLECTING_FAILED":"Klaida",
            "GENERAL_ADD":"Pridėti",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"Įvestys \"Slaptažodis\" ir \"Pakartoti slaptažodį\" turi būti vienodos.",
            "WIFI_SETTINGS":"WLAN nustatymai",
            "LEARN_PORTS_TITLE":"Pridėti prietaisą",
            "ERROR_CHANGE_USERNAME":"Nesėkmingai",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Kelio užtvara",
            "ERROR_INVALID_GATEWAY_CONTENT":"Nebuvo galima užmegzti ryšio su tinklų sąsaja. Patikrinkite pagrindinio kompiuterio vardą.",
            "DESC_EDIT_USERS_EDIT":"Ištrinti naudotoją",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Prietaiso pavadinimas turi būti iš 2–20 simbolių.",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Sparčioji prieiga negalima",
            "CHANNEL_UP":"Atidaryti",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"„Visada atidaryta“ įjungta",
            "PORTAL_VALIDATION_FAILED":"Nesėkmingai",
            "DESC_RESET_LOGIN_CANCEL":"Nutraukti veiksmą",
            "CHANGE_PWD_SETTING_PASSWORD":"Perimti",
            "LOADING_GROUPS_TITLE":"Įkeliu",
            "DESC_DEFAULT_GW_CANCEL":"Nutraukti veiksmą",
            "DESC_SET_RIGHTS_SAVE":"Perimti pakeitimus",
            "REMOVING_PROCESS":"Ištrinti",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Tinklų sąsaja nepasiekiama",
            "CONFIRM_DELETE_TITLE":"Ištrinti tinklų sąsają",
            "SCENARIOS_ADD_HELP":"Norėdami pridėti scenarijų, pasirinkite +simbolį.",
            "LOGOUT":"Išsiregistruoti",
            "DESC_ACTORS_BACK":"Atgal į pagrindinį meniu",
            "ERROR_ADAPTER_BUSY_CONTENT":"Komandos nebuvo galima įvykdyti.\n Tinklų sąsaja apkrauta.",
            "DESC_WIFI_NETWORK_SCAN":"Ieškoti tinklų",
            "DRIVE_MESSAGE_HALF":"Iš dalies atidaryti",
            "DESC_SCENARIOS_ADD":"Sukurti scenarijų",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Ryšio su tinklų sąsaja užmegzti nepavyko",
            "SAVING_USER_RIGHTS":"Išsaugoju",
            "DESC_GWSCREEN_PORTAL":"Portalo duomenų įvedimas",
            "GATE_JACK":"Radijo ryšiu valdomas kištukinis lizdas",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Ar esate tame pačiame tinkle, kaip ir Jūsų tinklų sąsaja?",
            "GATE_DOOR":"Durys",
            "POPUP_PORTAL_UNAVAILABLE":"Portalo serverio nebuvo galima pasiekti",
            "DESC_SET_RIGHTS_BACK":"Atgal prie naudotojų",
            "GATE_SMARTKEY":"Durų spynos pavara",
            "POPUP_GATEWAY_FOUND_TITILE":"Paieškos procesas baigtas",
            "WIFI_LOADING_DATA_TITLE":"Įkeliu",
            "GENERAL_PORTS":"Kanalai",
            "DESC_SCENARIOS_EDIT":"Administruoti arba ištrinti scenarijus",
            "OPTIONS_LEARNED_PORTS":"Suprogramuoti kanalai:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Aš sutinku su duomenų apsaugos sąlygomis.",
            "DESC_EDIT_USERS_SET_RIGHTS":"Parinkti naudotoją, norint pakeisti jo prieigos teises",
            "DRIVE_MESSAGE_HALF_MOVING":"Iš dalies atidaryti / judantys",
            "PORTAL_SET_ID_DIALOG":"Portalo nustatymai",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Nėra atskaitos taško",
            "POPUP_SETTING_STATE":"Laukite...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Nepavyko pakeisti naudotojo vardo",
            "GROUP_REQUESTABLE":"Prietaisas gali duoti atsaką",
            "LOADING_STATES_TITLE":"Įkeliu",
            "DESC_HOME_USERS":"Administruoti vartotojus",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Slaptažodis turi būti iš 4–20 simbolių",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Slaptažodis perimamas",
            "POPUP_GATE_OUT_OF_VIEW":"nematant vartų, automatinę vartų sistemą galima valdyti tik tada, kai, be serijinio jėgos ribotuvo, vartuose papildomai sumontuotas šviesos barjeras.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Pasirinkite, ar iššokantys pranešimai turi būti rodomi, ar slopinami",
            "CHANNEL_IMPULS":"Impulsas",
            "PORTAL_VALIDATION_SUCCEEDED":"Įgaliota",
            "DRIVE_MESSAGE_LOCKED":"užrakintos",
            "CHANNEL_DOWN":"Uždaryti",
            "POPUP_INET_SPEED_LOW":"Šiai taikomajai programai Jūsų duomenų perdavimo junties nepakanka",
            "CHANGE_PWD_FAILED_CONTENT":"Nepavyko pakeisti slaptažodžio",
            "GENERAL_GROUP_TYPE":"Prietaiso tipas",
            "CHANNEL_WALK":"Varstoma sąvara",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horizontaliai judantys garažo vartai",
            "POPUP_AGREEMENT_CONTENT":"Prieš naudodami taikomąją programą, sutikite su duomenų apsaugos / naudojimo sąlygomis",
            "INFO":"Informacija",
            "LOADING_GROUPS_CONTENT":"Įkeliu prietaisus",
            "GATE_PILOMAT_REIFENKILLER":"Padangų pradūrikliai",
            "GATE_PILOMAT_HUBBALKEN":"Pakeliamieji užkardai",
            "GENERAL_RETYPE":"Pakartoti slaptažodį",
            "DESC_OTIONS_BACK":"Atgal į pagrindinį meniu",
            "DESC_SET_RIGHTS":"Parinkti prietaisą, kad naudotojui būtų suteiktos prieigos teisės",
            "WIFI_SCANNING_TITLE":"Paieška",
            "WIFI_STATE_CONNECTION_FAILURE":"Užmegzti ryšio nepavyko",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Naudotojo vardas turi būti iš 2–20 simbolių",
            "REMOVE_PORTS":"Ištrinti",
            "GENERAL_ON":"Įjungta",
            "DESC_CHANGE_PASSWORD_CANCEL":"Nutraukti veiksmą",
            "LEARNING_PROCESS_CONTENT":"Laukite...",
            "LOGIN_FAILED_UNKNOWN":"Iškilo netikėta klaida",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Administratoriaus naudotojo teisių pakeisti negalima"
         };
         return _loc1_;
      }
   }
}
