package
{
   import mx.resources.ResourceBundle;
   
   public class lv_LV$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function lv_LV$LocalizedStrings_properties()
      {
         super("lv_LV","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Aizslēgt",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Ievadiet Hörmann portāla piekļuves datus",
            "ERROR_DELETE_ADMIN":"Nav iespējams",
            "LOGIN_SHOULD_SAVE":"Saglabāt datus",
            "LOAD_USERS_TITLE":"Lūdzu, gaidiet",
            "CHANGE_GW_NAME_SETTING":"Pārņemt",
            "CONFIRM_DELETE_GROUP":"Izdzēst ierīci",
            "GENERAL_NO":"Nē",
            "DESC_GWSCREEN_ADD":"Pievienot lokālu vārteju",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nav ievilkts",
            "WIFI_PASSPHRASE":"Parole",
            "CHANNEL_ON":"Ieslēgta",
            "SCENARIOS":"Scenāriji",
            "ERROR_SET_ADMIN_RIGHTS":"Nav iespējams",
            "DESC_DEFAULT_GW_SAVE":"Iestatīt ātro piekļuvi aktuālajai vārtejai",
            "POPUP_INFO":"NORĀDE",
            "DRIVE_MESSAGE_ERROR":"UZMANĪBU! Kļūda",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Tīkla nosaukums",
            "EMAIL_BODY":"Savus jautājumus Jūs mums varat sūtīt pa e-pastu. Šim mērķim Jums ir pieejama arī mūsu izveidotā biežāk uzdoto jautājumu funkcija.\n\nIhr BiSecur-Home atbalsta komanda",
            "CONFIRM_DELETE_USER":"Izdzēst lietotāju",
            "DESC_CHANNELS_BACK":"Atpakaļ uz ierīču sarakstu",
            "CHANGE_PWD_FIRST_START":"Drošības apsvērumu dēļ pēc pirmreizējās reģistrācijas nomainiet savas paroles rūpnīcas iestatījumu",
            "GENERAL_DEFAULT_GATEWAY":"Ātrā piekļuve",
            "CHANGE_PWD_PASSWORD_INVALID":"Kļūda",
            "ERROR_NO_GW_TITLE":"Nav vārteju",
            "POPUP_SETTING_STATE_CONTENT":"Notiek komandas izpilde",
            "WIFI_LOADING_DATA_CONTENT":"Notiek WLAN datu ielāde",
            "OPTIONS_RESET_LOGIN_DATA":"Izdzēst saglabātos pieteikšanās datus",
            "EDIT_USER_TITLE":"Apstrādāt lietotāju",
            "DESC_HOME_PREFERENCES":"Mainīt vārtejas un lietotnes iestatījumus",
            "WIFI_ACTIVE_STATE":"WLAN statuss",
            "STATE_COLLECTING":"Ielādēt",
            "ADD_SCENARIO":"Pievienot scenāriju",
            "STATE_COLLECTING_FAILED_CONTENT":"Statuss netika ielādēts",
            "GATE_SWING_GATE_SINGLE":"Vienvērtnes veramie vārti",
            "ACTORS":"ierīces",
            "POPUP_AGREEMENT":"Lietošana / Datu aizsardzība",
            "CHANNEL_OPEN_DOOR":"Atvērt",
            "DESC_ACTORS_REFRESH":"Aktualizēt statusu",
            "GENERAL_OFF":"Izslēgts",
            "OPTIONS_HELP":"Tiešsaistes palīdzība",
            "COPY_PORTS_CONTENT":"Pārslēdziet raidītāju pārsūtīšanas režīmā, skat. instrukciju. Izvēlieties kanālu, kas pieņems sūtīto kodu.",
            "GENERAL_SELECT":"Lūdzu, izvēlēties...",
            "ERROR_ADAPTER_BUSY":"Kļūda",
            "INFO_BOX_INFOS":"Vispārīgi",
            "GATE_LIGHT":"Gaisma",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Atvērt lietošanas noteikumus",
            "DESC_MANAGE_POPUPS_WARNINGS":"Nerādīt uznirstošos brīdinājuma paziņojumus",
            "MAX_USERSS_REACHED_CONTENT":"Sasniegts maksimālais lietotāju skaits.",
            "GENERAL_REMOVE":"Izņemt",
            "OPTIONS":"Iestatījumi",
            "DESC_HOME_SCENARIOS":"Sastādīt un pārvaldīt scenārijus",
            "CHANNEL_OFF":"Izslēgta",
            "GENERAL_PORTAL_ID":"Ierīces ID",
            "EDIT_GROUP":"Apstrādāt ierīci",
            "ERROR_LERANIN_PORT_CONTENT":"Vēlamā kanāla ieprogrammēšana nav izdevusies",
            "ERROR_CONNECTION_CLOSED":"Kļūda",
            "CHANNEL_ON_OFF":"Iesl. /izsl.",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Nosaukums",
            "OPTIONS_EDIT_USERS":"Pārvaldīt lietotājus",
            "LOADING_STATES_CONTENT":"Notiek aktuālā statusa pieprasījums.\nLūdzu, uzgaidiet...",
            "LERAN_PORTS_CONTENT":"Pārslēdziet ierīci ieprogrammēšanas režīmā, skat. instrukciju. Izvēlieties kanālu, ko nepieciešams ieprogrammēt.",
            "REMOVE_PORTS_CONTENT":"Izvēlieties kanālus, kurus vēlaties izdzēst.",
            "GATE_SWING_GATE_DOUBLE":"Divvērtņu veramie vārti",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Pārbaudiet, vai esat ievadījis savus portāla datus vai arī pievienojis lokālu vārteju.",
            "CHANNEL_SINK":"Nolaist",
            "OPTIONS_EDIT_USERS_TITLE":"Lietotājs",
            "MAX_PORTS_REACHED_CONTENT":"Maksimālais kanālu skaits aizņemts",
            "MAX_PORTS_REACHED":"Nav iespējams",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Ar pieprasīto ierīci nebija iespējams sazināties",
            "PORTAL_AUTHENTICATION_FAILED":"Nav izdevies",
            "NOTIFICATION_CENTER":"Paziņojumi",
            "LEARNING_PROCESS":"Ieprogrammēt",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Lietotāja vārdam ir jāsastāv no 2 - 20 zīmēm",
            "WIFI_STATE_CONNECTED":"Savienots",
            "COPY_PORTS":"Pārsūtīt no tālvadības pults",
            "POPUP_SEARCH_CONTENT":"Hörmann vārteju meklēšana \n\nŠis process var aizņemt dažas sekundes.",
            "DESC_MANAGE_POPUPS_CANCEL":"Pārtraukt darbību",
            "DESC_WIFI_PASSWORD":"Parole",
            "DESC_WIFI_SAVE":"Saglabāt",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Apstādināšana aktīva",
            "SELECT_GATEWAY":"Vārtejas",
            "CLEANING_PORTS":"Pievienot ierīci",
            "WIFI_STATE_BUSY":"Notiek savienojuma izveide",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Ievadītā parole ir nepareiza",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Mainīt vārtejas nosaukumu",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Notiek vārda pārņemšana",
            "DESC_ACTORS_EDIT":"Pārvaldīt vai izdzēst ierīces",
            "DESC_WIFI_STATE":"Savienojuma statuss",
            "ERROR_REMOVE_USER":"Nav izdevies.",
            "LANG_TAG":"LV",
            "DESC_MANAGE_POPUPS_SUBMIT":"Pārņemt iestatījumu",
            "HOME_TITLE":"Galvenā lapa",
            "GENERAL_USERNAME":"Lietotājvārds",
            "DRIVE_MESSAGE_OPENED":"Atvērti",
            "CONFIRM_DELETE":"Vai patiešām vēlaties dzēst vārteju?",
            "DRIVE_MESSAGE_CLOSED":"Aizvērti",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Nebija iespējams sazināties ar portāla serveri",
            "REMOVING_PROCESS_CONTENT":"Kanāls tiek izdzēsts",
            "DESC_EDIT_USERS_BACK":"Atpakaļ uz iestatījumiem",
            "ERROR_NO_GROUP_FOUND":"Ierīce nav atrasta",
            "ERROR_INVALID_GATEWAY":"Nav atrasta neviena vārteja",
            "DESC_WIFI_BACK":"Atpakaļ uz iestatījumiem",
            "MAX_USERS_REACHED":"Nav iespējams",
            "DESC_CHANGE_PASSWORD_USERNAME":"Lietotājvārds",
            "POPUP_AGREEMENT_ACCEPT_USE":"Es piekrītu lietošanas noteikumiem",
            "ERROR_LERNING_PORT":"Nav izdevies",
            "POPUP_ADD_GATEWAY_CONTENT":"Ierakstīt IP adresi:",
            "ERROR_ADD_GROUP":"Kļūda",
            "DRIVE_MESSAGE_NO_DATA":"Dati nav pieejami",
            "CHANGE_PWD_FAILED":"Nav izdevies.",
            "SAVING_USER_RIGHTS_CONTENT":"Norit lietotāja tiesību saglabāšana",
            "DRIVE_MESSAGE_UNLOCKED":"Nav aizslēgts",
            "GENERAL_SAVE":"Saglabāt",
            "INFO_BOX_FAQ":"Biežāk uzdotie jautājumi",
            "GENERAL_CONNNECT":"Savienot",
            "GATE_SECTIONAL_DOOR":"Vertikālas pārvirzes garāžas vārti",
            "OPTIONS_CHANGE_PASSWORD":"Mainīt paroli",
            "CHANNEL":"Vadība",
            "CHANGE_GW_NAME_CONTENT":"Vārtejas nosaukums",
            "DRIVE_MESSAGE_RETRACTED":"ievilkts",
            "DESC_ADDGWSCREEN_BACK":"Atpakaļ uz vārteju pārskatu",
            "EMAIL_SUBJECT":"Atbalsts",
            "ERROR_EDIT_ADMIN":"Nav iespējams",
            "OPTIONS_SET_USER_RIGHTS":"Lietotāja tiesības",
            "CHANGE_GW_NAME_ERROR":"Nav izdevies",
            "CHANNEL_LIFT":"Pacelt",
            "LOGIN_FAILED_TITLE":"Nav izdevies",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Apstiprinot pietiekšanās datu dzēšanu ar OK, izvēloties vārteju, parole ir jāievada no jauna",
            "CHANNEL_UNLOCK":"Atslēgt",
            "GENERAL_PORTAL_SERVER":"Portāla serveris",
            "DESC_SCENARIOS_BACK":"Atpakaļ uz galveno izvēlni",
            "CHANGE_PWD_USERNAME":"Lietotājs:",
            "POPUP_GATE_NOT_RESPONSABLE":"Lietotne šo komandu ierīcei var nosūtīt, bet nespēj identificēt ierīces aktuālo stāvokli.",
            "DESC_GW_NAME":"Vārtejas nosaukums",
            "GATE_BARRIER":"barjera",
            "LEARN_PORTS":"Ieprogrammēt radio kodu",
            "GENERAL_BACK":"Atpakaļ",
            "DESC_GWSCREEN_EDIT":"Dzēšanai saglabātās vārtejas",
            "OPTIONS_MANAGE_POPUPS":"Pārvaldīt uznirstošos paziņojumus",
            "POPUP_LOGIN_PROCESS_CONTENT":"Lūdzu, uzgaidiet...",
            "CONFIRM_DELETE_USER_CONTENT":"Vai patiešām vēlaties dzēs lietotāju?",
            "DESC_MENU":"Izvēlne",
            "LOGIN_FAILED_WRONG_DATA":"Ievadītais lietotājvārds vai parole ir nepareiza",
            "GENERAL_CANCEL":"Pārtraukt",
            "ADD_GROUP":"Pievienot ierīci",
            "WIFI_STATE_AP_NOT_FOUND":"Tīkls nav atrasts",
            "WIFI_STATE_NOT_CONNECTED":"Nav savienots",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Jūsu ierīces lietošana caur portālu ir aktivizēta!",
            "POPUP_ADD_GATEWAY":"Pievienot vārteju",
            "GENERAL_NEXT":"Tālāk",
            "POPUP_SUPPRESS":"Uznirstošo logu vairs neatvērt",
            "POPUP_SEARCH_TITLE":"Meklēt...",
            "WIFI_SCANNING_CONTENT":"Meklēt redzamos WLAN tīklus",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Nav atrasta neviena vārteja",
            "DESC_ACTORS_ADD":"Izveidot ierīci",
            "ERROR_ADD_GROUP_NO_TYPE":"Jaunajai ierīcei nav izvēlēts neviens tips.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Pārbaudiet pieteikšanās datus",
            "GENERAL_REFESHED":"Aktualizēts",
            "OPTIONS_SUPPRESS_WARNINGS":"Nerādīt brīdinājumus",
            "LOGIN_FAILED_GATEWAY_BUSY":"Vārteja ir noslogota. Pamēģiniet vēlreiz.",
            "DESC_EMAIL":"Nosūtīt e-pastu atbalsta daļai",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Pastāvīgi atvērts Izsl.",
            "CLEANING_PORTS_CONTENT":"Norit pievienošanas sagatavošanās process",
            "DESC_HOME_ACTORS":"Ieprogrammēt un pārvaldīt ierīces",
            "ERROR_TIMEOUT":"Savienojuma kļūda",
            "CREATE_USER_TITLE":"Pievienot lietotāju",
            "ERROR_DELETE_ADMIN_CONTENT":"Administratoru nav iespējams izdzēst",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Ātrā piekļuve",
            "ADD_SCENARIO_NAME":"Vārds, uzvārds",
            "HIST":"Vēsture",
            "DESC_RESET_LOGIN_SUBMIT":"Apstiprināt dzēšanu",
            "POPUP_WARNING":"Uzmanību!",
            "REMOVE_GROUP_PROCESS":"Ierīce tiek izdzēsta",
            "POPUP_LOGIN_PROCESS":"Pieteikties",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Lūdzu, uzgaidiet...",
            "DESC_DEFAULT_GW_SUBMIT":"Pārņemt iestatījumu",
            "DESC_CHANGE_PASSWORD_RETYPE":"Ievadīt vēlreiz",
            "LOAD_USERS_CONTENT":"Notiek visu lietotāju ielāde no vārtejas.\nŠis process var aizņemt dažas sekundes.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Ja kādai no vārtejām ir aktivizēta ātrā piekļuve, lietotne iespēju robežās piesakās sistēmā automātiski.",
            "GATE_OTHER":"Citas ierīces",
            "CHANGE_PWD_USER_INVALID":"Kļūda",
            "CHANNEL_LIGHT":"Gaisma",
            "LOGIN_TITLE":"Pieteikties",
            "CHANNEL_HALF":"Daļējs vārtu atvērums",
            "GATEWAY_SCREEN_ADD_HELP":"Lai pievienotu vārteju, izvēlieties +simbolu.",
            "ERROR_TIMEOUT_CONTENT":"Pārsniegts laiks, notiekot datu apmaiņai ar vārteju",
            "ERROR_NO_PORTS_LEARNED":"Pievienošana nav iespējama",
            "OPTIONS_SUPPRESS_INFOS":"Nerādīt norādes",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Kļūda",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automātiskās darbības režīms",
            "GENERAL_DELETE":"Dzēst",
            "GENERAL_PASSWORD":"Parole",
            "STATE_COLLECTING_CONTENT":"Notiek ierīču statusa pieprasījums",
            "ERROR_REMOVE_USER_CONTENT":"Lietotāju nevarēja izdzēst.",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Kļūda",
            "ACTORS_ADD_HELP":"Lai pievienotu ierīci, izvēlieties +simbolu.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Vai patiešām vēlaties dzēst ierīci?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Lūdzu, uzgaidiet...",
            "GENERAL_YES":"Jā",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Pirms ierīces pievienošanas ieprogrammēt vismaz vienu kanālu",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Nosaukumu nebija iespējams nomainīt",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Lietotne vēl nav atradusi nevienu vārteju.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentifikācija nav izdevusies",
            "DESC_MANAGE_POPUPS_INFOS":"Nerādīt uznirstošos informatīvos paziņojumus",
            "GATE_PILOMAT_POLLER":"Bollards",
            "DESC_CHANNELS_STATE":"Ierīces ar atbildes signāla raidīšanas funkciju statuss",
            "DESC_GWSCREEN_REFRESH":"Vārteju saraksta aktualizēšana",
            "POPUP_SCENARIO_DISPATCHING":"Notiek scenārija izpilde",
            "ERROR_PORT_UNREACHABLE":"Nav izdevies",
            "POPUP_GATEWAY_FOUND_CONTENT":"Tika pievienotas šādas vārtejas:",
            "WIFI_STATE_SECURITY_MISMATCH":"WLAN šifrēšanas veids netiek atbalstīts",
            "LOGOUT_NAMED":"atteikties",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Atvērt datu aizsardzības noteikumus",
            "ERROR_NO_GW_CONTENT":"Lokālajā tīklā nebija iespējams atrast nevienu Hörmann vārteju.\nPievienot citas vārtejas, izmantojot +simbolu",
            "DESC_EDIT_USERS_ADD":"Pievienot lietotāju",
            "ERROR_NO_PORT_FOUND":"Ports nav atrasts",
            "GATE_SLIDING_GATE":"Bīdāmie vārti",
            "DESC_CHANNELS_BUTTONS":"Ierīces vadības elementi",
            "DRIVE_MESSAGE_EXTENDED":"izbīdīts",
            "WIFI_SELECTED_NETWORK":"Vārds, uzvārds",
            "ERROR_ADD_GROUP_NO_NAME":"Jaunajai ierīcei nav ievadīts neviens nosaukums.",
            "DESC_HELP":"Palīgfunkcija",
            "CHANGE_PWD_NEW_PASSWORD":"Jaunā parole",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Pārņemt jauno paroli",
            "DESC_CHANGE_PASSWORD_PWD":"Jaunas paroles ievadīšana",
            "ERROR_EDIT_ADMIN_CONTENT":"Administratoru nevar apstrādāt.",
            "CHANGE_GW_NAME_NAME_INVALID":"Nav izdevies",
            "STATE_COLLECTING_FAILED":"Kļūda",
            "GENERAL_ADD":"Pievienot",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"Lauciņos \"Parole\" un \"Atkārtot paroli\" ievadītajai informācijai ir jābūt identiskai.",
            "WIFI_SETTINGS":"WLAN iestatījumi",
            "LEARN_PORTS_TITLE":"Pievienot ierīci",
            "ERROR_CHANGE_USERNAME":"Nav izdevies.",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Ceļa bloķētājs",
            "ERROR_INVALID_GATEWAY_CONTENT":"Nebija iespējams izveidot savienojumu ar vārteju. Lūdzu, pārbaudiet saimniekdatora nosaukumu.",
            "DESC_EDIT_USERS_EDIT":"Izdzēst lietotāju",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Ierīces nosaukumam ir jāsastāv no 2 - 20 zīmēm",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Ātrā piekļuve nav iespējama",
            "CHANNEL_UP":"Vārtu atvēršana",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Pastāvīgi atvērts Iesl.",
            "PORTAL_VALIDATION_FAILED":"Nav izdevies",
            "DESC_RESET_LOGIN_CANCEL":"Pārtraukt darbību",
            "CHANGE_PWD_SETTING_PASSWORD":"Pārņemt",
            "LOADING_GROUPS_TITLE":"Ielādēt",
            "DESC_DEFAULT_GW_CANCEL":"Pārtraukt darbību",
            "DESC_SET_RIGHTS_SAVE":"Pārņemt izmaiņas",
            "REMOVING_PROCESS":"Dzēst",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Vārteja nav sasniedzama",
            "CONFIRM_DELETE_TITLE":"Dzēst vārteju",
            "SCENARIOS_ADD_HELP":"Lai pievienotu scenāriju, izvēlieties +simbolu.",
            "LOGOUT":"Atteikties",
            "DESC_ACTORS_BACK":"Atpakaļ uz galveno izvēlni",
            "ERROR_ADAPTER_BUSY_CONTENT":"Komandu nebija iespējams izpildīt.\n Vārteja ir noslogota.",
            "DESC_WIFI_NETWORK_SCAN":"Meklēt tīklus",
            "DRIVE_MESSAGE_HALF":"Daļēji atvērti",
            "DESC_SCENARIOS_ADD":"Sastādīt scenāriju",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Datu apmaiņa ar vārteju nav izdevusies",
            "SAVING_USER_RIGHTS":"Saglabāt",
            "DESC_GWSCREEN_PORTAL":"Portāla datu ievade",
            "GATE_JACK":"Tālvadības kontaktligzda",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Vai atrodaties tajā pašā tīklā, kurā atrodas arī vārteja?",
            "GATE_DOOR":"Durvis",
            "POPUP_PORTAL_UNAVAILABLE":"Nebija iespējams sazināties ar portāla serveri",
            "DESC_SET_RIGHTS_BACK":"Atpakaļ uz lietotājiem",
            "GATE_SMARTKEY":"Durvju atslēgu piedziņa",
            "POPUP_GATEWAY_FOUND_TITILE":"Meklēšana pabeigta",
            "WIFI_LOADING_DATA_TITLE":"Ielādēt",
            "GENERAL_PORTS":"Kanāli",
            "DESC_SCENARIOS_EDIT":"Pārvaldīt vai izdzēst scenārijus",
            "OPTIONS_LEARNED_PORTS":"Ieprogrammētie kanāli:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Es piekrītu datu aizsardzības noteikumiem",
            "DESC_EDIT_USERS_SET_RIGHTS":"Izvēlēties lietotāju, lai izmainītu tā piekļuves tiesības",
            "DRIVE_MESSAGE_HALF_MOVING":"Daļējs atvērtu atvērums / vārti kustībā",
            "PORTAL_SET_ID_DIALOG":"Portāla iestatījumi",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Nav atiestates punkta.",
            "POPUP_SETTING_STATE":"Lūdzu, uzgaidiet...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Lietotāju nevarēja nomainīt.",
            "GROUP_REQUESTABLE":"Ierīce spēj raidīt atbildes signālu",
            "LOADING_STATES_TITLE":"Ielādēt",
            "DESC_HOME_USERS":"Pārvaldīt lietotājus",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Parolei ir jāsastāv no 4 - 20 zīmēm",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Notiek paroles pārņemšana",
            "POPUP_GATE_OUT_OF_VIEW":"Automātiskās vārtu iekārtas vadības ierīces uzstādīšana vietā, no kuras vārti nav redzami, ir atļauta tikai tad, ja Jūs papildus sērijveidā pieejamajam spēka ierobežotājam pie vārtiem esat uzstādījis arī fotoelementu.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Izvēlieties, vai uznirstošie paziņojumi tiks parādīti vai noslēpti",
            "CHANNEL_IMPULS":"Impulss",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorizēts",
            "DRIVE_MESSAGE_LOCKED":"Aizslēgts",
            "CHANNEL_DOWN":"Vārtu aizvēršana",
            "POPUP_INET_SPEED_LOW":"Jūsu datu savienojums šai lietojumprogrammai nav pietiekams",
            "CHANGE_PWD_FAILED_CONTENT":"Paroli nevarēja nomainīt.",
            "GENERAL_GROUP_TYPE":"Ierīces modelis",
            "CHANNEL_WALK":"Ieiešanas/iziešanas vērtne",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horziontālas pārvirzes garāžas vārti",
            "POPUP_AGREEMENT_CONTENT":"Pirms lietotnes izmantošanas piekrītiet datu aizsardzības / lietošanas noteikumiem",
            "INFO":"Informācija",
            "LOADING_GROUPS_CONTENT":"Ielādēt ierīces",
            "GATE_PILOMAT_REIFENKILLER":"Riepu dūrējs",
            "GATE_PILOMAT_HUBBALKEN":"Paceļamā barjera",
            "GENERAL_RETYPE":"Atkārtot paroli",
            "DESC_OTIONS_BACK":"Atpakaļ uz galveno izvēlni",
            "DESC_SET_RIGHTS":"Izvēlēties ierīci, lai lietotājam garantētu piekļuves tiesības",
            "WIFI_SCANNING_TITLE":"Meklēt",
            "WIFI_STATE_CONNECTION_FAILURE":"Savienojuma izveide nav izdevusies",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Lietotāja vārdam ir jāsastāv no 2 - 20 zīmēm",
            "REMOVE_PORTS":"Dzēst",
            "GENERAL_ON":"Ieslēgts",
            "DESC_CHANGE_PASSWORD_CANCEL":"Pārtraukt darbību",
            "LEARNING_PROCESS_CONTENT":"Lūdzu, uzgaidiet...",
            "LOGIN_FAILED_UNKNOWN":"Radusies negaidīta kļūda",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Administratora lietotāja tiesības nav iespējams izmainīt"
         };
         return _loc1_;
      }
   }
}
