package
{
   import mx.resources.ResourceBundle;
   
   public class nl_NL$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function nl_NL$LocalizedStrings_properties()
      {
         super("nl_NL","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Vergrendelen",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Vul de toegangsgegevens voor het Hörmann-portaal in",
            "ERROR_DELETE_ADMIN":"Niet mogelijk",
            "LOGIN_SHOULD_SAVE":"Gegevens opslaan",
            "LOAD_USERS_TITLE":"Wachten a.u.b.",
            "CHANGE_GW_NAME_SETTING":"Overnemen",
            "CONFIRM_DELETE_GROUP":"Toestel wissen",
            "GENERAL_NO":"Nee",
            "DESC_GWSCREEN_ADD":"Lokale gateways toevoegen",
            "DRIVE_MESSAGE_NOT_RETRACTED":"niet ingeschoven",
            "WIFI_PASSPHRASE":"Wachtwoord",
            "CHANNEL_ON":"Aan",
            "SCENARIOS":"Scenario\'s",
            "ERROR_SET_ADMIN_RIGHTS":"Niet mogelijk",
            "DESC_DEFAULT_GW_SAVE":"Snelle toegang voor actuele gateway inrichten",
            "POPUP_INFO":"Aanwijzing",
            "DRIVE_MESSAGE_ERROR":"LET OP: fout",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/nl/gegevensbescherming",
            "DESC_WIFI_NETWORK_NAME":"Netwerknaam",
            "EMAIL_BODY":"U kunt uw vragen per e-mail naar ons toesturen. Hiervoor staat ook onze FAQ-functie ter beschikking.\n\nUw BiSecur-home support-team",
            "CONFIRM_DELETE_USER":"Gebruiker wissen",
            "DESC_CHANNELS_BACK":"Terug naar de toestellijst",
            "CHANGE_PWD_FIRST_START":"Wijzig de fabrieksinstelling van uw wachtwoord om veiligheidsredenen na de eerste aanmelding",
            "GENERAL_DEFAULT_GATEWAY":"Snelle toegang",
            "CHANGE_PWD_PASSWORD_INVALID":"Fout",
            "ERROR_NO_GW_TITLE":"Geen gateways",
            "POPUP_SETTING_STATE_CONTENT":"Het commando wordt uitgevoerd",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-gegevens worden geladen",
            "OPTIONS_RESET_LOGIN_DATA":"Opgeslagen inloggegevens wissen",
            "EDIT_USER_TITLE":"Gebruiker bewerken",
            "DESC_HOME_PREFERENCES":"Instellingen van gateway en app wijzigen",
            "WIFI_ACTIVE_STATE":"WLAN-status",
            "STATE_COLLECTING":"Laad",
            "ADD_SCENARIO":"Scenario toevoegen",
            "STATE_COLLECTING_FAILED_CONTENT":"Status werd niet geladen",
            "GATE_SWING_GATE_SINGLE":"1-vlg. draaihek",
            "ACTORS":"Toestellen",
            "POPUP_AGREEMENT":"Gebruik / Privacybescherming",
            "CHANNEL_OPEN_DOOR":"Openen",
            "DESC_ACTORS_REFRESH":"Status bijwerken",
            "GENERAL_OFF":"Uitgeschakeld",
            "OPTIONS_HELP":"Online-hulp",
            "COPY_PORTS_CONTENT":"Zet de zender in de overnamemodus, zie handleiding. Selecteer het kanaal dat inregelt.",
            "GENERAL_SELECT":"Selecteren a.u.b.",
            "ERROR_ADAPTER_BUSY":"Fout",
            "INFO_BOX_INFOS":"Algemeen",
            "GATE_LIGHT":"Licht",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Gebruiksvoorwaarden openen",
            "DESC_MANAGE_POPUPS_WARNINGS":"Pop-ups met waarschuwingen onderdrukken",
            "MAX_USERSS_REACHED_CONTENT":"Het maximale aantal gebruikers werd bereikt.",
            "GENERAL_REMOVE":"Verwijderen",
            "OPTIONS":"Instellingen",
            "DESC_HOME_SCENARIOS":"Scenario\'s aanmaken en beheren",
            "CHANNEL_OFF":"Uit",
            "GENERAL_PORTAL_ID":"Toestel-ID",
            "EDIT_GROUP":"Toestel bewerken",
            "ERROR_LERANIN_PORT_CONTENT":"Het inregelen van het gewenste kanaal is mislukt",
            "ERROR_CONNECTION_CLOSED":"Fout",
            "CHANNEL_ON_OFF":"Aan / Uit",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Benaming",
            "OPTIONS_EDIT_USERS":"Gebruiker beheren",
            "LOADING_STATES_CONTENT":"De actuele status wordt opgevraagd.\nWachten a.u.b. ...",
            "LERAN_PORTS_CONTENT":"Zet het toestel in de inregelmodus, zie handleiding. Selecteer het in te regelen kanaal.",
            "REMOVE_PORTS_CONTENT":"Selecteer de kanalen die u wilt wissen.",
            "GATE_SWING_GATE_DOUBLE":"2-vlg. draaihek",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Controleer of u uw portaalgegevens heeft ingevuld of een lokale gateway heeft toegevoegd.",
            "CHANNEL_SINK":"Zakken",
            "OPTIONS_EDIT_USERS_TITLE":"Gebruiker",
            "MAX_PORTS_REACHED_CONTENT":"Maximaal aantal kanalen bezet",
            "MAX_PORTS_REACHED":"Niet mogelijk",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Het opgevraagde toestel kon niet worden bereikt",
            "PORTAL_AUTHENTICATION_FAILED":"Mislukt",
            "NOTIFICATION_CENTER":"Berichten",
            "LEARNING_PROCESS":"Inregelen",
            "CHANGE_PWD_USER_INVALID_CONTENT":"De gebruikersnaam moet bestaan uit 2 - 20 tekens",
            "WIFI_STATE_CONNECTED":"Verbonden",
            "COPY_PORTS":"Van handzender overnemen",
            "POPUP_SEARCH_CONTENT":"Zoek naar Hörmann-gateways \n\nDit proces kan enkele seconden duren.",
            "DESC_MANAGE_POPUPS_CANCEL":"Actie annuleren",
            "DESC_WIFI_PASSWORD":"Wachtwoord",
            "DESC_WIFI_SAVE":"Opslaan",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop actief",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Toestel toevoegen",
            "WIFI_STATE_BUSY":"Verbinding wordt tot stand gebracht",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Het ingevoerde wachtwoord is fout",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Naam van de gateway wijzigen",
            "CHANGE_GW_NAME_SETTING_CONTENT":"De naam wordt overgenomen",
            "DESC_ACTORS_EDIT":"Toestellen inregelen of wissen",
            "DESC_WIFI_STATE":"Verbindingsstatus",
            "ERROR_REMOVE_USER":"Mislukt",
            "LANG_TAG":"NL",
            "DESC_MANAGE_POPUPS_SUBMIT":"Instelling overnemen",
            "HOME_TITLE":"Hoofdpagina",
            "GENERAL_USERNAME":"Gebruikersnaam",
            "DRIVE_MESSAGE_OPENED":"Geopend",
            "CONFIRM_DELETE":"Weet u zeker dat u de gateway wilt wissen?",
            "DRIVE_MESSAGE_CLOSED":"Gesloten",
            "PORTAL_VALIDATION_FAILED_CONTENT":"De portaalserver kon niet worden bereikt",
            "REMOVING_PROCESS_CONTENT":"Het kanaal wordt gewist",
            "DESC_EDIT_USERS_BACK":"Terug naar instellingen",
            "ERROR_NO_GROUP_FOUND":"Toestel niet gevonden",
            "ERROR_INVALID_GATEWAY":"Geen gateway gevonden",
            "DESC_WIFI_BACK":"Terug naar de instellingen",
            "MAX_USERS_REACHED":"Niet mogelijk",
            "DESC_CHANGE_PASSWORD_USERNAME":"Gebruikersnaam",
            "POPUP_AGREEMENT_ACCEPT_USE":"Ik accepteer de gebruiksvoorwaarden",
            "ERROR_LERNING_PORT":"Mislukt",
            "POPUP_ADD_GATEWAY_CONTENT":"IP-adres invoeren:",
            "ERROR_ADD_GROUP":"Fout",
            "DRIVE_MESSAGE_NO_DATA":"Geen gegevens beschikbaar",
            "CHANGE_PWD_FAILED":"Mislukt",
            "SAVING_USER_RIGHTS_CONTENT":"Gebruikersrechten worden opgeslagen",
            "DRIVE_MESSAGE_UNLOCKED":"ontgrendeld",
            "GENERAL_SAVE":"Opslaan",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Verbinden",
            "GATE_SECTIONAL_DOOR":"Verticaal bewegende garagedeur",
            "OPTIONS_CHANGE_PASSWORD":"Wachtwoord wijzigen",
            "CHANNEL":"Bediening",
            "CHANGE_GW_NAME_CONTENT":"Naam van de gateway",
            "DRIVE_MESSAGE_RETRACTED":"ingeschoven",
            "DESC_ADDGWSCREEN_BACK":"Terug naar gateway-overzicht",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Niet mogelijk",
            "OPTIONS_SET_USER_RIGHTS":"Gebruikersrechten",
            "CHANGE_GW_NAME_ERROR":"Mislukt",
            "CHANNEL_LIFT":"Heffen",
            "LOGIN_FAILED_TITLE":"Mislukt",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Wanneer u het wissen van de inloggegevens bevestigt met OK, moet het wachtwoord bij het selecteren van de gateway opnieuw worden ingevoerd",
            "CHANNEL_UNLOCK":"Ontgrendelen",
            "GENERAL_PORTAL_SERVER":"Portaalserver",
            "DESC_SCENARIOS_BACK":"Terug naar het hoofdmenu",
            "CHANGE_PWD_USERNAME":"Gebruiker:",
            "POPUP_GATE_NOT_RESPONSABLE":"De app kan dit commando naar het toestel verzenden, maar herkent de actuele toestand van het toestel niet.",
            "DESC_GW_NAME":"Naam van de gateway",
            "GATE_BARRIER":"slagboom",
            "LEARN_PORTS":"Radiocode inregelen",
            "GENERAL_BACK":"Vorige",
            "DESC_GWSCREEN_EDIT":"Opgeslagen gateways om te wissen",
            "OPTIONS_MANAGE_POPUPS":"Pop-upmeldingen beheren",
            "POPUP_LOGIN_PROCESS_CONTENT":"Wachten a.u.b. ...",
            "CONFIRM_DELETE_USER_CONTENT":"Weet u zeker dat u de gebruiker wilt wissen?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"De ingevoerde gebruikersnaam of het wachtwoord is fout",
            "GENERAL_CANCEL":"Annuleren",
            "ADD_GROUP":"Toestel toevoegen",
            "WIFI_STATE_AP_NOT_FOUND":"Netwerk niet gevonden",
            "WIFI_STATE_NOT_CONNECTED":"Niet verbonden",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Uw bediening via het portaal is geactiveerd!",
            "POPUP_ADD_GATEWAY":"Gateway toevoegen",
            "GENERAL_NEXT":"Volgende",
            "POPUP_SUPPRESS":"Pop-up niet meer openen",
            "POPUP_SEARCH_TITLE":"Zoek...",
            "WIFI_SCANNING_CONTENT":"Zoek naar zichtbare WLAN-netwerken",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Geen gateway gevonden",
            "DESC_ACTORS_ADD":"Toestel aanmaken",
            "ERROR_ADD_GROUP_NO_TYPE":"Er werd geen type voor het nieuwe toestel geselecteerd.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Controleer de inloggegevens",
            "GENERAL_REFESHED":"Bijgewerkt",
            "OPTIONS_SUPPRESS_WARNINGS":"Waarschuwingen onderdrukken",
            "LOGIN_FAILED_GATEWAY_BUSY":"De gateway is overbelast. Probeer het opnieuw.",
            "DESC_EMAIL":"E-mail naar de support sturen",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Permanent Open Uit",
            "CLEANING_PORTS_CONTENT":"Toevoegen wordt voorbereid",
            "DESC_HOME_ACTORS":"Toestellen inregelen en beheren",
            "ERROR_TIMEOUT":"Verbindingsfout",
            "CREATE_USER_TITLE":"Gebruiker toevoegen",
            "ERROR_DELETE_ADMIN_CONTENT":"De beheerder kan niet worden gewist",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Snelle toegang",
            "ADD_SCENARIO_NAME":"Naam",
            "HIST":"Historie",
            "DESC_RESET_LOGIN_SUBMIT":"Wissen bevestigen",
            "POPUP_WARNING":"LET OP",
            "REMOVE_GROUP_PROCESS":"Het toestel wordt gewist",
            "POPUP_LOGIN_PROCESS":"Aanmelden",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Wachten a.u.b. ...",
            "DESC_DEFAULT_GW_SUBMIT":"Instelling overnemen",
            "DESC_CHANGE_PASSWORD_RETYPE":"Invoer herhalen",
            "LOAD_USERS_CONTENT":"Alle gebruikers van de gateway worden geladen.\nDit proces kan enkele seconden duren.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Wanneer de snelle toegang voor een gateway is geactiveerd, logt de app indien mogelijk automatisch in",
            "GATE_OTHER":"Overige toestellen",
            "CHANGE_PWD_USER_INVALID":"Fout",
            "CHANNEL_LIGHT":"Licht",
            "LOGIN_TITLE":"Aanmelden",
            "CHANNEL_HALF":"Gedeeltelijke opening",
            "GATEWAY_SCREEN_ADD_HELP":"Voor het toevoegen van een gateway kiest u het +symbool.",
            "ERROR_TIMEOUT_CONTENT":"Tijdsoverschrijding bij de communicatie met de gateway",
            "ERROR_NO_PORTS_LEARNED":"Toevoegen niet mogelijk",
            "OPTIONS_SUPPRESS_INFOS":"Aanwijzingen onderdrukken",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Fout",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatische modus",
            "GENERAL_DELETE":"Wissen",
            "GENERAL_PASSWORD":"Wachtwoord",
            "STATE_COLLECTING_CONTENT":"Status van de toestellen wordt opgevraagd",
            "ERROR_REMOVE_USER_CONTENT":"De gebruiker kon niet worden gewist",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Fout",
            "ACTORS_ADD_HELP":"Voor het toevoegen van een toestel kiest u het +symbool.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Weet u zeker dat u het toestel wilt wissen?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Wachten a.u.b. ...",
            "GENERAL_YES":"Ja",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Alvorens een toestel toe te voegen ten minste één kanaal inregelen",
            "CHANGE_GW_NAME_ERROR_CONTENT":"De naam kon niet worden gewijzigd",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"De app heeft nog geen gateways gevonden.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Authenticatie mislukt",
            "DESC_MANAGE_POPUPS_INFOS":"Pop-ups met informatie onderdrukken",
            "GATE_PILOMAT_POLLER":"Poller",
            "DESC_CHANNELS_STATE":"Status van het toestel dat terugmeldingen kan geven",
            "DESC_GWSCREEN_REFRESH":"Gatewaylijst bijwerken",
            "POPUP_SCENARIO_DISPATCHING":"Scenario wordt uitgevoerd",
            "ERROR_PORT_UNREACHABLE":"Mislukt",
            "POPUP_GATEWAY_FOUND_CONTENT":"De volgende gateways werden toegevoegd:",
            "WIFI_STATE_SECURITY_MISMATCH":"Het versleutelingstype van de WLAN wordt niet ondersteund",
            "LOGOUT_NAMED":"afmelden",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Privacybeschermingsvoorwaarden openen",
            "ERROR_NO_GW_CONTENT":"Er kon geen Hörmann-gateway in het lokale netwerk worden gevonden.\nMeer gateways toevoegen via het +teken",
            "DESC_EDIT_USERS_ADD":"Gebruiker toevoegen",
            "ERROR_NO_PORT_FOUND":"Poort niet gevonden",
            "GATE_SLIDING_GATE":"Schuifdeur",
            "DESC_CHANNELS_BUTTONS":"Bedieningselementen van het toestel",
            "DRIVE_MESSAGE_EXTENDED":"uitgeschoven",
            "WIFI_SELECTED_NETWORK":"Naam",
            "ERROR_ADD_GROUP_NO_NAME":"Er werd geen naam voor het nieuwe toestel ingevoerd.",
            "DESC_HELP":"Help-functie",
            "CHANGE_PWD_NEW_PASSWORD":"Nieuw wachtwoord",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Nieuw wachtwoord overnemen",
            "DESC_CHANGE_PASSWORD_PWD":"Nieuw wachtwoord invoeren",
            "ERROR_EDIT_ADMIN_CONTENT":"De administrator kan niet worden bewerkt",
            "CHANGE_GW_NAME_NAME_INVALID":"Mislukt",
            "STATE_COLLECTING_FAILED":"Fout",
            "GENERAL_ADD":"Toevoegen",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Wachtwoord\" en \"Wachtwoord herhalen\" moeten gelijk zijn",
            "WIFI_SETTINGS":"WLAN-instellingen",
            "LEARN_PORTS_TITLE":"Toestel toevoegen",
            "ERROR_CHANGE_USERNAME":"Mislukt",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Wegblokkering",
            "ERROR_INVALID_GATEWAY_CONTENT":"Er kon geen verbinding worden gemaakt met de gateway. Controleer de host-naam.",
            "DESC_EDIT_USERS_EDIT":"Gebruiker wissen",
            "ERROR_ADD_GROUP_NAME_LENGTH":"De toestelnaam moet bestaan uit 2 - 20 tekens",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Snelle toegang niet mogelijk",
            "CHANNEL_UP":"Open",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Permanent Open Aan",
            "PORTAL_VALIDATION_FAILED":"Mislukt",
            "DESC_RESET_LOGIN_CANCEL":"Actie annuleren",
            "CHANGE_PWD_SETTING_PASSWORD":"Overnemen",
            "LOADING_GROUPS_TITLE":"Laad",
            "DESC_DEFAULT_GW_CANCEL":"Actie annuleren",
            "DESC_SET_RIGHTS_SAVE":"Wijzigingen overnemen",
            "REMOVING_PROCESS":"Wissen",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"De gateway is niet bereikbaar",
            "CONFIRM_DELETE_TITLE":"Gateway wissen",
            "SCENARIOS_ADD_HELP":"Voor het toevoegen van een scenario kiest u het +symbool.",
            "LOGOUT":"Afmelden",
            "DESC_ACTORS_BACK":"Terug naar het hoofdmenu",
            "ERROR_ADAPTER_BUSY_CONTENT":"Het commando kon niet worden uitgevoerd.\n De gateway is overbelast.",
            "DESC_WIFI_NETWORK_SCAN":"Naar netwerken zoeken",
            "DRIVE_MESSAGE_HALF":"Gedeeltelijk geopend",
            "DESC_SCENARIOS_ADD":"Scenario aanmaken",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Communicatie met de gateway is mislukt",
            "SAVING_USER_RIGHTS":"Sla op",
            "DESC_GWSCREEN_PORTAL":"Invoer van portaalgegevens",
            "GATE_JACK":"Draadloze contactdoos",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Bent u in hetzelfde netwerk als uw gateway?",
            "GATE_DOOR":"Deur",
            "POPUP_PORTAL_UNAVAILABLE":"De portaalserver kon niet worden bereikt",
            "DESC_SET_RIGHTS_BACK":"Terug naar gebruikers",
            "GATE_SMARTKEY":"Deurslotaandrijving",
            "POPUP_GATEWAY_FOUND_TITILE":"Zoeken beëindigd",
            "WIFI_LOADING_DATA_TITLE":"Laad",
            "GENERAL_PORTS":"Kanalen",
            "DESC_SCENARIOS_EDIT":"Scenario\'s beheren of wissen",
            "OPTIONS_LEARNED_PORTS":"Ingeregelde kanalen:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Ik accepteer de privacybeschermingvoorwaarden",
            "DESC_EDIT_USERS_SET_RIGHTS":"Gebruiker selecteren om diens toegangsrechten te wijzigen",
            "DRIVE_MESSAGE_HALF_MOVING":"Gedeeltelijk geopend / bewegend",
            "PORTAL_SET_ID_DIALOG":"Portaalinstellingen",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Geen referentiepunt",
            "POPUP_SETTING_STATE":"Wachten a.u.b. ...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/nl/gebruiksvoorwaarden",
            "ERROR_CHANGE_USERNAME_CONTENT":"De gebruikersnaam kon niet worden gewijzigd",
            "GROUP_REQUESTABLE":"Het toestel kan terugmeldingen geven",
            "LOADING_STATES_TITLE":"Laad",
            "DESC_HOME_USERS":"Gebruiker beheren",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Het wachtwoord moet bestaan uit 4- 20 tekens",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Het wachtwoord wordt overgenomen",
            "POPUP_GATE_OUT_OF_VIEW":"De besturing van een automatische deurinstallatie zonder zicht op de deur is alleen toegestaan, wanneer u behalve de standaard aanwezige krachtbegrenzing ook een extra fotocel op de deur hebt geïnstalleerd.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Selecteer of pop-upmeldingen weergegeven of onderdrukt worden",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Bevoegd",
            "DRIVE_MESSAGE_LOCKED":"vergrendeld",
            "CHANNEL_DOWN":"Dicht",
            "POPUP_INET_SPEED_LOW":"Uw dataverbinding is niet toereikend voor deze toepassing",
            "CHANGE_PWD_FAILED_CONTENT":"Het wachtwoord kon niet worden gewijzigd",
            "GENERAL_GROUP_TYPE":"Toesteltype",
            "CHANNEL_WALK":"Doorgangsvleugel",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horizontaal bewegende garagedeur",
            "POPUP_AGREEMENT_CONTENT":"Accepteer de privacybeschermings- en gebruiksvoorwaarden alvorens de app te gebruiken",
            "INFO":"Informatie",
            "LOADING_GROUPS_CONTENT":"Laad toestel",
            "GATE_PILOMAT_REIFENKILLER":"Banden killer",
            "GATE_PILOMAT_HUBBALKEN":"Aanrijbalk",
            "GENERAL_RETYPE":"Wachtwoord herhalen",
            "DESC_OTIONS_BACK":"Terug naar het hoofdmenu",
            "DESC_SET_RIGHTS":"Toestel selecteren om aan de gebruiker toegangsrechten toe te kennen",
            "WIFI_SCANNING_TITLE":"Zoeken",
            "WIFI_STATE_CONNECTION_FAILURE":"Verbinding is niet tot stand gekomen",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"De gebruikersnaam moet bestaan uit 2 - 20 tekens",
            "REMOVE_PORTS":"Wissen",
            "GENERAL_ON":"Ingeschakeld",
            "DESC_CHANGE_PASSWORD_CANCEL":"Actie annuleren",
            "LEARNING_PROCESS_CONTENT":"Wachten a.u.b. ...",
            "LOGIN_FAILED_UNKNOWN":"Er is een onverwachte fout opgetreden",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"De gebruikersrechten van de beheerder kunnen niet worden gewijzigd"
         };
         return _loc1_;
      }
   }
}
