package
{
   import mx.resources.ResourceBundle;
   
   public class no_NO$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function no_NO$LocalizedStrings_properties()
      {
         super("no_NO","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Låse",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Skriv inn login-data for Hörmann-portalen",
            "ERROR_DELETE_ADMIN":"Ikke mulig",
            "LOGIN_SHOULD_SAVE":"Lagre data",
            "LOAD_USERS_TITLE":"Vennligst vent",
            "CHANGE_GW_NAME_SETTING":"Overta",
            "CONFIRM_DELETE_GROUP":"Slette enhet",
            "GENERAL_NO":"Nei",
            "DESC_GWSCREEN_ADD":"Legg til lokale gatewayer",
            "DRIVE_MESSAGE_NOT_RETRACTED":"ikke kjørt inn",
            "WIFI_PASSPHRASE":"Passord",
            "CHANNEL_ON":"På",
            "SCENARIOS":"Scenarier",
            "ERROR_SET_ADMIN_RIGHTS":"Ikke mulig",
            "DESC_DEFAULT_GW_SAVE":"Konfigurere hurtigtilgang for aktuell gateway",
            "POPUP_INFO":"Merk",
            "DRIVE_MESSAGE_ERROR":"NB: Feil",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Nettverksnavn",
            "EMAIL_BODY":"Du kan sende oss spørsmålene dine med e-post. Her kan du også benytte vår FAQ-funksjon.\n\nDitt BiSecur-Home brukerstøtteteam",
            "CONFIRM_DELETE_USER":"Slette brukere",
            "DESC_CHANNELS_BACK":"Tilbake til enhetsliste",
            "CHANGE_PWD_FIRST_START":"Av sikkerhetsmessige årsaker bør du endre passordet etter at du har logget inn første gang.",
            "GENERAL_DEFAULT_GATEWAY":"Hurtigtilgang",
            "CHANGE_PWD_PASSWORD_INVALID":"Feil",
            "ERROR_NO_GW_TITLE":"Ingen gatewayer",
            "POPUP_SETTING_STATE_CONTENT":"Kommandoen utføres",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-data lastes",
            "OPTIONS_RESET_LOGIN_DATA":"Slette lagrede login-data",
            "EDIT_USER_TITLE":"Redigere brukere",
            "DESC_HOME_PREFERENCES":"Endre innstillinger for gateway og app",
            "WIFI_ACTIVE_STATE":"WLAN-status",
            "STATE_COLLECTING":"Laste",
            "ADD_SCENARIO":"Legg til scenario",
            "STATE_COLLECTING_FAILED_CONTENT":"Status ble ikke lastet",
            "GATE_SWING_GATE_SINGLE":"1-fløyet slaggrind",
            "ACTORS":"Enheter",
            "POPUP_AGREEMENT":"Bruk / databeskyttelse",
            "CHANNEL_OPEN_DOOR":"Åpne",
            "DESC_ACTORS_REFRESH":"Oppdatere status",
            "GENERAL_OFF":"Slått av",
            "OPTIONS_HELP":"Online-hjelp",
            "COPY_PORTS_CONTENT":"Sett senderen i overføringsmodus, se anvisningen. Velg kanalen det skal overføres til.",
            "GENERAL_SELECT":"Vennligst velg...",
            "ERROR_ADAPTER_BUSY":"Feil",
            "INFO_BOX_INFOS":"Generelt",
            "GATE_LIGHT":"Lys",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Åpne vilkårene for bruk",
            "DESC_MANAGE_POPUPS_WARNINGS":"Skjule popup-advarsler",
            "MAX_USERSS_REACHED_CONTENT":"Maks. antall brukere er nådd.",
            "GENERAL_REMOVE":"Fjerne",
            "OPTIONS":"Innstilinger",
            "DESC_HOME_SCENARIOS":"Opprette og administrere scenarier",
            "CHANNEL_OFF":"Av",
            "GENERAL_PORTAL_ID":"Enhets-ID",
            "EDIT_GROUP":"Bearbeide enheten",
            "ERROR_LERANIN_PORT_CONTENT":"Programmeringen av ønsket kanal er mislykket.",
            "ERROR_CONNECTION_CLOSED":"Feil",
            "CHANNEL_ON_OFF":"På / av",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Betegnelse",
            "OPTIONS_EDIT_USERS":"Administrere brukere",
            "LOADING_STATES_CONTENT":"Den aktuelle status hentes.\nVennligst vent...",
            "LERAN_PORTS_CONTENT":"Sett enheten i programmeringsmodus, se anvisningen. Velg kanalen som skal programmeres.",
            "REMOVE_PORTS_CONTENT":"Velg kanalene du ønsker å slette.",
            "GATE_SWING_GATE_DOUBLE":"2-fløyet slaggrind",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Kontroller om du har lagt inn portaldataene dine eller lagt til en lokal gateway.",
            "CHANNEL_SINK":"Senke",
            "OPTIONS_EDIT_USERS_TITLE":"Bruker",
            "MAX_PORTS_REACHED_CONTENT":"Maksimalt antall kanaler opptatt",
            "MAX_PORTS_REACHED":"Ikke mulig",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Den forespurte enheten kunne ikke nås",
            "PORTAL_AUTHENTICATION_FAILED":"Mislykket",
            "NOTIFICATION_CENTER":"Meldinger",
            "LEARNING_PROCESS":"Programmering",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Brukernavnet må bestå av 2 - 20 tegn",
            "WIFI_STATE_CONNECTED":"Tilkoblet",
            "COPY_PORTS":"Overføre fra håndsender",
            "POPUP_SEARCH_CONTENT":"Søk etter Hörmann-gatewayer \n\nDette kan ta noen sekunder.",
            "DESC_MANAGE_POPUPS_CANCEL":"Avbryte handlingen",
            "DESC_WIFI_PASSWORD":"Passord",
            "DESC_WIFI_SAVE":"Lagre",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stopp aktiv",
            "SELECT_GATEWAY":"Gatewayer",
            "CLEANING_PORTS":"Legg til enhet",
            "WIFI_STATE_BUSY":"Tilkoblingen opprettes",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Det angitte passordet er feil",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Endre navnet på gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Navnet godtas",
            "DESC_ACTORS_EDIT":"Administrere eller slette enheter",
            "DESC_WIFI_STATE":"Tilkoblingsstatus",
            "ERROR_REMOVE_USER":"Mislykket",
            "LANG_TAG":"NO",
            "DESC_MANAGE_POPUPS_SUBMIT":"Godta innstilling",
            "HOME_TITLE":"Hovedside",
            "GENERAL_USERNAME":"Brukernavn",
            "DRIVE_MESSAGE_OPENED":"Åpen",
            "CONFIRM_DELETE":"Er du sikker på, at du virkelig ønsker å slette gatewayen?",
            "DRIVE_MESSAGE_CLOSED":"Lukket",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portalserveren kunne ikke nås",
            "REMOVING_PROCESS_CONTENT":"Kanalen slettes",
            "DESC_EDIT_USERS_BACK":"Tilbake til innstillinger",
            "ERROR_NO_GROUP_FOUND":"Enhet ikke funnet",
            "ERROR_INVALID_GATEWAY":"Ingen gateway funnet",
            "DESC_WIFI_BACK":"Tilbake til innstillingene",
            "MAX_USERS_REACHED":"Ikke mulig",
            "DESC_CHANGE_PASSWORD_USERNAME":"Brukernavn",
            "POPUP_AGREEMENT_ACCEPT_USE":"Jeg godtar vilkårene for bruk",
            "ERROR_LERNING_PORT":"Mislykket",
            "POPUP_ADD_GATEWAY_CONTENT":"Vennligst angi IP-adresse:",
            "ERROR_ADD_GROUP":"Feil",
            "DRIVE_MESSAGE_NO_DATA":"Ingen data tilgjengelig",
            "CHANGE_PWD_FAILED":"Mislykket",
            "SAVING_USER_RIGHTS_CONTENT":"Brukerrettigheter lagres",
            "DRIVE_MESSAGE_UNLOCKED":"Ikke låst",
            "GENERAL_SAVE":"Lagre",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Tilkoble",
            "GATE_SECTIONAL_DOOR":"Garasjeport med vertikalt portløp",
            "OPTIONS_CHANGE_PASSWORD":"Endre passord",
            "CHANNEL":"Betjening",
            "CHANGE_GW_NAME_CONTENT":"Navnet på gateway",
            "DRIVE_MESSAGE_RETRACTED":"kjørt inn",
            "DESC_ADDGWSCREEN_BACK":"Tilbake til gateway-oversikten",
            "EMAIL_SUBJECT":"Brukerstøtte",
            "ERROR_EDIT_ADMIN":"Ikke mulig",
            "OPTIONS_SET_USER_RIGHTS":"Brukerrettigheter",
            "CHANGE_GW_NAME_ERROR":"Mislykket",
            "CHANNEL_LIFT":"Heve",
            "LOGIN_FAILED_TITLE":"Mislykket",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Dersom du bekrefter sletting av login-data med OK, må passordet legges inn på nytt ved valg av gatewayen",
            "CHANNEL_UNLOCK":"Frikople",
            "GENERAL_PORTAL_SERVER":"Portalserver",
            "DESC_SCENARIOS_BACK":"Tilbake til hovedmenyen",
            "CHANGE_PWD_USERNAME":"Bruker:",
            "POPUP_GATE_NOT_RESPONSABLE":"Appen kan sende denne kommandoen til enheten, men identifiserer ikke enhetens aktuelle tilstand.",
            "DESC_GW_NAME":"Navnet på gateway",
            "GATE_BARRIER":"bom",
            "LEARN_PORTS":"Programmere radiokoden",
            "GENERAL_BACK":"Tilbake",
            "DESC_GWSCREEN_EDIT":"Til sletting av lagrede gatewayer",
            "OPTIONS_MANAGE_POPUPS":"Administrere popup-meldinger",
            "POPUP_LOGIN_PROCESS_CONTENT":"Vennligst vent...",
            "CONFIRM_DELETE_USER_CONTENT":"Er du sikker på at du virkelig ønsker å slette gatewayen?",
            "DESC_MENU":"Meny",
            "LOGIN_FAILED_WRONG_DATA":"Ugyldig brukernavn eller feil passord.",
            "GENERAL_CANCEL":"Avbryte",
            "ADD_GROUP":"Legg til enhet",
            "WIFI_STATE_AP_NOT_FOUND":"Nettverk ikke funnet",
            "WIFI_STATE_NOT_CONNECTED":"Ikke tilkoblet",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Din betjening via portalen er aktivert!",
            "POPUP_ADD_GATEWAY":"Legg til gateway",
            "GENERAL_NEXT":"Fortsett",
            "POPUP_SUPPRESS":"Ikke åpne popup",
            "POPUP_SEARCH_TITLE":"Søk...",
            "WIFI_SCANNING_CONTENT":"Søk etter synlige WLAN-nettverk",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Ingen gateway funnet",
            "DESC_ACTORS_ADD":"Opprette enhet",
            "ERROR_ADD_GROUP_NO_TYPE":"Det ble ikke valgt noen type på den nye enheten.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Kontroller login-data",
            "GENERAL_REFESHED":"Aktualisert",
            "OPTIONS_SUPPRESS_WARNINGS":"Skjule advarsler",
            "LOGIN_FAILED_GATEWAY_BUSY":"Gatewayen er opptatt. Vennligst prøv igjen senere.",
            "DESC_EMAIL":"Send e-post til brukerstøtten",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Kontinuerlig-på deaktivert",
            "CLEANING_PORTS_CONTENT":"Legge til enheten forberedes",
            "DESC_HOME_ACTORS":"Programmere og administrere enheter",
            "ERROR_TIMEOUT":"Påloggingsfeil",
            "CREATE_USER_TITLE":"Legg til bruker",
            "ERROR_DELETE_ADMIN_CONTENT":"Administratoren kan ikke slettes",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Hurtigtilgang",
            "ADD_SCENARIO_NAME":"Navn",
            "HIST":"Historie",
            "DESC_RESET_LOGIN_SUBMIT":"Bekrefte sletting",
            "POPUP_WARNING":"OBS!",
            "REMOVE_GROUP_PROCESS":"Enheten slettes",
            "POPUP_LOGIN_PROCESS":"Pålogge",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Vennligst vent...",
            "DESC_DEFAULT_GW_SUBMIT":"Godta innstilling",
            "DESC_CHANGE_PASSWORD_RETYPE":"Gjenta inntasting",
            "LOAD_USERS_CONTENT":"Alle brukere av gateway lastes inn.\nDette kan ta noen sekunder!",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Dersom hurtigtilgangen er aktivert for en gateway, logger appen seg automatisk inn om det er mulig",
            "GATE_OTHER":"Andre enheter",
            "CHANGE_PWD_USER_INVALID":"Feil",
            "CHANNEL_LIGHT":"Lys",
            "LOGIN_TITLE":"Pålogge",
            "CHANNEL_HALF":"Luftestilling",
            "GATEWAY_SCREEN_ADD_HELP":"Velg +symbolet for å legge til en gateway.",
            "ERROR_TIMEOUT_CONTENT":"Tidsavbrudd under pålogging til gateway",
            "ERROR_NO_PORTS_LEARNED":"Ikke mulig å legge til",
            "OPTIONS_SUPPRESS_INFOS":"Skjule merknader",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Feil",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatisk drift",
            "GENERAL_DELETE":"Slette",
            "GENERAL_PASSWORD":"Passord",
            "STATE_COLLECTING_CONTENT":"Status for enhetene forespørres",
            "ERROR_REMOVE_USER_CONTENT":"Kan ikke slette bruker",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Feil",
            "ACTORS_ADD_HELP":"Velg +symbolet for å legge til en enhet.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Er du sikker på at du virkelig ønsker å slette gatewayen?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Vennligst vent...",
            "GENERAL_YES":"Ja",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Minst én kanal må programmeres før det legges til en enhet",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Navnet kunne ikke endres",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Appen har ikke funnet noen gatewayer ennå.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentisering mislyktes",
            "DESC_MANAGE_POPUPS_INFOS":"Skjule popup-informasjoner",
            "GATE_PILOMAT_POLLER":"Pullert",
            "DESC_CHANNELS_STATE":"Status for enhet med tilbakemeldingsfunksjon",
            "DESC_GWSCREEN_REFRESH":"Oppdatering av gateway-listen",
            "POPUP_SCENARIO_DISPATCHING":"Scenario utføres",
            "ERROR_PORT_UNREACHABLE":"Mislykket",
            "POPUP_GATEWAY_FOUND_CONTENT":"Følgende gatewayer ble lagt til:",
            "WIFI_STATE_SECURITY_MISMATCH":"Krypteringsmåten for det trådløse nettverket støttes ikke",
            "LOGOUT_NAMED":"Utlogge",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Åpne vilkårene for databeskyttelse",
            "ERROR_NO_GW_CONTENT":"Det finnes ingen Hörmann-gateway på det lokale nettverket.\nLegg til flere gatewayer med tegnet+",
            "DESC_EDIT_USERS_ADD":"Legg til bruker",
            "ERROR_NO_PORT_FOUND":"Port ikke funnet",
            "GATE_SLIDING_GATE":"Skyveport",
            "DESC_CHANNELS_BUTTONS":"Betjeningselementer av enheten",
            "DRIVE_MESSAGE_EXTENDED":"kjørt ut",
            "WIFI_SELECTED_NETWORK":"Navn",
            "ERROR_ADD_GROUP_NO_NAME":"Det ble ikke angitt noe navn på den nye enheten.",
            "DESC_HELP":"Hjelpefunksjon",
            "CHANGE_PWD_NEW_PASSWORD":"Nytt passord",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Godta nytt passord",
            "DESC_CHANGE_PASSWORD_PWD":"Inntasting av nytt passord",
            "ERROR_EDIT_ADMIN_CONTENT":"Kan ikke redigere administrator",
            "CHANGE_GW_NAME_NAME_INVALID":"Mislykket",
            "STATE_COLLECTING_FAILED":"Feil",
            "GENERAL_ADD":"Legg til",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Passord\" må være identisk med \"Gjenta passord\"",
            "WIFI_SETTINGS":"WLAN-innstillinger",
            "LEARN_PORTS_TITLE":"Legg til enhet",
            "ERROR_CHANGE_USERNAME":"Mislykket",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Veisperre",
            "ERROR_INVALID_GATEWAY_CONTENT":"Det kunne ikke opprettes en forbindelse til gatewayen. Vennligst kontroller det angitte hostnavnet.",
            "DESC_EDIT_USERS_EDIT":"Slette brukere",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Enhetsnavnet må bestå av 2 - 20 tegn",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Hurtigtilgang ikke mulig",
            "CHANNEL_UP":"Åpen",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Kontinuerlig-på aktivert",
            "PORTAL_VALIDATION_FAILED":"Mislykket",
            "DESC_RESET_LOGIN_CANCEL":"Avbryte handlingen",
            "CHANGE_PWD_SETTING_PASSWORD":"Overta",
            "LOADING_GROUPS_TITLE":"Laste",
            "DESC_DEFAULT_GW_CANCEL":"Avbryte handlingen",
            "DESC_SET_RIGHTS_SAVE":"Overta endringer",
            "REMOVING_PROCESS":"Slette",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Portalen kan ikke nås",
            "CONFIRM_DELETE_TITLE":"Slette gateway",
            "SCENARIOS_ADD_HELP":"Velg +symbolet for å legge til et scenario.",
            "LOGOUT":"Utlogge",
            "DESC_ACTORS_BACK":"Tilbake til hovedmenyen",
            "ERROR_ADAPTER_BUSY_CONTENT":"Kommandoen kunne ikke utføres.\n Gatewayen er opptatt.",
            "DESC_WIFI_NETWORK_SCAN":"Søk etter nettverk",
            "DRIVE_MESSAGE_HALF":"Luftestilling",
            "DESC_SCENARIOS_ADD":"Opprette scenario",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Mislykket innlogging til gateway",
            "SAVING_USER_RIGHTS":"Lagre",
            "DESC_GWSCREEN_PORTAL":"Inntasting av portaldata",
            "GATE_JACK":"Trådløs stikkontakt",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Er du i samme nettverk som gatewayen din?",
            "GATE_DOOR":"Dør",
            "POPUP_PORTAL_UNAVAILABLE":"Portalserveren kunne ikke nås",
            "DESC_SET_RIGHTS_BACK":"Tilbake til brukere",
            "GATE_SMARTKEY":"Dørlåsåpner",
            "POPUP_GATEWAY_FOUND_TITILE":"Søket avsluttet",
            "WIFI_LOADING_DATA_TITLE":"Laste",
            "GENERAL_PORTS":"Kanaler",
            "DESC_SCENARIOS_EDIT":"Administrere eller slette scenarier",
            "OPTIONS_LEARNED_PORTS":"Programmerte kanaler:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Jeg godtar vilkårene for databeskyttelse",
            "DESC_EDIT_USERS_SET_RIGHTS":"Velg bruker for å endre dens tilgangsrettigheter",
            "DRIVE_MESSAGE_HALF_MOVING":"Luftestilling / kjørende",
            "PORTAL_SET_ID_DIALOG":"Portalinnstillinger",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Ikke noe referansepunkt",
            "POPUP_SETTING_STATE":"Vennligst vent...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Kan ikke endre brukernavn",
            "GROUP_REQUESTABLE":"Enheten har tilbakemeldingsfunksjon",
            "LOADING_STATES_TITLE":"Laste",
            "DESC_HOME_USERS":"Administrere brukere",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Passordet må bestå av 4 - 20 tegn",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Passordet godtas",
            "POPUP_GATE_OUT_OF_VIEW":"Styring av en automatisk port uten direkte siktforbindelse til porten er kun tillatt når du har installert en fotocelle på porten, i tillegg til den eksisterende standard kraftbegrensningen.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Velg om popup-meldinger skal vises eller skjules",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorisert",
            "DRIVE_MESSAGE_LOCKED":"Låst",
            "CHANNEL_DOWN":"Lukket",
            "POPUP_INET_SPEED_LOW":"Datatilkoblingen er for treg for denne applikasjonen",
            "CHANGE_PWD_FAILED_CONTENT":"Kan ikke endre passord",
            "GENERAL_GROUP_TYPE":"Apparattype",
            "CHANNEL_WALK":"Gangfløy",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Garasjeport med horisontalt portløp",
            "POPUP_AGREEMENT_CONTENT":"Før bruk av appen må vilkårene for databeskyttelse / bruk godtas",
            "INFO":"Opplysninger",
            "LOADING_GROUPS_CONTENT":"Laste enheter",
            "GATE_PILOMAT_REIFENKILLER":"Bilsperre med stålpigger",
            "GATE_PILOMAT_HUBBALKEN":"Løftebom",
            "GENERAL_RETYPE":"Gjenta passord",
            "DESC_OTIONS_BACK":"Tilbake til hovedmenyen",
            "DESC_SET_RIGHTS":"Velg enhet for å gi brukeren tilgangsrettigheter",
            "WIFI_SCANNING_TITLE":"Søk",
            "WIFI_STATE_CONNECTION_FAILURE":"Tilkoblingen mislyktes",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Brukernavnet må bestå av 2 - 20 tegn",
            "REMOVE_PORTS":"Slette",
            "GENERAL_ON":"Slått på",
            "DESC_CHANGE_PASSWORD_CANCEL":"Avbryte handlingen",
            "LEARNING_PROCESS_CONTENT":"Vennligst vent...",
            "LOGIN_FAILED_UNKNOWN":"Det har oppstått en uventet feil.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Administrators brukerrettigheter kan ikke endres"
         };
         return _loc1_;
      }
   }
}
