package
{
   import mx.resources.ResourceBundle;
   
   public class pl_PL$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function pl_PL$LocalizedStrings_properties()
      {
         super("pl_PL","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Zaryglowanie",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Wprowadź dane dostępu do portalu Hörmann",
            "ERROR_DELETE_ADMIN":"brak możliwości",
            "LOGIN_SHOULD_SAVE":"Zapisywanie danych",
            "LOAD_USERS_TITLE":"Proszę czekać",
            "CHANGE_GW_NAME_SETTING":"Przejmij",
            "CONFIRM_DELETE_GROUP":"Usuń urządzenie",
            "GENERAL_NO":"Nie",
            "DESC_GWSCREEN_ADD":"Dodaj lokalne Bramki",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nie opuszczony",
            "WIFI_PASSPHRASE":"Hasło",
            "CHANNEL_ON":"wł",
            "SCENARIOS":"Scenariusze",
            "ERROR_SET_ADMIN_RIGHTS":"brak możliwości",
            "DESC_DEFAULT_GW_SAVE":"Utwórz szybki dostęp do aktualnej Bramki",
            "POPUP_INFO":"Wskazówka",
            "DRIVE_MESSAGE_ERROR":"UWAGA: błąd",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/pl/ochrona-danych",
            "DESC_WIFI_NETWORK_NAME":"Nazwa sieci",
            "EMAIL_BODY":"Pytania można do nas wysyłać poprzez wiadomość e-mail. W tym celu udostępniliśmy również funkcję FAQ.\n\nTwój Zespół Pomocy Technicznej BiSecur-Home",
            "CONFIRM_DELETE_USER":"Usuń użytkownika",
            "DESC_CHANNELS_BACK":"Powrót do listy urządzeń",
            "CHANGE_PWD_FIRST_START":"Ze względów bezpieczeństwa zmień ustawienie fabryczne Twojego hasła podczas następnego logowania",
            "GENERAL_DEFAULT_GATEWAY":"Szybki dostęp",
            "CHANGE_PWD_PASSWORD_INVALID":"Błąd",
            "ERROR_NO_GW_TITLE":"Brak Bram",
            "POPUP_SETTING_STATE_CONTENT":"Trwa realizacja polecenia",
            "WIFI_LOADING_DATA_CONTENT":"Trwa pobieranie danych sieci bezprzewodowej",
            "OPTIONS_RESET_LOGIN_DATA":"Usuń zapisane dane logowania",
            "EDIT_USER_TITLE":"Edytuj użytkownika",
            "DESC_HOME_PREFERENCES":"Zmiana ustawień Bramki i aplikacji",
            "WIFI_ACTIVE_STATE":"Status sieci bezprzewodowej",
            "STATE_COLLECTING":"Pobierz",
            "ADD_SCENARIO":"Dodaj scenariusz",
            "STATE_COLLECTING_FAILED_CONTENT":"Nie pobrano statusu",
            "GATE_SWING_GATE_SINGLE":"Brama 1-skrzydł.",
            "ACTORS":"Urządzenia",
            "POPUP_AGREEMENT":"Korzystanie / Ochrona danych",
            "CHANNEL_OPEN_DOOR":"Otwieranie",
            "DESC_ACTORS_REFRESH":"Odśwież status",
            "GENERAL_OFF":"Wyłączone",
            "OPTIONS_HELP":"Pomoc online",
            "COPY_PORTS_CONTENT":"Przełącz nadajnik na tryb kopiowania, patrz instrukcja. Wybierz kanał, który chcesz skopiować.",
            "GENERAL_SELECT":"Wybierz...",
            "ERROR_ADAPTER_BUSY":"Błąd",
            "INFO_BOX_INFOS":"Ogólne",
            "GATE_LIGHT":"Oświetlenie",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Otwórz warunki korzystania",
            "DESC_MANAGE_POPUPS_WARNINGS":"Wyłącz wyskakujące okienka o ostrzeżeniach",
            "MAX_USERSS_REACHED_CONTENT":"Została osiągnięta maksymalna liczba użytkowników.",
            "GENERAL_REMOVE":"Usuń",
            "OPTIONS":"Ustawienia",
            "DESC_HOME_SCENARIOS":"Tworzenie i zarządzanie scenariuszami",
            "CHANNEL_OFF":"wył",
            "GENERAL_PORTAL_ID":"ID urządzeń",
            "EDIT_GROUP":"Edytuj urządzenie",
            "ERROR_LERANIN_PORT_CONTENT":"Programowanie wybranego kanału nie powiodło się.",
            "ERROR_CONNECTION_CLOSED":"Błąd",
            "CHANNEL_ON_OFF":"Włącz / wyłącz",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Opis",
            "OPTIONS_EDIT_USERS":"Administrowanie użytkownikami",
            "LOADING_STATES_CONTENT":"Trwa odczytywanie aktualnego statusu.\nProszę czekać...",
            "LERAN_PORTS_CONTENT":"Przełącz urządzenie na tryb programowania, patrz instrukcja. Wybierz kanał, który chcesz zaprogramować.",
            "REMOVE_PORTS_CONTENT":"Wybierz kanały, które chcesz usunąć.",
            "GATE_SWING_GATE_DOUBLE":"Brama 2-skrzydł.",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Sprawdź, czy wpisałeś dane portalu lub czy dodałeś lokalną Bramkę.",
            "CHANNEL_SINK":"Opuszczanie",
            "OPTIONS_EDIT_USERS_TITLE":"Użytkownik",
            "MAX_PORTS_REACHED_CONTENT":"Maksymalna liczba kanałów jest zajęta",
            "MAX_PORTS_REACHED":"brak możliwości",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Wywołane urządzenie jest niedostępne",
            "PORTAL_AUTHENTICATION_FAILED":"Nie powiodło się.",
            "NOTIFICATION_CENTER":"Powiadomienia",
            "LEARNING_PROCESS":"Programowanie",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Nazwa użytkownika musi się składać z 2 - 20 znaków",
            "WIFI_STATE_CONNECTED":"Połączono",
            "COPY_PORTS":"Skopiuj z nadajnika",
            "POPUP_SEARCH_CONTENT":"Wyszukiwanie bramek Hörmann \n\nTen proces może potrwać kilka sekund!",
            "DESC_MANAGE_POPUPS_CANCEL":"Przerwij akcję",
            "DESC_WIFI_PASSWORD":"Hasło",
            "DESC_WIFI_SAVE":"Zapisz",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop uruchomiony",
            "SELECT_GATEWAY":"Bramki",
            "CLEANING_PORTS":"Dodaj urządzenie",
            "WIFI_STATE_BUSY":"Trwa nawiązywanie połączenia",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Wprowadzono nieprawidłowe hasło",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Zmień nazwę Bramy",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Trwa przejmowanie nazwy",
            "DESC_ACTORS_EDIT":"Zarządzanie lub usuwanie urządzeń",
            "DESC_WIFI_STATE":"Status połączenia",
            "ERROR_REMOVE_USER":"Nie powiodło się.",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Zastosuj ustawienie",
            "HOME_TITLE":"Strona główna",
            "GENERAL_USERNAME":"Nazwa użytkownika",
            "DRIVE_MESSAGE_OPENED":"Otwarta",
            "CONFIRM_DELETE":"Czy na pewno chcesz usunąć Bramę?",
            "DRIVE_MESSAGE_CLOSED":"Zamknięta",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Serwer portalu jest niedostępny",
            "REMOVING_PROCESS_CONTENT":"Usuwanie kanału",
            "DESC_EDIT_USERS_BACK":"Powrót do ustawień",
            "ERROR_NO_GROUP_FOUND":"Nie odnaleziono urządzenia",
            "ERROR_INVALID_GATEWAY":"Nie odnaleziono Bramy.",
            "DESC_WIFI_BACK":"Powrót do ustawień",
            "MAX_USERS_REACHED":"brak możliwości",
            "DESC_CHANGE_PASSWORD_USERNAME":"Nazwa użytkownika",
            "POPUP_AGREEMENT_ACCEPT_USE":"Akceptuję warunki korzystania",
            "ERROR_LERNING_PORT":"Nie powiodło się.",
            "POPUP_ADD_GATEWAY_CONTENT":"Wprowadź adres IP:",
            "ERROR_ADD_GROUP":"Błąd",
            "DRIVE_MESSAGE_NO_DATA":"Brak dostępnych danych",
            "CHANGE_PWD_FAILED":"Nie powiodło się.",
            "SAVING_USER_RIGHTS_CONTENT":"Trwa zapisywanie uprawnień użytkownika",
            "DRIVE_MESSAGE_UNLOCKED":"niezaryglowane",
            "GENERAL_SAVE":"Zapisz",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Połącz",
            "GATE_SECTIONAL_DOOR":"Pionowa brama garażowa",
            "OPTIONS_CHANGE_PASSWORD":"Zmień hasło",
            "CHANNEL":"Obsługa",
            "CHANGE_GW_NAME_CONTENT":"Nazwa Bramy",
            "DRIVE_MESSAGE_RETRACTED":"opuszczony",
            "DESC_ADDGWSCREEN_BACK":"Powrót do listy Bramek",
            "EMAIL_SUBJECT":"Pomoc",
            "ERROR_EDIT_ADMIN":"Brak możliwości",
            "OPTIONS_SET_USER_RIGHTS":"Uprawnienia użytkownika",
            "CHANGE_GW_NAME_ERROR":"Nie powiodło się.",
            "CHANNEL_LIFT":"Podnoszenie",
            "LOGIN_FAILED_TITLE":"Nie powiodło się.",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Po zatwierdzeniu usunięcia danych logowania przyciskiem OK przy wybieraniu Bramki należy ponownie wprowadzić hasło.",
            "CHANNEL_UNLOCK":"Odryglowanie",
            "GENERAL_PORTAL_SERVER":"Serwer portalu",
            "DESC_SCENARIOS_BACK":"Powrót do menu głównego",
            "CHANGE_PWD_USERNAME":"Użytkownik:",
            "POPUP_GATE_NOT_RESPONSABLE":"Aplikacja może wysłać to polecenie do urządzenia, jednak nie rozpoznaje jego aktualnego statusu.",
            "DESC_GW_NAME":"Nazwa Bramy",
            "GATE_BARRIER":"szlaban",
            "LEARN_PORTS":"Zaprogramuj kod radiowy",
            "GENERAL_BACK":"Powrót",
            "DESC_GWSCREEN_EDIT":"Zapisane Bramki do usunięcia",
            "OPTIONS_MANAGE_POPUPS":"Zarządzaj powiadomieniami o wyskakujących okienkach",
            "POPUP_LOGIN_PROCESS_CONTENT":"Proszę czekać...",
            "CONFIRM_DELETE_USER_CONTENT":"Czy na pewno chcesz usunąć tego użytkownika?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"Nieprawidłowa nazwa użytkownika lub hasło",
            "GENERAL_CANCEL":"Przerwij",
            "ADD_GROUP":"Dodaj urządzenie",
            "WIFI_STATE_AP_NOT_FOUND":"Nie odnaleziono sieci",
            "WIFI_STATE_NOT_CONNECTED":"Nie połączono",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"możliwość obsługi przez portal została aktywowana!",
            "POPUP_ADD_GATEWAY":"Dodaj Bramę",
            "GENERAL_NEXT":"Dalej",
            "POPUP_SUPPRESS":"Nie otwieraj więcej wyskakujących okienek",
            "POPUP_SEARCH_TITLE":"Wyszukiwanie...",
            "WIFI_SCANNING_CONTENT":"Wyszukiwanie widocznych sieci bezprzewodowych",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Nie odnaleziono Bramy.",
            "DESC_ACTORS_ADD":"Tworzenie urządzenia",
            "ERROR_ADD_GROUP_NO_TYPE":"Nie wybrano typu nowego urządzenia.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Sprawdź dane logowania",
            "GENERAL_REFESHED":"odświeżono",
            "OPTIONS_SUPPRESS_WARNINGS":"Wyłącz ostrzeżenia",
            "LOGIN_FAILED_GATEWAY_BUSY":"Bramka jest przeciążona. Spróbuj ponownie.",
            "DESC_EMAIL":"Wyślij wiadomość do pomocy technicznej",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"wył. stałe Otw.",
            "CLEANING_PORTS_CONTENT":"Trwa przygotowanie dodania",
            "DESC_HOME_ACTORS":"Programowanie i zarządzanie urządzeniami",
            "ERROR_TIMEOUT":"Błąd połączenia",
            "CREATE_USER_TITLE":"Dodaj użytkownika",
            "ERROR_DELETE_ADMIN_CONTENT":"Nie można usunąć administratora",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Szybki dostęp",
            "ADD_SCENARIO_NAME":"Nazwa",
            "HIST":"Historia",
            "DESC_RESET_LOGIN_SUBMIT":"Potwierdź usunięcie",
            "POPUP_WARNING":"UWAGA",
            "REMOVE_GROUP_PROCESS":"Usuwanie urządzenia",
            "POPUP_LOGIN_PROCESS":"Logowanie",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Proszę czekać...",
            "DESC_DEFAULT_GW_SUBMIT":"Zastosuj ustawienie",
            "DESC_CHANGE_PASSWORD_RETYPE":"Powtórz wprowadzenie",
            "LOAD_USERS_CONTENT":"Nastąpi pobranie wszystkich użytkowników z Bramy.\nTen proces może potrwać kilka sekund.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Jeżeli aktywowano funkcję szybkiego dostępu Bramki, aplikacja loguje się w miarę możliwości automatycznie",
            "GATE_OTHER":"Inne urządzenia",
            "CHANGE_PWD_USER_INVALID":"Błąd",
            "CHANNEL_LIGHT":"Oświetlenie",
            "LOGIN_TITLE":"Logowanie",
            "CHANNEL_HALF":"Otwarcie częściowe",
            "GATEWAY_SCREEN_ADD_HELP":"Aby dodać Bramkę, wybierz symbol+.",
            "ERROR_TIMEOUT_CONTENT":"Przekroczono limit czasu komunikacji z Bramką",
            "ERROR_NO_PORTS_LEARNED":"Nie można dodać",
            "OPTIONS_SUPPRESS_INFOS":"Wyłącz wskazówki",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Błąd",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Tryb automatyczny",
            "GENERAL_DELETE":"Kasowanie",
            "GENERAL_PASSWORD":"Hasło",
            "STATE_COLLECTING_CONTENT":"Zapytanie o status urządzeń w toku",
            "ERROR_REMOVE_USER_CONTENT":"Nie udało się usunąć użytkownika",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Błąd",
            "ACTORS_ADD_HELP":"Aby dodać urządzenie, wybierz symbol+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Czy na pewno chcesz usunąć to urządzenie?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Proszę czekać...",
            "GENERAL_YES":"Tak",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Przed dodaniem urządzenia należy zaprogramować co najmniej jeden kanał",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Nie można zmienić nazwy",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Aplikacja nie odnalazła jeszcze żadnych bramek.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Uwierzytelnianie nie powiodło się",
            "DESC_MANAGE_POPUPS_INFOS":"Wyłącz wyskakujące okienka z informacjami",
            "GATE_PILOMAT_POLLER":"Słupek parkingowy",
            "DESC_CHANNELS_STATE":"Status urządzenia obsługującego funkcję sygnalizacji zwrotnej",
            "DESC_GWSCREEN_REFRESH":"Aktualizacja listy Bramek",
            "POPUP_SCENARIO_DISPATCHING":"Trwa wykonywanie scenariusza",
            "ERROR_PORT_UNREACHABLE":"Nie powiodło się.",
            "POPUP_GATEWAY_FOUND_CONTENT":"Dodano następujące Bramki:",
            "WIFI_STATE_SECURITY_MISMATCH":"Ten rodzaj szyfrowania sieci bezprzewodowej nie jest wspierany",
            "LOGOUT_NAMED":"Wyloguj",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Otwórz warunki ochrony danych",
            "ERROR_NO_GW_CONTENT":"Nie odnaleziono Bramy Hörmann w sieci lokalnej.\nDodaj kolejne Bramki, używając w tym celu znaku+.",
            "DESC_EDIT_USERS_ADD":"Dodaj użytkownika",
            "ERROR_NO_PORT_FOUND":"Nie odnaleziono portu",
            "GATE_SLIDING_GATE":"Brama przesuwna",
            "DESC_CHANNELS_BUTTONS":"Elementy obsługi urządzenia",
            "DRIVE_MESSAGE_EXTENDED":"wysunięty",
            "WIFI_SELECTED_NETWORK":"Nazwa",
            "ERROR_ADD_GROUP_NO_NAME":"Nie wprowadzono nazwy nowego urządzenia.",
            "DESC_HELP":"funkcja pomocy",
            "CHANGE_PWD_NEW_PASSWORD":"Nowe hasło",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Zastosuj nowe hasło",
            "DESC_CHANGE_PASSWORD_PWD":"Wprowadź nowe hasło",
            "ERROR_EDIT_ADMIN_CONTENT":"Nie można edytować administratora",
            "CHANGE_GW_NAME_NAME_INVALID":"Nie powiodło się.",
            "STATE_COLLECTING_FAILED":"Błąd",
            "GENERAL_ADD":"Dodaj",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"Wprowadzone znaki \"Hasło\" i \"Powtórz hasło\" muszą być takie same",
            "WIFI_SETTINGS":"Ustawienia sieci bezprzewodowej",
            "LEARN_PORTS_TITLE":"Dodaj urządzenie",
            "ERROR_CHANGE_USERNAME":"Nie powiodło się.",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Zapora drogowa",
            "ERROR_INVALID_GATEWAY_CONTENT":"Nie można nawiązać połączenia z Bramą. Sprawdź podaną nazwę hosta.",
            "DESC_EDIT_USERS_EDIT":"Usuń użytkownika",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Nazwa urządzenia musi się składać z 2 - 20 znaków",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Szybki dostęp nie jest możliwy",
            "CHANNEL_UP":"Otwieranie",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"wł. stałe Otw.",
            "PORTAL_VALIDATION_FAILED":"Nie powiodło się.",
            "DESC_RESET_LOGIN_CANCEL":"Przerwij akcję",
            "CHANGE_PWD_SETTING_PASSWORD":"Przejmij",
            "LOADING_GROUPS_TITLE":"Pobierz",
            "DESC_DEFAULT_GW_CANCEL":"Przerwij akcję",
            "DESC_SET_RIGHTS_SAVE":"Zastosuj zmiany",
            "REMOVING_PROCESS":"Kasowanie",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Bramka jest niedostępna",
            "CONFIRM_DELETE_TITLE":"Usuń Bramę",
            "SCENARIOS_ADD_HELP":"Aby dodać scenariusz, wybierz symbol+.",
            "LOGOUT":"Wyloguj",
            "DESC_ACTORS_BACK":"Powrót do menu głównego",
            "ERROR_ADAPTER_BUSY_CONTENT":"Nie można wykonać polecenia.\n Bramka jest przeciążona.",
            "DESC_WIFI_NETWORK_SCAN":"Skanuj sieci",
            "DRIVE_MESSAGE_HALF":"Częściowo otwarta",
            "DESC_SCENARIOS_ADD":"Tworzenie scenariusza",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Nawiązanie komunikacji z Bramką nie powiodło się",
            "SAVING_USER_RIGHTS":"Zapisz",
            "DESC_GWSCREEN_PORTAL":"Wprowadzanie danych portalu",
            "GATE_JACK":"Odbiornik sygnałów radiowych z gniazdem wtykowym",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Czy znajdujesz się w tej samej sieci, co Bramka?",
            "GATE_DOOR":"Drzwi",
            "POPUP_PORTAL_UNAVAILABLE":"Serwer portalu jest niedostępny",
            "DESC_SET_RIGHTS_BACK":"Powrót do użytkowników",
            "GATE_SMARTKEY":"Napęd zamka drzwiowego",
            "POPUP_GATEWAY_FOUND_TITILE":"Wyszukiwanie zakończone",
            "WIFI_LOADING_DATA_TITLE":"Pobierz",
            "GENERAL_PORTS":"Kanały",
            "DESC_SCENARIOS_EDIT":"Zarządzanie lub usuwanie scenariuszy",
            "OPTIONS_LEARNED_PORTS":"Zaprogramowane kanały:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Akceptuję warunki ochrony danych",
            "DESC_EDIT_USERS_SET_RIGHTS":"Wybierz użytkownika, aby zmienić jego uprawnienia dostępu",
            "DRIVE_MESSAGE_HALF_MOVING":"Częściowo otwarta / koniec biegu",
            "PORTAL_SET_ID_DIALOG":"Ustawienia portalu",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Brak punktu odniesienia",
            "POPUP_SETTING_STATE":"Proszę czekać...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/pl/Warunki-korzystania",
            "ERROR_CHANGE_USERNAME_CONTENT":"Nie udało się zmienić nazwy użytkownika",
            "GROUP_REQUESTABLE":"Urządzenie obsługuje funkcję sygnalizacji zwrotnej.",
            "LOADING_STATES_TITLE":"Pobierz",
            "DESC_HOME_USERS":"Administrowanie użytkownikami",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Hasło musi się składać z 4 - 20 znaków",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Trwa przejmowanie hasła",
            "POPUP_GATE_OUT_OF_VIEW":"Zezwala się na korzystanie ze sterowania automatycznej bramy, znajdującej się poza zasięgiem wzroku użytkownika, wyłącznie pod warunkiem, że na bramie zainstalowano fotokomórkę jako dodatkowe zabezpieczenie oprócz montowanego standardowo ograniczenia siły.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Wybierz, czy chcesz wyświetlać czy wyłączyć powiadomienia o wyskakujących okienkach",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"uprawniony",
            "DRIVE_MESSAGE_LOCKED":"zaryglowane",
            "CHANNEL_DOWN":"Zamykanie",
            "POPUP_INET_SPEED_LOW":"Łącze danych jest niewystarczające dla tego zastosowania",
            "CHANGE_PWD_FAILED_CONTENT":"Nie udało się zmienić hasła",
            "GENERAL_GROUP_TYPE":"Typ urządzenia",
            "CHANNEL_WALK":"Skrzydło przechodnie",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Pozioma brama garażowa",
            "POPUP_AGREEMENT_CONTENT":"Przed rozpoczęciem korzystania z aplikacji zaakceptuj warunki ochrony danych / warunki korzystania",
            "INFO":"Informacje",
            "LOADING_GROUPS_CONTENT":"Pobierz urządzenia",
            "GATE_PILOMAT_REIFENKILLER":"Kolczatka drogowa",
            "GATE_PILOMAT_HUBBALKEN":"Szlaban",
            "GENERAL_RETYPE":"Powtórz hasło",
            "DESC_OTIONS_BACK":"Powrót do menu głównego",
            "DESC_SET_RIGHTS":"Wybierz urządzenie, aby nadać użytkownikowi uprawnienia dostępu",
            "WIFI_SCANNING_TITLE":"Wyszukiwanie",
            "WIFI_STATE_CONNECTION_FAILURE":"Nawiązanie połączenia nie powiodło się",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Nazwa użytkownika musi się składać z 2 - 20 znaków",
            "REMOVE_PORTS":"Kasowanie",
            "GENERAL_ON":"Włączone",
            "DESC_CHANGE_PASSWORD_CANCEL":"Przerwij akcję",
            "LEARNING_PROCESS_CONTENT":"Proszę czekać...",
            "LOGIN_FAILED_UNKNOWN":"Wystąpił nieoczekiwany błąd",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Nie można zmienić uprawnień administratora"
         };
         return _loc1_;
      }
   }
}
