package
{
   import mx.resources.ResourceBundle;
   
   public class pt_PT$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function pt_PT$LocalizedStrings_properties()
      {
         super("pt_PT","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Bloquear",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Registe os dados de acesso no portal Hörmann",
            "ERROR_DELETE_ADMIN":"Não é possível",
            "LOGIN_SHOULD_SAVE":"Guardar dados",
            "LOAD_USERS_TITLE":"Aguarde por favor",
            "CHANGE_GW_NAME_SETTING":"Aceitar",
            "CONFIRM_DELETE_GROUP":"Apagar equipamento",
            "GENERAL_NO":"Não",
            "DESC_GWSCREEN_ADD":"Inserir gateways locais",
            "DRIVE_MESSAGE_NOT_RETRACTED":"não recolhido",
            "WIFI_PASSPHRASE":"Palavra-passe",
            "CHANNEL_ON":"Ligado",
            "SCENARIOS":"Cenários",
            "ERROR_SET_ADMIN_RIGHTS":"Não é possível",
            "DESC_DEFAULT_GW_SAVE":"Providenciar o acesso rápido para o gateway atual",
            "POPUP_INFO":"Nota",
            "DRIVE_MESSAGE_ERROR":"ATENÇÃO: erros",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Nome de redes",
            "EMAIL_BODY":"Pode enviar-nos as suas questões por e-mail. A nossa função FAQ também está à sua disposição.\n\nA sua equipa de assistência BiSecur-Home",
            "CONFIRM_DELETE_USER":"Apagar utilizador",
            "DESC_CHANNELS_BACK":"Voltar à lista de equipamentos",
            "CHANGE_PWD_FIRST_START":"Por motivos de segurança, altere a configuração de fábrica da sua palavra-passe após o primeiro registo",
            "GENERAL_DEFAULT_GATEWAY":"Acesso rápido",
            "CHANGE_PWD_PASSWORD_INVALID":"Erros",
            "ERROR_NO_GW_TITLE":"Não existem gateways",
            "POPUP_SETTING_STATE_CONTENT":"A ordem está a ser realizada",
            "WIFI_LOADING_DATA_CONTENT":"Os dados WLAN vão ser carregados",
            "OPTIONS_RESET_LOGIN_DATA":"Apagar dados de login guardados",
            "EDIT_USER_TITLE":"Editar utilizador",
            "DESC_HOME_PREFERENCES":"Alterar as configurações relativas ao gateway e à aplicação",
            "WIFI_ACTIVE_STATE":"Estado WLAN",
            "STATE_COLLECTING":"Carregar",
            "ADD_SCENARIO":"Inserir cenário",
            "STATE_COLLECTING_FAILED_CONTENT":"O estado não foi carregado",
            "GATE_SWING_GATE_SINGLE":"Porta de batente com 1 folha",
            "ACTORS":"Equipamentos",
            "POPUP_AGREEMENT":"Utilização / Proteção de dados",
            "CHANNEL_OPEN_DOOR":"Abrir",
            "DESC_ACTORS_REFRESH":"Atualizar o estado",
            "GENERAL_OFF":"Desligado",
            "OPTIONS_HELP":"Ajuda online",
            "COPY_PORTS_CONTENT":"Coloque o emissor no modo de hereditariedade, ver instruções. Selecione o canal que vai ser herdado.",
            "GENERAL_SELECT":"Por favor selecionar...",
            "ERROR_ADAPTER_BUSY":"Erros",
            "INFO_BOX_INFOS":"Generalidades",
            "GATE_LIGHT":"Luz",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Abrir as condições de utilização",
            "DESC_MANAGE_POPUPS_WARNINGS":"Ocultar os pop-ups de aviso",
            "MAX_USERSS_REACHED_CONTENT":"O número máximo de utilizadores foi atingido.",
            "GENERAL_REMOVE":"Remover",
            "OPTIONS":"Configurações",
            "DESC_HOME_SCENARIOS":"Criar e gerir os cenários",
            "CHANNEL_OFF":"Desligado",
            "GENERAL_PORTAL_ID":"Equipamentos ID",
            "EDIT_GROUP":"Editar equipamento",
            "ERROR_LERANIN_PORT_CONTENT":"A programação do canal pretendido falhou",
            "ERROR_CONNECTION_CLOSED":"Erros",
            "CHANNEL_ON_OFF":"Ligado / Desligado",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Designação",
            "OPTIONS_EDIT_USERS":"Gerir utilizadores",
            "LOADING_STATES_CONTENT":"É consultado o estado atual.\nAguarde por favor...",
            "LERAN_PORTS_CONTENT":"Coloque o equipamento no modo de programação, ver instruções. Selecione o canal que vai ser programado.",
            "REMOVE_PORTS_CONTENT":"Selecione os canais que pretende apagar.",
            "GATE_SWING_GATE_DOUBLE":"Porta de batente com 2 folhas",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Verifique, se registou os seus dados no portal ou inseriu um gateway local.",
            "CHANNEL_SINK":"Rebaixar",
            "OPTIONS_EDIT_USERS_TITLE":"Utilizador",
            "MAX_PORTS_REACHED_CONTENT":"O número máximo dos canais está ocupado",
            "MAX_PORTS_REACHED":"Não é possível",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Não foi possível aceder ao equipamento solicitado",
            "PORTAL_AUTHENTICATION_FAILED":"Falhou",
            "NOTIFICATION_CENTER":"Avisos",
            "LEARNING_PROCESS":"Programar",
            "CHANGE_PWD_USER_INVALID_CONTENT":"O nome do utilizador tem de ser composto por 2 - 20 caracteres",
            "WIFI_STATE_CONNECTED":"Encontra-se ligado",
            "COPY_PORTS":"Herdar de emissores",
            "POPUP_SEARCH_CONTENT":"Procura por gateways Hörmann \nEste processo pode demorar alguns segundos.",
            "DESC_MANAGE_POPUPS_CANCEL":"Cancelar ação",
            "DESC_WIFI_PASSWORD":"Palavra-passe",
            "DESC_WIFI_SAVE":"Guardar",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Imobilização ativa",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Inserir equipamento",
            "WIFI_STATE_BUSY":"A ligação vai ser estabelecida",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"A palavra-passe introduzida está errada",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Alterar o nome do gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"O nome vai ser aceite",
            "DESC_ACTORS_EDIT":"Gerir ou apagar equipamentos",
            "DESC_WIFI_STATE":"Estado de ligação",
            "ERROR_REMOVE_USER":"Falhou",
            "LANG_TAG":"PT",
            "DESC_MANAGE_POPUPS_SUBMIT":"Aceitar a configuração",
            "HOME_TITLE":"Página principal",
            "GENERAL_USERNAME":"Nome do utilizador",
            "DRIVE_MESSAGE_OPENED":"Aberto",
            "CONFIRM_DELETE":"Tem a certeza, que pretende apagar o gateway?",
            "DRIVE_MESSAGE_CLOSED":"Fechado",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Não foi possível aceder ao servidor do portal",
            "REMOVING_PROCESS_CONTENT":"O equipamento vai ser apagado",
            "DESC_EDIT_USERS_BACK":"Voltar às configurações",
            "ERROR_NO_GROUP_FOUND":"Equipamento não encontrado",
            "ERROR_INVALID_GATEWAY":"Não foi encontrado nenhum gateway",
            "DESC_WIFI_BACK":"Voltar às configurações",
            "MAX_USERS_REACHED":"Não é possível",
            "DESC_CHANGE_PASSWORD_USERNAME":"Nome do utilizador",
            "POPUP_AGREEMENT_ACCEPT_USE":"Aceito as condições de utilização",
            "ERROR_LERNING_PORT":"Falhou",
            "POPUP_ADD_GATEWAY_CONTENT":"Registar o endereço IP:",
            "ERROR_ADD_GROUP":"Erros",
            "DRIVE_MESSAGE_NO_DATA":"Não existem dados disponíveis",
            "CHANGE_PWD_FAILED":"Falhou",
            "SAVING_USER_RIGHTS_CONTENT":"Os direitos de utilizador vão ser guardados",
            "DRIVE_MESSAGE_UNLOCKED":"não bloqueado",
            "GENERAL_SAVE":"Guardar",
            "INFO_BOX_FAQ":"FAQ (Perguntas frequentes)",
            "GENERAL_CONNNECT":"Ligar",
            "GATE_SECTIONAL_DOOR":"Porta de garagem que se desloca na vertical",
            "OPTIONS_CHANGE_PASSWORD":"Alterar palavra-passe",
            "CHANNEL":"Manuseamento",
            "CHANGE_GW_NAME_CONTENT":"Nome do gateway",
            "DRIVE_MESSAGE_RETRACTED":"recolhido",
            "DESC_ADDGWSCREEN_BACK":"Voltar para o resumo de gateways",
            "EMAIL_SUBJECT":"Assistência",
            "ERROR_EDIT_ADMIN":"Não é possível",
            "OPTIONS_SET_USER_RIGHTS":"Direitos de utilizador",
            "CHANGE_GW_NAME_ERROR":"Falhou",
            "CHANNEL_LIFT":"Elevar",
            "LOGIN_FAILED_TITLE":"Falhou",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Se confirmar a anulação dos dados de login com OK, tem de ser introduzida novamente a palavra-passe aquando da seleção do gateway",
            "CHANNEL_UNLOCK":"Desbloquear",
            "GENERAL_PORTAL_SERVER":"Servidor do portal",
            "DESC_SCENARIOS_BACK":"Voltar ao menu principal",
            "CHANGE_PWD_USERNAME":"Utilizador:",
            "POPUP_GATE_NOT_RESPONSABLE":"A aplicação pode enviar esta ordem ao equipamento, no entanto, não reconhece o estado atual do equipamento.",
            "DESC_GW_NAME":"Nome do gateway",
            "GATE_BARRIER":"barreira",
            "LEARN_PORTS":"Programar código de radiofrequência",
            "GENERAL_BACK":"Voltar",
            "DESC_GWSCREEN_EDIT":"Gateways guardados para apagar",
            "OPTIONS_MANAGE_POPUPS":"Gerir as janelas pop-up",
            "POPUP_LOGIN_PROCESS_CONTENT":"Aguarde por favor...",
            "CONFIRM_DELETE_USER_CONTENT":"Tem a certeza, que pretende apagar o utilizador?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"O nome de utilizador introduzido ou a palavra-passe está errada",
            "GENERAL_CANCEL":"Cancelar",
            "ADD_GROUP":"Inserir equipamento",
            "WIFI_STATE_AP_NOT_FOUND":"A rede não foi encontrada",
            "WIFI_STATE_NOT_CONNECTED":"Não se encontra ligado",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"A sua operação através do portal encontra-se ativada!",
            "POPUP_ADD_GATEWAY":"Inserir gateway",
            "GENERAL_NEXT":"Continuar",
            "POPUP_SUPPRESS":"Não voltar a abrir o pop-up",
            "POPUP_SEARCH_TITLE":"Procura...",
            "WIFI_SCANNING_CONTENT":"Procura por redes WLAN visíveis",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Não foi encontrado nenhum gateway",
            "DESC_ACTORS_ADD":"Criar equipamento",
            "ERROR_ADD_GROUP_NO_TYPE":"Não foi selecionado nenhum modelo para o novo equipamento.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Verifique os dados de login",
            "GENERAL_REFESHED":"Atualizado",
            "OPTIONS_SUPPRESS_WARNINGS":"Ocultar avisos",
            "LOGIN_FAILED_GATEWAY_BUSY":"O gateway está sobrecarregado. Tente novamente.",
            "DESC_EMAIL":"Enviar e-mail para a assistência",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Abertura permanente desligada",
            "CLEANING_PORTS_CONTENT":"A inserção está a ser preparada",
            "DESC_HOME_ACTORS":"Programar e gerir os equipamentos",
            "ERROR_TIMEOUT":"Erro de ligação",
            "CREATE_USER_TITLE":"Inserir utilizador",
            "ERROR_DELETE_ADMIN_CONTENT":"Não é possível apagar o administrador",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Acesso rápido",
            "ADD_SCENARIO_NAME":"Nome",
            "HIST":"História",
            "DESC_RESET_LOGIN_SUBMIT":"Confirmar a anulação",
            "POPUP_WARNING":"ATENÇÃO",
            "REMOVE_GROUP_PROCESS":"O equipamento vai ser apagado",
            "POPUP_LOGIN_PROCESS":"Registar",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Aguarde por favor...",
            "DESC_DEFAULT_GW_SUBMIT":"Aceitar a configuração",
            "DESC_CHANGE_PASSWORD_RETYPE":"Repetir a introdução",
            "LOAD_USERS_CONTENT":"São carregados todos os utilizadores do gateway.\nEste processo pode demorar alguns segundos.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Caso se encontre ativado um gateway, o acesso rápido, a aplicação acede automaticamente, na medida do possível",
            "GATE_OTHER":"Outros equipamentos",
            "CHANGE_PWD_USER_INVALID":"Erros",
            "CHANNEL_LIGHT":"Luz",
            "LOGIN_TITLE":"Registar",
            "CHANNEL_HALF":"Abertura parcial",
            "GATEWAY_SCREEN_ADD_HELP":"Para inserir um gateway, selecione o símbolo+.",
            "ERROR_TIMEOUT_CONTENT":"O tempo expirou durante a comunicação com o gateway",
            "ERROR_NO_PORTS_LEARNED":"Não é possível inserir",
            "OPTIONS_SUPPRESS_INFOS":"Ocultar notas",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Erros",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Funcionamento automático",
            "GENERAL_DELETE":"Apagar",
            "GENERAL_PASSWORD":"Palavra-passe",
            "STATE_COLLECTING_CONTENT":"Vai ser pedido o estado dos equipamentos",
            "ERROR_REMOVE_USER_CONTENT":"Não foi possível eliminar o utilizador",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Erros",
            "ACTORS_ADD_HELP":"Para inserir um equipamento, selecione o símbolo+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Tem a certeza, que pretende apagar o equipamento?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Aguarde por favor...",
            "GENERAL_YES":"Sim",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Antes de inserir um equipamento, programar pelo menos um canal",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Não foi possível alterar o nome",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"A aplicação ainda não encontrou gateways.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"A autenticação falhou",
            "DESC_MANAGE_POPUPS_INFOS":"Ocultar os pop-ups de informação",
            "GATE_PILOMAT_POLLER":"Dissuasor",
            "DESC_CHANNELS_STATE":"Estado do equipamento que pode ser confirmado",
            "DESC_GWSCREEN_REFRESH":"Atualização da lista de gateways",
            "POPUP_SCENARIO_DISPATCHING":"É executado o cenário",
            "ERROR_PORT_UNREACHABLE":"Falhou",
            "POPUP_GATEWAY_FOUND_CONTENT":"Os seguintes gateways foram inseridos:",
            "WIFI_STATE_SECURITY_MISMATCH":"O tipo de encriptação da WLAN não é apoiado",
            "LOGOUT_NAMED":"cancelar",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Abrir as condições de proteção de dados",
            "ERROR_NO_GW_CONTENT":"Não foi encontrado nenhum gateway da Hörmann na rede local.\nInserir outros gateways através do sinal+",
            "DESC_EDIT_USERS_ADD":"Inserir utilizador",
            "ERROR_NO_PORT_FOUND":"Entrada não encontrada",
            "GATE_SLIDING_GATE":"Porta de correr",
            "DESC_CHANNELS_BUTTONS":"Elementos de comando do equipamento",
            "DRIVE_MESSAGE_EXTENDED":"estendido",
            "WIFI_SELECTED_NETWORK":"Nome",
            "ERROR_ADD_GROUP_NO_NAME":"Não foi introduzido nenhum nome para o novo equipamento.",
            "DESC_HELP":"Função de ajuda",
            "CHANGE_PWD_NEW_PASSWORD":"Palavra-passe nova",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Aceitar a palavra-passe nova",
            "DESC_CHANGE_PASSWORD_PWD":"Introdução da nova palavra-passe",
            "ERROR_EDIT_ADMIN_CONTENT":"O administrador não pode ser editado",
            "CHANGE_GW_NAME_NAME_INVALID":"Falhou",
            "STATE_COLLECTING_FAILED":"Erros",
            "GENERAL_ADD":"Inserir",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Palavra-passe\" e \"Repetir palavra-passe\" têm de ser iguais",
            "WIFI_SETTINGS":"Configurações WLAN",
            "LEARN_PORTS_TITLE":"Inserir equipamento",
            "ERROR_CHANGE_USERNAME":"Falhou",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Bloqueio de passagem",
            "ERROR_INVALID_GATEWAY_CONTENT":"Não foi possível estabelecer qualquer ligação com o gateway. Verifique o nome do Host.",
            "DESC_EDIT_USERS_EDIT":"Apagar utilizador",
            "ERROR_ADD_GROUP_NAME_LENGTH":"O nome do equipamento tem de ser composto por 2 - 20 caracteres",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Não é possível o acesso rápido",
            "CHANNEL_UP":"Aberto",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Abertura permanente ligada",
            "PORTAL_VALIDATION_FAILED":"Falhou",
            "DESC_RESET_LOGIN_CANCEL":"Cancelar ação",
            "CHANGE_PWD_SETTING_PASSWORD":"Aceitar",
            "LOADING_GROUPS_TITLE":"Carregar",
            "DESC_DEFAULT_GW_CANCEL":"Cancelar ação",
            "DESC_SET_RIGHTS_SAVE":"Aceitar as alterações",
            "REMOVING_PROCESS":"Apagar",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"O gateway não está acessível",
            "CONFIRM_DELETE_TITLE":"Apagar gateway",
            "SCENARIOS_ADD_HELP":"Para inserir um cenário, selecione o símbolo+.",
            "LOGOUT":"Cancelar",
            "DESC_ACTORS_BACK":"Voltar ao menu principal",
            "ERROR_ADAPTER_BUSY_CONTENT":"Não foi possível realizar a ordem.\n O gateway está sobrecarregado.",
            "DESC_WIFI_NETWORK_SCAN":"Procurar por redes",
            "DRIVE_MESSAGE_HALF":"Meio aberto",
            "DESC_SCENARIOS_ADD":"Criar cenário",
            "ERROR_CONNECTION_CLOSED_CONTENT":"A comunicação com o gateway falhou.",
            "SAVING_USER_RIGHTS":"Guardar",
            "DESC_GWSCREEN_PORTAL":"Introdução dos dados no portal",
            "GATE_JACK":"Tomada com radiofrequência",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Encontra-se na mesma rede que o seu gateway?",
            "GATE_DOOR":"Porta",
            "POPUP_PORTAL_UNAVAILABLE":"Não foi possível aceder ao servidor do portal",
            "DESC_SET_RIGHTS_BACK":"Voltar aos utilizadores",
            "GATE_SMARTKEY":"Automatismo para fechadura de porta",
            "POPUP_GATEWAY_FOUND_TITILE":"Processo de procura concluído",
            "WIFI_LOADING_DATA_TITLE":"Carregar",
            "GENERAL_PORTS":"Canais",
            "DESC_SCENARIOS_EDIT":"Gerir ou apagar cenários",
            "OPTIONS_LEARNED_PORTS":"Canais programados:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Aceito as condições de proteção de dados",
            "DESC_EDIT_USERS_SET_RIGHTS":"Selecionar o utilizador para alterar os direitos de acesso",
            "DRIVE_MESSAGE_HALF_MOVING":"Meio aberto / Em deslocação",
            "PORTAL_SET_ID_DIALOG":"Configurações do portal",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Não existe qualquer ponto de referência",
            "POPUP_SETTING_STATE":"Aguarde por favor...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Não foi possível alterar o nome do utilizador",
            "GROUP_REQUESTABLE":"O equipamento deve ser confirmado",
            "LOADING_STATES_TITLE":"Carregar",
            "DESC_HOME_USERS":"Gerir utilizadores",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"A palavra-passe tem de ser composta por 4 - 20 caracteres",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"A palavra-passe vai ser aceite",
            "POPUP_GATE_OUT_OF_VIEW":"O acionamento de um sistema automático de porta sem visibilidade para a porta só é permitido, se tiver sido instalada adicionalmente uma célula fotoelétrica na porta, para além da limitação de força existente de série.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Selecione, independentemente se as janelas pop-up são visualizadas ou ocultadas",
            "CHANNEL_IMPULS":"Impulso",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorizado",
            "DRIVE_MESSAGE_LOCKED":"bloqueado",
            "CHANNEL_DOWN":"Fechado",
            "POPUP_INET_SPEED_LOW":"A sua ligação de dados não é suficiente para esta aplicação",
            "CHANGE_PWD_FAILED_CONTENT":"Não foi possível alterar a palavra-passe",
            "GENERAL_GROUP_TYPE":"Modelo do equipamento",
            "CHANNEL_WALK":"Batente de arrastamento",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Porta de garagem que se desloca na horizontal",
            "POPUP_AGREEMENT_CONTENT":"Antes da utilização da aplicação, aceite as condições de utilização e proteção de dados",
            "INFO":"Informações",
            "LOADING_GROUPS_CONTENT":"Carregar equipamentos",
            "GATE_PILOMAT_REIFENKILLER":"Destruidores de pneus",
            "GATE_PILOMAT_HUBBALKEN":"Cancela",
            "GENERAL_RETYPE":"Repetir palavra-passe",
            "DESC_OTIONS_BACK":"Voltar ao menu principal",
            "DESC_SET_RIGHTS":"Selecionar o equipamento para conceder direitos de acesso ao utilizador",
            "WIFI_SCANNING_TITLE":"Procura",
            "WIFI_STATE_CONNECTION_FAILURE":"O estabelecimento de chamadas falhou",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"O nome do utilizador tem de ser composto por 2 - 20 caracteres",
            "REMOVE_PORTS":"Apagar",
            "GENERAL_ON":"Ligado",
            "DESC_CHANGE_PASSWORD_CANCEL":"Cancelar ação",
            "LEARNING_PROCESS_CONTENT":"Aguarde por favor...",
            "LOGIN_FAILED_UNKNOWN":"Verificou-se um erro inesperado",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Os direitos de utilização do administrador não podem ser alterados"
         };
         return _loc1_;
      }
   }
}
