package
{
   import mx.resources.ResourceBundle;
   
   public class ro_RO$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function ro_RO$LocalizedStrings_properties()
      {
         super("ro_RO","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Blocare",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Introduceţi datele de accesare ale portalului Hörmann",
            "ERROR_DELETE_ADMIN":"Nu este posibil",
            "LOGIN_SHOULD_SAVE":"Salvare date",
            "LOAD_USERS_TITLE":"Vă rugăm să aşteptaţi",
            "CHANGE_GW_NAME_SETTING":"Preluare",
            "CONFIRM_DELETE_GROUP":"Ștergere aparat",
            "GENERAL_NO":"Nu",
            "DESC_GWSCREEN_ADD":"Adăugare Gateway local",
            "DRIVE_MESSAGE_NOT_RETRACTED":"Neretractat",
            "WIFI_PASSPHRASE":"Parolă",
            "CHANNEL_ON":"Pornit",
            "SCENARIOS":"Scenarii",
            "ERROR_SET_ADMIN_RIGHTS":"Nu este posibil",
            "DESC_DEFAULT_GW_SAVE":"Setare acces rapid pentru Gateway activ",
            "POPUP_INFO":"Indicație",
            "DRIVE_MESSAGE_ERROR":"ATENŢIE: Eroare",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Nume reţea",
            "EMAIL_BODY":"Puteţi să ne trimiteţi întrebările dvs. prin e-mail. Aici vă stă la dispoziţie funcţia noastră de FAQ.\n\n Echipa dumneavoastră de suport BiSecur-Home",
            "CONFIRM_DELETE_USER":"Ştergere utilizator",
            "DESC_CHANNELS_BACK":"Înapoi la lista aparatelor",
            "CHANGE_PWD_FIRST_START":"Din considerente de siguranţă modificaţi după prima înregistrare setările din fabrică ale parolei",
            "GENERAL_DEFAULT_GATEWAY":"Acces rapid",
            "CHANGE_PWD_PASSWORD_INVALID":"Eroare",
            "ERROR_NO_GW_TITLE":"Fără gateway",
            "POPUP_SETTING_STATE_CONTENT":"Comanda se execută",
            "WIFI_LOADING_DATA_CONTENT":"Se încarcă datele WLAN",
            "OPTIONS_RESET_LOGIN_DATA":"Ştergerea datelor de autentificare salvate",
            "EDIT_USER_TITLE":"Editare utilizator",
            "DESC_HOME_PREFERENCES":"Modificarea setărilor Gateway şi setărilor aplicaţiei",
            "WIFI_ACTIVE_STATE":"Stare WLAN",
            "STATE_COLLECTING":"Încarcă",
            "ADD_SCENARIO":"Adăugare scenariu",
            "STATE_COLLECTING_FAILED_CONTENT":"Starea nu s-a încărcat",
            "GATE_SWING_GATE_SINGLE":"Poartă batantă cu un canat",
            "ACTORS":"Aparate:",
            "POPUP_AGREEMENT":"Utilizare / protecţia datelor.",
            "CHANNEL_OPEN_DOOR":"Deschidere",
            "DESC_ACTORS_REFRESH":"Actualizarea stării",
            "GENERAL_OFF":"Oprit",
            "OPTIONS_HELP":"Ajutor online",
            "COPY_PORTS_CONTENT":"Comutaţi emiţătorul în modul de moştenire, vezi instrucţiunile de utilizare. Alegeţi un canal care se doreşte moştenit.",
            "GENERAL_SELECT":"Vă rugăm să selectaţi ...",
            "ERROR_ADAPTER_BUSY":"Eroare",
            "INFO_BOX_INFOS":"General",
            "GATE_LIGHT":"Lumină",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Deschidere condiţii de utilizare",
            "DESC_MANAGE_POPUPS_WARNINGS":"Ascunderea pop -up -urilor de avertizare",
            "MAX_USERSS_REACHED_CONTENT":"A fost atins numărul maxim de utilizatori.",
            "GENERAL_REMOVE":"Ștergere",
            "OPTIONS":"Setări",
            "DESC_HOME_SCENARIOS":"Elaborarea şi administrarea scenariilor",
            "CHANNEL_OFF":"Oprit",
            "GENERAL_PORTAL_ID":"ID aparat",
            "EDIT_GROUP":"Prelucrare aparat",
            "ERROR_LERANIN_PORT_CONTENT":"Învăţarea canalului dorit a eşuat",
            "ERROR_CONNECTION_CLOSED":"Eroare",
            "CHANNEL_ON_OFF":"Pornit / oprit",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Cod de identificare",
            "OPTIONS_EDIT_USERS":"Administrare utilizatori",
            "LOADING_STATES_CONTENT":"Starea actuală este apelată.\nVă rugăm să aşteptaţi ...",
            "LERAN_PORTS_CONTENT":"Comutaţi aparatul în modul de învăţare, vezi instrucţiunile de utilizare. Alegeţi un canal care se doreşte învăţat.",
            "REMOVE_PORTS_CONTENT":"Selectaţi canalele pe care doriţi să le ştergeţi.",
            "GATE_SWING_GATE_DOUBLE":"Poartă batantă cu două canaturi",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Verificaţi, dacă datele portalului dumneavoastră sau dacă un Gateway a fost adăugat.",
            "CHANNEL_SINK":"Coborâre",
            "OPTIONS_EDIT_USERS_TITLE":"Utilizator",
            "MAX_PORTS_REACHED_CONTENT":"S-a atins numărul maxim de canale ocupate",
            "MAX_PORTS_REACHED":"Nu este posibil",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Aparatul solicitat nu a putut fi accesat",
            "PORTAL_AUTHENTICATION_FAILED":"Eşuat",
            "NOTIFICATION_CENTER":"Înştiinţări",
            "LEARNING_PROCESS":"Învăţare",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Numele de utilizator trebuie să aibă între 2 şi 20 caractere",
            "WIFI_STATE_CONNECTED":"Conectat",
            "COPY_PORTS":"Moştenire de la transmiţătorul radio",
            "POPUP_SEARCH_CONTENT":"Căutare Gateway Hörmann \n\nAcest proces poate dura câteva secunde.",
            "DESC_MANAGE_POPUPS_CANCEL":"Anulare operaţiune",
            "DESC_WIFI_PASSWORD":"Parolă",
            "DESC_WIFI_SAVE":"Salvează",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop activat",
            "SELECT_GATEWAY":"Gateway-uri",
            "CLEANING_PORTS":"Adăugare aparat",
            "WIFI_STATE_BUSY":"Se stabileşte conexiunea",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Parola introdusă este falsă.",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Modificare nume Gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Numele a fost preluat",
            "DESC_ACTORS_EDIT":"Administrarea şi ştergerea aparatelor",
            "DESC_WIFI_STATE":"Stare conexiune",
            "ERROR_REMOVE_USER":"Eşuat",
            "LANG_TAG":"RO",
            "DESC_MANAGE_POPUPS_SUBMIT":"Preluare setare",
            "HOME_TITLE":"Pagina principală",
            "GENERAL_USERNAME":"Nume utilizator",
            "DRIVE_MESSAGE_OPENED":"Deschisă",
            "CONFIRM_DELETE":"Sunteţi sigur că doriţi să ştergeţi gateway?",
            "DRIVE_MESSAGE_CLOSED":"Închis",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Serverul portalului nu a putut fi accesat",
            "REMOVING_PROCESS_CONTENT":"Se şterge canalul",
            "DESC_EDIT_USERS_BACK":"Înapoi la setări",
            "ERROR_NO_GROUP_FOUND":"Aparat negăsit",
            "ERROR_INVALID_GATEWAY":"Nu s-a găsit niciun gateway",
            "DESC_WIFI_BACK":"Înapoi la setări",
            "MAX_USERS_REACHED":"Nu este posibil",
            "DESC_CHANGE_PASSWORD_USERNAME":"Nume utilizator",
            "POPUP_AGREEMENT_ACCEPT_USE":"Accept condiţiile de utilizare",
            "ERROR_LERNING_PORT":"Eşuat",
            "POPUP_ADD_GATEWAY_CONTENT":"Introducere adresă IP:",
            "ERROR_ADD_GROUP":"Eroare",
            "DRIVE_MESSAGE_NO_DATA":"Nu sunt date disponibile",
            "CHANGE_PWD_FAILED":"Eşuat",
            "SAVING_USER_RIGHTS_CONTENT":"Autorizaţiile utilizatorului sunt salvate",
            "DRIVE_MESSAGE_UNLOCKED":"nu este blocat",
            "GENERAL_SAVE":"Salvează",
            "INFO_BOX_FAQ":"Întrebări frecvente",
            "GENERAL_CONNNECT":"Conectare",
            "GATE_SECTIONAL_DOOR":"Uşă de garaj cu ghidaj vertical",
            "OPTIONS_CHANGE_PASSWORD":"Modificare parolă",
            "CHANNEL":"Utilizare",
            "CHANGE_GW_NAME_CONTENT":"Nume gateway",
            "DRIVE_MESSAGE_RETRACTED":"Retractat",
            "DESC_ADDGWSCREEN_BACK":"Înapoi la lista cu Gateway",
            "EMAIL_SUBJECT":"Suport",
            "ERROR_EDIT_ADMIN":"Nu este posibil",
            "OPTIONS_SET_USER_RIGHTS":"Drepturi utilizator",
            "CHANGE_GW_NAME_ERROR":"Eşuat",
            "CHANNEL_LIFT":"Ridicare",
            "LOGIN_FAILED_TITLE":"Eşuat",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Dacă confirmaţi cu OK ştergerea datelor de autentificare, la selectarea Gateway parola trebuie introdusă din nou",
            "CHANNEL_UNLOCK":"Deblocare",
            "GENERAL_PORTAL_SERVER":"Server portal",
            "DESC_SCENARIOS_BACK":"Înapoi la meniul principal",
            "CHANGE_PWD_USERNAME":"Utilizator:",
            "POPUP_GATE_NOT_RESPONSABLE":"Aplicaţia poate transmite această comandă la aparat însă nu detectează starea actuală a aparatului.",
            "DESC_GW_NAME":"Nume gateway",
            "GATE_BARRIER":"barieră",
            "LEARN_PORTS":"Învăţare cod radio",
            "GENERAL_BACK":"Înapoi",
            "DESC_GWSCREEN_EDIT":"Pentru ştergerea Gateway -urilor salvate",
            "OPTIONS_MANAGE_POPUPS":"Administrarea mesajelor pop -up",
            "POPUP_LOGIN_PROCESS_CONTENT":"Vă rugăm să aşteptaţi ...",
            "CONFIRM_DELETE_USER_CONTENT":"Sunteţi sigur că doriţi să ştergeţi utilizatorul?",
            "DESC_MENU":"Meniu",
            "LOGIN_FAILED_WRONG_DATA":"Numele sau parola introdusă sunt false.",
            "GENERAL_CANCEL":"Anulare",
            "ADD_GROUP":"Adăugare aparat",
            "WIFI_STATE_AP_NOT_FOUND":"Reţea negăsită",
            "WIFI_STATE_NOT_CONNECTED":"Neconectat",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Operarea prin portal este activată!",
            "POPUP_ADD_GATEWAY":"Adăugare gateway",
            "GENERAL_NEXT":"Mai departe",
            "POPUP_SUPPRESS":"Nu se mai deschide fereastra Popup",
            "POPUP_SEARCH_TITLE":"Caută...",
            "WIFI_SCANNING_CONTENT":"Căutarea reţelelor WLAN vizibile",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Nu s-a găsit niciun gateway",
            "DESC_ACTORS_ADD":"Creare aparat",
            "ERROR_ADD_GROUP_NO_TYPE":"Nu s-a selectat niciun tip pentru noul aparat.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Verificaţi datele de autentificare",
            "GENERAL_REFESHED":"Actualizat",
            "OPTIONS_SUPPRESS_WARNINGS":"Ascunderea avertizărilor",
            "LOGIN_FAILED_GATEWAY_BUSY":"Gateway suprasolicitat. Încercaţi din nou.",
            "DESC_EMAIL":"Trimitere e-mail la suport",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"„Permanent deschis” dezactivat",
            "CLEANING_PORTS_CONTENT":"Se pregăteşte adăugarea",
            "DESC_HOME_ACTORS":"Învăţarea şi administrarea aparatelor",
            "ERROR_TIMEOUT":"Eroare de conexiune",
            "CREATE_USER_TITLE":"Adăugare utilizator",
            "ERROR_DELETE_ADMIN_CONTENT":"Administratorul nu poate fi şters",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Acces rapid",
            "ADD_SCENARIO_NAME":"Nume",
            "HIST":"Istoric",
            "DESC_RESET_LOGIN_SUBMIT":"Confirmare ştergere",
            "POPUP_WARNING":"ATENŢIE",
            "REMOVE_GROUP_PROCESS":"Se şterge aparatul",
            "POPUP_LOGIN_PROCESS":"Înregistrare",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Vă rugăm să aşteptaţi ...",
            "DESC_DEFAULT_GW_SUBMIT":"Preluare setare",
            "DESC_CHANGE_PASSWORD_RETYPE":"Repetare introducere",
            "LOAD_USERS_CONTENT":"Se încarcă toţi utilizatorii din Gateway.\nAcest proces poate dura câteva secunde.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Dacă pentru un Gateway este activat accesul rapid, în funcţie de posibilitate aplicaţia se autentifică automat",
            "GATE_OTHER":"Alte aparate",
            "CHANGE_PWD_USER_INVALID":"Eroare",
            "CHANNEL_LIGHT":"Lumină",
            "LOGIN_TITLE":"Înregistrare",
            "CHANNEL_HALF":"Deschidere parţială",
            "GATEWAY_SCREEN_ADD_HELP":"Pentru a adăuga un Gateway alegeţi simbolul+.",
            "ERROR_TIMEOUT_CONTENT":"Depăşirea timpului la comunicarea cu Gateway",
            "ERROR_NO_PORTS_LEARNED":"Adăugarea nu este posibilă",
            "OPTIONS_SUPPRESS_INFOS":"Ascunderea indicaţiilor",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Eroare",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Regim automat",
            "GENERAL_DELETE":"Ștergere",
            "GENERAL_PASSWORD":"Parolă",
            "STATE_COLLECTING_CONTENT":"Se interoghează starea aparatului",
            "ERROR_REMOVE_USER_CONTENT":"Utilizatorul nu a putut fi şters",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Eroare",
            "ACTORS_ADD_HELP":"Pentru a adăuga un aparat alegeţi simbolul+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Sunteţi sigur că doriţi să ştergeţi aparatul?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Vă rugăm să aşteptaţi ...",
            "GENERAL_YES":"Da",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Înainte de adăugarea unui aparat trebuie învăţat cel puţin un canal",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Numele nu a putut fi schimbat",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Aparatul nu a găsit nici un Gateway.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentificare eşuată",
            "DESC_MANAGE_POPUPS_INFOS":"Ascunderea pop -up -urilor de informare",
            "GATE_PILOMAT_POLLER":"Sâlp",
            "DESC_CHANNELS_STATE":"Starea aparatelor capabile de răspuns",
            "DESC_GWSCREEN_REFRESH":"Actualizarea listei de Gateway-uri",
            "POPUP_SCENARIO_DISPATCHING":"Scenariul se execută",
            "ERROR_PORT_UNREACHABLE":"Eşuat",
            "POPUP_GATEWAY_FOUND_CONTENT":"Următoarele Gateway au fost adăugate:",
            "WIFI_STATE_SECURITY_MISMATCH":"Modul de codificare al WLAN nu este suportată",
            "LOGOUT_NAMED":"Logout",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Deschidere condiţii de protecţia datelor",
            "ERROR_NO_GW_CONTENT":"În reţeaua locală nu s-a putut găsi un gateway Hörmann.\nAdăugarea Gateway -uri suplimentare prin tasta+",
            "DESC_EDIT_USERS_ADD":"Adăugare utilizator",
            "ERROR_NO_PORT_FOUND":"Port negăsit",
            "GATE_SLIDING_GATE":"Uşă culisantă",
            "DESC_CHANNELS_BUTTONS":"Elementele de control ale aparatului",
            "DRIVE_MESSAGE_EXTENDED":"Extins",
            "WIFI_SELECTED_NETWORK":"Nume",
            "ERROR_ADD_GROUP_NO_NAME":"Nu a fost introdus niciun nume pentru noul aparat.",
            "DESC_HELP":"Funcţia de ajutor",
            "CHANGE_PWD_NEW_PASSWORD":"Parolă nouă",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Preluare parolă nouă",
            "DESC_CHANGE_PASSWORD_PWD":"Introducere parolă nouă",
            "ERROR_EDIT_ADMIN_CONTENT":"Administratorul nu poate fi editat",
            "CHANGE_GW_NAME_NAME_INVALID":"Eşuat",
            "STATE_COLLECTING_FAILED":"Eroare",
            "GENERAL_ADD":"Adăugare",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"Datele editate la „parolă” şi „repetare parolă” trebuie să fie identice",
            "WIFI_SETTINGS":"Setări WLAN",
            "LEARN_PORTS_TITLE":"Adăugare aparat",
            "ERROR_CHANGE_USERNAME":"Eşuat",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Barieră",
            "ERROR_INVALID_GATEWAY_CONTENT":"Nu a putut fi stabilită nicio conexiune cu gateway. Vă rugăm să verificaţi numele host.",
            "DESC_EDIT_USERS_EDIT":"Ştergere utilizator",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Numele aparatului trebuie să aibă 2 - 20 caractere",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Accesul rapid nu este posibil",
            "CHANNEL_UP":"Deschis",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"„Permanent deschis” activat",
            "PORTAL_VALIDATION_FAILED":"Eşuat",
            "DESC_RESET_LOGIN_CANCEL":"Anulare operaţiune",
            "CHANGE_PWD_SETTING_PASSWORD":"Preluare",
            "LOADING_GROUPS_TITLE":"Încarcă",
            "DESC_DEFAULT_GW_CANCEL":"Anulare operaţiune",
            "DESC_SET_RIGHTS_SAVE":"Preluarea modificărilor",
            "REMOVING_PROCESS":"Ștergere",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Gateway nu este accesibil",
            "CONFIRM_DELETE_TITLE":"Ştergere gateway",
            "SCENARIOS_ADD_HELP":"Pentru a adăuga un scenariu alegeţi simbolul+.",
            "LOGOUT":"Logout",
            "DESC_ACTORS_BACK":"Înapoi la meniul principal",
            "ERROR_ADAPTER_BUSY_CONTENT":"Comanda nu s-a putut executa.\n Gateway suprasolicitat.",
            "DESC_WIFI_NETWORK_SCAN":"Căutare reţea",
            "DRIVE_MESSAGE_HALF":"Întredeschisă",
            "DESC_SCENARIOS_ADD":"Creare scenariu",
            "ERROR_CONNECTION_CLOSED_CONTENT":"A eşuat comunicarea cu Gateway.",
            "SAVING_USER_RIGHTS":"Memorii",
            "DESC_GWSCREEN_PORTAL":"Introducerea datelor portalului",
            "GATE_JACK":"Priză cu comandă radio",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Sunteţi în aceeaşi reţea cu Gateway?",
            "GATE_DOOR":"Uşă",
            "POPUP_PORTAL_UNAVAILABLE":"Serverul portalului nu a putut fi accesat",
            "DESC_SET_RIGHTS_BACK":"Înapoi la utilizatori",
            "GATE_SMARTKEY":"Sistem de acţionare încuietoare uşă",
            "POPUP_GATEWAY_FOUND_TITILE":"Căutare terminată",
            "WIFI_LOADING_DATA_TITLE":"Încarcă",
            "GENERAL_PORTS":"Canale",
            "DESC_SCENARIOS_EDIT":"Administrarea şi ştergerea scenariilor",
            "OPTIONS_LEARNED_PORTS":"Canale învăţate:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Accept condiţiile de protecţia datelor",
            "DESC_EDIT_USERS_SET_RIGHTS":"Selectaţi utilizatorul şi modificaţi drepturile de acces ale acestuia",
            "DRIVE_MESSAGE_HALF_MOVING":"Întredeschisă / în deplasare",
            "PORTAL_SET_ID_DIALOG":"Setările portalului",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Niciun punct de referinţă",
            "POPUP_SETTING_STATE":"Vă rugăm să aşteptaţi ...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Numele de utilizator nu a putut fi modificat",
            "GROUP_REQUESTABLE":"Aparatul este capabil de reacţie",
            "LOADING_STATES_TITLE":"Încarcă",
            "DESC_HOME_USERS":"Administrare utilizatori",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Parola trebuie să aibă între 4 şi 20 caractere",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Parola a fost preluată",
            "POPUP_GATE_OUT_OF_VIEW":"Utilizarea unui sistem de comandă pentru o uşă automată, fără vedere spre uşă este permisă numai dacă aţi instalat în plus faţă de limitarea forţei cu care este dotată în mod standard uşa, o barieră fotoelectrică.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Alegeţi afişarea sau ascunderea mesajelor pop-up",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"autorizat",
            "DRIVE_MESSAGE_LOCKED":"blocat",
            "CHANNEL_DOWN":"Închis",
            "POPUP_INET_SPEED_LOW":"Conexiunea de date nu este suficientă pentru această aplicaţie",
            "CHANGE_PWD_FAILED_CONTENT":"Parola nu a putut fi modificată",
            "GENERAL_GROUP_TYPE":"Tip aparat",
            "CHANNEL_WALK":"Canat de trecere",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Uşă de garaj cu ghidaj orizontal",
            "POPUP_AGREEMENT_CONTENT":"Înainte de utilizarea aplicaţiei acceptaţi condiţiile de protecţie a datelor şi condiţiile de utilizare",
            "INFO":"Informaţii",
            "LOADING_GROUPS_CONTENT":"Încărcare aparate",
            "GATE_PILOMAT_REIFENKILLER":"Distrugător anvelope",
            "GATE_PILOMAT_HUBBALKEN":"Traversă",
            "GENERAL_RETYPE":"Repetare parolă",
            "DESC_OTIONS_BACK":"Înapoi la meniul principal",
            "DESC_SET_RIGHTS":"Selectaţi aparatul şi acordaţi drepturi de acces utilizatorului",
            "WIFI_SCANNING_TITLE":"Căutare",
            "WIFI_STATE_CONNECTION_FAILURE":"Stabilirea conexiunii eşuată",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Numele de utilizator trebuie să aibă între 2 şi 20 caractere",
            "REMOVE_PORTS":"Ștergere",
            "GENERAL_ON":"Pornit",
            "DESC_CHANGE_PASSWORD_CANCEL":"Anulare operaţiune",
            "LEARNING_PROCESS_CONTENT":"Vă rugăm să aşteptaţi ...",
            "LOGIN_FAILED_UNKNOWN":"A apărut o eroare neaşteptată.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Nu pot fi modificate drepturile de utilizator ale administratorului!"
         };
         return _loc1_;
      }
   }
}
