package
{
   import mx.resources.ResourceBundle;
   
   public class ru_RU$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function ru_RU$LocalizedStrings_properties()
      {
         super("ru_RU","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Запирание",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Введите авторизационные данные для портала Hörmann",
            "ERROR_DELETE_ADMIN":"Невозможно",
            "LOGIN_SHOULD_SAVE":"Сохранить введенные данные",
            "LOAD_USERS_TITLE":"Пожалуйста, подождите",
            "CHANGE_GW_NAME_SETTING":"Перенять",
            "CONFIRM_DELETE_GROUP":"Удаление устройства",
            "GENERAL_NO":"нет",
            "DESC_GWSCREEN_ADD":"Добавить локальные сетевые шлюзы",
            "DRIVE_MESSAGE_NOT_RETRACTED":"не задвинут",
            "WIFI_PASSPHRASE":"Пароль",
            "CHANNEL_ON":"Вкл.",
            "SCENARIOS":"Сценарии",
            "ERROR_SET_ADMIN_RIGHTS":"Невозможно",
            "DESC_DEFAULT_GW_SAVE":"Установить быстрый доступ для актуального шлюза",
            "POPUP_INFO":"Примечание",
            "DRIVE_MESSAGE_ERROR":"ВНИМАНИЕ: Ошибка",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/ru/zaschita-dannyh",
            "DESC_WIFI_NETWORK_NAME":"Имя сети",
            "EMAIL_BODY":"Ваши вопросы Вы можете отправить на нашу электронную почту. Для этого Вы можете воспользоваться также нашей функцией часто задаваемых вопросов.\n\nВаша служба технической поддержки портала BiSecur-Home",
            "CONFIRM_DELETE_USER":"Удаление пользователя",
            "DESC_CHANNELS_BACK":"Вернуться к списку устройств",
            "CHANGE_PWD_FIRST_START":"Из соображений безопасности измените заводскую настройку Вашего пароля после первого входа в систему",
            "GENERAL_DEFAULT_GATEWAY":"Быстрый доступ",
            "CHANGE_PWD_PASSWORD_INVALID":"Ошибка",
            "ERROR_NO_GW_TITLE":"Шлюз отсутствует",
            "POPUP_SETTING_STATE_CONTENT":"Команда выполняется",
            "WIFI_LOADING_DATA_CONTENT":"Загружаются данные WLAN",
            "OPTIONS_RESET_LOGIN_DATA":"Удалить сохраненные данные для входа в систему",
            "EDIT_USER_TITLE":"Редактировать пользователя",
            "DESC_HOME_PREFERENCES":"Изменить настройки для шлюза и Приложения",
            "WIFI_ACTIVE_STATE":"Статус сети WLAN",
            "STATE_COLLECTING":"Загрузка",
            "ADD_SCENARIO":"Добавить сценарий",
            "STATE_COLLECTING_FAILED_CONTENT":"Статус не был загружен",
            "GATE_SWING_GATE_SINGLE":"1-створч. распашные ворота",
            "ACTORS":"Устройства",
            "POPUP_AGREEMENT":"Использование / защита данных",
            "CHANNEL_OPEN_DOOR":"Oткрывание",
            "DESC_ACTORS_REFRESH":"Обновить статус",
            "GENERAL_OFF":"Выключено",
            "OPTIONS_HELP":"Помощь онлайн",
            "COPY_PORTS_CONTENT":"Переведите передатчик в режим передачи сигнала, см. инструкцию. Выберите канал, который должен получить сигнал.",
            "GENERAL_SELECT":"Выбрать...",
            "ERROR_ADAPTER_BUSY":"Ошибка",
            "INFO_BOX_INFOS":"Общие данные",
            "GATE_LIGHT":"Освещение",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Открыть Условия пользования",
            "DESC_MANAGE_POPUPS_WARNINGS":"Блокировать всплывающие окна с предупреждениями",
            "MAX_USERSS_REACHED_CONTENT":"Было достигнуто максимальное количество пользователей.",
            "GENERAL_REMOVE":"Удалить",
            "OPTIONS":"Настройки",
            "DESC_HOME_SCENARIOS":"Создание сценария и управление сценарием",
            "CHANNEL_OFF":"Выкл.",
            "GENERAL_PORTAL_ID":"ID устройства",
            "EDIT_GROUP":"Редактировать устройство",
            "ERROR_LERANIN_PORT_CONTENT":"Программирование желаемого канала дало сбой",
            "ERROR_CONNECTION_CLOSED":"Ошибка",
            "CHANNEL_ON_OFF":"Вкл./Выкл.",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Обозначение",
            "OPTIONS_EDIT_USERS":"Управление пользователем",
            "LOADING_STATES_CONTENT":"Запрашивается актуальный статус.\nПодождите...",
            "LERAN_PORTS_CONTENT":"Приведите устройство в режим обучения, см. инструкцию. Выберите канал, который должен послать сигнал.",
            "REMOVE_PORTS_CONTENT":"Выберите каналы, которые Вы хотите удалить.",
            "GATE_SWING_GATE_DOUBLE":"2-створч. распашные ворота",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Проверьте, внесли ли Вы Ваши данные портала или добавили локальный сетевой шлюз.",
            "CHANNEL_SINK":"Опускание",
            "OPTIONS_EDIT_USERS_TITLE":"Пользователь",
            "MAX_PORTS_REACHED_CONTENT":"Занято максимальное количество каналов",
            "MAX_PORTS_REACHED":"Невозможно",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Не удалось соединиться с запрашиваемым устройством",
            "PORTAL_AUTHENTICATION_FAILED":"Произошел сбой",
            "NOTIFICATION_CENTER":"Уведомления",
            "LEARNING_PROCESS":"Обучение",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Имя пользователя должно состоять из 2 - 20 знаков",
            "WIFI_STATE_CONNECTED":"Соединение установлено",
            "COPY_PORTS":"Передать от пульта ДУ",
            "POPUP_SEARCH_CONTENT":"Поиск сетевых шлюзов Hörmann \n\nДанный процесс займет несколько секунд.",
            "DESC_MANAGE_POPUPS_CANCEL":"Отмена операции",
            "DESC_WIFI_PASSWORD":"Пароль",
            "DESC_WIFI_SAVE":"Сохранить",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Стоп активен",
            "SELECT_GATEWAY":"Сетевые шлюзы",
            "CLEANING_PORTS":"Добавить устройство",
            "WIFI_STATE_BUSY":"Производится подключение",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Введенный пароль неверен",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Изменить имя шлюза",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Перенимается имя",
            "DESC_ACTORS_EDIT":"Управлять устройствами или удалить устройства",
            "DESC_WIFI_STATE":"Статус соединения",
            "ERROR_REMOVE_USER":"Произошел сбой",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Принять настройку",
            "HOME_TITLE":"Главная страница",
            "GENERAL_USERNAME":"Имя пользователя",
            "DRIVE_MESSAGE_OPENED":"Открыто",
            "CONFIRM_DELETE":"Вы уверены, что хотите удалить шлюз?",
            "DRIVE_MESSAGE_CLOSED":"Закрыто",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Не удалось соединиться с сервером портала",
            "REMOVING_PROCESS_CONTENT":"Канал удаляется",
            "DESC_EDIT_USERS_BACK":"Вернуться к настройкам",
            "ERROR_NO_GROUP_FOUND":"Устройство не найдено",
            "ERROR_INVALID_GATEWAY":"Шлюз не найден",
            "DESC_WIFI_BACK":"Вернуться к настройкам",
            "MAX_USERS_REACHED":"Невозможно",
            "DESC_CHANGE_PASSWORD_USERNAME":"Имя пользователя",
            "POPUP_AGREEMENT_ACCEPT_USE":"Я согласен(-на) с Условиями пользования",
            "ERROR_LERNING_PORT":"Произошел сбой",
            "POPUP_ADD_GATEWAY_CONTENT":"Введите IP-адрес:",
            "ERROR_ADD_GROUP":"Ошибка",
            "DRIVE_MESSAGE_NO_DATA":"Нет доступных данных",
            "CHANGE_PWD_FAILED":"Произошел сбой",
            "SAVING_USER_RIGHTS_CONTENT":"Права пользователя сохраняются",
            "DRIVE_MESSAGE_UNLOCKED":"Не заперта",
            "GENERAL_SAVE":"Сохранить",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Соединить",
            "GATE_SECTIONAL_DOOR":"Открывающиеся вертикально гаражные ворота",
            "OPTIONS_CHANGE_PASSWORD":"Сменить пароль",
            "CHANNEL":"Эксплуатация",
            "CHANGE_GW_NAME_CONTENT":"Имя шлюза",
            "DRIVE_MESSAGE_RETRACTED":"задвинут",
            "DESC_ADDGWSCREEN_BACK":"Назад к списку сетевых шлюзов",
            "EMAIL_SUBJECT":"Служба поддержки",
            "ERROR_EDIT_ADMIN":"Невозможно",
            "OPTIONS_SET_USER_RIGHTS":"Права пользователя",
            "CHANGE_GW_NAME_ERROR":"Произошел сбой",
            "CHANNEL_LIFT":"Подъем",
            "LOGIN_FAILED_TITLE":"Произошел сбой",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Если, нажав на ОК, Вы подтвердите удаление данных для входа в систему, то при выборе шлюза надо будет вновь ввести пароль",
            "CHANNEL_UNLOCK":"Pазблокировка",
            "GENERAL_PORTAL_SERVER":"Сервер портала",
            "DESC_SCENARIOS_BACK":"Вернуться в главное меню",
            "CHANGE_PWD_USERNAME":"Пользователь:",
            "POPUP_GATE_NOT_RESPONSABLE":"Приложение может отправить эту команду на устройство, при этом оно не распознает актуальное состояние устройства.",
            "DESC_GW_NAME":"Имя шлюза",
            "GATE_BARRIER":"шлагбаум",
            "LEARN_PORTS":"Программирование радиокода",
            "GENERAL_BACK":"Вернуться назад",
            "DESC_GWSCREEN_EDIT":"Перейти к удалению сохраненных шлюзов",
            "OPTIONS_MANAGE_POPUPS":"Управление всплывающими окнами с сообщениями",
            "POPUP_LOGIN_PROCESS_CONTENT":"Подождите...",
            "CONFIRM_DELETE_USER_CONTENT":"Вы уверены, что хотите удалить пользователя?",
            "DESC_MENU":"Меню",
            "LOGIN_FAILED_WRONG_DATA":"Неверное имя пользователя или неверный пароль",
            "GENERAL_CANCEL":"Отмена",
            "ADD_GROUP":"Добавить устройство",
            "WIFI_STATE_AP_NOT_FOUND":"Сеть не найдена",
            "WIFI_STATE_NOT_CONNECTED":"Соединение не установлено",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Ваше управление через Портал активировано!",
            "POPUP_ADD_GATEWAY":"Добавить шлюз",
            "GENERAL_NEXT":"Далее",
            "POPUP_SUPPRESS":"Больше не открывать всплывающее окно",
            "POPUP_SEARCH_TITLE":"Поиск...",
            "WIFI_SCANNING_CONTENT":"Поиск видимых сетей WLAN",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Шлюз не найден",
            "DESC_ACTORS_ADD":"Создать устройство",
            "ERROR_ADD_GROUP_NO_TYPE":"Не выбран тип для нового устройства.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Проверьте данные для входа в систему",
            "GENERAL_REFESHED":"Актуализированы",
            "OPTIONS_SUPPRESS_WARNINGS":"Отменить предупреждения",
            "LOGIN_FAILED_GATEWAY_BUSY":"Шлюз перегружен. Повторите попытку.",
            "DESC_EMAIL":"Отправить сообщение по электронной почте в службу поддержки",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Длит. Откр. Выкл.",
            "CLEANING_PORTS_CONTENT":"Идет подготовка к добавлению",
            "DESC_HOME_ACTORS":"Программирование устройств и управление устройствами",
            "ERROR_TIMEOUT":"Тайм-аут",
            "CREATE_USER_TITLE":"Добавить пользователя",
            "ERROR_DELETE_ADMIN_CONTENT":"Администратор не может быть удален",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Быстрый доступ",
            "ADD_SCENARIO_NAME":"Имя",
            "HIST":"История",
            "DESC_RESET_LOGIN_SUBMIT":"Подтвердить удаление",
            "POPUP_WARNING":"ВНИМАНИЕ!",
            "REMOVE_GROUP_PROCESS":"Устройство удаляется",
            "POPUP_LOGIN_PROCESS":"Войти",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Подождите...",
            "DESC_DEFAULT_GW_SUBMIT":"Принять настройку",
            "DESC_CHANGE_PASSWORD_RETYPE":"Повторить ввод",
            "LOAD_USERS_CONTENT":"Данные пользователей загружаются со шлюза.\nДанный процесс займет несколько секунд.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Если для сетевого шлюза активирована функция быстрого доступа, то приложение автоматически включается по мере возможности",
            "GATE_OTHER":"Прочие устройства",
            "CHANGE_PWD_USER_INVALID":"Ошибка",
            "CHANNEL_LIGHT":"Освещение",
            "LOGIN_TITLE":"Войти",
            "CHANNEL_HALF":"Частичное открывание",
            "GATEWAY_SCREEN_ADD_HELP":"Чтобы добавить сетевой шлюз, выберите символ+.",
            "ERROR_TIMEOUT_CONTENT":"Истечение времени ожидания при соединении со шлюзом",
            "ERROR_NO_PORTS_LEARNED":"Добавление невозможно",
            "OPTIONS_SUPPRESS_INFOS":"Отменить указания",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Ошибка",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Автоматический режим",
            "GENERAL_DELETE":"Удалить",
            "GENERAL_PASSWORD":"Пароль",
            "STATE_COLLECTING_CONTENT":"Запрашивается статус устройства",
            "ERROR_REMOVE_USER_CONTENT":"Не удалось удалить пользователя",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Ошибка",
            "ACTORS_ADD_HELP":"Чтобы добавить устройство, выберите символ+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Вы уверены, что хотите удалить устройство?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Подождите...",
            "GENERAL_YES":"да",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Перед добавлением устройства запрограммируйте как минимум один канал",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Имя не могло быть изменено",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Приложение пока не нашло сетевой шлюз.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Произошел сбой аутентификации",
            "DESC_MANAGE_POPUPS_INFOS":"Блокировать всплывающие окна с сообщениями",
            "GATE_PILOMAT_POLLER":"Боллард",
            "DESC_CHANNELS_STATE":"Статус устройства с функцией обратной связи",
            "DESC_GWSCREEN_REFRESH":"Обновить список шлюзов",
            "POPUP_SCENARIO_DISPATCHING":"Сценарий выполняется",
            "ERROR_PORT_UNREACHABLE":"Произошел сбой",
            "POPUP_GATEWAY_FOUND_CONTENT":"Были добавлены следующие сетевые шлюзы:",
            "WIFI_STATE_SECURITY_MISMATCH":"Тип шифрования WLAN не поддерживается",
            "LOGOUT_NAMED":"Выход",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Открыть Условия защиты данных",
            "ERROR_NO_GW_CONTENT":"Шлюз Hörmann в локальной сети не найден.\nДобавьте другие шлюзы с помощью знака+",
            "DESC_EDIT_USERS_ADD":"Добавить пользователя",
            "ERROR_NO_PORT_FOUND":"Порт не найден",
            "GATE_SLIDING_GATE":"Откатные ворота",
            "DESC_CHANNELS_BUTTONS":"Элементы управления устройства",
            "DRIVE_MESSAGE_EXTENDED":"выдвинут",
            "WIFI_SELECTED_NETWORK":"Имя",
            "ERROR_ADD_GROUP_NO_NAME":"Не введено имя для нового устройства.",
            "DESC_HELP":"Функция помощи",
            "CHANGE_PWD_NEW_PASSWORD":"Новый пароль",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Принять новый пароль",
            "DESC_CHANGE_PASSWORD_PWD":"Ввод нового пароля",
            "ERROR_EDIT_ADMIN_CONTENT":"Редактирование администратора невозможно",
            "CHANGE_GW_NAME_NAME_INVALID":"Произошел сбой",
            "STATE_COLLECTING_FAILED":"Ошибка",
            "GENERAL_ADD":"Добавить",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"Данные в полях \"Пароль\" и \"Повторите пароль\" должны быть одинаковыми",
            "WIFI_SETTINGS":"Настройки WLAN",
            "LEARN_PORTS_TITLE":"Добавить устройство",
            "ERROR_CHANGE_USERNAME":"Произошел сбой",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Въездной барьер",
            "ERROR_INVALID_GATEWAY_CONTENT":"Соединение со шлюзом не состоялось. Проверьте сетевое имя шлюза.",
            "DESC_EDIT_USERS_EDIT":"Удаление пользователя",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Имя устройства должно состоять из 2 - 20 знаков",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Быстрый доступ невозможен",
            "CHANNEL_UP":"Откр.",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Длит. Откр. Вкл.",
            "PORTAL_VALIDATION_FAILED":"Произошел сбой",
            "DESC_RESET_LOGIN_CANCEL":"Отмена операции",
            "CHANGE_PWD_SETTING_PASSWORD":"Перенять",
            "LOADING_GROUPS_TITLE":"Загрузка",
            "DESC_DEFAULT_GW_CANCEL":"Отмена операции",
            "DESC_SET_RIGHTS_SAVE":"Принять изменения",
            "REMOVING_PROCESS":"Удалить",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Шлюз недоступен",
            "CONFIRM_DELETE_TITLE":"Удаление шлюза",
            "SCENARIOS_ADD_HELP":"Чтобы добавить сценарий, выберите символ+.",
            "LOGOUT":"Выход",
            "DESC_ACTORS_BACK":"Вернуться в главное меню",
            "ERROR_ADAPTER_BUSY_CONTENT":"Команда не может быть выполнена.\n Шлюз перегружен.",
            "DESC_WIFI_NETWORK_SCAN":"Искать сети",
            "DRIVE_MESSAGE_HALF":"Частично открыто",
            "DESC_SCENARIOS_ADD":"Создать сценарий",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Соединение со шлюзом прервано",
            "SAVING_USER_RIGHTS":"Сохранение",
            "DESC_GWSCREEN_PORTAL":"Ввод данных портала",
            "GATE_JACK":"Розетка с дистанционным управлением",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Вы находитесь в одной сети с Вашим сетевым шлюзом?",
            "GATE_DOOR":"Дверь",
            "POPUP_PORTAL_UNAVAILABLE":"Не удалось соединиться с сервером портала",
            "DESC_SET_RIGHTS_BACK":"Вернуться к списку пользователей",
            "GATE_SMARTKEY":"Привод дверного замка",
            "POPUP_GATEWAY_FOUND_TITILE":"Процесс поиска завершен",
            "WIFI_LOADING_DATA_TITLE":"Загрузка",
            "GENERAL_PORTS":"Каналы",
            "DESC_SCENARIOS_EDIT":"Управлять сценариями или удалить сценарии",
            "OPTIONS_LEARNED_PORTS":"Запрограммированные каналы:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Я согласен(-на) с Условиями защиты данных",
            "DESC_EDIT_USERS_SET_RIGHTS":"Выбрать пользователя, чтобы изменить его права доступа",
            "DRIVE_MESSAGE_HALF_MOVING":"Частично открыты / Движутся",
            "PORTAL_SET_ID_DIALOG":"Настройки портала",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Отсутствуют базовые значения",
            "POPUP_SETTING_STATE":"Подождите...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/ru/uslovia-polzovania",
            "ERROR_CHANGE_USERNAME_CONTENT":"Не удалось изменить имя пользователя",
            "GROUP_REQUESTABLE":"Устройство обладает функцией обратной связи",
            "LOADING_STATES_TITLE":"Загрузка",
            "DESC_HOME_USERS":"Управление пользователем",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Пароль должен состоять из 4 - 20 знаков",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Пароль перенимается",
            "POPUP_GATE_OUT_OF_VIEW":"Управление автоматическими воротами вне зоны видимости ворот допускается только при наличии на них светового барьера дополнительно к серийному ограничению усилия.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Выберите, показывать или блокировать всплывающие окна с сообщениями",
            "CHANNEL_IMPULS":"Импульс",
            "PORTAL_VALIDATION_SUCCEEDED":"Авторизованный",
            "DRIVE_MESSAGE_LOCKED":"Заперта",
            "CHANNEL_DOWN":"Закр.",
            "POPUP_INET_SPEED_LOW":"Вашего канала передачи данных недостаточно для этого приложения",
            "CHANGE_PWD_FAILED_CONTENT":"Не удалось изменить пароль",
            "GENERAL_GROUP_TYPE":"Тип устройства",
            "CHANNEL_WALK":"Проходная створка",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Открывающиеся горизонтально гаражные ворота",
            "POPUP_AGREEMENT_CONTENT":"Перед использованием Приложения согласитесь с Условиями пользования и Условиями защиты данных",
            "INFO":"Сведения",
            "LOADING_GROUPS_CONTENT":"Загрузка устройства",
            "GATE_PILOMAT_REIFENKILLER":"Шиповой барьер",
            "GATE_PILOMAT_HUBBALKEN":"Заградительный барьер",
            "GENERAL_RETYPE":"Повторите пароль",
            "DESC_OTIONS_BACK":"Вернуться в главное меню",
            "DESC_SET_RIGHTS":"Выбрать устройство, чтобы предоставить пользователю право доступа",
            "WIFI_SCANNING_TITLE":"Поиск",
            "WIFI_STATE_CONNECTION_FAILURE":"Произошел сбой соединения",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Имя пользователя должно состоять из 2 - 20 знаков",
            "REMOVE_PORTS":"Удалить",
            "GENERAL_ON":"Включено",
            "DESC_CHANGE_PASSWORD_CANCEL":"Отмена операции",
            "LEARNING_PROCESS_CONTENT":"Подождите...",
            "LOGIN_FAILED_UNKNOWN":"Возникла неожиданная ошибка.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Пользовательские права администратора не могут быть изменены"
         };
         return _loc1_;
      }
   }
}
