package
{
   import mx.resources.ResourceBundle;
   
   public class sk_SK$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function sk_SK$LocalizedStrings_properties()
      {
         super("sk_SK","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Zamknúť",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Zadajte prístupové údaje portálu Hörmann",
            "ERROR_DELETE_ADMIN":"Nie je možné",
            "LOGIN_SHOULD_SAVE":"Uložiť údaje",
            "LOAD_USERS_TITLE":"Čakajte prosím",
            "CHANGE_GW_NAME_SETTING":"Prevziať",
            "CONFIRM_DELETE_GROUP":"Vymazať prístroj",
            "GENERAL_NO":"Nie",
            "DESC_GWSCREEN_ADD":"Pridať lokálne gateways",
            "DRIVE_MESSAGE_NOT_RETRACTED":"nezasunutý",
            "WIFI_PASSPHRASE":"Heslo",
            "CHANNEL_ON":"Zap",
            "SCENARIOS":"Scenáre",
            "ERROR_SET_ADMIN_RIGHTS":"Nie je možné",
            "DESC_DEFAULT_GW_SAVE":"Zriadiť rýchly prístup pre aktuálnu gateway",
            "POPUP_INFO":"Upozornenie",
            "DRIVE_MESSAGE_ERROR":"POZOR: chyba",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Názov siete",
            "EMAIL_BODY":"Vaše otázky nám môžete poslať e-mailom. Na tento účel máte k dispozícii aj našu funkciu veľmi častých otázok (FAQ).\n\nVáš tím technickej podpory BiSecur-Home",
            "CONFIRM_DELETE_USER":"Vymazať užívateľa",
            "DESC_CHANNELS_BACK":"Naspäť do zoznamu prístrojov",
            "CHANGE_PWD_FIRST_START":"Po prvom prihlásení zmeňte z bezpečnostných dôvodov nastavenie vášho hesla zo závodu",
            "GENERAL_DEFAULT_GATEWAY":"Rýchly prístup",
            "CHANGE_PWD_PASSWORD_INVALID":"Chyba",
            "ERROR_NO_GW_TITLE":"Žiadne gateways",
            "POPUP_SETTING_STATE_CONTENT":"Príkaz sa vykonáva",
            "WIFI_LOADING_DATA_CONTENT":"Údaje WLAN sa nahrávajú",
            "OPTIONS_RESET_LOGIN_DATA":"Vymazať uložené prihlasovacie údaje",
            "EDIT_USER_TITLE":"Správa používateľov",
            "DESC_HOME_PREFERENCES":"Zmeniť nastavenia ku gateway a aplikácii",
            "WIFI_ACTIVE_STATE":"Stav WLAN",
            "STATE_COLLECTING":"Nahraj",
            "ADD_SCENARIO":"Pridať scenár",
            "STATE_COLLECTING_FAILED_CONTENT":"Stav nebol nahratý",
            "GATE_SWING_GATE_SINGLE":"1-krídlová otváravá brána",
            "ACTORS":"Prístroje",
            "POPUP_AGREEMENT":"Použitie / ochrana údajov",
            "CHANNEL_OPEN_DOOR":"Otvoriť",
            "DESC_ACTORS_REFRESH":"Aktualizovať stav",
            "GENERAL_OFF":"Vypnutý",
            "OPTIONS_HELP":"Online nápoveda",
            "COPY_PORTS_CONTENT":"Vysielač prestavte do režimu odovzdania, pozri návod. Zvoľte kanál, ktorý sa má odovzdať.",
            "GENERAL_SELECT":"Zvoľte prosím...",
            "ERROR_ADAPTER_BUSY":"Chyba",
            "INFO_BOX_INFOS":"Všeobecne",
            "GATE_LIGHT":"Svetlo",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Otvoriť podmienky použitia",
            "DESC_MANAGE_POPUPS_WARNINGS":"Skryť výstražné vyskakovacie okná",
            "MAX_USERSS_REACHED_CONTENT":"Maximálny počet užívateľov bol dosiahnutý.",
            "GENERAL_REMOVE":"Odstrániť",
            "OPTIONS":"Nastavenia",
            "DESC_HOME_SCENARIOS":"Vytváranie a správa scenárov",
            "CHANNEL_OFF":"Vyp",
            "GENERAL_PORTAL_ID":"ID prístroja",
            "EDIT_GROUP":"Spracovať prístroj",
            "ERROR_LERANIN_PORT_CONTENT":"Zaúčanie požadovaného kanálu zlyhalo",
            "ERROR_CONNECTION_CLOSED":"Chyba",
            "CHANNEL_ON_OFF":"Zap / Vyp",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Označenie",
            "OPTIONS_EDIT_USERS":"Správa užívateľov",
            "LOADING_STATES_CONTENT":"Aktuálny stav sa vyvolá.\nČakajte prosím...",
            "LERAN_PORTS_CONTENT":"Prístroj prestavte do režimu zaúčania, pozri návod. Zvoľte kanál, ktorý sa má zaučiť.",
            "REMOVE_PORTS_CONTENT":"Zvoľte kanály, ktoré by ste chceli vymazať.",
            "GATE_SWING_GATE_DOUBLE":"2-krídlová otváravá brána",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Prekontrolujte, či ste zadali svoje údaje o portáli alebo pridali lokálnu gateway.",
            "CHANNEL_SINK":"Spúšťanie",
            "OPTIONS_EDIT_USERS_TITLE":"Užívateľ",
            "MAX_PORTS_REACHED_CONTENT":"Maximálny počet kanálov obsadený",
            "MAX_PORTS_REACHED":"Nie je možné",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Kontrolovaný prístroj nebolo možné dosiahnuť",
            "PORTAL_AUTHENTICATION_FAILED":"Zlyhalo",
            "NOTIFICATION_CENTER":"Správy",
            "LEARNING_PROCESS":"Zaučiť",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Meno užívateľa musí pozostávať zo 2 – 20 znakov",
            "WIFI_STATE_CONNECTED":"Spojené",
            "COPY_PORTS":"Odovzdať z ručného vysielača",
            "POPUP_SEARCH_CONTENT":"Vyhľadávanie podľa brán Hörmann \n\nTento proces môže trvať niekoľko sekúnd!",
            "DESC_MANAGE_POPUPS_CANCEL":"Zrušiť akciu",
            "DESC_WIFI_PASSWORD":"Heslo",
            "DESC_WIFI_SAVE":"Uložiť",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Zastavenie aktívne",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Pridať prístroj",
            "WIFI_STATE_BUSY":"Spojenie sa vytvára",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Zadané heslo je nesprávne",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Zmena názvu gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Meno sa preberie",
            "DESC_ACTORS_EDIT":"Správa alebo vymazávanie prístrojov",
            "DESC_WIFI_STATE":"Stav spojenia",
            "ERROR_REMOVE_USER":"Zlyhalo",
            "LANG_TAG":"SK",
            "DESC_MANAGE_POPUPS_SUBMIT":"Prevziať nastavenie",
            "HOME_TITLE":"Hlavná strana",
            "GENERAL_USERNAME":"Meno užívateľa",
            "DRIVE_MESSAGE_OPENED":"Otvorená",
            "CONFIRM_DELETE":"Ste si istý, že chcete vymazať gateway?",
            "DRIVE_MESSAGE_CLOSED":"Zatvorená",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Server portálu nebolo možné dosiahnuť",
            "REMOVING_PROCESS_CONTENT":"Kanál sa vymaže",
            "DESC_EDIT_USERS_BACK":"Naspäť k nastaveniam",
            "ERROR_NO_GROUP_FOUND":"Prístroj nenájdený",
            "ERROR_INVALID_GATEWAY":"Nenájdená žiadna gateway",
            "DESC_WIFI_BACK":"Naspäť k nastaveniam",
            "MAX_USERS_REACHED":"Nie je možné",
            "DESC_CHANGE_PASSWORD_USERNAME":"Meno užívateľa",
            "POPUP_AGREEMENT_ACCEPT_USE":"Akceptujem podmienky použitia",
            "ERROR_LERNING_PORT":"Zlyhalo",
            "POPUP_ADD_GATEWAY_CONTENT":"Zadajte IP adresu:",
            "ERROR_ADD_GROUP":"Chyba",
            "DRIVE_MESSAGE_NO_DATA":"Údaje nie sú dostupné",
            "CHANGE_PWD_FAILED":"Zlyhalo",
            "SAVING_USER_RIGHTS_CONTENT":"Užívateľské práva sa ukladajú",
            "DRIVE_MESSAGE_UNLOCKED":"nezablokované",
            "GENERAL_SAVE":"Uložiť",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Spojiť",
            "GATE_SECTIONAL_DOOR":"Vertikálne sa presúvajúca garážová brána",
            "OPTIONS_CHANGE_PASSWORD":"Zmeniť heslo",
            "CHANNEL":"Obsluha",
            "CHANGE_GW_NAME_CONTENT":"Názov gateway",
            "DRIVE_MESSAGE_RETRACTED":"zasunutý",
            "DESC_ADDGWSCREEN_BACK":"Naspäť do prehľadu gateways",
            "EMAIL_SUBJECT":"Technická podpora",
            "ERROR_EDIT_ADMIN":"Nie je možné",
            "OPTIONS_SET_USER_RIGHTS":"Užívateľské práva",
            "CHANGE_GW_NAME_ERROR":"Zlyhalo",
            "CHANNEL_LIFT":"Zdvíhanie",
            "LOGIN_FAILED_TITLE":"Zlyhalo",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Ak vymazanie prihlasovacích údajov potvrdíte pomocou OK, musí sa pri výbere gateway opätovne zadať heslo",
            "CHANNEL_UNLOCK":"Odomknúť",
            "GENERAL_PORTAL_SERVER":"Server portálu",
            "DESC_SCENARIOS_BACK":"Naspäť do hlavného menu",
            "CHANGE_PWD_USERNAME":"Užívateľ:",
            "POPUP_GATE_NOT_RESPONSABLE":"Aplikácia môže tento príkaz odoslať prístroju, nerozpozná však aktuálny stav prístroja.",
            "DESC_GW_NAME":"Názov gateway",
            "GATE_BARRIER":"závora",
            "LEARN_PORTS":"Zaučiť rádiový kód",
            "GENERAL_BACK":"Späť",
            "DESC_GWSCREEN_EDIT":"K vymazaniu uložených gateway",
            "OPTIONS_MANAGE_POPUPS":"Správa hlásení vo vyskakovacom okne",
            "POPUP_LOGIN_PROCESS_CONTENT":"Čakajte prosím...",
            "CONFIRM_DELETE_USER_CONTENT":"Ste si istý, že chcete vymazať užívateľa?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"Zadané meno užívateľa alebo heslo je nesprávne",
            "GENERAL_CANCEL":"Zrušiť",
            "ADD_GROUP":"Pridať prístroj",
            "WIFI_STATE_AP_NOT_FOUND":"Sieť nenájdená",
            "WIFI_STATE_NOT_CONNECTED":"Nespojené",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Vaša obsluha prostredníctvom portálu je aktivovaná!",
            "POPUP_ADD_GATEWAY":"Pridať gateway",
            "GENERAL_NEXT":"Ďalej",
            "POPUP_SUPPRESS":"Už neotvárať vyskakovacie okno",
            "POPUP_SEARCH_TITLE":"Vyhľadávanie...",
            "WIFI_SCANNING_CONTENT":"Vyhľadávanie viditeľných sietí WLAN",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Nenájdená žiadna gateway",
            "DESC_ACTORS_ADD":"Vytvoriť prístroj",
            "ERROR_ADD_GROUP_NO_TYPE":"Nebol zvolený typ pre nový prístroj.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Prekontrolujte prihlasovacie údaje",
            "GENERAL_REFESHED":"Aktualizované",
            "OPTIONS_SUPPRESS_WARNINGS":"Skrývať výstrahy",
            "LOGIN_FAILED_GATEWAY_BUSY":"Gateway je vyťažená. Vyskúšajte to znova.",
            "DESC_EMAIL":"Odoslať e-mail technickej podpore",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Doba OTV VYP",
            "CLEANING_PORTS_CONTENT":"Pridanie sa pripravuje",
            "DESC_HOME_ACTORS":"Zaučenie a správa prístrojov",
            "ERROR_TIMEOUT":"Chyba spojenia",
            "CREATE_USER_TITLE":"Pridať užívateľa",
            "ERROR_DELETE_ADMIN_CONTENT":"Administrátora nie je možné vymazať",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Rýchly prístup",
            "ADD_SCENARIO_NAME":"Meno",
            "HIST":"História",
            "DESC_RESET_LOGIN_SUBMIT":"Potvrdiť vymazanie",
            "POPUP_WARNING":"POZOR",
            "REMOVE_GROUP_PROCESS":"Prístroj sa vymaže",
            "POPUP_LOGIN_PROCESS":"Prihlásiť",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Čakajte prosím...",
            "DESC_DEFAULT_GW_SUBMIT":"Prevziať nastavenie",
            "DESC_CHANGE_PASSWORD_RETYPE":"Zopakovať zadanie",
            "LOAD_USERS_CONTENT":"Nahrajú sa všetci užívatelia gateway.\nTento proces môže trvať niekoľko sekúnd.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Ak je gateway aktivovaná pre rýchly prístup, prihlási sa gateway podľa možnosti automaticky",
            "GATE_OTHER":"Ostatné prístroje",
            "CHANGE_PWD_USER_INVALID":"Chyba",
            "CHANNEL_LIGHT":"Svetlo",
            "LOGIN_TITLE":"Prihlásiť",
            "CHANNEL_HALF":"Čiastočné otvorenie",
            "GATEWAY_SCREEN_ADD_HELP":"Na pridanie gateway zvoľte symbol+.",
            "ERROR_TIMEOUT_CONTENT":"Prekročenie času pri komunikácii s gateway",
            "ERROR_NO_PORTS_LEARNED":"Pridanie nie je možné",
            "OPTIONS_SUPPRESS_INFOS":"Skrývať upozornenia",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Chyba",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatická prevádzka",
            "GENERAL_DELETE":"Vymazať",
            "GENERAL_PASSWORD":"Heslo",
            "STATE_COLLECTING_CONTENT":"Zisťuje sa stav prístrojov",
            "ERROR_REMOVE_USER_CONTENT":"Používateľa nebolo možné vymazať",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Chyba",
            "ACTORS_ADD_HELP":"Na pridanie prístroja zvoľte symbol+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Ste si istý, že chcete vymazať prístroj?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Čakajte prosím...",
            "GENERAL_YES":"Áno",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Pred pridaním prístroja zaučiť minimálne jeden kanál",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Meno nebolo možné zmeniť",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Aplikácia ešte nenašla žiadne gateways.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentifikácia zlyhala",
            "DESC_MANAGE_POPUPS_INFOS":"Skryť informačné vyskakovacie okná",
            "GATE_PILOMAT_POLLER":"Stĺpik",
            "DESC_CHANNELS_STATE":"Stav prístroja s poskytovaním spätných hlásení",
            "DESC_GWSCREEN_REFRESH":"Aktualizácia zoznamu gateways",
            "POPUP_SCENARIO_DISPATCHING":"Scenár sa vykonáva",
            "ERROR_PORT_UNREACHABLE":"Zlyhalo",
            "POPUP_GATEWAY_FOUND_CONTENT":"Nasledujúce gateway boli pridané:",
            "WIFI_STATE_SECURITY_MISMATCH":"Druh kódovania siete WLAN sa nepodporuje",
            "LOGOUT_NAMED":"odhlásiť",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Otvoriť podmienky ochrany údajov",
            "ERROR_NO_GW_CONTENT":"V lokálnej sieti nebolo možné nájsť gateway Hörmann.\nĎalšie gateways pridajte prostredníctvom symbolu+",
            "DESC_EDIT_USERS_ADD":"Pridať užívateľa",
            "ERROR_NO_PORT_FOUND":"Port nenájdený",
            "GATE_SLIDING_GATE":"Posuvná brána",
            "DESC_CHANNELS_BUTTONS":"Prvky obsluhy prístroja",
            "DRIVE_MESSAGE_EXTENDED":"vysunutý",
            "WIFI_SELECTED_NETWORK":"Meno",
            "ERROR_ADD_GROUP_NO_NAME":"Nebol zadaný názov pre nový prístroj.",
            "DESC_HELP":"Funkcia nápovedy",
            "CHANGE_PWD_NEW_PASSWORD":"Nové heslo",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Prevziať nové heslo",
            "DESC_CHANGE_PASSWORD_PWD":"Zadanie nového hesla",
            "ERROR_EDIT_ADMIN_CONTENT":"Administrátora nie je možné editovať",
            "CHANGE_GW_NAME_NAME_INVALID":"Zlyhalo",
            "STATE_COLLECTING_FAILED":"Chyba",
            "GENERAL_ADD":"Pridať",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Heslo\" a \"Zopakovať heslo\" musia byť identické",
            "WIFI_SETTINGS":"Nastavenia WLAN",
            "LEARN_PORTS_TITLE":"Pridať prístroj",
            "ERROR_CHANGE_USERNAME":"Zlyhalo",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Prejazdové zábrany",
            "ERROR_INVALID_GATEWAY_CONTENT":"Pomocou gateway nebolo možné vytvoriť žiadne spojenie. Prekontrolujte, prosím, názov hostu.",
            "DESC_EDIT_USERS_EDIT":"Vymazať užívateľa",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Názov prístroja musí pozostávať zo 2 – 20 znakov",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Rýchly prístup nie je možný",
            "CHANNEL_UP":"Otváranie",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Doba OTV ZAP",
            "PORTAL_VALIDATION_FAILED":"Zlyhalo",
            "DESC_RESET_LOGIN_CANCEL":"Zrušiť akciu",
            "CHANGE_PWD_SETTING_PASSWORD":"Prevziať",
            "LOADING_GROUPS_TITLE":"Nahraj",
            "DESC_DEFAULT_GW_CANCEL":"Zrušiť akciu",
            "DESC_SET_RIGHTS_SAVE":"Prevziať zmeny",
            "REMOVING_PROCESS":"Vymazať",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Gateway nie je dostupná",
            "CONFIRM_DELETE_TITLE":"Vymazať gateway",
            "SCENARIOS_ADD_HELP":"Na pridanie scenára zvoľte symbol+.",
            "LOGOUT":"Odhlásiť",
            "DESC_ACTORS_BACK":"Naspäť do hlavného menu",
            "ERROR_ADAPTER_BUSY_CONTENT":"Príkaz nebolo možné vykonať.\n Gateway je vyťažená.",
            "DESC_WIFI_NETWORK_SCAN":"Hľadať podľa sietí",
            "DRIVE_MESSAGE_HALF":"Čiastočne otvorená",
            "DESC_SCENARIOS_ADD":"Vytvoriť scenár",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Komunikácia s gateway zlyhala",
            "SAVING_USER_RIGHTS":"Ukladám",
            "DESC_GWSCREEN_PORTAL":"Zadanie údajov portálu",
            "GATE_JACK":"Rádiová zásuvka",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Nachádzate sa v rovnakej sieti ako vaša gateway?",
            "GATE_DOOR":"Dvere",
            "POPUP_PORTAL_UNAVAILABLE":"Server portálu nebolo možné dosiahnuť",
            "DESC_SET_RIGHTS_BACK":"Naspäť k užívateľom",
            "GATE_SMARTKEY":"Pohon zámku dverí",
            "POPUP_GATEWAY_FOUND_TITILE":"Postup vyhľadávania ukončený",
            "WIFI_LOADING_DATA_TITLE":"Nahraj",
            "GENERAL_PORTS":"Kanály",
            "DESC_SCENARIOS_EDIT":"Správa alebo vymazávanie scenárov",
            "OPTIONS_LEARNED_PORTS":"Zaúčené kanály:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Akceptujem podmienky ochrany údajov",
            "DESC_EDIT_USERS_SET_RIGHTS":"Výber užívateľa pre zmenu jeho prístupových práv",
            "DRIVE_MESSAGE_HALF_MOVING":"Čiastočne otvorená / presúvajúca sa",
            "PORTAL_SET_ID_DIALOG":"Nastavenia portálu",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Žiadny referenčný bod",
            "POPUP_SETTING_STATE":"Čakajte prosím...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Meno používateľa nebolo možné zmeniť",
            "GROUP_REQUESTABLE":"Prístroj je spôsobilý na poskytovanie spätných hlásení",
            "LOADING_STATES_TITLE":"Nahraj",
            "DESC_HOME_USERS":"Správa užívateľov",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Heslo musí pozostávať zo 4 – 20 znakov",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Heslo sa prevezme",
            "POPUP_GATE_OUT_OF_VIEW":"Obsluha automatického bránového systému bez výhľadu na bránu je dovolená iba vtedy, ak ste na bránu nainštalovali svetelnú závoru dodatočne k sériovo prítomnému obmedzeniu sily.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Zvoľte, či sa majú zobraziť alebo skrývať hlásenia vo vyskakovacom okne",
            "CHANNEL_IMPULS":"Impulz",
            "PORTAL_VALIDATION_SUCCEEDED":"Autorizované",
            "DRIVE_MESSAGE_LOCKED":"zablokované",
            "CHANNEL_DOWN":"Zatváranie",
            "POPUP_INET_SPEED_LOW":"Vaše dátové spojenie nepostačuje pre túto aplikáciu",
            "CHANGE_PWD_FAILED_CONTENT":"Heslo nebolo možné zmeniť",
            "GENERAL_GROUP_TYPE":"Typ prístrojov",
            "CHANNEL_WALK":"Prechodové krídlo",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horizontálne sa presúvajúca garážová brána",
            "POPUP_AGREEMENT_CONTENT":"Pred použitím akceptujte prosím podmienky ochrany údajov / použitia",
            "INFO":"Informácie",
            "LOADING_GROUPS_CONTENT":"Nahraj prístroje",
            "GATE_PILOMAT_REIFENKILLER":"Cestné zábrany",
            "GATE_PILOMAT_HUBBALKEN":"Výsuvné stĺpiky",
            "GENERAL_RETYPE":"Zopakovať heslo",
            "DESC_OTIONS_BACK":"Naspäť do hlavného menu",
            "DESC_SET_RIGHTS":"Výber prístroja pre zaručenie prístupových práv užívateľovi",
            "WIFI_SCANNING_TITLE":"Vyhľadávanie",
            "WIFI_STATE_CONNECTION_FAILURE":"Vytváranie spojenia zlyhalo",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Meno užívateľa musí pozostávať zo 2 – 20 znakov",
            "REMOVE_PORTS":"Vymazať",
            "GENERAL_ON":"Zapnutý",
            "DESC_CHANGE_PASSWORD_CANCEL":"Zrušiť akciu",
            "LEARNING_PROCESS_CONTENT":"Čakajte prosím...",
            "LOGIN_FAILED_UNKNOWN":"Vyskytla sa neočakávaná chyba",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Užívateľské práva administrátora nie je možné meniť"
         };
         return _loc1_;
      }
   }
}
