package
{
   import mx.resources.ResourceBundle;
   
   public class sl_SL$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function sl_SL$LocalizedStrings_properties()
      {
         super("sl_SL","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Zaklepanje",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Vnesite podatke za dostop do portala Hörmann",
            "ERROR_DELETE_ADMIN":"Ni možno",
            "LOGIN_SHOULD_SAVE":"Shranite podatke",
            "LOAD_USERS_TITLE":"Prosimo počakajte",
            "CHANGE_GW_NAME_SETTING":"Prevzem",
            "CONFIRM_DELETE_GROUP":"Izbris naprave",
            "GENERAL_NO":"Ne",
            "DESC_GWSCREEN_ADD":"Dodajte lokalne vmesnike",
            "DRIVE_MESSAGE_NOT_RETRACTED":"niso spuščeni",
            "WIFI_PASSPHRASE":"Geslo",
            "CHANNEL_ON":"vklop",
            "SCENARIOS":"Scenariji",
            "ERROR_SET_ADMIN_RIGHTS":"Ni možno",
            "DESC_DEFAULT_GW_SAVE":"Nastavitev hitrega dostopa za aktualni pretvornik",
            "POPUP_INFO":"Navodilo:",
            "DRIVE_MESSAGE_ERROR":"POZOR: napaka",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Ime omrežja",
            "EMAIL_BODY":"Svoja vprašanja nam lahko pošljete po e-pošti. V ta namen vam je na voljo tudi naša funkcija FAQ.\n\n Vaš tim BiSecur za domačo podporo",
            "CONFIRM_DELETE_USER":"Brisanje uporabnika",
            "DESC_CHANNELS_BACK":"Nazaj do seznama priprav",
            "CHANGE_PWD_FIRST_START":"Iz varnostnih razlogov spremenite tovarniško privzeto nastavitev vašega gesla po prvi prijavi",
            "GENERAL_DEFAULT_GATEWAY":"Hitri dostop",
            "CHANGE_PWD_PASSWORD_INVALID":"Napaka",
            "ERROR_NO_GW_TITLE":"Brez vmesnikov",
            "POPUP_SETTING_STATE_CONTENT":"Ukaz se izvaja",
            "WIFI_LOADING_DATA_CONTENT":"Podatki brezžičnega omrežja se nalagajo",
            "OPTIONS_RESET_LOGIN_DATA":"Izbris shranjenih podatkov za prijavo",
            "EDIT_USER_TITLE":"Obdelava uporabnika",
            "DESC_HOME_PREFERENCES":"Spreminjanje nastavitev pretvornika in aplikacije",
            "WIFI_ACTIVE_STATE":"Status brezžičnega omrežja",
            "STATE_COLLECTING":"Napolnite",
            "ADD_SCENARIO":"Dodajte scenarij",
            "STATE_COLLECTING_FAILED_CONTENT":"Status ni bil napolnjen",
            "GATE_SWING_GATE_SINGLE":"1-krilna vrata",
            "ACTORS":"Priprave",
            "POPUP_AGREEMENT":"Uporaba / varstvo podatkov",
            "CHANNEL_OPEN_DOOR":"Odpiranje",
            "DESC_ACTORS_REFRESH":"Aktualiziranje statusa",
            "GENERAL_OFF":"Izključeno",
            "OPTIONS_HELP":"Spletna pomoč",
            "COPY_PORTS_CONTENT":"Prestavite oddajnik v način za prenos, glej navodilo. Izberite kanal, ki ga želite prenesti.",
            "GENERAL_SELECT":"Izberite...",
            "ERROR_ADAPTER_BUSY":"Napaka",
            "INFO_BOX_INFOS":"Splošno",
            "GATE_LIGHT":"Luč",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Odprite pogoje uporabe",
            "DESC_MANAGE_POPUPS_WARNINGS":"Odstranitev pop-up opozorila",
            "MAX_USERSS_REACHED_CONTENT":"Doseženo je maksimalno število uporabnikov",
            "GENERAL_REMOVE":"Odstranitev",
            "OPTIONS":"Nastavitve",
            "DESC_HOME_SCENARIOS":"Priprava in upravljanje scenarijev",
            "CHANNEL_OFF":"izklop",
            "GENERAL_PORTAL_ID":"Naprave ID",
            "EDIT_GROUP":"Obdelava priprave",
            "ERROR_LERANIN_PORT_CONTENT":"Programiranje želenega kanala žal ni uspelo.",
            "ERROR_CONNECTION_CLOSED":"Napaka",
            "CHANNEL_ON_OFF":"Vklop / izklop",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Oznaka",
            "OPTIONS_EDIT_USERS":"Upravljanje z uporabniki",
            "LOADING_STATES_CONTENT":"Aktualni status se preverja.\nProsimo počakajte...",
            "LERAN_PORTS_CONTENT":"Prestavite pripravo v način za programiranje, glej navodilo. Izberite kanal, ki ga želite programirati.",
            "REMOVE_PORTS_CONTENT":"Izberite kanale, ki jih želite izbrisati.",
            "GATE_SWING_GATE_DOUBLE":"2-krilna vrata",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Preverite, če ste vnesli svoje portalne podatke ali dodali lokalni vmesnik.",
            "CHANNEL_SINK":"spuščanje",
            "OPTIONS_EDIT_USERS_TITLE":"Uporabniki",
            "MAX_PORTS_REACHED_CONTENT":"Zasedeno je maksimalno število kanalov",
            "MAX_PORTS_REACHED":"Ni možno",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Iskana naprava ni bila dosegljiva",
            "PORTAL_AUTHENTICATION_FAILED":"Ni uspelo",
            "NOTIFICATION_CENTER":"Obvestila",
            "LEARNING_PROCESS":"Programirajte",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Uporabniško ime mora biti sestavljeno iz 2 - 20 znakov",
            "WIFI_STATE_CONNECTED":"Povezava",
            "COPY_PORTS":"Prenesite z ročnega oddajnika",
            "POPUP_SEARCH_CONTENT":"Iščite Hörmann vmesnike \n\n Ta postopek lahko traja nekaj sekund!",
            "DESC_MANAGE_POPUPS_CANCEL":"Prekinitev akcije",
            "DESC_WIFI_PASSWORD":"Geslo",
            "DESC_WIFI_SAVE":"Shranitev",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Ustavitev aktivirana",
            "SELECT_GATEWAY":"Pretvorniki",
            "CLEANING_PORTS":"Dodajte napravo",
            "WIFI_STATE_BUSY":"Povezava se ne vzpostavi",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Vneseno geslo je napačno",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Spremenite ime vmesnika",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Ime se prevzame",
            "DESC_ACTORS_EDIT":"Upravljanje ali izbris priprav",
            "DESC_WIFI_STATE":"Status povezave",
            "ERROR_REMOVE_USER":"Ni uspelo",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Prevzem nastavitve",
            "HOME_TITLE":"Glavna stran",
            "GENERAL_USERNAME":"Uporabniško ime",
            "DRIVE_MESSAGE_OPENED":"Odprto",
            "CONFIRM_DELETE":"Ste prepričani, da želite izbrisati vmesnik?",
            "DRIVE_MESSAGE_CLOSED":"Zaprto",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portalni strežnik ni bil dosegljiv",
            "REMOVING_PROCESS_CONTENT":"Kanal se izbriše",
            "DESC_EDIT_USERS_BACK":"Nazaj na nastavitve",
            "ERROR_NO_GROUP_FOUND":"Priprava se ne najde",
            "ERROR_INVALID_GATEWAY":"Vmesnik ni na voljo",
            "DESC_WIFI_BACK":"Nazaj na nastavitve",
            "MAX_USERS_REACHED":"Ni možno",
            "DESC_CHANGE_PASSWORD_USERNAME":"Uporabniško ime",
            "POPUP_AGREEMENT_ACCEPT_USE":"Sprejemam pogoje uporabe",
            "ERROR_LERNING_PORT":"Ni uspelo",
            "POPUP_ADD_GATEWAY_CONTENT":"Vnos naslova IP:",
            "ERROR_ADD_GROUP":"Napaka",
            "DRIVE_MESSAGE_NO_DATA":"Na voljo niso nobeni podatki",
            "CHANGE_PWD_FAILED":"Ni uspelo",
            "SAVING_USER_RIGHTS_CONTENT":"Pravice uporabnika se shranijo",
            "DRIVE_MESSAGE_UNLOCKED":"Ni zapahnjeno",
            "GENERAL_SAVE":"Shranitev",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Povezava",
            "GATE_SECTIONAL_DOOR":"Garažna vrata z navpičnim odpiranjem",
            "OPTIONS_CHANGE_PASSWORD":"Spremenite geslo",
            "CHANNEL":"Upravljanje",
            "CHANGE_GW_NAME_CONTENT":"Ime vmesnika",
            "DRIVE_MESSAGE_RETRACTED":"spuščeni",
            "DESC_ADDGWSCREEN_BACK":"Nazak k pregledu vmesnikov",
            "EMAIL_SUBJECT":"Podpora",
            "ERROR_EDIT_ADMIN":"Ni možno",
            "OPTIONS_SET_USER_RIGHTS":"Pravice uporabnikov",
            "CHANGE_GW_NAME_ERROR":"Ni uspelo",
            "CHANNEL_LIFT":"dvigovanje",
            "LOGIN_FAILED_TITLE":"Ni uspelo",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Če potrdite brisanje podatkov za prijavo z OK, morate pri izbiri pretvornika ponovno vnesti geslo.",
            "CHANNEL_UNLOCK":"Odklepanje",
            "GENERAL_PORTAL_SERVER":"Portalni strežnik",
            "DESC_SCENARIOS_BACK":"Nazaj do glavnega menija",
            "CHANGE_PWD_USERNAME":"Uporabniki:",
            "POPUP_GATE_NOT_RESPONSABLE":"Aplikacija lahko pošlje ta ukaz napravi, vendar pa ne prepozna trenutnega stanja naprave.",
            "DESC_GW_NAME":"Ime vmesnika",
            "GATE_BARRIER":"zapornica",
            "LEARN_PORTS":"Programiranje radijske kode",
            "GENERAL_BACK":"Nazaj",
            "DESC_GWSCREEN_EDIT":"Za izbris shranjenih pretvornikov",
            "OPTIONS_MANAGE_POPUPS":"Upravljanje s pop-up prijavami",
            "POPUP_LOGIN_PROCESS_CONTENT":"Prosimo počakajte...",
            "CONFIRM_DELETE_USER_CONTENT":"Ste prepričani, da želite izbrisati uporabnika?",
            "DESC_MENU":"Meni",
            "LOGIN_FAILED_WRONG_DATA":"Vneseno uporabniško ime ali geslo je napačno",
            "GENERAL_CANCEL":"Prekinite",
            "ADD_GROUP":"Dodajte napravo",
            "WIFI_STATE_AP_NOT_FOUND":"Omrežje se ne najde",
            "WIFI_STATE_NOT_CONNECTED":"Ni povezave",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Vaše upravljanje preko portala je aktivirano!",
            "POPUP_ADD_GATEWAY":"Dodajte vmesnik",
            "GENERAL_NEXT":"Nadaljujte",
            "POPUP_SUPPRESS":"Pop-up ne odpirajte več",
            "POPUP_SEARCH_TITLE":"Iskanje...",
            "WIFI_SCANNING_CONTENT":"Iskanje vidnih brezžičnih omrežij",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Vmesnik ni na voljo",
            "DESC_ACTORS_ADD":"Priprava naprave",
            "ERROR_ADD_GROUP_NO_TYPE":"Za novo pripravo tip ni bil izbran.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Preverite podatke za prijavo",
            "GENERAL_REFESHED":"Aktualizirano",
            "OPTIONS_SUPPRESS_WARNINGS":"Odstranitev opozoril",
            "LOGIN_FAILED_GATEWAY_BUSY":"Pretvornik je polno obremenjen. Prosimo poskusite znova.",
            "DESC_EMAIL":"E-pošto pošljite na Podporo",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Stalno odprto izključeno",
            "CLEANING_PORTS_CONTENT":"Dodajanje se pripravlja",
            "DESC_HOME_ACTORS":"Programiranje in upravljanje priprav",
            "ERROR_TIMEOUT":"Napaka v povezavi",
            "CREATE_USER_TITLE":"Dodajte uporabnike",
            "ERROR_DELETE_ADMIN_CONTENT":"Administratorja ni mogoče izbrisati",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Hitri dostop",
            "ADD_SCENARIO_NAME":"Ime",
            "HIST":"Zgodovina",
            "DESC_RESET_LOGIN_SUBMIT":"Potrditev izbrisa",
            "POPUP_WARNING":"POZOR",
            "REMOVE_GROUP_PROCESS":"Priprava se izbriše",
            "POPUP_LOGIN_PROCESS":"Prijavite se",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Prosimo počakajte...",
            "DESC_DEFAULT_GW_SUBMIT":"Prevzem nastavitve",
            "DESC_CHANGE_PASSWORD_RETYPE":"Ponovitev vnosa",
            "LOAD_USERS_CONTENT":"Vsi uporabniki z vmesnika so naloženi.\nTa postopek lahko traja nekaj sekund.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Če je za pretvornik aktiviran hitri dostop, se aplikacija avtomatsko prijavi glede na dane možnosti.",
            "GATE_OTHER":"Druge priprave",
            "CHANGE_PWD_USER_INVALID":"Napaka",
            "CHANNEL_LIGHT":"Luč",
            "LOGIN_TITLE":"Prijavite se",
            "CHANNEL_HALF":"Delno odpiranje",
            "GATEWAY_SCREEN_ADD_HELP":"Za dodajanje vmesnika izberite +simbol.",
            "ERROR_TIMEOUT_CONTENT":"Prekoračitev časa pri komunikaciji s pretvornikom",
            "ERROR_NO_PORTS_LEARNED":"Dodajanje ni možno",
            "OPTIONS_SUPPRESS_INFOS":"Odstranitev navodil",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Napaka",
            "OPTIONS_WIFI_SETTINGS":"Brezžično omrežje WLAN",
            "CHANNEL_AUTO_CLOSE":"Avtomatsko delovanje",
            "GENERAL_DELETE":"Brisanje",
            "GENERAL_PASSWORD":"Geslo",
            "STATE_COLLECTING_CONTENT":"Preverja se status naprav",
            "ERROR_REMOVE_USER_CONTENT":"Uporabnika ni mogoče izbrisati",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Napaka",
            "ACTORS_ADD_HELP":"Za dodajanje priprave izberite +simbol.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Ste prepričani, da želite izbrisati napravo?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Prosimo počakajte...",
            "GENERAL_YES":"Da",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Pred dodajanjem naprave morate programirati minimalno en kanal",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Imena ni bilo mogoče spremeniti.",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Aplikacija še ni našla vmesnikov.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Avtentifikacija ni uspela",
            "DESC_MANAGE_POPUPS_INFOS":"Odstranitev pop-up informacije",
            "GATE_PILOMAT_POLLER":"potopni stebriček",
            "DESC_CHANNELS_STATE":"Status priprave, ki je usposobljena za povratno javljanje",
            "DESC_GWSCREEN_REFRESH":"Aktualiziranje pretvornikov",
            "POPUP_SCENARIO_DISPATCHING":"Izvede se scenarij",
            "ERROR_PORT_UNREACHABLE":"Ni uspelo",
            "POPUP_GATEWAY_FOUND_CONTENT":"Dodani so bili naslednji vmesniki:",
            "WIFI_STATE_SECURITY_MISMATCH":"Način kodiranja brezžičnega omrežja nima podpore",
            "LOGOUT_NAMED":"Odjavite se",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Odprite pogoje za varstvo podatkov",
            "ERROR_NO_GW_CONTENT":"V lokalnem omrežju ni bilo mogoče najti Hörmann vmesnika.\nDruge pretvornike dodajte z znakom+",
            "DESC_EDIT_USERS_ADD":"Dodajte uporabnike",
            "ERROR_NO_PORT_FOUND":"Port ni na voljo",
            "GATE_SLIDING_GATE":"Drsna vrata",
            "DESC_CHANNELS_BUTTONS":"Elementi upravljanja priprave",
            "DRIVE_MESSAGE_EXTENDED":"dvignjeni",
            "WIFI_SELECTED_NETWORK":"Ime",
            "ERROR_ADD_GROUP_NO_NAME":"Ni bilo vneseno ime za novo napravo.",
            "DESC_HELP":"Funkcija za pomoč",
            "CHANGE_PWD_NEW_PASSWORD":"Novo geslo",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Prevzem novega gesla",
            "DESC_CHANGE_PASSWORD_PWD":"Vnos novega gesla",
            "ERROR_EDIT_ADMIN_CONTENT":"Administratorja ni mogoče obdelati",
            "CHANGE_GW_NAME_NAME_INVALID":"Ni uspelo",
            "STATE_COLLECTING_FAILED":"Napaka",
            "GENERAL_ADD":"Dodajte",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"geslo\" in \"ponovite geslo\" biti mora enako",
            "WIFI_SETTINGS":"Nastavitve brezžične povezave",
            "LEARN_PORTS_TITLE":"Dodajte pripravo",
            "ERROR_CHANGE_USERNAME":"Ni uspelo",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"zapora prehoda",
            "ERROR_INVALID_GATEWAY_CONTENT":"Ni bilo mogoče vzpostaviti povezave z vmesnikom. Preverite vneseno ime gostitelja.",
            "DESC_EDIT_USERS_EDIT":"Brisanje uporabnika",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Ime priprave mora biti sestavljeno iz 2 - 20 znakov",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Hitri dostop ni možen",
            "CHANNEL_UP":"Odpiranje",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Stalno odprto vključeno",
            "PORTAL_VALIDATION_FAILED":"Ni uspelo",
            "DESC_RESET_LOGIN_CANCEL":"Prekinitev akcije",
            "CHANGE_PWD_SETTING_PASSWORD":"Prevzem",
            "LOADING_GROUPS_TITLE":"Polnjenje",
            "DESC_DEFAULT_GW_CANCEL":"Prekinitev akcije",
            "DESC_SET_RIGHTS_SAVE":"Prevzem sprememb",
            "REMOVING_PROCESS":"Brisanje",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Pretvornik ni dosegljiv",
            "CONFIRM_DELETE_TITLE":"Izbrišite vmesnik",
            "SCENARIOS_ADD_HELP":"Za dodajanje scenarija izberite +simbol.",
            "LOGOUT":"Odjavite se",
            "DESC_ACTORS_BACK":"Nazaj do glavnega menija",
            "ERROR_ADAPTER_BUSY_CONTENT":"Ukaza ni mogoče izpeljati.\n Pretvornik je polno obremenjen.",
            "DESC_WIFI_NETWORK_SCAN":"Iskanje omrežij",
            "DRIVE_MESSAGE_HALF":"Delno odprto",
            "DESC_SCENARIOS_ADD":"Priprava scenarija",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Komunikacija s pretvornikom ni uspela",
            "SAVING_USER_RIGHTS":"Shranite",
            "DESC_GWSCREEN_PORTAL":"Vnos portalnih podatkov",
            "GATE_JACK":"Brezžična vtičnica",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Ste na istem omrežju kot vaš vmesnik?",
            "GATE_DOOR":"Vrata",
            "POPUP_PORTAL_UNAVAILABLE":"Portalni strežnik ni bil dosegljiv",
            "DESC_SET_RIGHTS_BACK":"Nazaj do uporabnikov",
            "GATE_SMARTKEY":"Motorni pogon za ključavnico vrat",
            "POPUP_GATEWAY_FOUND_TITILE":"Postopek iskanja končan",
            "WIFI_LOADING_DATA_TITLE":"Napolnite",
            "GENERAL_PORTS":"Kanali",
            "DESC_SCENARIOS_EDIT":"Upravljanje ali izbris scenarijev",
            "OPTIONS_LEARNED_PORTS":"Programirani kanali:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Sprejmem pogoje za varstvo podatkov",
            "DESC_EDIT_USERS_SET_RIGHTS":"Izberite uporabnika, da bi lahko spremenili njegove pravice dostopa",
            "DRIVE_MESSAGE_HALF_MOVING":"Delno odprto / vrata se premikajo",
            "PORTAL_SET_ID_DIALOG":"Nastavitve portala",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Brez referenčne točke",
            "POPUP_SETTING_STATE":"Prosimo počakajte...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Ime uporabnika ni mogoče spremeniti",
            "GROUP_REQUESTABLE":"Naprava je usposobljena za povratno javljanje",
            "LOADING_STATES_TITLE":"Polnjenje",
            "DESC_HOME_USERS":"Upravljanje z uporabniki",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Geslo mora biti sestavljeno iz 4 - 20 znakov",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Geslo se prevzame",
            "POPUP_GATE_OUT_OF_VIEW":"Uporaba krmiljenja avtomatskega pogona vrat brez vidnega kontakta z vrati, je dovoljena le, če ste na vratih dodatno poleg serijsko vgrajene mejne obremenitve namestili še fotocelico.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Izberite, ali naj se pop-up prijave prikažejo ali odstranijo",
            "CHANNEL_IMPULS":"Impulz",
            "PORTAL_VALIDATION_SUCCEEDED":"Avtorizirano",
            "DRIVE_MESSAGE_LOCKED":"Zapahnjeno",
            "CHANNEL_DOWN":"Zapiranje",
            "POPUP_INET_SPEED_LOW":"Vaša podatkovna povezava za to uporabo ne zadostuje",
            "CHANGE_PWD_FAILED_CONTENT":"Gesla ni mogoče spremeniti",
            "GENERAL_GROUP_TYPE":"Tip priprave",
            "CHANNEL_WALK":"Aktivno vratno krilo",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Garažna vrata z vodoravnim odpiranjem",
            "POPUP_AGREEMENT_CONTENT":"Potrdite pred uporabo aplikacije pogoje za varstvo podatkov / uporabe",
            "INFO":"Informacije",
            "LOADING_GROUPS_CONTENT":"Polnilci",
            "GATE_PILOMAT_REIFENKILLER":"uničevalec pnevmatik",
            "GATE_PILOMAT_HUBBALKEN":"dvižni nosilec",
            "GENERAL_RETYPE":"Ponovite geslo",
            "DESC_OTIONS_BACK":"Nazaj do glavnega menija",
            "DESC_SET_RIGHTS":"Izberite pripravo, da bi lahko uporabniku zagotovili pravice dostopa",
            "WIFI_SCANNING_TITLE":"Iskanje",
            "WIFI_STATE_CONNECTION_FAILURE":"Postavitev povezave ni uspela",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Uporabniško ime mora biti sestavljeno iz 2 - 20 znakov",
            "REMOVE_PORTS":"Brisanje",
            "GENERAL_ON":"Vključeno",
            "DESC_CHANGE_PASSWORD_CANCEL":"Prekinitev akcije",
            "LEARNING_PROCESS_CONTENT":"Prosimo počakajte…",
            "LOGIN_FAILED_UNKNOWN":"Prišlo je do nepričakovane napake",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Uporabniških pravic administratorja ni mogoče spremeniti"
         };
         return _loc1_;
      }
   }
}
