package
{
   import mx.resources.ResourceBundle;
   
   public class sr_SR$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function sr_SR$LocalizedStrings_properties()
      {
         super("sr_SR","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Zaključavanje",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Unesite pristupne podatke za Hörmann-ov portal",
            "ERROR_DELETE_ADMIN":"Nije moguće",
            "LOGIN_SHOULD_SAVE":"Memorisanje podataka",
            "LOAD_USERS_TITLE":"Molimo sačekajte",
            "CHANGE_GW_NAME_SETTING":"Preuzimanje",
            "CONFIRM_DELETE_GROUP":"Obriši uređaj",
            "GENERAL_NO":"Ne",
            "DESC_GWSCREEN_ADD":"Dodavanje lokalnih mrežnih prolaza",
            "DRIVE_MESSAGE_NOT_RETRACTED":"Nije uvučen",
            "WIFI_PASSPHRASE":"Lozinka",
            "CHANNEL_ON":"Uključeno",
            "SCENARIOS":"Scenarija",
            "ERROR_SET_ADMIN_RIGHTS":"Nije moguće",
            "DESC_DEFAULT_GW_SAVE":"Podešavanje brzog pristupa za trenutni mrežni prolaz",
            "POPUP_INFO":"Napomena",
            "DRIVE_MESSAGE_ERROR":"PAŽNJA: Greška",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Naziv mreže",
            "EMAIL_BODY":"Vaša pitanja možete poslati preko e-pošte. U tu svrhu vam stoji na raspolaganju i naša funkcija najčešće postavljena pitanja.\n\nVaš tim za BiSecur-Home podršku",
            "CONFIRM_DELETE_USER":"Obriši korisnika",
            "DESC_CHANNELS_BACK":"Nazad u spisak sa uređajima",
            "CHANGE_PWD_FIRST_START":"Iz bezbednosnih razloga promenite fabričko podešenje lozinke nakon prvog prijavljivanja",
            "GENERAL_DEFAULT_GATEWAY":"Brzi pristup",
            "CHANGE_PWD_PASSWORD_INVALID":"Greška",
            "ERROR_NO_GW_TITLE":"Nema mrežnih prolaza",
            "POPUP_SETTING_STATE_CONTENT":"Komanda se izvršava",
            "WIFI_LOADING_DATA_CONTENT":"Učitavaju se WLAN podaci",
            "OPTIONS_RESET_LOGIN_DATA":"Brisanje memorisanih podataka za prijavljivanje",
            "EDIT_USER_TITLE":"Uređivanje korisnika",
            "DESC_HOME_PREFERENCES":"Menjanje podešenja za mrežni prolaz i aplikaciju",
            "WIFI_ACTIVE_STATE":"WLAN status",
            "STATE_COLLECTING":"Učitavanje",
            "ADD_SCENARIO":"Dodati scenario",
            "STATE_COLLECTING_FAILED_CONTENT":"Status nije učitan",
            "GATE_SWING_GATE_SINGLE":"Jednokrilna kapija",
            "ACTORS":"uređaji",
            "POPUP_AGREEMENT":"Upotreba / zaštita podataka",
            "CHANNEL_OPEN_DOOR":"Otvaranje",
            "DESC_ACTORS_REFRESH":"Ažuriranje statusa",
            "GENERAL_OFF":"Isključeno",
            "OPTIONS_HELP":"Onlajn pomoć",
            "COPY_PORTS_CONTENT":"Prebacite predajnik u režimu nasleđivanja, vidi uputstvo. Izaberite kanal koji treba naslediti.",
            "GENERAL_SELECT":"Izaberite...",
            "ERROR_ADAPTER_BUSY":"Greška",
            "INFO_BOX_INFOS":"Opšte",
            "GATE_LIGHT":"Svetlo",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Otvoriti uslove upotrebe",
            "DESC_MANAGE_POPUPS_WARNINGS":"Ne prikazuj iskačuće prozore sa upozorenjima",
            "MAX_USERSS_REACHED_CONTENT":"Postignut je maksimalan broj korisnika.",
            "GENERAL_REMOVE":"Ukloniti",
            "OPTIONS":"Podešenja",
            "DESC_HOME_SCENARIOS":"Kreiranje i uređivanje scenarija",
            "CHANNEL_OFF":"Isključeno",
            "GENERAL_PORTAL_ID":"ID uređaja",
            "EDIT_GROUP":"Uređivanje uređaja",
            "ERROR_LERANIN_PORT_CONTENT":"Programiranje željenog kanala je na žalost neuspelo",
            "ERROR_CONNECTION_CLOSED":"Greška",
            "CHANNEL_ON_OFF":"Uključeno / isključeno",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Opis",
            "OPTIONS_EDIT_USERS":"Upravljanje korisnikom",
            "LOADING_STATES_CONTENT":"Zahte za trenutni status.\nMolimo sačekajte...",
            "LERAN_PORTS_CONTENT":"Prebacite uređaj u režim programiranja, vidi uputstvo. Izaberite kanal koji treba programirati.",
            "REMOVE_PORTS_CONTENT":"Izaberite kanale koje želite da obrišete.",
            "GATE_SWING_GATE_DOUBLE":"Dvokrilna kapija",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Proverite da li ste uneli vaše podatke o portalu ili dodali mrežni prolaz.",
            "CHANNEL_SINK":"Spuštanje",
            "OPTIONS_EDIT_USERS_TITLE":"Korisnik",
            "MAX_PORTS_REACHED_CONTENT":"Zauzet maksimalan broj kanala",
            "MAX_PORTS_REACHED":"Nije moguće",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Zahtevani uređaj nije pronađen",
            "PORTAL_AUTHENTICATION_FAILED":"Neuspelo",
            "NOTIFICATION_CENTER":"Obaveštenja",
            "LEARNING_PROCESS":"Pogramiranje",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Korisničko ime mora da se sastoji od 2 - 20 karaktera",
            "WIFI_STATE_CONNECTED":"Povezan",
            "COPY_PORTS":"Naslediti od daljinskog upravljača",
            "POPUP_SEARCH_CONTENT":"Pretraga za Hörmann-ovim mrežnim prolazima \n\nOvaj postupak može potrajati nekoliko sekundi.",
            "DESC_MANAGE_POPUPS_CANCEL":"Prekid akcije",
            "DESC_WIFI_PASSWORD":"Lozinka",
            "DESC_WIFI_SAVE":"Memorisati",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop aktivan",
            "SELECT_GATEWAY":"Mrežni prolazi",
            "CLEANING_PORTS":"Dodati uređaj",
            "WIFI_STATE_BUSY":"Veza se uspostavlja",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Unešena lozinka je pogrešna",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Menjanje naziva mrežnog prolaza",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Ime se preuzima",
            "DESC_ACTORS_EDIT":"Uređivanje ili brisanje uređaja",
            "DESC_WIFI_STATE":"Status veze",
            "ERROR_REMOVE_USER":"Neuspelo",
            "LANG_TAG":"SER",
            "DESC_MANAGE_POPUPS_SUBMIT":"Preuzimanje podešenja",
            "HOME_TITLE":"Naslovna strana",
            "GENERAL_USERNAME":"Korisničko ime",
            "DRIVE_MESSAGE_OPENED":"Otvorena",
            "CONFIRM_DELETE":"Da li ste sigurni da želite da obrišete ovaj mrežni prolaz?",
            "DRIVE_MESSAGE_CLOSED":"Zatvorena",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Nije bilo moguće za portal servera",
            "REMOVING_PROCESS_CONTENT":"Kanal se briše",
            "DESC_EDIT_USERS_BACK":"Nazad ka podešenjima",
            "ERROR_NO_GROUP_FOUND":"Uređaj nije pronađen",
            "ERROR_INVALID_GATEWAY":"Nije pronađen mrežni prolaz",
            "DESC_WIFI_BACK":"Nazad ka podešenjima",
            "MAX_USERS_REACHED":"Nije moguće",
            "DESC_CHANGE_PASSWORD_USERNAME":"Korisničko ime",
            "POPUP_AGREEMENT_ACCEPT_USE":"Ja prihvatam uslove upotrebe",
            "ERROR_LERNING_PORT":"Neuspelo",
            "POPUP_ADD_GATEWAY_CONTENT":"Unesite IP adresu:",
            "ERROR_ADD_GROUP":"Greška",
            "DRIVE_MESSAGE_NO_DATA":"Nema raspoloživih podataka",
            "CHANGE_PWD_FAILED":"Neuspelo",
            "SAVING_USER_RIGHTS_CONTENT":"Korisnička prava se memorišu",
            "DRIVE_MESSAGE_UNLOCKED":"nisu zaključana",
            "GENERAL_SAVE":"Memorisati",
            "INFO_BOX_FAQ":"Najčešće postavljana pitanja",
            "GENERAL_CONNNECT":"Povezivanje",
            "GATE_SECTIONAL_DOOR":"Vertikalna garažna vrata",
            "OPTIONS_CHANGE_PASSWORD":"Promeni lozinku",
            "CHANNEL":"Kontrola",
            "CHANGE_GW_NAME_CONTENT":"Naziv mrežnog prolaza",
            "DRIVE_MESSAGE_RETRACTED":"Uvučen",
            "DESC_ADDGWSCREEN_BACK":"Nazad u pregled mrežnih prolaza",
            "EMAIL_SUBJECT":"Podrška",
            "ERROR_EDIT_ADMIN":"Nije moguće",
            "OPTIONS_SET_USER_RIGHTS":"Korisnička prava",
            "CHANGE_GW_NAME_ERROR":"Neuspelo",
            "CHANNEL_LIFT":"Podizanje",
            "LOGIN_FAILED_TITLE":"Neuspelo",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Kada potvrdite brisanje podataka za prijavljivanje sa OK, onda morate ponovo uneti lozinku prilikom biranja mrežnog prolaza",
            "CHANNEL_UNLOCK":"Otključavanje",
            "GENERAL_PORTAL_SERVER":"Portal servera",
            "DESC_SCENARIOS_BACK":"Nazad u glavni meni",
            "CHANGE_PWD_USERNAME":"Korisnik:",
            "POPUP_GATE_NOT_RESPONSABLE":"Aplikacija može da pošalje ovu komandu ka uređaju, međutim ne može da prepozna trenutni status uređaja.",
            "DESC_GW_NAME":"Naziv mrežnog prolaza",
            "GATE_BARRIER":"rampa",
            "LEARN_PORTS":"Programiranje kôda",
            "GENERAL_BACK":"Nazad",
            "DESC_GWSCREEN_EDIT":"Za brisanje memorisanih mrežnih prolaza",
            "OPTIONS_MANAGE_POPUPS":"Uređivanje poruke u iskačućim prozorima",
            "POPUP_LOGIN_PROCESS_CONTENT":"Molimo sačekajte...",
            "CONFIRM_DELETE_USER_CONTENT":"Da li ste sigurni da želite da obrišete korisnika?",
            "DESC_MENU":"Meni",
            "LOGIN_FAILED_WRONG_DATA":"Unešeno korisničko ime ili lozinka je pogrešna",
            "GENERAL_CANCEL":"Poništi",
            "ADD_GROUP":"Dodati uređaj",
            "WIFI_STATE_AP_NOT_FOUND":"Mreža nije pronađena",
            "WIFI_STATE_NOT_CONNECTED":"Nije povezan",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Vaše korišćenje preko portala je aktivirano!",
            "POPUP_ADD_GATEWAY":"Dodati mrežni prolaz",
            "GENERAL_NEXT":"Dalje",
            "POPUP_SUPPRESS":"Ne otvarati više iskačući prozor",
            "POPUP_SEARCH_TITLE":"Pretraga...",
            "WIFI_SCANNING_CONTENT":"Pretraži vidljive WLAN mreže",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Nije pronađen mrežni prolaz",
            "DESC_ACTORS_ADD":"Kreiranje uređaja",
            "ERROR_ADD_GROUP_NO_TYPE":"Nije izabran tip za novi uređaj.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Proverite podatke za prijavljivanje",
            "GENERAL_REFESHED":"ažurirano",
            "OPTIONS_SUPPRESS_WARNINGS":"Ne prikazuj upozorenja",
            "LOGIN_FAILED_GATEWAY_BUSY":"Mrežni prolaz je preopterećen. Pokušajte ponovo.",
            "DESC_EMAIL":"Slanje e-pošte na podršku",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Trajno otključana isključeno",
            "CLEANING_PORTS_CONTENT":"Dodavanje se priprema",
            "DESC_HOME_ACTORS":"Programiranje i uređivanje uređaja",
            "ERROR_TIMEOUT":"Greška u povezivanju",
            "CREATE_USER_TITLE":"Dodati korisnika",
            "ERROR_DELETE_ADMIN_CONTENT":"Ne možete obrisati administratora",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Brzi pristup",
            "ADD_SCENARIO_NAME":"Ime",
            "HIST":"Istorija",
            "DESC_RESET_LOGIN_SUBMIT":"Potvrđivanje komande za brisanje",
            "POPUP_WARNING":"PAŽNJA",
            "REMOVE_GROUP_PROCESS":"Uređaj se briše",
            "POPUP_LOGIN_PROCESS":"Prijava",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Molimo sačekajte...",
            "DESC_DEFAULT_GW_SUBMIT":"Preuzimanje podešenja",
            "DESC_CHANGE_PASSWORD_RETYPE":"Ponoviti unos",
            "LOAD_USERS_CONTENT":"Učitavaju se svi korisnici od mrežnog prolaza.\nOvaj postupak može potrajati nekoliko sekundi.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Ako je aktiviran brzi pristup za mrežni prolaz, onda se aplikacija automatski prijavljuje prema mogućnostima",
            "GATE_OTHER":"Ostali uređaji",
            "CHANGE_PWD_USER_INVALID":"Greška",
            "CHANNEL_LIGHT":"Svetlo",
            "LOGIN_TITLE":"Prijava",
            "CHANNEL_HALF":"Delimično otvaranje",
            "GATEWAY_SCREEN_ADD_HELP":"Za dodavanje mrežnog prolaza izaberite simbol+.",
            "ERROR_TIMEOUT_CONTENT":"Prekoračenje vremena prilikom komunikacije sa mrežnim prolazom",
            "ERROR_NO_PORTS_LEARNED":"Ne postoji mogućnost dodavanja",
            "OPTIONS_SUPPRESS_INFOS":"Ne prikazuj napomene",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Greška",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatski režim rada",
            "GENERAL_DELETE":"Izbrisati",
            "GENERAL_PASSWORD":"Lozinka",
            "STATE_COLLECTING_CONTENT":"Upit o statusu uređaja",
            "ERROR_REMOVE_USER_CONTENT":"Neuspešno brisanje korsnika",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Greška",
            "ACTORS_ADD_HELP":"Za dodavanje uređaja izaberite simbol+.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Da li ste sigurni da želite da obrišete ovaj uređaj?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Molimo sačekajte...",
            "GENERAL_YES":"Da",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Pre dodavanja uređaja memorišite najmanje jedan kanal",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Ime se ne može promeniti",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Aplikacija nije pronašla nijedan mrežni prolaz.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Neuspela potvrda identiteta",
            "DESC_MANAGE_POPUPS_INFOS":"Ne prikazuj iskačuće prozore sa informacijama",
            "GATE_PILOMAT_POLLER":"Stub",
            "DESC_CHANNELS_STATE":"Status uređaja sa povratnim informacijama",
            "DESC_GWSCREEN_REFRESH":"Ažuriranje spiska sa mrežnim prolazima",
            "POPUP_SCENARIO_DISPATCHING":"Scenarijo se sprovodi",
            "ERROR_PORT_UNREACHABLE":"Neuspelo",
            "POPUP_GATEWAY_FOUND_CONTENT":"Sledeći mrežni prolazi su dodati:",
            "WIFI_STATE_SECURITY_MISMATCH":"Tip kodiranja WLAN mreže nije podržan",
            "LOGOUT_NAMED":"odjavljivanje",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Otvoriti zaštitu podataka",
            "ERROR_NO_GW_CONTENT":"Nije pronađen Hörmann-ov mrežni prolaz u lokalnoj mreži.\nDodati sledeće mrežne prolaze pomoću znaka+",
            "DESC_EDIT_USERS_ADD":"Dodati korisnika",
            "ERROR_NO_PORT_FOUND":"Port nije pronađen",
            "GATE_SLIDING_GATE":"Klizna vrata",
            "DESC_CHANNELS_BUTTONS":"Upravljački elementi uređaja",
            "DRIVE_MESSAGE_EXTENDED":"Izvučen",
            "WIFI_SELECTED_NETWORK":"Ime",
            "ERROR_ADD_GROUP_NO_NAME":"Nije unešen naziv za novi uređaj.",
            "DESC_HELP":"Funkcija pomoć",
            "CHANGE_PWD_NEW_PASSWORD":"Nova lozinka",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Preuzimanje nove lozinke",
            "DESC_CHANGE_PASSWORD_PWD":"Unos nove lozinke",
            "ERROR_EDIT_ADMIN_CONTENT":"Administrator ne može da se obradi",
            "CHANGE_GW_NAME_NAME_INVALID":"Neuspelo",
            "STATE_COLLECTING_FAILED":"Greška",
            "GENERAL_ADD":"Dodati",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Lozinka\" i \"Ponovo ukucati lozinku\" moraju da budu identični",
            "WIFI_SETTINGS":"WLAN podešenja",
            "LEARN_PORTS_TITLE":"Dodati uređaj",
            "ERROR_CHANGE_USERNAME":"Neuspelo",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Blokada za prolaz vozila",
            "ERROR_INVALID_GATEWAY_CONTENT":"Nije moglo da se uspostavi veza sa mrežnim prolazom. Proverite ime glavnog računara.",
            "DESC_EDIT_USERS_EDIT":"Obriši korisnika",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Naziv uređaja mora da se sastoji od 2 - 20 karaktera",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Nije moguć brzi pristup",
            "CHANNEL_UP":"Otvaranje",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Trajno otključana uključeno",
            "PORTAL_VALIDATION_FAILED":"Neuspelo",
            "DESC_RESET_LOGIN_CANCEL":"Prekid akcije",
            "CHANGE_PWD_SETTING_PASSWORD":"Preuzimanje",
            "LOADING_GROUPS_TITLE":"Učitavanje",
            "DESC_DEFAULT_GW_CANCEL":"Prekid akcije",
            "DESC_SET_RIGHTS_SAVE":"Preuzmi izmene",
            "REMOVING_PROCESS":"Izbrisati",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Mrežni prolaz nije pristupačan",
            "CONFIRM_DELETE_TITLE":"Obriši mrežni prolaz",
            "SCENARIOS_ADD_HELP":"Za dodavanje scenarija izaberite simbol+.",
            "LOGOUT":"Odjava",
            "DESC_ACTORS_BACK":"Nazad u glavni meni",
            "ERROR_ADAPTER_BUSY_CONTENT":"Komanda nije izvršena.\n Mrežni prolaz je preopterećen.",
            "DESC_WIFI_NETWORK_SCAN":"Pretraži mreže",
            "DRIVE_MESSAGE_HALF":"Delimično otvorena",
            "DESC_SCENARIOS_ADD":"Kreiranje scenarija",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Komunikacija sa mrežnim prolazom neuspela",
            "SAVING_USER_RIGHTS":"Memorisanje",
            "DESC_GWSCREEN_PORTAL":"Unos podataka portala",
            "GATE_JACK":"Utičnica sa daljinskim upravljačem",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Da li se nalazite u istoj mreži kao vaš mrežni prolaz?",
            "GATE_DOOR":"Vrata",
            "POPUP_PORTAL_UNAVAILABLE":"Nije bilo moguće za portal servera",
            "DESC_SET_RIGHTS_BACK":"Nazad u korisnici",
            "GATE_SMARTKEY":"Motor za bravu",
            "POPUP_GATEWAY_FOUND_TITILE":"Postupak pretrage završen",
            "WIFI_LOADING_DATA_TITLE":"Učitavanje",
            "GENERAL_PORTS":"Kanali",
            "DESC_SCENARIOS_EDIT":"Uređivanje i brisanje scenarija",
            "OPTIONS_LEARNED_PORTS":"Memorisani kanali:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Ja prihvatam uslove zaštite podataka",
            "DESC_EDIT_USERS_SET_RIGHTS":"Izaberi korisnika radi menjanje njegovih prava pristupanja",
            "DRIVE_MESSAGE_HALF_MOVING":"Delimično otvoreno / Vožnja u toku",
            "PORTAL_SET_ID_DIALOG":"Podešavanje portala",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Nema referentne tačke",
            "POPUP_SETTING_STATE":"Molimo sačekajte...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Neuspešna promena korsnika",
            "GROUP_REQUESTABLE":"Uređaj ima mogućnost povratne informacije",
            "LOADING_STATES_TITLE":"Učitavanje",
            "DESC_HOME_USERS":"Upravljanje korisnikom",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Lozinka mora da se sastoji od 4 - 20 karaktera",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Lozinka se preuzima",
            "POPUP_GATE_OUT_OF_VIEW":"Upravljanje sa automatskim garažnim vratima, sa kojima nemate vizuelni kontakt, je dozvoljeno samo ako ste dodatno instalirali fotoćeliju na vratima uz standardno postojeće ograničenje sile.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Izaberite da li želite prikazivanje poruka u iskačućim prozorima ili ne",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"ovlašćeno",
            "DRIVE_MESSAGE_LOCKED":"zaključana",
            "CHANNEL_DOWN":"Zatvaranje",
            "POPUP_INET_SPEED_LOW":"Vaša digitalna veza nije dovoljna za ovu primenu",
            "CHANGE_PWD_FAILED_CONTENT":"Neuspešna promena lozinke",
            "GENERAL_GROUP_TYPE":"Tip uređaja",
            "CHANNEL_WALK":"Krilo za prolaz pešaka",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horizontalna garažna vrata",
            "POPUP_AGREEMENT_CONTENT":"Pre upotrebe aplikacije potrebno je da prihvatite uslove upotrebe i zaštite podataka",
            "INFO":"Informacije",
            "LOADING_GROUPS_CONTENT":"Učitavanje uređaja",
            "GATE_PILOMAT_REIFENKILLER":"Uređaji za bušenje pneumatika",
            "GATE_PILOMAT_HUBBALKEN":"Podizne rampe",
            "GENERAL_RETYPE":"Ponovo ukucajte lozinku",
            "DESC_OTIONS_BACK":"Nazad u glavni meni",
            "DESC_SET_RIGHTS":"Izaberi uređaj za izdavanje prava pristupanja korisniku",
            "WIFI_SCANNING_TITLE":"Pretraga",
            "WIFI_STATE_CONNECTION_FAILURE":"Neuspelo uspostavljanje veze",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Korisničko ime mora da se sastoji od 2 - 20 karaktera",
            "REMOVE_PORTS":"Izbrisati",
            "GENERAL_ON":"Uključeno",
            "DESC_CHANGE_PASSWORD_CANCEL":"Prekid akcije",
            "LEARNING_PROCESS_CONTENT":"Molimo sačekajte...",
            "LOGIN_FAILED_UNKNOWN":"Nastupila je neočekivana greška",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Ne mogu se promeniti korisnička prava administratora"
         };
         return _loc1_;
      }
   }
}
