package
{
   import mx.resources.ResourceBundle;
   
   public class sv_SE$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function sv_SE$LocalizedStrings_properties()
      {
         super("sv_SE","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Låsa",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Ange åtkomstinformation för Hörmann-portalen",
            "ERROR_DELETE_ADMIN":"Ej möjligt",
            "LOGIN_SHOULD_SAVE":"Spara data",
            "LOAD_USERS_TITLE":"Var god vänta",
            "CHANGE_GW_NAME_SETTING":"Hämta",
            "CONFIRM_DELETE_GROUP":"Radera enhet",
            "GENERAL_NO":"Nej",
            "DESC_GWSCREEN_ADD":"Lägg till lokala gateways",
            "DRIVE_MESSAGE_NOT_RETRACTED":"ej infälld",
            "WIFI_PASSPHRASE":"Lösenord",
            "CHANNEL_ON":"På",
            "SCENARIOS":"Scenarier",
            "ERROR_SET_ADMIN_RIGHTS":"Ej möjligt",
            "DESC_DEFAULT_GW_SAVE":"Upprätta snabbåtkomst för aktuell gateway",
            "POPUP_INFO":"Anmärkning",
            "DRIVE_MESSAGE_ERROR":"OBS: Fel",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Nätverksnamn",
            "EMAIL_BODY":"Du kan skicka din fråga per mejl. Dessutom finns en  FAQ-funktion.\n\nBiSecur-home supportteam",
            "CONFIRM_DELETE_USER":"Ta bort användare",
            "DESC_CHANNELS_BACK":"Tillbaka till enhetslistan",
            "CHANGE_PWD_FIRST_START":"Av säkerhetsskäl ändra det fabriksinställda lösenordet första gången du loggar in",
            "GENERAL_DEFAULT_GATEWAY":"Snabbåtkomst",
            "CHANGE_PWD_PASSWORD_INVALID":"Fel",
            "ERROR_NO_GW_TITLE":"Inga gateways",
            "POPUP_SETTING_STATE_CONTENT":"Kommandot utförs",
            "WIFI_LOADING_DATA_CONTENT":"WLAN-uppgifter laddas",
            "OPTIONS_RESET_LOGIN_DATA":"Radera sparade login-uppgifter",
            "EDIT_USER_TITLE":"Bearbeta användare",
            "DESC_HOME_PREFERENCES":"Ändra inställningar för gateway och app",
            "WIFI_ACTIVE_STATE":"WLAN status",
            "STATE_COLLECTING":"Ladda",
            "ADD_SCENARIO":"Lägg till scenario",
            "STATE_COLLECTING_FAILED_CONTENT":"Status laddades inte",
            "GATE_SWING_GATE_SINGLE":"1-flyglig slaggrind",
            "ACTORS":"Enheter",
            "POPUP_AGREEMENT":"Användning / Dataskydd",
            "CHANNEL_OPEN_DOOR":"Öppna",
            "DESC_ACTORS_REFRESH":"Uppdatera status",
            "GENERAL_OFF":"Frånkopplad",
            "OPTIONS_HELP":"Online-hjälp",
            "COPY_PORTS_CONTENT":"Sätt enheten i överföringsläge, se anvisning. Välj den kanal som ska överföras.",
            "GENERAL_SELECT":"Var god välj...",
            "ERROR_ADAPTER_BUSY":"Fel",
            "INFO_BOX_INFOS":"Allmänt",
            "GATE_LIGHT":"Ljus",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Öppna användarvillkor",
            "DESC_MANAGE_POPUPS_WARNINGS":"Dölja varnings-popups",
            "MAX_USERSS_REACHED_CONTENT":"Maximalt antal användare utnyttjas.",
            "GENERAL_REMOVE":"Ta bort",
            "OPTIONS":"Inställningar",
            "DESC_HOME_SCENARIOS":"Upprätta och administrera scenarier",
            "CHANNEL_OFF":"Av",
            "GENERAL_PORTAL_ID":"Enhet ID",
            "EDIT_GROUP":"Enheten bearbetar",
            "ERROR_LERANIN_PORT_CONTENT":"Programmeringen av den valda kanalen misslyckades.",
            "ERROR_CONNECTION_CLOSED":"Fel",
            "CHANNEL_ON_OFF":"Till/Från",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Beteckning",
            "OPTIONS_EDIT_USERS":"Administrera användare",
            "LOADING_STATES_CONTENT":"Aktuell status kontrolleras.\nVar god vänta...",
            "LERAN_PORTS_CONTENT":"Sätt enheten i programmeringsläge, se anvisning. Välj den kanal som ska programmeras.",
            "REMOVE_PORTS_CONTENT":"Välj de kanaler som du vill radera.",
            "GATE_SWING_GATE_DOUBLE":"2-flyglig slaggrind",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Kontrollera om du har skrivit in dina portaluppgifter eller har lagt till en lokal gateway.",
            "CHANNEL_SINK":"Sänkning",
            "OPTIONS_EDIT_USERS_TITLE":"Användare",
            "MAX_PORTS_REACHED_CONTENT":"Maximalt antal kanaler utnyttjas",
            "MAX_PORTS_REACHED":"Ej möjligt",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Den efterfrågade enheten kunde inte nås",
            "PORTAL_AUTHENTICATION_FAILED":"Misslyckades",
            "NOTIFICATION_CENTER":"Meddelanden",
            "LEARNING_PROCESS":"Programmera",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Användarnamnet måste ha 2 - 20 tecken",
            "WIFI_STATE_CONNECTED":"Ansluten",
            "COPY_PORTS":"Föra över från fjärrkontroll",
            "POPUP_SEARCH_CONTENT":"Söker efter Hörmann-gatewayer \n\nDetta förlopp kan ta några sekunder!",
            "DESC_MANAGE_POPUPS_CANCEL":"Avbryta åtgärd",
            "DESC_WIFI_PASSWORD":"Lösenord",
            "DESC_WIFI_SAVE":"Spara",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stopp aktiv",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Lägga till enhet",
            "WIFI_STATE_BUSY":"Förbindelse upprättas",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Det angivna lösenordet är felaktigt.",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Ändra gateway-namn",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Namnet sparades",
            "DESC_ACTORS_EDIT":"Administrera eller radera enheter",
            "DESC_WIFI_STATE":"Anslutningsstatus",
            "ERROR_REMOVE_USER":"Misslyckades",
            "LANG_TAG":"SE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Överför inställning",
            "HOME_TITLE":"Huvudsida",
            "GENERAL_USERNAME":"Användarnamn",
            "DRIVE_MESSAGE_OPENED":"Öppen",
            "CONFIRM_DELETE":"Är du säker på att du vill radera gatewayen?",
            "DRIVE_MESSAGE_CLOSED":"Stängd",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portalservern kunde inte nås",
            "REMOVING_PROCESS_CONTENT":"Kanalen raderas",
            "DESC_EDIT_USERS_BACK":"Tillbaka till inställningar",
            "ERROR_NO_GROUP_FOUND":"Enheten hittades inte",
            "ERROR_INVALID_GATEWAY":"Ingen gateway hittades",
            "DESC_WIFI_BACK":"Tillbaka till inställningar",
            "MAX_USERS_REACHED":"Ej möjligt",
            "DESC_CHANGE_PASSWORD_USERNAME":"Användarnamn",
            "POPUP_AGREEMENT_ACCEPT_USE":"Jag accepterar användarvillkoren",
            "ERROR_LERNING_PORT":"Misslyckades",
            "POPUP_ADD_GATEWAY_CONTENT":"Ange IP-adress:",
            "ERROR_ADD_GROUP":"Fel",
            "DRIVE_MESSAGE_NO_DATA":"Inga data tillgängliga",
            "CHANGE_PWD_FAILED":"Misslyckades",
            "SAVING_USER_RIGHTS_CONTENT":"Användarrättigheter sparas",
            "DRIVE_MESSAGE_UNLOCKED":"Inte låst",
            "GENERAL_SAVE":"Spara",
            "INFO_BOX_FAQ":"FAQ",
            "GENERAL_CONNNECT":"Ansluta",
            "GATE_SECTIONAL_DOOR":"Garageport med vertikal drift",
            "OPTIONS_CHANGE_PASSWORD":"Ändra lösenord",
            "CHANNEL":"Manövrering",
            "CHANGE_GW_NAME_CONTENT":"Gateway-namn",
            "DRIVE_MESSAGE_RETRACTED":"infälld",
            "DESC_ADDGWSCREEN_BACK":"Tillbaka till gateway-översikten",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Ej möjligt",
            "OPTIONS_SET_USER_RIGHTS":"Användarrättigheter",
            "CHANGE_GW_NAME_ERROR":"Misslyckades",
            "CHANNEL_LIFT":"Lyft",
            "LOGIN_FAILED_TITLE":"Misslyckades",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Om du bekräftar radering av login-uppgifterna med OK, måste lösenordet anges igen vid val av gateway",
            "CHANNEL_UNLOCK":"Låsa upp",
            "GENERAL_PORTAL_SERVER":"Portal server",
            "DESC_SCENARIOS_BACK":"Tillbaka till huvudmenyn",
            "CHANGE_PWD_USERNAME":"Användare:",
            "POPUP_GATE_NOT_RESPONSABLE":"Appen kan skicka detta kommando till enheten, men kan inte avläsa enhetens aktuella läge.",
            "DESC_GW_NAME":"Gateway-namn",
            "GATE_BARRIER":"bom",
            "LEARN_PORTS":"Programmera fjärrkod",
            "GENERAL_BACK":"Tillbaka",
            "DESC_GWSCREEN_EDIT":"Radera sparade gateways",
            "OPTIONS_MANAGE_POPUPS":"Administrera popup-meddelanden",
            "POPUP_LOGIN_PROCESS_CONTENT":"Var god vänta...",
            "CONFIRM_DELETE_USER_CONTENT":"Är du säker på att du vill radera användaren?",
            "DESC_MENU":"Meny",
            "LOGIN_FAILED_WRONG_DATA":"Det användarnamn eller lösenord som angetts är felaktigt.",
            "GENERAL_CANCEL":"Avbryt",
            "ADD_GROUP":"Lägga till enhet",
            "WIFI_STATE_AP_NOT_FOUND":"Nätverket hittades inte",
            "WIFI_STATE_NOT_CONNECTED":"Inte ansluten",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Portalmanövrering aktiverad",
            "POPUP_ADD_GATEWAY":"Lägg till gateway",
            "GENERAL_NEXT":"Fortsätt",
            "POPUP_SUPPRESS":"Öppna inte popup",
            "POPUP_SEARCH_TITLE":"Sökning...",
            "WIFI_SCANNING_CONTENT":"Söker efter tillgängliga WLAN-nätverk",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Ingen gateway hittades",
            "DESC_ACTORS_ADD":"Ange enhet",
            "ERROR_ADD_GROUP_NO_TYPE":"Ingen typ har valts för den nya enheten.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Kontrollera login-uppgifter",
            "GENERAL_REFESHED":"Aktualiserad",
            "OPTIONS_SUPPRESS_WARNINGS":"Visa inte varningar",
            "LOGIN_FAILED_GATEWAY_BUSY":"Gatewayen är upptagen. Försök igen.",
            "DESC_EMAIL":"Skicka ett mejl till supporten",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Permanent öppen deaktiverad",
            "CLEANING_PORTS_CONTENT":"Att lägga till förbereds",
            "DESC_HOME_ACTORS":"Programmera och administrera enheter",
            "ERROR_TIMEOUT":"Anslutningsfel",
            "CREATE_USER_TITLE":"Lägg till användare",
            "ERROR_DELETE_ADMIN_CONTENT":"Administratör kan inte tas bort",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Snabbåtkomst",
            "ADD_SCENARIO_NAME":"Namn",
            "HIST":"Historik",
            "DESC_RESET_LOGIN_SUBMIT":"Bekräfta radering",
            "POPUP_WARNING":"OBS!",
            "REMOVE_GROUP_PROCESS":"Enheten raderas",
            "POPUP_LOGIN_PROCESS":"Logga in",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Var god vänta...",
            "DESC_DEFAULT_GW_SUBMIT":"Överför inställning",
            "DESC_CHANGE_PASSWORD_RETYPE":"Upprepa inmatningen",
            "LOAD_USERS_CONTENT":"Alla användare laddas från gatewayen.\nDetta förlopp kan ta några sekunder.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Om en gateway är aktiverad med snabbåtkomst, loggas appen in automatiskt om det går",
            "GATE_OTHER":"Övriga enheter",
            "CHANGE_PWD_USER_INVALID":"Fel",
            "CHANNEL_LIGHT":"Ljus",
            "LOGIN_TITLE":"Logga in",
            "CHANNEL_HALF":"Delöppning",
            "GATEWAY_SCREEN_ADD_HELP":"Välj +symbolen för att lägga till en gateway.",
            "ERROR_TIMEOUT_CONTENT":"Tidsgränsen för kommunikationen med gatewayen har överskridits",
            "ERROR_NO_PORTS_LEARNED":"Kan inte läggas till",
            "OPTIONS_SUPPRESS_INFOS":"Visa inte information",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Fel",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatisk drift",
            "GENERAL_DELETE":"Radera",
            "GENERAL_PASSWORD":"Lösenord",
            "STATE_COLLECTING_CONTENT":"Enhetens status kontrolleras",
            "ERROR_REMOVE_USER_CONTENT":"Användaren kunde inte tas bort.",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Fel",
            "ACTORS_ADD_HELP":"Välj +symbolen för att lägga till en enhet.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Är du säker på att du vill radera enheten?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Var god vänta...",
            "GENERAL_YES":"Ja",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Programmera minst en kanal innan en enhet läggs till",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Namnet kunde inte ändras.",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Appen har ännu inte hittat någon gateway.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Autentisering misslyckades",
            "DESC_MANAGE_POPUPS_INFOS":"Dölja informations-popups",
            "GATE_PILOMAT_POLLER":"Pollare",
            "DESC_CHANNELS_STATE":"Status för enheter med svarsfunktion",
            "DESC_GWSCREEN_REFRESH":"Uppdatera gatewaylista",
            "POPUP_SCENARIO_DISPATCHING":"Scenariot utförs",
            "ERROR_PORT_UNREACHABLE":"Misslyckades",
            "POPUP_GATEWAY_FOUND_CONTENT":"Följande gateway har lagts till:",
            "WIFI_STATE_SECURITY_MISMATCH":"Krypteringstypen för WLAN stöds inte",
            "LOGOUT_NAMED":"Logga ut",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Öppna dataskyddsvillkor",
            "ERROR_NO_GW_CONTENT":"Ingen Hörmann-gateway kunde hittas i det lokala nätverket.\nLägg till ytterligare gateways med +-tecknet",
            "DESC_EDIT_USERS_ADD":"Lägg till användare",
            "ERROR_NO_PORT_FOUND":"Porten hittades inte",
            "GATE_SLIDING_GATE":"Skjutport",
            "DESC_CHANNELS_BUTTONS":"Enhetens manövreringskomponenter",
            "DRIVE_MESSAGE_EXTENDED":"utfälld",
            "WIFI_SELECTED_NETWORK":"Namn",
            "ERROR_ADD_GROUP_NO_NAME":"Inget namn har angetts för den nya enheten.",
            "DESC_HELP":"Hjälpfunktioner",
            "CHANGE_PWD_NEW_PASSWORD":"Nytt lösenord",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Överför nytt lösenord",
            "DESC_CHANGE_PASSWORD_PWD":"Ange nytt lösenord",
            "ERROR_EDIT_ADMIN_CONTENT":"Administratören kan inte bearbetas.",
            "CHANGE_GW_NAME_NAME_INVALID":"Misslyckades",
            "STATE_COLLECTING_FAILED":"Fel",
            "GENERAL_ADD":"Lägg till",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Lösenord\" och \"Upprepa lösenord\" måste vara identiska",
            "WIFI_SETTINGS":"WLAN inställningar",
            "LEARN_PORTS_TITLE":"Lägga till enhet",
            "ERROR_CHANGE_USERNAME":"Misslyckades",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Genomfartsspärr",
            "ERROR_INVALID_GATEWAY_CONTENT":"Anslutning till gatewayen kunde inte upprättas. Kontrollera host-namnet.",
            "DESC_EDIT_USERS_EDIT":"Ta bort användare",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Enhetens namn måste ha 2 - 20 tecken",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Snabbåtkomst ej möjligt",
            "CHANNEL_UP":"Öppna",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Permanent öppen aktiv",
            "PORTAL_VALIDATION_FAILED":"Misslyckades",
            "DESC_RESET_LOGIN_CANCEL":"Avbryta åtgärd",
            "CHANGE_PWD_SETTING_PASSWORD":"Hämta",
            "LOADING_GROUPS_TITLE":"Ladda",
            "DESC_DEFAULT_GW_CANCEL":"Avbryta åtgärd",
            "DESC_SET_RIGHTS_SAVE":"Överföra ändringar",
            "REMOVING_PROCESS":"Radera",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Gateway kan inte nås",
            "CONFIRM_DELETE_TITLE":"Radera gateway",
            "SCENARIOS_ADD_HELP":"Välj +symbolen för att lägga till ett scenario.",
            "LOGOUT":"Logga ut",
            "DESC_ACTORS_BACK":"Tillbaka till huvudmenyn",
            "ERROR_ADAPTER_BUSY_CONTENT":"Kommandot kunde inte utföras./n Gatewayen är upptagen.",
            "DESC_WIFI_NETWORK_SCAN":"Söka efter nätverk",
            "DRIVE_MESSAGE_HALF":"Delvis öppnad",
            "DESC_SCENARIOS_ADD":"Ange scenarier",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Kommunikationen med gatewayen misslyckades.",
            "SAVING_USER_RIGHTS":"Spara",
            "DESC_GWSCREEN_PORTAL":"Ange portaluppgifter",
            "GATE_JACK":"Trådlöst vägguttag",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Befinner du i samma nätverk som din gateway?",
            "GATE_DOOR":"Dörr",
            "POPUP_PORTAL_UNAVAILABLE":"Portalservern kunde inte nås",
            "DESC_SET_RIGHTS_BACK":"Tillbaka till användare",
            "GATE_SMARTKEY":"Dörrlåsmaskineri",
            "POPUP_GATEWAY_FOUND_TITILE":"Sökningen avslutad",
            "WIFI_LOADING_DATA_TITLE":"Ladda",
            "GENERAL_PORTS":"Kanaler",
            "DESC_SCENARIOS_EDIT":"Administrera eller radera scenarier",
            "OPTIONS_LEARNED_PORTS":"Programmerade kanaler",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Jag accepterar dataskyddsvilllkoren",
            "DESC_EDIT_USERS_SET_RIGHTS":"Välja användare för att ändra åtkomsträttigheterna",
            "DRIVE_MESSAGE_HALF_MOVING":"Delvis öppnad / öppnas",
            "PORTAL_SET_ID_DIALOG":"Portalinställningar",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Ingen referenspunkt",
            "POPUP_SETTING_STATE":"Var god vänta...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"Användarnamnet kunde inte ändras.",
            "GROUP_REQUESTABLE":"Enheten har svarsfunktion",
            "LOADING_STATES_TITLE":"Ladda",
            "DESC_HOME_USERS":"Administrera användare",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Lösenordet måste ha 4 - 20 tecken",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Lösenordet sparas",
            "POPUP_GATE_OUT_OF_VIEW":"Automatiska portsystem där man inte har fri sikt mot porten får endast styras om det, tillsammans med kraftbegränsning som standard, även finns en ljusridå monterad på porten.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Välj om popup-meddelanden ska visas eller inte",
            "CHANNEL_IMPULS":"Impuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Auktoriserad",
            "DRIVE_MESSAGE_LOCKED":"Låst",
            "CHANNEL_DOWN":"Stäng",
            "POPUP_INET_SPEED_LOW":"Din datorförbindelse har inte tillräcklig kapacitet för denna användning",
            "CHANGE_PWD_FAILED_CONTENT":"Lösenordet kunde inte ändras.",
            "GENERAL_GROUP_TYPE":"Enhetstyp",
            "CHANNEL_WALK":"Gångflygel",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Garageport med horisontell drift",
            "POPUP_AGREEMENT_CONTENT":"Godkänn dataskydd- / användarvillkor innan appen används.",
            "INFO":"Information",
            "LOADING_GROUPS_CONTENT":"Ladda enhet",
            "GATE_PILOMAT_REIFENKILLER":"Däckspärrar",
            "GATE_PILOMAT_HUBBALKEN":"Lyftbalkar",
            "GENERAL_RETYPE":"Upprepa lösenord",
            "DESC_OTIONS_BACK":"Tillbaka till huvudmenyn",
            "DESC_SET_RIGHTS":"Välja enhet för att bekräfta åtkomsträttigheter för användare",
            "WIFI_SCANNING_TITLE":"Sök",
            "WIFI_STATE_CONNECTION_FAILURE":"Anslutning misslyckades",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Användarnamnet måste ha 2 - 20 tecken",
            "REMOVE_PORTS":"Radera",
            "GENERAL_ON":"Tillkopplad",
            "DESC_CHANGE_PASSWORD_CANCEL":"Avbryta åtgärd",
            "LEARNING_PROCESS_CONTENT":"Var god vänta...",
            "LOGIN_FAILED_UNKNOWN":"Ett oväntat fel har uppstått.",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Administratörens användarbehörigheter kan inte ändras!"
         };
         return _loc1_;
      }
   }
}
