package
{
   import mx.resources.ResourceBundle;
   
   public class tr_TR$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function tr_TR$LocalizedStrings_properties()
      {
         super("tr_TR","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Kilitlenmesi",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Hörmann Portal giriş bilgileri yazınız",
            "ERROR_DELETE_ADMIN":"Uygulanamaz",
            "LOGIN_SHOULD_SAVE":"Dosyayı kaydet",
            "LOAD_USERS_TITLE":"Lütfen bekleyiniz",
            "CHANGE_GW_NAME_SETTING":"Kabul et",
            "CONFIRM_DELETE_GROUP":"Cihazı sil",
            "GENERAL_NO":"Hayır",
            "DESC_GWSCREEN_ADD":"Yerel Gateways ekle",
            "DRIVE_MESSAGE_NOT_RETRACTED":"İçeri sürülmemiş",
            "WIFI_PASSPHRASE":"Şifre",
            "CHANNEL_ON":"Açık",
            "SCENARIOS":"Senaryolar",
            "ERROR_SET_ADMIN_RIGHTS":"Uygulanamaz",
            "DESC_DEFAULT_GW_SAVE":"Güncel ağ geçidi için hızlı erişim oluştur",
            "POPUP_INFO":"Not",
            "DRIVE_MESSAGE_ERROR":"DİKKAT: Hata",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/tr/bilgikoruma",
            "DESC_WIFI_NETWORK_NAME":"Ağ adı",
            "EMAIL_BODY":"Sorunuzu bize E-posta olarak gönderebilirsiniz. SSS bölümüne de bakabilirsiniz.\n\nBiSecur-Home Destek Ekibiniz",
            "CONFIRM_DELETE_USER":"Kullanıcıyı sil",
            "DESC_CHANNELS_BACK":"Cihaz listesine geri dön",
            "CHANGE_PWD_FIRST_START":"Güvenlikten dolayı il kayıttan sonra sifrenizin fabrika ayarını değiştiriniz",
            "GENERAL_DEFAULT_GATEWAY":"Hızlı erişim",
            "CHANGE_PWD_PASSWORD_INVALID":"Hata",
            "ERROR_NO_GW_TITLE":"Ağ geçitleri yok",
            "POPUP_SETTING_STATE_CONTENT":"Komut gerçekleştiriliyor",
            "WIFI_LOADING_DATA_CONTENT":"WLAN verileri yükleniyor",
            "OPTIONS_RESET_LOGIN_DATA":"Kaydedilen giriş bilgileri sil",
            "EDIT_USER_TITLE":"Kullanıcıyı düzenle",
            "DESC_HOME_PREFERENCES":"Gateway ve App ayarları değiştir",
            "WIFI_ACTIVE_STATE":"WLAN durum",
            "STATE_COLLECTING":"Yükle",
            "ADD_SCENARIO":"Senaryo ekle",
            "STATE_COLLECTING_FAILED_CONTENT":"Durum yüklenmiyor",
            "GATE_SWING_GATE_SINGLE":"1 kanatlı dairesel açılır kapı",
            "ACTORS":"Cihazlar",
            "POPUP_AGREEMENT":"Kullanım / Bilgi koruma",
            "CHANNEL_OPEN_DOOR":"Açmak ",
            "DESC_ACTORS_REFRESH":"Durumu aktifleştir",
            "GENERAL_OFF":"Kapalı",
            "OPTIONS_HELP":"Online-Yardım",
            "COPY_PORTS_CONTENT":"Vericiyi öğrenme moduna al, bkz. kullanım kulavuzu. Atanacak kanalı seçiniz.",
            "GENERAL_SELECT":"Lütfen seçiniz...",
            "ERROR_ADAPTER_BUSY":"Hata",
            "INFO_BOX_INFOS":"Genel",
            "GATE_LIGHT":"Işık",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Kullanım koşulları aç",
            "DESC_MANAGE_POPUPS_WARNINGS":"Uyarı Popup ları gösterme",
            "MAX_USERSS_REACHED_CONTENT":"Maksimum kullanıcı sayısına ulaşıldı.",
            "GENERAL_REMOVE":"Uzaklaştır",
            "OPTIONS":"Ayarlar",
            "DESC_HOME_SCENARIOS":"Senaryoyu ayarla ve idare et",
            "CHANNEL_OFF":"Kapalı",
            "GENERAL_PORTAL_ID":"Cihazlar ID",
            "EDIT_GROUP":"Cihazda çalışma yap",
            "ERROR_LERANIN_PORT_CONTENT":"Seçilen kanalın öğretilmesi başarısız.",
            "ERROR_CONNECTION_CLOSED":"Hata",
            "CHANNEL_ON_OFF":"Aç / Kapat",
            "GENERAL_SUBMIT":"TAMAM",
            "GENERAL_GROUP_NAME":"Açıklama",
            "OPTIONS_EDIT_USERS":"Kullanıcıları yönet",
            "LOADING_STATES_CONTENT":"Güncel durum sorgulanıyor.\nLütfen bekleyiniz...",
            "LERAN_PORTS_CONTENT":"Cihazı öğrenme moduna al, bkz. kullanım kulavuzu. Öğretilecek kanalı seçiniz.",
            "REMOVE_PORTS_CONTENT":"Lütfen silinecek kanalları seçiniz.",
            "GATE_SWING_GATE_DOUBLE":"2 kanatlı dairesel açılır kapı",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Portal bilgiler doldurulmuş veya yerel Gateway eklenmiş olduğunu kontrol ediniz.",
            "CHANNEL_SINK":"İndirme",
            "OPTIONS_EDIT_USERS_TITLE":"Kullanıcı",
            "MAX_PORTS_REACHED_CONTENT":"Kanallerin maksimum sayısı aşılmış",
            "MAX_PORTS_REACHED":"Uygulanamaz",
            "ERROR_PORT_UNREACHABLE_CONTENT":"Soruşturulan cihaza ulaşılamadı",
            "PORTAL_AUTHENTICATION_FAILED":"Başarısız",
            "NOTIFICATION_CENTER":"Bilgilendirmeler",
            "LEARNING_PROCESS":"Öğretmek",
            "CHANGE_PWD_USER_INVALID_CONTENT":"Kullanıcı adı 2 - 20 karakterden oluşmalıdır",
            "WIFI_STATE_CONNECTED":"Bağlandı",
            "COPY_PORTS":"Uzaktan kumandadan kopyala",
            "POPUP_SEARCH_CONTENT":"Hörmann Gateways için arama \n\nBu işlem birkaç saniye sürebilir.",
            "DESC_MANAGE_POPUPS_CANCEL":"İşlemi iptal et",
            "DESC_WIFI_PASSWORD":"Şifre",
            "DESC_WIFI_SAVE":"Kaydet",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop aktif",
            "SELECT_GATEWAY":"Ağ geçitler",
            "CLEANING_PORTS":"Cihaz ekle",
            "WIFI_STATE_BUSY":"Bağlantı oluşturuluyor",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"Girilen şifre yanlış",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Ağ geçidin adını değiştir",
            "CHANGE_GW_NAME_SETTING_CONTENT":"Ad kullanılacak",
            "DESC_ACTORS_EDIT":"Cihazları idare et veya sil",
            "DESC_WIFI_STATE":"Bağlantı durumu",
            "ERROR_REMOVE_USER":"Başarısız",
            "LANG_TAG":"DE",
            "DESC_MANAGE_POPUPS_SUBMIT":"Ayarları kabul et",
            "HOME_TITLE":"Ana sayfa",
            "GENERAL_USERNAME":"Kullanıcı adı",
            "DRIVE_MESSAGE_OPENED":"Açık",
            "CONFIRM_DELETE":"Ağ geçidini silmek istiyor musunuz?",
            "DRIVE_MESSAGE_CLOSED":"Kapalı",
            "PORTAL_VALIDATION_FAILED_CONTENT":"Portal servere ulaşılamadı",
            "REMOVING_PROCESS_CONTENT":"Kanal siliniyor",
            "DESC_EDIT_USERS_BACK":"Ayarlara geri dön",
            "ERROR_NO_GROUP_FOUND":"Cihaz bulunamadı",
            "ERROR_INVALID_GATEWAY":"Ağ geçidi bulunamadı",
            "DESC_WIFI_BACK":"Ayarlara geri dön",
            "MAX_USERS_REACHED":"Uygulanamaz",
            "DESC_CHANGE_PASSWORD_USERNAME":"Kullanıcı adı",
            "POPUP_AGREEMENT_ACCEPT_USE":"Kullanım koşulları kabul ediyorum",
            "ERROR_LERNING_PORT":"Başarısız",
            "POPUP_ADD_GATEWAY_CONTENT":"IP adresi gir:",
            "ERROR_ADD_GROUP":"Hata",
            "DRIVE_MESSAGE_NO_DATA":"Herhangi bir veri yok",
            "CHANGE_PWD_FAILED":"Başarısız",
            "SAVING_USER_RIGHTS_CONTENT":"Kullanıcı hakları kaydediliyor",
            "DRIVE_MESSAGE_UNLOCKED":"kilitli değil",
            "GENERAL_SAVE":"Kaydet",
            "INFO_BOX_FAQ":"SSS",
            "GENERAL_CONNNECT":"Bağlan",
            "GATE_SECTIONAL_DOOR":"Dikey hareket eden garaj kapısı",
            "OPTIONS_CHANGE_PASSWORD":"Şifreyi değiştir",
            "CHANNEL":"Kullanım",
            "CHANGE_GW_NAME_CONTENT":"Ağ geçidin adı",
            "DRIVE_MESSAGE_RETRACTED":"İçeri sürülmüş",
            "DESC_ADDGWSCREEN_BACK":"Gateway listesine geri dön",
            "EMAIL_SUBJECT":"Destek",
            "ERROR_EDIT_ADMIN":"Uygulanamaz",
            "OPTIONS_SET_USER_RIGHTS":"Kullanıcı hakları",
            "CHANGE_GW_NAME_ERROR":"Başarısız",
            "CHANNEL_LIFT":"Kaldırma",
            "LOGIN_FAILED_TITLE":"Başarısız",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"Giriş bilgilerin silinmesini OK ile onayladığınızda, ağ geçidi seçimi için şifre tekrar yazılmalıdır",
            "CHANNEL_UNLOCK":"Kilidin açılması",
            "GENERAL_PORTAL_SERVER":"Portal Server",
            "DESC_SCENARIOS_BACK":"Ana menüye geri dön",
            "CHANGE_PWD_USERNAME":"Kullanıcı:",
            "POPUP_GATE_NOT_RESPONSABLE":"Uygulama bu komutu cihaza gönderebilir, ancak cihazın güncel durumunu algılayamaz.",
            "DESC_GW_NAME":"Ağ geçidin adı",
            "GATE_BARRIER":"Bariyer",
            "LEARN_PORTS":"Telsiz kodu tanıt",
            "GENERAL_BACK":"Geri",
            "DESC_GWSCREEN_EDIT":"Kayıtlı ağ geçitlerin silinmesi için",
            "OPTIONS_MANAGE_POPUPS":"Popup bildirgeleri yönet",
            "POPUP_LOGIN_PROCESS_CONTENT":"Lütfen bekleyiniz...",
            "CONFIRM_DELETE_USER_CONTENT":"Kullanıcıyı gerçekten silmek istiyor musunuz?",
            "DESC_MENU":"Menü",
            "LOGIN_FAILED_WRONG_DATA":"Kullanıcı adı veya şifre yanlış",
            "GENERAL_CANCEL":"İptal",
            "ADD_GROUP":"Cihaz ekle",
            "WIFI_STATE_AP_NOT_FOUND":"Ağ bulunamadı",
            "WIFI_STATE_NOT_CONNECTED":"Bağlı değil",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Portal ile kullanımınız aktifleştirildi!",
            "POPUP_ADD_GATEWAY":"Ağ geçidi ekle",
            "GENERAL_NEXT":"İleri",
            "POPUP_SUPPRESS":"Popup artık açılmasın",
            "POPUP_SEARCH_TITLE":"Arama...",
            "WIFI_SCANNING_CONTENT":"Görünmeyen WLAN ağları ara",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"Ağ geçidi bulunamadı",
            "DESC_ACTORS_ADD":"Cihazı ayarla",
            "ERROR_ADD_GROUP_NO_TYPE":"Yeni cihaz için tip seçilmedi.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Giriş bilgileri kontrol ediniz",
            "GENERAL_REFESHED":"Güncellendi",
            "OPTIONS_SUPPRESS_WARNINGS":"Uyarıları gösterme",
            "LOGIN_FAILED_GATEWAY_BUSY":"Ağ geçidi şuanda meşgul. Tekrar deneyiniz.",
            "DESC_EMAIL":"Destek bölümüne E-posta gönder",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Sürekli Aç kapalı",
            "CLEANING_PORTS_CONTENT":"Ekle ve hazırla",
            "DESC_HOME_ACTORS":"Cihazları ayarla ve idare et",
            "ERROR_TIMEOUT":"Bağlantı hatası",
            "CREATE_USER_TITLE":"Kullanıcı ekle",
            "ERROR_DELETE_ADMIN_CONTENT":"Yönetici silinemez",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Hızlı erişim",
            "ADD_SCENARIO_NAME":"İsim",
            "HIST":"Geçmiş",
            "DESC_RESET_LOGIN_SUBMIT":"Sil onayı",
            "POPUP_WARNING":"DİKKAT",
            "REMOVE_GROUP_PROCESS":"Cihaz silinecek",
            "POPUP_LOGIN_PROCESS":"Kayıt",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Lütfen bekleyiniz...",
            "DESC_DEFAULT_GW_SUBMIT":"Ayarları kabul et",
            "DESC_CHANGE_PASSWORD_RETYPE":"Girişi tekrarla",
            "LOAD_USERS_CONTENT":"Ağ geçidindeki tüm kullanıcılar yükleniyor.\nBu işlem birkaç saniye sürebilir.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"Bir Gateway için hızlı erişim aktifleştirilirse, uygulamalara otomatik giriş yapılır",
            "GATE_OTHER":"Diğer cihazlar",
            "CHANGE_PWD_USER_INVALID":"Hata",
            "CHANNEL_LIGHT":"Işık",
            "LOGIN_TITLE":"Kayıt",
            "CHANNEL_HALF":"Kısmi açılma",
            "GATEWAY_SCREEN_ADD_HELP":"Gateways eklemek için +sembolü seçiniz.",
            "ERROR_TIMEOUT_CONTENT":"Ağ geçidi haberleşmesinde zaman aşımı",
            "ERROR_NO_PORTS_LEARNED":"Eklenemiyor",
            "OPTIONS_SUPPRESS_INFOS":"Notları gösteme",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Hata",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Otomatik işletim",
            "GENERAL_DELETE":"Sil",
            "GENERAL_PASSWORD":"Şifre",
            "STATE_COLLECTING_CONTENT":"Cihaz durumu sorgulanıyor",
            "ERROR_REMOVE_USER_CONTENT":"Kullanıcı silinemedi",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Hata",
            "ACTORS_ADD_HELP":"Cihaz eklemek için +sembolü seçiniz.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Cihazı silmek istiyor musunuz?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Lütfen bekleyiniz...",
            "GENERAL_YES":"Evet",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Cihazı eklemeden önce en az bir kanal öğretiniz",
            "CHANGE_GW_NAME_ERROR_CONTENT":"Ad değiştirilemedi",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"Uygulama henüz Gateways bulamadı.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Doğrulama yapılamadı",
            "DESC_MANAGE_POPUPS_INFOS":"Bilgi Popup ları gösterme",
            "GATE_PILOMAT_POLLER":"Duba",
            "DESC_CHANNELS_STATE":"Geri bilgirgeye sahip cihazın durumu",
            "DESC_GWSCREEN_REFRESH":"Ağ geçit listesini güncelle",
            "POPUP_SCENARIO_DISPATCHING":"Senaryo gerçekleştiriliyor",
            "ERROR_PORT_UNREACHABLE":"Başarısız",
            "POPUP_GATEWAY_FOUND_CONTENT":"Bulunan Gateways:",
            "WIFI_STATE_SECURITY_MISMATCH":"WLAN ın şifreleme tipi desteklenmiyor",
            "LOGOUT_NAMED":"çık",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Bilgi koruma koşulları aç",
            "ERROR_NO_GW_CONTENT":"Yerel ağ\'da Hörmann ağ geçidi bulunamadı.\nDiğer ağ geçitleri +sembolü ile ekleyiniz",
            "DESC_EDIT_USERS_ADD":"Kullanıcı ekle",
            "ERROR_NO_PORT_FOUND":"Port bulunamadı",
            "GATE_SLIDING_GATE":"Sürme garaj kapısı",
            "DESC_CHANNELS_BUTTONS":"Cihazın kontol elemanları",
            "DRIVE_MESSAGE_EXTENDED":"Dışarı sürülmüş",
            "WIFI_SELECTED_NETWORK":"İsim",
            "ERROR_ADD_GROUP_NO_NAME":"Yeni cihaz için ad yazılmadı.",
            "DESC_HELP":"Yardım fonksiyonu",
            "CHANGE_PWD_NEW_PASSWORD":"Yeni şifre",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Yeni şifreyi kabul et",
            "DESC_CHANGE_PASSWORD_PWD":"Yeni şifreyi gir",
            "ERROR_EDIT_ADMIN_CONTENT":"Yönetici düzenlenemez",
            "CHANGE_GW_NAME_NAME_INVALID":"Başarısız",
            "STATE_COLLECTING_FAILED":"Hata",
            "GENERAL_ADD":"Ekle",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Şifre\" ve \"Şifreyi tekrarla\" aynı olmalıdır",
            "WIFI_SETTINGS":"WLAN ayarları",
            "LEARN_PORTS_TITLE":"Cihaz ekle",
            "ERROR_CHANGE_USERNAME":"Başarısız",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Araç stoperi",
            "ERROR_INVALID_GATEWAY_CONTENT":"Ağ geçidine bağlanamadı. Host adını kontrol ediniz.",
            "DESC_EDIT_USERS_EDIT":"Kullanıcıyı sil",
            "ERROR_ADD_GROUP_NAME_LENGTH":"Cihaz adı 2 - 20 karakterden oluşmalıdır",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Hızlı erişim mümkün değil",
            "CHANNEL_UP":"Aç",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Sürekli Aç açık",
            "PORTAL_VALIDATION_FAILED":"Başarısız",
            "DESC_RESET_LOGIN_CANCEL":"İşlemi iptal et",
            "CHANGE_PWD_SETTING_PASSWORD":"Kabul et",
            "LOADING_GROUPS_TITLE":"Yükle",
            "DESC_DEFAULT_GW_CANCEL":"İşlemi iptal et",
            "DESC_SET_RIGHTS_SAVE":"Değişiklikleri kabul et",
            "REMOVING_PROCESS":"Sil",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"Gateway\'e ulaşılamıyor",
            "CONFIRM_DELETE_TITLE":"Ağ geçidi sil",
            "SCENARIOS_ADD_HELP":"Senaryo eklemek için +sembolü seçiniz.",
            "LOGOUT":"Çık",
            "DESC_ACTORS_BACK":"Ana menüye geri dön",
            "ERROR_ADAPTER_BUSY_CONTENT":"Komut gerçekleştirilemedi.\n Ağ geçidi şuanda meşgul.",
            "DESC_WIFI_NETWORK_SCAN":"Ağ ara",
            "DRIVE_MESSAGE_HALF":"Kısmı açık",
            "DESC_SCENARIOS_ADD":"Senaryo ayarla",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Ağ geçit haberleşmesinde hata oluştu",
            "SAVING_USER_RIGHTS":"Kaydet",
            "DESC_GWSCREEN_PORTAL":"Portal verilerin girilmesi",
            "GATE_JACK":"Kablosuz priz",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Gateway ile aynı ağ\'da misiniz?",
            "GATE_DOOR":"Kapı",
            "POPUP_PORTAL_UNAVAILABLE":"Portal servere ulaşılamadı",
            "DESC_SET_RIGHTS_BACK":"Kullanıcılara geri dön",
            "GATE_SMARTKEY":"Kapı kilidi motoru",
            "POPUP_GATEWAY_FOUND_TITILE":"Arama tamamlandı",
            "WIFI_LOADING_DATA_TITLE":"Yükle",
            "GENERAL_PORTS":"Kanallar",
            "DESC_SCENARIOS_EDIT":"Senaryoyu idare et veya sil",
            "OPTIONS_LEARNED_PORTS":"Tanıtılan kanallar:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"Bilgi koruma koşulları kabul ediyorum",
            "DESC_EDIT_USERS_SET_RIGHTS":"Giriş hakları değiştirmek için kullanıcı seç",
            "DRIVE_MESSAGE_HALF_MOVING":"Kısmı açık / Seyir halinde",
            "PORTAL_SET_ID_DIALOG":"Portal ayarları",
            "DRIVE_MESSAGE_NOT_REFERENCED":"Nirengi noktası yok",
            "POPUP_SETTING_STATE":"Lütfen bekleyiniz...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/tr/kullan-m-kosullari",
            "ERROR_CHANGE_USERNAME_CONTENT":"Kullanıcı adı değiştirilemedi",
            "GROUP_REQUESTABLE":"Cihaz geri bildirim özelliğine sahip",
            "LOADING_STATES_TITLE":"Yükle",
            "DESC_HOME_USERS":"Kullanıcıları yönet",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"Şifre 4 - 20 karakterden oluşmalıdır",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"Şifre kullanılacak",
            "POPUP_GATE_OUT_OF_VIEW":"Kapının görüş alanında olmayan otomatik kapı sistemi kumandayı kullanmak için, kapıya standart güç sınırlamasına ilave olarak bir fotosel kurulmalıdır.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Popup bildirgelerin gösterilip gösterilmeyeceğini seçiniz",
            "CHANNEL_IMPULS":"İmpuls",
            "PORTAL_VALIDATION_SUCCEEDED":"Yetkili",
            "DRIVE_MESSAGE_LOCKED":"kilitli",
            "CHANNEL_DOWN":"Kapat",
            "POPUP_INET_SPEED_LOW":"Bu uygulama için bağlantınız yeterli değildir",
            "CHANGE_PWD_FAILED_CONTENT":"Şifre değiştirilemedi",
            "GENERAL_GROUP_TYPE":"Cihaz tipi",
            "CHANNEL_WALK":"Trafik kanadı",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Yatay hareket eden garaj kapısı",
            "POPUP_AGREEMENT_CONTENT":"Uygulamayı kullanmadan önce Bilgi Koruma / Kullanım koşulları kabul ediniz",
            "INFO":"Bilgiler",
            "LOADING_GROUPS_CONTENT":"Cihazlar yükle",
            "GATE_PILOMAT_REIFENKILLER":"Araç kapanı",
            "GATE_PILOMAT_HUBBALKEN":"Mantar bariyer sistemi",
            "GENERAL_RETYPE":"Şifreyi tekrar giriniz",
            "DESC_OTIONS_BACK":"Ana menüye geri dön",
            "DESC_SET_RIGHTS":"Kullanıcı giriş hakların sağlanması için cihaz seç",
            "WIFI_SCANNING_TITLE":"Arama",
            "WIFI_STATE_CONNECTION_FAILURE":"Bağlantı oluşturulamadı",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"Kullanıcı adı 2 - 20 karakterden oluşmalıdır",
            "REMOVE_PORTS":"Sil",
            "GENERAL_ON":"Açık",
            "DESC_CHANGE_PASSWORD_CANCEL":"İşlemi iptal et",
            "LEARNING_PROCESS_CONTENT":"Lütfen bekleyiniz...",
            "LOGIN_FAILED_UNKNOWN":"Beklenmeyen bir hata oluştu",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"Yöneticinin kullanım hakları değiştirilemez!"
         };
         return _loc1_;
      }
   }
}
