package
{
   import mx.resources.ResourceBundle;
   
   public class xu_XU$LocalizedStrings_properties extends ResourceBundle
   {
       
      
      public function xu_XU$LocalizedStrings_properties()
      {
         super("xu_XU","LocalizedStrings");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CHANNEL_LOCK":"Lock",
            "PORTAL_SET_ID_DIALOG_CONTENT":"Enter the Hörmann portal access data",
            "ERROR_DELETE_ADMIN":"Not possible",
            "LOGIN_SHOULD_SAVE":"Save data",
            "LOAD_USERS_TITLE":"Please wait",
            "CHANGE_GW_NAME_SETTING":"Apply",
            "CONFIRM_DELETE_GROUP":"Delete device",
            "GENERAL_NO":"No",
            "DESC_GWSCREEN_ADD":"Add local gateways",
            "DRIVE_MESSAGE_NOT_RETRACTED":"not lowered",
            "WIFI_PASSPHRASE":"Password",
            "CHANNEL_ON":"",
            "SCENARIOS":"Scenarios",
            "ERROR_SET_ADMIN_RIGHTS":"Not possible",
            "DESC_DEFAULT_GW_SAVE":"Set up quick access for current gateway",
            "POPUP_INFO":"Note",
            "DRIVE_MESSAGE_ERROR":"ATTENTION: Error",
            "LINK_TERMS_OF_PRIVACY":"http://www.bisecur-home.com/en/dataprotection",
            "DESC_WIFI_NETWORK_NAME":"Network name",
            "EMAIL_BODY":"You can send your questions to us via e-mail. Our FAQ function is also available to assist you.\n\nYour BiSecur Home Support Team",
            "CONFIRM_DELETE_USER":"Delete user",
            "DESC_CHANNELS_BACK":"Back to device list",
            "CHANGE_PWD_FIRST_START":"For security reasons, change the factory setting of your password after initial login",
            "GENERAL_DEFAULT_GATEWAY":"Quick Access",
            "CHANGE_PWD_PASSWORD_INVALID":"Error",
            "ERROR_NO_GW_TITLE":"No gateways",
            "POPUP_SETTING_STATE_CONTENT":"The command is being carried out",
            "WIFI_LOADING_DATA_CONTENT":"WLAN data is being loaded",
            "OPTIONS_RESET_LOGIN_DATA":"Delete saved login data",
            "EDIT_USER_TITLE":"Edit user",
            "DESC_HOME_PREFERENCES":"Change settings for gateway and app",
            "WIFI_ACTIVE_STATE":"WLAN status",
            "STATE_COLLECTING":"Load",
            "ADD_SCENARIO":"Add scenario",
            "STATE_COLLECTING_FAILED_CONTENT":"Status was not loaded",
            "GATE_SWING_GATE_SINGLE":"Single-leaf hinged gate",
            "ACTORS":"Devices ",
            "POPUP_AGREEMENT":"Usage/Data protection",
            "CHANNEL_OPEN_DOOR":"Open",
            "DESC_ACTORS_REFRESH":"Update status",
            "GENERAL_OFF":"Switched off",
            "OPTIONS_HELP":"Online help",
            "COPY_PORTS_CONTENT":"Switch the transmitter to inheritance mode, see instructions. Select the inheriting channel.",
            "GENERAL_SELECT":"Please select...",
            "ERROR_ADAPTER_BUSY":"Error",
            "INFO_BOX_INFOS":"General",
            "GATE_LIGHT":"Light",
            "POPUP_AGREEMENT_TERMS_OF_USE":"Open terms and conditions",
            "DESC_MANAGE_POPUPS_WARNINGS":"Disable warning pop-ups",
            "MAX_USERSS_REACHED_CONTENT":"The maximum number of users has been reached.",
            "GENERAL_REMOVE":"Remove",
            "OPTIONS":"Settings",
            "DESC_HOME_SCENARIOS":"Create and manage scenarios",
            "CHANNEL_OFF":"",
            "GENERAL_PORTAL_ID":"Device ID",
            "EDIT_GROUP":"Edit device",
            "ERROR_LERANIN_PORT_CONTENT":"The teach-in of the desired channel has failed",
            "ERROR_CONNECTION_CLOSED":"Error",
            "CHANNEL_ON_OFF":"On/Off",
            "GENERAL_SUBMIT":"OK",
            "GENERAL_GROUP_NAME":"Designation",
            "OPTIONS_EDIT_USERS":"Manage users",
            "LOADING_STATES_CONTENT":"The current status is being retrieved.\nPlease wait...",
            "LERAN_PORTS_CONTENT":"Switch the device to teach-in mode, see instructions. Select the channel to be taught in.",
            "REMOVE_PORTS_CONTENT":"Select the channels that you want to delete.",
            "GATE_SWING_GATE_DOUBLE":"Double-leaf hinged gate",
            "GATEWAY_SCREEN_NO_GATEWAYS_CONTENT":"Check whether you have added your portal data or a local gateway.",
            "CHANNEL_SINK":"Lowering",
            "OPTIONS_EDIT_USERS_TITLE":"Users",
            "MAX_PORTS_REACHED_CONTENT":"Maximum number of channels assigned",
            "MAX_PORTS_REACHED":"Not possible",
            "ERROR_PORT_UNREACHABLE_CONTENT":"The queried device could not be reached",
            "PORTAL_AUTHENTICATION_FAILED":"Failed",
            "NOTIFICATION_CENTER":"Alerts",
            "LEARNING_PROCESS":"Teach in",
            "CHANGE_PWD_USER_INVALID_CONTENT":"The user name must consist of 2–20 characters",
            "WIFI_STATE_CONNECTED":"Connected",
            "COPY_PORTS":"Inherit from hand transmitter",
            "POPUP_SEARCH_CONTENT":"Searching for Hörmann gateways \n\nThis process may take a few seconds.",
            "DESC_MANAGE_POPUPS_CANCEL":"Cancel action",
            "DESC_WIFI_PASSWORD":"Password",
            "DESC_WIFI_SAVE":"Save",
            "DRIVE_MESSAGE_STOP_ACTIVE":"Stop active",
            "SELECT_GATEWAY":"Gateways",
            "CLEANING_PORTS":"Add device",
            "WIFI_STATE_BUSY":"Connection is being established",
            "CHANGE_PWD_PASSWORD_INVALID_CONTENT":"The password entered is wrong",
            "OPTIONS_CHANGE_GATEWAY_NAME":"Change name of the gateway",
            "CHANGE_GW_NAME_SETTING_CONTENT":"The name is being applied",
            "DESC_ACTORS_EDIT":"Manage or delete devices",
            "DESC_WIFI_STATE":"Connection status",
            "ERROR_REMOVE_USER":"Failed",
            "LANG_TAG":"EN",
            "DESC_MANAGE_POPUPS_SUBMIT":"Apply setting",
            "HOME_TITLE":"Home page",
            "GENERAL_USERNAME":"User name",
            "DRIVE_MESSAGE_OPENED":"Open",
            "CONFIRM_DELETE":"Are you sure you want to delete the gateway?",
            "DRIVE_MESSAGE_CLOSED":"Closed",
            "PORTAL_VALIDATION_FAILED_CONTENT":"The portal server could not be reached",
            "REMOVING_PROCESS_CONTENT":"The channel is being deleted",
            "DESC_EDIT_USERS_BACK":"Back to settings",
            "ERROR_NO_GROUP_FOUND":"Device not found",
            "ERROR_INVALID_GATEWAY":"No gateway found",
            "DESC_WIFI_BACK":"Back to settings",
            "MAX_USERS_REACHED":"Not possible",
            "DESC_CHANGE_PASSWORD_USERNAME":"User name",
            "POPUP_AGREEMENT_ACCEPT_USE":"I accept the terms and conditions",
            "ERROR_LERNING_PORT":"Failed",
            "POPUP_ADD_GATEWAY_CONTENT":"Enter IP address:",
            "ERROR_ADD_GROUP":"Error",
            "DRIVE_MESSAGE_NO_DATA":"No data available",
            "CHANGE_PWD_FAILED":"Failed",
            "SAVING_USER_RIGHTS_CONTENT":"User rights are being saved",
            "DRIVE_MESSAGE_UNLOCKED":"Not locked",
            "GENERAL_SAVE":"Save",
            "INFO_BOX_FAQ":"FAQ ",
            "GENERAL_CONNNECT":"Connect",
            "GATE_SECTIONAL_DOOR":"Vertical garage door",
            "OPTIONS_CHANGE_PASSWORD":"Change password",
            "CHANNEL":"Operation",
            "CHANGE_GW_NAME_CONTENT":"Name of the gateway",
            "DRIVE_MESSAGE_RETRACTED":"lowered",
            "DESC_ADDGWSCREEN_BACK":"Back to gateway overview",
            "EMAIL_SUBJECT":"Support",
            "ERROR_EDIT_ADMIN":"Not possible",
            "OPTIONS_SET_USER_RIGHTS":"User rights",
            "CHANGE_GW_NAME_ERROR":"Failed",
            "CHANNEL_LIFT":"Lifting",
            "LOGIN_FAILED_TITLE":"Failed",
            "OPTIONS_RESET_LOGIN_DATA_CONTENT":"If you confirm deleting login data by clicking OK, the password must be re-entered when the gateway is selected",
            "CHANNEL_UNLOCK":"Unlock",
            "GENERAL_PORTAL_SERVER":"Portal Server",
            "DESC_SCENARIOS_BACK":"Back to main menu",
            "CHANGE_PWD_USERNAME":"User:",
            "POPUP_GATE_NOT_RESPONSABLE":"The app can send this command to the device, but does not recognise the current condition of the device.",
            "DESC_GW_NAME":"Name of the gateway",
            "GATE_BARRIER":"barrier",
            "LEARN_PORTS":"Teach in radio code",
            "GENERAL_BACK":"Back",
            "DESC_GWSCREEN_EDIT":"To delete saved gateways",
            "OPTIONS_MANAGE_POPUPS":"Manage pop-up messages",
            "POPUP_LOGIN_PROCESS_CONTENT":"Please wait...",
            "CONFIRM_DELETE_USER_CONTENT":"Are you sure you want to delete the user?",
            "DESC_MENU":"Menu",
            "LOGIN_FAILED_WRONG_DATA":"The user name or password entered is wrong",
            "GENERAL_CANCEL":"Cancel",
            "ADD_GROUP":"Add device",
            "WIFI_STATE_AP_NOT_FOUND":"Network not found",
            "WIFI_STATE_NOT_CONNECTED":"Not connected",
            "PORTAL_VALIDATION_SUCCEEDED_CONTENT":"Your operation via the portal is activated!",
            "POPUP_ADD_GATEWAY":"Add gateway",
            "GENERAL_NEXT":"Next",
            "POPUP_SUPPRESS":"Do not open popups",
            "POPUP_SEARCH_TITLE":"Search...",
            "WIFI_SCANNING_CONTENT":"Search for visible WLAN networks",
            "ADD_GATEWAY_NO_GATEWAYS_TITLE":"No gateway found",
            "DESC_ACTORS_ADD":"Create device",
            "ERROR_ADD_GROUP_NO_TYPE":"No type has been selected for the new device.",
            "PORTAL_AUTHENTICATION_FAILED_CONTENT":"Check the login data",
            "GENERAL_REFESHED":"Updated",
            "OPTIONS_SUPPRESS_WARNINGS":"Disable warnings",
            "LOGIN_FAILED_GATEWAY_BUSY":"The gateway is busy. Please try again later.",
            "DESC_EMAIL":"Send e-mail to support",
            "DRIVE_MESSAGE_PERMANENT_LOCKED":"Permanent Open off",
            "CLEANING_PORTS_CONTENT":"Adding device is being prepared",
            "DESC_HOME_ACTORS":"Teach in and manage devices",
            "ERROR_TIMEOUT":"Connection Error",
            "CREATE_USER_TITLE":"Add user",
            "ERROR_DELETE_ADMIN_CONTENT":"The administrator cannot be deleted",
            "OPTIONS_SET_DEFAULT_GATEWAY":"Quick Access",
            "ADD_SCENARIO_NAME":"Name",
            "HIST":"History",
            "DESC_RESET_LOGIN_SUBMIT":"Confirm deletion",
            "POPUP_WARNING":"ATTENTION",
            "REMOVE_GROUP_PROCESS":"The device is being deleted",
            "POPUP_LOGIN_PROCESS":"Log on",
            "POPUP_SCENARIO_DISPATCHING_CONTENT":"Please wait...",
            "DESC_DEFAULT_GW_SUBMIT":"Apply setting",
            "DESC_CHANGE_PASSWORD_RETYPE":"Repeat entry",
            "LOAD_USERS_CONTENT":"All users are being loaded by the gateway.\nThis process may take a few seconds.",
            "OPTIONS_SET_DEFAULT_GATEWAY_CONTENT":"If quick access is activated for a gateway, the app will automatically log in whenever possible",
            "GATE_OTHER":"Other devices",
            "CHANGE_PWD_USER_INVALID":"Error",
            "CHANNEL_LIGHT":"Light",
            "LOGIN_TITLE":"Log on",
            "CHANNEL_HALF":"Partial opening",
            "GATEWAY_SCREEN_ADD_HELP":"Select the +symbol to add a gateway.",
            "ERROR_TIMEOUT_CONTENT":"Communication with the gateway has timed out",
            "ERROR_NO_PORTS_LEARNED":"Not possible to add",
            "OPTIONS_SUPPRESS_INFOS":"Disable notifications",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL":"Error",
            "OPTIONS_WIFI_SETTINGS":"WLAN",
            "CHANNEL_AUTO_CLOSE":"Automatic operation",
            "GENERAL_DELETE":"Delete",
            "GENERAL_PASSWORD":"Password",
            "STATE_COLLECTING_CONTENT":"Status of the device is being queried",
            "ERROR_REMOVE_USER_CONTENT":"The user could not be deleted",
            "CHANGE_PWD_NEW_PASSWORD_INVALID":"Error",
            "ACTORS_ADD_HELP":"Select the +symbol to add a device.",
            "CONFIRM_DELETE_GROUP_CONTENT":"Are you sure you want to delete the device?",
            "REMOVE_GROUP_PROCESS_CONTENT":"Please wait...",
            "GENERAL_YES":"Yes",
            "ERROR_NO_PORTS_LEARNED_CONTENT":"Teach in at least one channel before adding a device",
            "CHANGE_GW_NAME_ERROR_CONTENT":"The name could not be changed",
            "GATEWAY_SCREEN_NO_GATEWAYS_TITLE":"The app has not found any gateways yet.",
            "WIFI_STATE_AUTHENTICATION_FAILURE":"Authentication failed",
            "DESC_MANAGE_POPUPS_INFOS":"Disable information pop-ups",
            "GATE_PILOMAT_POLLER":"Bollard",
            "DESC_CHANNELS_STATE":"Status of the feedback-capable device",
            "DESC_GWSCREEN_REFRESH":"Update the gateway list",
            "POPUP_SCENARIO_DISPATCHING":"Scenario is being carried out",
            "ERROR_PORT_UNREACHABLE":"Failed",
            "POPUP_GATEWAY_FOUND_CONTENT":"The following gateways have been added:",
            "WIFI_STATE_SECURITY_MISMATCH":"The WLAN encryption is not supported",
            "LOGOUT_NAMED":"Log out",
            "POPUP_AGREEMENT_TERMS_OF_PRIVACY":"Open data protection conditions",
            "ERROR_NO_GW_CONTENT":"A Hörmann gateway could not be found in the local network.\nAdd further gateways using the +sign",
            "DESC_EDIT_USERS_ADD":"Add user",
            "ERROR_NO_PORT_FOUND":"Port not found",
            "GATE_SLIDING_GATE":"Sliding gate",
            "DESC_CHANNELS_BUTTONS":"Device control elements",
            "DRIVE_MESSAGE_EXTENDED":"raised",
            "WIFI_SELECTED_NETWORK":"Name",
            "ERROR_ADD_GROUP_NO_NAME":"No name has been entered for the new device.",
            "DESC_HELP":"Help function",
            "CHANGE_PWD_NEW_PASSWORD":"New password",
            "DESC_CHANGE_PASSWORD_SUBMIT":"Apply new password",
            "DESC_CHANGE_PASSWORD_PWD":"Enter new password",
            "ERROR_EDIT_ADMIN_CONTENT":"The administrator cannot be edited",
            "CHANGE_GW_NAME_NAME_INVALID":"Failed",
            "STATE_COLLECTING_FAILED":"Error",
            "GENERAL_ADD":"Add",
            "CHANGE_PWD_PASSWORD_NOT_EQUAL_CONTENT":"\"Password\" and \"Re-enter password\" must be identical",
            "WIFI_SETTINGS":"WLAN settings",
            "LEARN_PORTS_TITLE":"Add device",
            "ERROR_CHANGE_USERNAME":"Failed",
            "GATE_PILOMAT_DURCHFAHRTSSPERRE":"Road blocker",
            "ERROR_INVALID_GATEWAY_CONTENT":"A connection could not be established with the gateway. Check the host name.",
            "DESC_EDIT_USERS_EDIT":"Delete user",
            "ERROR_ADD_GROUP_NAME_LENGTH":"The device name must consist of 2–20 characters.",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND":"Quick access not possible",
            "CHANNEL_UP":"Open",
            "DRIVE_MESSAGE_PERMANENT_UNLOCKED":"Permanent Open on",
            "PORTAL_VALIDATION_FAILED":"Failed",
            "DESC_RESET_LOGIN_CANCEL":"Cancel action",
            "CHANGE_PWD_SETTING_PASSWORD":"Apply",
            "LOADING_GROUPS_TITLE":"Load",
            "DESC_DEFAULT_GW_CANCEL":"Cancel action",
            "DESC_SET_RIGHTS_SAVE":"Apply changes",
            "REMOVING_PROCESS":"Delete",
            "ERROR_DFAULT_GATEWAY_NOT_FOUND_CONTENT":"The gateway is not accessible",
            "CONFIRM_DELETE_TITLE":"Delete gateway",
            "SCENARIOS_ADD_HELP":"Select the +symbol to add a scenario.",
            "LOGOUT":"Log out",
            "DESC_ACTORS_BACK":"Back to main menu",
            "ERROR_ADAPTER_BUSY_CONTENT":"The command could not be performed.\n The gateway is busy.",
            "DESC_WIFI_NETWORK_SCAN":"Search for networks",
            "DRIVE_MESSAGE_HALF":"Partially open",
            "DESC_SCENARIOS_ADD":"Create scenario",
            "ERROR_CONNECTION_CLOSED_CONTENT":"Communication with the gateway has failed",
            "SAVING_USER_RIGHTS":"Save",
            "DESC_GWSCREEN_PORTAL":"Enter portal data",
            "ADD_GATEWAY_NO_GATEWAYS_CONTENT":"Are you in the same network as your gateway?",
            "GATE_DOOR":"Door",
            "POPUP_PORTAL_UNAVAILABLE":"The portal server could not be reached",
            "DESC_SET_RIGHTS_BACK":"Back to users",
            "GATE_SMARTKEY":"Door lock operator",
            "POPUP_GATEWAY_FOUND_TITILE":"Search over",
            "WIFI_LOADING_DATA_TITLE":"Load",
            "GENERAL_PORTS":"Channels",
            "DESC_SCENARIOS_EDIT":"Manage or delete scenarios",
            "OPTIONS_LEARNED_PORTS":"Taught-in channels:",
            "POPUP_AGREEMENT_ACCEPT_PRIVACY":"I accept the data protection conditions",
            "DESC_EDIT_USERS_SET_RIGHTS":"Select user to change access rights",
            "DRIVE_MESSAGE_HALF_MOVING":"Partially open / travelling",
            "PORTAL_SET_ID_DIALOG":"Portal settings",
            "DRIVE_MESSAGE_NOT_REFERENCED":"No reference point",
            "POPUP_SETTING_STATE":"Please wait...",
            "LINK_TERMS_OF_USE":"http://www.bisecur-home.com/en/terms-and-conditions",
            "ERROR_CHANGE_USERNAME_CONTENT":"The user name could not be changed",
            "GROUP_REQUESTABLE":"The device has feedback capability",
            "LOADING_STATES_TITLE":"Load",
            "DESC_HOME_USERS":"Manage users",
            "CHANGE_PWD_NEW_PASSWORD_INVALID_CONTENT":"The password must consist of 4–20 characters",
            "CHANGE_PWD_SETTING_PASSWORD_CONTENT":"The password is being applied",
            "POPUP_GATE_OUT_OF_VIEW":"Attention: An automatic door system may only be controlled without visual contact to the door if you have installed an photocell on the door in addition to the standard power limit.",
            "OPTIONS_MANAGE_POPUPS_CONTENT":"Select whether pop-up messages should be displayed or disabled",
            "CHANNEL_IMPULS":"Impulse",
            "PORTAL_VALIDATION_SUCCEEDED":"Authorised",
            "DRIVE_MESSAGE_LOCKED":"Locked",
            "CHANNEL_DOWN":"Closed",
            "POPUP_INET_SPEED_LOW":"Your data connection is insufficient for this application",
            "CHANGE_PWD_FAILED_CONTENT":"The password could not be changed",
            "GENERAL_GROUP_TYPE":"Device type",
            "CHANNEL_WALK":"Traffic leaf",
            "GATE_HORIZONTAL_SECTIONAL_DOOR":"Horizontal garage door",
            "POPUP_AGREEMENT_CONTENT":"Accept the data protection/terms and conditions before using the app",
            "INFO":"Information",
            "LOADING_GROUPS_CONTENT":"Load devices",
            "GATE_PILOMAT_REIFENKILLER":"Tyre Killers",
            "GATE_PILOMAT_HUBBALKEN":"Lift Barriers",
            "GENERAL_RETYPE":"Repeat password",
            "DESC_OTIONS_BACK":"Back to main menu",
            "DESC_SET_RIGHTS":"Select device to grant access rights to the user",
            "WIFI_SCANNING_TITLE":"Search",
            "WIFI_STATE_CONNECTION_FAILURE":"Establishment of the connection failed",
            "CHANGE_GW_NAME_NAME_INVALID_CONTENT":"The user name must consist of 2–20 characters",
            "REMOVE_PORTS":"Delete",
            "GENERAL_ON":"Switched on",
            "DESC_CHANGE_PASSWORD_CANCEL":"Cancel action",
            "LEARNING_PROCESS_CONTENT":"Please wait...",
            "LOGIN_FAILED_UNKNOWN":"An unexpected error occurred",
            "ERROR_SET_ADMIN_RIGHTS_CONTENT":"The administrator\'s user rights cannot be changed"
         };
         return _loc1_;
      }
   }
}
